In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
stats_current_gameweek = 23
picks_current_gameweek = 23
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 24
Squad Points: 71.2

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,24.0,DEF,Arsenal,Leeds,5.871777,73.0
1,Matheus N.,a,75.0,24.0,DEF,Man City,Spurs,5.142156,66.0
2,Khusanov,a,100.0,24.0,DEF,Man City,Spurs,4.991684,77.0
3,Raya,a,NaN,24.0,GK,Arsenal,Leeds,4.503312,90.0
4,Brobbey,a,100.0,24.0,FWD,Sunderland,Burnley,4.496824,84.0
5,Szoboszlai,a,100.0,24.0,MID,Liverpool,Newcastle,4.445211,84.0
6,B.Fernandes,a,100.0,24.0,MID,Man Utd,Fulham,4.415989,67.0
7,Konaté,d,25.0,24.0,DEF,Liverpool,Newcastle,4.319943,85.0
8,Reijnders,a,NaN,24.0,MID,Man City,Spurs,4.272504,63.0
9,Raúl,a,100.0,24.0,FWD,Fulham,Man Utd,4.158901,84.0
10,Gibbs-White,a,100.0,24.0,MID,Nott'm Forest,Crystal Palace,4.120044,83.0
11,Mitoma,a,100.0,24.0,MID,Brighton,Everton,3.877180,76.0
12,Martinez,d,75.0,24.0,GK,Aston Villa,Brentford,3.829624,90.0
13,Gyökeres,a,100.0,24.0,FWD,Arsenal,Leeds,3.485677,50.0
14,Tarkowski,a,NaN,24.0,DEF,Everton,Brighton,3.393834,86.0

In [6]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
        -- AND position IN ('MID','FWD')
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 24

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,White,a,100.0,24.0,DEF,Arsenal,Leeds,5.060300
1,Alleyne,a,NaN,24.0,DEF,Man City,Spurs,4.938547
2,Hume,a,NaN,24.0,DEF,Sunderland,Burnley,4.934503
3,Amad,a,100.0,24.0,MID,Man Utd,Fulham,4.866357
4,Truffert,a,NaN,24.0,DEF,Bournemouth,Wolves,4.618026
5,Reinildo,a,100.0,24.0,DEF,Sunderland,Burnley,4.585262
6,Mosquera,a,100.0,24.0,DEF,Arsenal,Leeds,4.558956
7,Senesi,a,100.0,24.0,DEF,Bournemouth,Wolves,4.484197
8,A.Jimenez,a,NaN,24.0,DEF,Bournemouth,Wolves,4.483818
9,Zubimendi,a,100.0,24.0,MID,Arsenal,Leeds,4.477297

In [7]:
print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 38
    ORDER BY xpoints DESC
""")
view.head(10)

When to use second TRIPLE CAPTAIN chip (gws19-38)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,31.0,DEF,Arsenal,Wolves,5.916582
1,Gabriel dos Santos Magalhães,37.0,DEF,Arsenal,Burnley,5.907078
2,Gabriel dos Santos Magalhães,36.0,DEF,Arsenal,West Ham,5.871777
3,Gabriel dos Santos Magalhães,24.0,DEF,Arsenal,Leeds,5.871777
4,Gabriel dos Santos Magalhães,27.0,DEF,Arsenal,Spurs,5.821863
5,Abdukodir Khusanov,34.0,DEF,Man City,Burnley,5.512516
6,Matheus Nunes,34.0,DEF,Man City,Burnley,5.421986
7,Matheus Nunes,30.0,DEF,Man City,West Ham,5.188535
8,Matheus Nunes,28.0,DEF,Man City,Leeds,5.183555
9,Matheus Nunes,24.0,DEF,Man City,Spurs,5.142156

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND 38")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND 38
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW24 AND 38

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1041.0,76.45,72.6,0.102,0.089,0.858
1,Amad Diallo,0,MID,Man Utd,1063.3,73.80,69.6,0.382,0.225,1.510
2,Benjamin White,0,DEF,Arsenal,1041.0,68.86,68.8,0.060,0.067,0.934
3,John Stones,0,DEF,Man City,1065.0,68.60,57.3,0.284,0.123,1.286
4,Conor Gallagher,0,MID,Spurs,1088.1,67.66,71.5,0.260,0.206,1.593
5,Dominik Szoboszlai,1,MID,Liverpool,1063.6,67.36,84.4,0.163,0.163,1.206
6,Ibrahima Konaté,1,DEF,Liverpool,1063.6,66.50,85.4,0.043,0.040,1.077
7,Bruno Borges Fernandes,1,MID,Man Utd,1063.3,66.43,66.9,0.214,0.273,1.352
8,Matheus Nunes,1,DEF,Man City,1065.0,66.43,65.9,0.038,0.083,0.961
9,Joško Gvardiol,0,DEF,Man City,1065.0,65.65,59.4,0.118,0.063,1.004
10,Max Alleyne,0,DEF,Man City,1065.0,64.83,75.6,0.035,0.041,1.040
11,Martín Zubimendi Ibáñez,0,MID,Arsenal,1041.0,64.62,75.9,0.166,0.116,0.948
12,Abdukodir Khusanov,1,DEF,Man City,1065.0,64.55,77.1,0.038,0.046,1.080
13,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1065.0,63.46,59.9,0.108,0.049,1.052
14,Moisés Caicedo Corozo,0,MID,Chelsea,1062.0,63.34,79.4,0.160,0.139,1.280
15,Trai Hume,0,DEF,Sunderland,1062.6,62.92,73.3,0.074,0.283,1.517
16,Cristhian Mosquera,0,DEF,Arsenal,1041.0,62.82,57.8,0.188,0.060,1.199
17,Marcus Tavernier,0,MID,Bournemouth,1058.7,62.78,78.5,0.144,0.153,1.222
18,Raúl Jiménez Rodríguez,1,FWD,Fulham,1067.1,62.64,83.8,0.378,0.056,1.300
19,Alex Scott,0,MID,Bournemouth,1058.7,62.56,82.8,0.146,0.106,1.256
20,Conor Bradley,0,DEF,Liverpool,1063.6,62.34,67.6,0.035,0.059,1.053
21,Morgan Gibbs-White,1,MID,Nott'm Forest,1061.2,62.31,82.8,0.150,0.128,1.304
22,Youri Tielemans,0,MID,Aston Villa,1043.4,62.20,79.5,0.101,0.167,1.114
23,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1065.0,62.14,79.8,0.103,0.138,0.996
24,Vitaly Janelt,0,MID,Brentford,1070.1,61.60,82.0,0.126,0.127,1.321
25,Emile Smith Rowe,0,MID,Fulham,1067.1,61.21,76.0,0.156,0.117,1.280
26,Ibrahim Sangaré,0,MID,Nott'm Forest,1061.2,61.04,64.2,0.259,0.147,1.412
27,Brian Brobbey,1,FWD,Sunderland,1062.6,61.00,84.6,0.304,0.086,1.367
28,Ethan Pinnock,0,DEF,Brentford,1070.1,60.96,67.1,0.182,0.042,1.438
29,Enzo Le Fée,0,MID,Sunderland,1062.6,60.89,85.6,0.098,0.139,1.364
30,Emiliano Martínez Romero,1,GK,Aston Villa,1043.4,60.66,89.9,NaN,NaN,1.057
31,Harvey Barnes,0,MID,Newcastle,1083.2,60.64,70.2,0.196,0.123,1.357
32,Tijjani Reijnders,1,MID,Man City,1065.0,60.49,63.0,0.190,0.151,0.904
33,Carlos Henrique Casimiro,0,MID,Man Utd,1063.3,60.43,72.5,0.164,0.142,1.354
34,Crysencio Summerville,0,MID,West Ham,1079.8,60.37,83.6,0.147,0.099,1.483
35,Julio Soler Barreto,0,DEF,Bournemouth,1058.7,60.25,57.9,0.241,0.067,1.409
36,Callum Hudson-Odoi,0,MID,Nott'm Forest,1061.2,60.23,81.2,0.138,0.103,1.282
37,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1079.8,60.11,83.6,0.116,0.125,1.458
38,James Ward-Prowse,0,MID,West Ham,1079.8,60.07,52.8,0.428,0.167,1.844
39,Adrien Truffert,0,DEF,Bournemouth,1058.7,60.01,86.3,0.038,0.061,1.269
40,Matthijs de Ligt,0,DEF,Man Utd,1063.3,60.00,64.0,0.236,0.047,1.432
41,Brenden Aaronson,0,MID,Leeds,1061.8,59.65,81.0,0.139,0.107,1.343
42,Matt O'Riley,0,MID,Brighton,1060.8,59.64,52.1,0.399,0.188,1.733
43,Diego Coppola,0,DEF,Brighton,1060.8,59.61,64.7,0.177,0.049,1.451
44,Marcos Senesi Barón,0,DEF,Bournemouth,1058.7,59.33,82.6,0.038,0.046,1.240
45,David Raya Martín,1,GK,Arsenal,1041.0,59.20,89.9,NaN,NaN,0.996
46,Ferdi Kadıoğlu,0,DEF,Brighton,1060.8,59.14,83.5,0.046,0.051,1.359
47,Mitoma Kaoru,1,MID,Brighton,1060.8,58.87,75.7,0.136,0.115,1.281
48,Facundo Buonanotte,0,MID,Leeds,1061.8,58.84,52.8,0.398,0.157,1.688
49,Nikola Milenković,0,DEF,Nott'm Forest,1061.2,58.71,85.2,0.034,0.039,1.305

In [9]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW24 AND 28

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1040.1,25.82,72.7,0.102,0.086,0.832
1,Amad Diallo,0,MID,Man Utd,1029.1,24.75,69.6,0.378,0.234,1.412
2,John Stones,0,DEF,Man City,1059.6,23.12,57.1,0.282,0.124,1.250
3,Benjamin White,0,DEF,Arsenal,1040.1,23.09,68.9,0.059,0.066,0.925
4,Matheus Nunes,1,DEF,Man City,1059.6,22.77,66.0,0.038,0.083,0.908
5,Dominik Szoboszlai,1,MID,Liverpool,1071.6,22.44,84.4,0.162,0.161,1.169
6,Joško Gvardiol,0,DEF,Man City,1059.6,22.32,59.5,0.118,0.063,0.967
7,Bruno Borges Fernandes,1,MID,Man Utd,1029.1,22.31,66.9,0.214,0.276,1.275
8,Moisés Caicedo Corozo,0,MID,Chelsea,1001.3,22.06,78.7,0.182,0.151,1.162
9,Conor Gallagher,0,MID,Spurs,1141.9,22.03,71.3,0.253,0.197,1.804
10,Max Alleyne,0,DEF,Man City,1059.6,22.03,75.6,0.035,0.041,0.999
11,Ibrahima Konaté,1,DEF,Liverpool,1071.6,21.99,85.4,0.043,0.039,1.099
12,Abdukodir Khusanov,1,DEF,Man City,1059.6,21.92,77.0,0.038,0.046,1.040
13,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1059.6,21.60,60.0,0.106,0.048,1.012
14,Martín Zubimendi Ibáñez,0,MID,Arsenal,1040.1,21.57,75.7,0.167,0.115,0.924
15,Marcus Tavernier,0,MID,Bournemouth,1032.8,21.25,78.6,0.146,0.163,1.148
16,Alex Scott,0,MID,Bournemouth,1032.8,21.08,82.9,0.147,0.109,1.187
17,Youri Tielemans,0,MID,Aston Villa,1017.9,21.07,79.5,0.103,0.179,1.065
18,Morgan Gibbs-White,1,MID,Nott'm Forest,1038.1,21.07,82.8,0.155,0.134,1.267
19,Cristhian Mosquera,0,DEF,Arsenal,1040.1,21.03,57.7,0.189,0.059,1.184
20,Raúl Jiménez Rodríguez,1,FWD,Fulham,1077.2,20.74,84.0,0.367,0.055,1.295
21,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1059.6,20.74,79.9,0.102,0.138,0.977
22,Benoît Badiashile Mukinayi,0,DEF,Chelsea,1001.3,20.71,71.3,0.099,0.048,1.254
23,Adrien Truffert,0,DEF,Bournemouth,1032.8,20.70,86.3,0.038,0.061,1.197
24,Matthijs de Ligt,0,DEF,Man Utd,1029.1,20.67,64.2,0.234,0.049,1.375
25,Conor Bradley,0,DEF,Liverpool,1071.6,20.62,67.5,0.036,0.058,1.073
26,Ibrahim Sangaré,0,MID,Nott'm Forest,1038.1,20.53,64.3,0.259,0.154,1.355
27,Julio Soler Barreto,0,DEF,Bournemouth,1032.8,20.48,57.4,0.242,0.066,1.346
28,Wesley Fofana,0,DEF,Chelsea,1001.3,20.48,68.7,0.036,0.045,1.116
29,Trai Hume,0,DEF,Sunderland,1086.8,20.46,73.2,0.075,0.284,1.576
30,Brian Brobbey,1,FWD,Sunderland,1086.8,20.42,84.1,0.315,0.089,1.499
31,Carlos Henrique Casimiro,0,MID,Man Utd,1029.1,20.41,72.4,0.165,0.149,1.285
32,Emiliano Martínez Romero,1,GK,Aston Villa,1017.9,20.39,89.9,NaN,NaN,1.026
33,Vitaly Janelt,0,MID,Brentford,1098.8,20.36,81.9,0.125,0.122,1.353
34,Marcos Senesi Barón,0,DEF,Bournemouth,1032.8,20.35,82.6,0.038,0.047,1.181
35,Callum Hudson-Odoi,0,MID,Nott'm Forest,1038.1,20.32,81.2,0.140,0.108,1.236
36,Tijjani Reijnders,1,MID,Man City,1059.6,20.32,63.1,0.194,0.152,0.876
37,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1061.7,20.25,83.5,0.117,0.131,1.433
38,Álex Jiménez Sánchez,0,DEF,Bournemouth,1032.8,20.22,82.9,0.042,0.050,1.204
39,Crysencio Summerville,0,MID,West Ham,1061.7,20.22,83.6,0.148,0.101,1.476
40,Ethan Pinnock,0,DEF,Brentford,1098.8,20.20,67.3,0.183,0.040,1.459
41,Nikola Milenković,0,DEF,Nott'm Forest,1038.1,20.20,85.2,0.034,0.039,1.236
42,Emile Smith Rowe,0,MID,Fulham,1077.2,20.19,76.1,0.153,0.112,1.318
43,David Raya Martín,1,GK,Arsenal,1040.1,20.18,89.9,NaN,NaN,0.959
44,Enzo Le Fée,0,MID,Sunderland,1086.8,20.10,85.5,0.097,0.136,1.466
45,James Ward-Prowse,0,MID,West Ham,1061.7,20.09,52.9,0.428,0.166,1.847
46,Harvey Barnes,0,MID,Newcastle,1102.6,20.06,70.2,0.196,0.121,1.430
47,Tosin Adarabioyo,0,DEF,Chelsea,1001.3,20.06,76.0,0.037,0.044,1.235
48,Filip Jörgensen,0,GK,Chelsea,1001.3,20.04,89.2,NaN,NaN,1.259
49,Neco Williams,0,DEF,Nott'm Forest,1038.1,19.98,83.4,0.034,0.041,1.262

In [10]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW24 AND 28

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Viktor Gyökeres,1,FWD,Arsenal,1040.1,16.53,50.2,0.490,0.064,0.930
1,James Tarkowski,1,DEF,Everton,1073.1,17.06,85.7,0.037,0.039,1.651
2,Mitoma Kaoru,1,MID,Brighton,1075.7,19.45,75.8,0.136,0.113,1.330
3,David Raya Martín,1,GK,Arsenal,1040.1,20.18,89.9,NaN,NaN,0.959
4,Tijjani Reijnders,1,MID,Man City,1059.6,20.32,63.1,0.194,0.152,0.876
5,Emiliano Martínez Romero,1,GK,Aston Villa,1017.9,20.39,89.9,NaN,NaN,1.026
6,Brian Brobbey,1,FWD,Sunderland,1086.8,20.42,84.1,0.315,0.089,1.499
7,Raúl Jiménez Rodríguez,1,FWD,Fulham,1077.2,20.74,84.0,0.367,0.055,1.295
8,Morgan Gibbs-White,1,MID,Nott'm Forest,1038.1,21.07,82.8,0.155,0.134,1.267
9,Abdukodir Khusanov,1,DEF,Man City,1059.6,21.92,77.0,0.038,0.046,1.040
10,Ibrahima Konaté,1,DEF,Liverpool,1071.6,21.99,85.4,0.043,0.039,1.099
11,Bruno Borges Fernandes,1,MID,Man Utd,1029.1,22.31,66.9,0.214,0.276,1.275
12,Dominik Szoboszlai,1,MID,Liverpool,1071.6,22.44,84.4,0.162,0.161,1.169
13,Matheus Nunes,1,DEF,Man City,1059.6,22.77,66.0,0.038,0.083,0.908
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1040.1,25.82,72.7,0.102,0.086,0.832

In [11]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team: 24 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Man Utd,Amad Diallo,73.798224,Mitoma Kaoru,58.868505,14.929719
1,DEF,Arsenal,Benjamin White,68.864307,James Tarkowski,54.161522,14.702785
2,DEF,Man City,John Stones,68.599541,James Tarkowski,54.161522,14.438019
3,DEF,Man City,Joško Gvardiol,65.654817,James Tarkowski,54.161522,11.493295
4,DEF,Man City,Max Alleyne,64.831970,James Tarkowski,54.161522,10.670448
5,DEF,Man City,Rúben dos Santos Gato Alves Dias,63.462994,James Tarkowski,54.161522,9.301472
6,MID,Spurs,Conor Gallagher,67.663805,Mitoma Kaoru,58.868505,8.795300
7,DEF,Sunderland,Trai Hume,62.916169,James Tarkowski,54.161522,8.754647
8,DEF,Arsenal,Cristhian Mosquera,62.818490,James Tarkowski,54.161522,8.656968
9,DEF,Liverpool,Conor Bradley,62.340655,James Tarkowski,54.161522,8.179133
10,FWD,Liverpool,Alexander Isak,57.269802,Viktor Gyökeres,49.538310,7.731492
11,DEF,Brentford,Ethan Pinnock,60.960793,James Tarkowski,54.161522,6.799271
12,DEF,Bournemouth,Julio Soler Barreto,60.248413,James Tarkowski,54.161522,6.086891
13,DEF,Bournemouth,Adrien Truffert,60.007813,James Tarkowski,54.161522,5.846291
14,DEF,Man Utd,Matthijs de Ligt,60.001807,James Tarkowski,54.161522,5.840285
15,MID,Arsenal,Martín Zubimendi Ibáñez,64.623151,Mitoma Kaoru,58.868505,5.754646
16,DEF,Brighton,Diego Coppola,59.611539,James Tarkowski,54.161522,5.450017
17,FWD,Newcastle,William Osula,54.739211,Viktor Gyökeres,49.538310,5.200900
18,DEF,Bournemouth,Marcos Senesi Barón,59.327012,James Tarkowski,54.161522,5.165490
19,DEF,Brighton,Ferdi Kadıoğlu,59.143344,James Tarkowski,54.161522,4.981822

In [17]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Amad Diallo'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 24 and 28:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Amad Diallo,24.0,MID,Man Utd,Fulham,6.2,1062.457219,4.866357,69.552497,0.381328,0.221498,1.618935
1,Amad Diallo,25.0,MID,Man Utd,Spurs,6.2,990.668127,5.042937,69.580628,0.370472,0.247486,1.158673
2,Amad Diallo,26.0,MID,Man Utd,West Ham,6.2,971.988000,5.078222,69.580628,0.374219,0.250614,1.119846
3,Amad Diallo,27.0,MID,Man Utd,Everton,6.2,1063.956178,4.868977,69.552497,0.381328,0.221498,1.605794
4,Amad Diallo,28.0,MID,Man Utd,Crystal Palace,6.2,1056.251684,4.895083,69.552497,0.382335,0.226763,1.557147

In [13]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [14]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [15]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.02 minute(s)