In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

# Load TRDL Data

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 6
current_season = 20262027

In [5]:
#fpl_picks_history:
#combine fpl_picks and fpl_picks2 into a single sql table in the database
#add fpl_picks_{current_season} and fpl_picks_2_{current_season} into a single sql table in the database

In [6]:
# Erling Haaland goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT player_name_id, season, event, fixture, goals_scored, expected_goals, expected_assists, assists
                          FROM playergw_transformed
                          WHERE expected_goals IS NOT NULL
                            AND player_name_id = 'Erling Haaland'
                          ORDER BY season, event, fixture
""")
view.pivot_table(index=['season'], values=['goals_scored', 'expected_goals', 'expected_assists', 'assists'], aggfunc='sum',margins=True,dropna=False)

            assists  expected_assists  expected_goals  goals_scored
season
20222023.0      9.0           1.33591         17.4943          36.0
20232024.0      8.0           2.18000         29.5700          27.0
20242025.0      3.0           2.04000         21.9000          22.0
20252026.0      8.0           2.67000         25.5000          27.0
20262027.0      0.0           0.54000          4.8200           6.0
All            28.0           8.76591         99.2843         118.0

In [7]:
# Erling Haaland goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT *
FROM predictions
""")
view.columns

Index(['player_name_id', 'element', 'season', 'event', 'team_name', 'team_elo',
       'opp_team_name', 'opp_team_elo', 'team_attack_elo',
       'opp_team_attack_elo', 'team_defence_elo', 'opp_team_defence_elo',
       'position', 'value', 'fixture_count', 'mins_pred', 'xpoints',
       'xpoints_mins', 'xpoints_goals', 'xpoints_assists',
       'xg_overperf_factor', 'xa_overperf_factor', 'xpoints_clean_sheets',
       'xpoints_shots_saved', 'xpoints_goals_conceded', 'xpoints_defcon',
       'xpoints_bonus', 'xgp90_pred', 'xap90_pred', 'xgcp90_pred',
       'in_any_team', 'in_my_team', 'latest_any_team', 'latest_my_team',
       'prediction_timestamp', 'prediction_gameweek'],
      dtype='str')

In [8]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

from FPL_Optimizer import FPLOptimizer

remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {current_gw+1} AND 38
""")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=remaining_gw_predictions[remaining_gw_predictions['event']==current_gw+1],
        budget=999.9,
        column_mapping=custom_columns
    )
    optimizer.optimize()

    # Get results as DataFrames
    # squad = optimizer.get_squad_dataframe()
    # starting_xi = optimizer.get_starting_xi_dataframe()
    result = optimizer.calculate_bench_boost_xpoints()
    result['event'] = current_gw+1

Optimizing team selection for GW7 to GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 53.17
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.34
 ✅        Martinez                       Chelsea      £5.0     3.64

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.53
 🪑        Mykolenko                      Everton      £4.6     3.69
 ✅        Khusanov                       Man City     £5.4     4.68
 ✅        Matheus N.                     Man City     £5.9     5.41
 ✅        Calafiori                      Arsenal      £5.9     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.94
 ✅        Xhaka                          Sunderland   £5.4     4.56
 ✅        Barnes                         Newcastle    £6.1     4.75
 ✅        Tavernier                      Bournemouth  £6.1     4.50
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.98

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.02
 ✅        Haaland                        Man City     £15.6    6.27
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

In [9]:
print(f"Team Selection Details - GW {current_gw+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        xpoints,
        CAST(ROUND(mins_pred) as INT) as mins_pred,
        CAST(ROUND(team_elo) as INT) as team_elo,
        CAST(ROUND(team_attack_elo) as INT) as team_attack_elo,
        CAST(ROUND(team_defence_elo) as INT) as team_defence_elo,
        opp_team_name,
        CAST(ROUND(opp_team_elo) as INT) as opp_team_elo,
        CAST(ROUND(opp_team_attack_elo) as INT) as opp_team_attack_elo,
        CAST(ROUND(opp_team_defence_elo) as INT) as opp_team_defence_elo,
        ROUND(xgp90_pred, 2) as xgp90_pred,
        ROUND(xg_overperf_factor, 2) as xg_overperf_factor,
        ROUND(xap90_pred, 2) as xap90_pred,
        ROUND(xa_overperf_factor, 2) as xa_overperf_factor,
        ROUND(xgcp90_pred, 2) as xgcp90_pred
        

    FROM predictions_status
    WHERE latest_my_team = 1
        AND event = {current_gw+1}
    ORDER BY xpoints DESC
""")
# print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view#.head(15)

Team Selection Details - GW 7

,web_name,status,chance_of_playing_this_round,event,position,team_name,xpoints,mins_pred,team_elo,team_attack_elo,team_defence_elo,opp_team_name,opp_team_elo,opp_team_attack_elo,opp_team_defence_elo,xgp90_pred,xg_overperf_factor,xap90_pred,xa_overperf_factor,xgcp90_pred
0,Haaland,a,NaN,7.0,FWD,Man City,6.266831,80,1267,1368,1301,Ipswich Town,1011,1028,966,0.88,1.16,0.19,2.90,1.09
1,Matheus N.,a,100.0,7.0,DEF,Man City,5.407393,81,1267,1368,1301,Ipswich Town,1011,1028,966,0.04,1.00,0.34,2.58,0.84
2,Gibbs-White,a,100.0,7.0,MID,Nott'm Forest,4.977240,85,1024,1018,1149,Arsenal,1264,1202,1348,0.23,1.00,0.32,1.90,1.74
3,Calafiori,a,NaN,7.0,DEF,Arsenal,4.757564,77,1264,1202,1348,Nott'm Forest,1024,1018,1149,0.08,1.00,0.13,1.86,0.93
4,Barnes,a,NaN,7.0,MID,Newcastle,4.750357,83,1057,1126,991,Aston Villa,1103,1097,1062,0.32,1.37,0.16,1.00,1.57
5,Khusanov,a,NaN,7.0,DEF,Man City,4.676348,67,1267,1368,1301,Ipswich Town,1011,1028,966,0.06,1.00,0.08,1.00,0.89
6,Xhaka,a,NaN,7.0,MID,Sunderland,4.558687,84,1034,980,1059,Bournemouth,1081,1088,1103,0.12,1.66,0.25,1.78,1.36
7,Tavernier,a,NaN,7.0,MID,Bournemouth,4.495081,73,1081,1088,1103,Sunderland,1034,980,1059,0.25,1.00,0.23,1.31,1.35
8,Thiago,a,NaN,7.0,FWD,Brentford,4.339247,87,1085,1141,1162,Liverpool,1144,1139,1135,0.46,1.00,0.05,1.00,1.50
9,Gakpo,i,0.0,7.0,MID,Liverpool,3.935087,70,1144,1139,1135,Brentford,1085,1141,1162,0.23,1.00,0.20,1.35,1.38
10,Mykolenko,d,75.0,7.0,DEF,Everton,3.694322,87,1056,1019,1166,Chelsea,1085,1201,1014,0.04,1.00,0.04,1.00,1.53
11,Martinez,a,NaN,7.0,GK,Chelsea,3.642546,90,1085,1201,1014,Everton,1056,1019,1166,NaN,1.00,NaN,1.00,1.30
12,Khalaili,a,100.0,7.0,DEF,Crystal Palace,3.532383,82,1029,1014,1034,Brighton,1107,1238,1221,0.06,1.00,0.06,1.00,1.53
13,A.Becker,a,NaN,7.0,GK,Liverpool,3.344480,90,1144,1139,1135,Brentford,1085,1141,1162,NaN,1.00,NaN,1.00,1.48
14,Emersonn,a,100.0,7.0,FWD,Ipswich Town,3.019564,64,1011,1028,966,Man City,1267,1368,1301,0.34,1.00,0.05,1.00,1.80

In [10]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{current_gw+1} AND {current_gw+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {current_gw+1} AND {current_gw+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW7 AND 11

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Emersonn Correia da Silva,1,FWD,Ipswich Town,1072.4,15.66,64.8,0.358,1.000,0.046,1.000,1.391
1,Alisson Becker,1,GK,Liverpool,1121.0,17.02,90.0,NaN,1.000,NaN,1.000,1.478
2,Anan Khalaili,1,DEF,Crystal Palace,1055.9,18.08,82.4,0.065,1.000,0.065,1.000,1.516
3,Emiliano Martínez Romero,1,GK,Chelsea,1043.0,18.26,90.0,NaN,1.000,NaN,1.000,1.314
4,Vitalii Mykolenko,1,DEF,Everton,1098.3,18.45,87.0,0.045,1.000,0.041,1.000,1.541
5,Cody Gakpo,1,MID,Liverpool,1121.0,19.47,69.2,0.225,1.000,0.205,1.349,1.397
6,Igor Thiago Nascimento Rodrigues,1,FWD,Brentford,1070.3,21.85,86.5,0.469,1.000,0.051,1.000,1.330
7,Abdukodir Khusanov,1,DEF,Man City,1052.0,22.06,67.8,0.058,1.000,0.080,1.000,1.060
8,Marcus Tavernier,1,MID,Bournemouth,1044.6,22.25,73.0,0.240,1.000,0.225,1.308,1.391
9,Riccardo Calafiori,1,DEF,Arsenal,1060.3,22.82,76.9,0.076,1.000,0.129,1.860,1.017
10,Granit Xhaka,1,MID,Sunderland,1060.7,23.32,84.3,0.122,1.662,0.266,1.779,1.345
11,Matheus Nunes,1,DEF,Man City,1052.0,23.56,81.3,0.040,1.000,0.214,2.580,1.060
12,Harvey Barnes,1,MID,Newcastle,1093.4,24.20,82.6,0.337,1.372,0.159,1.000,1.517
13,Morgan Gibbs-White,1,MID,Nott'm Forest,1141.5,25.94,85.2,0.240,1.000,0.352,1.896,1.506
14,Erling Haaland,1,FWD,Man City,1052.0,30.34,79.3,0.829,1.163,0.193,2.898,1.161

In [11]:
## Multi-week Optimizer

# from FPL_Optimizer import FPLOptimizer

# remaining_gw_predictions = db_creator.run_sql(f"""
    
#     WITH predictions_status AS (
#     SELECT *
#     FROM predictions
#     LEFT JOIN player_status ON predictions.element = player_status.id
#     )
#     SELECT
#         web_name,
#         status,
#         now_cost/10 as value,
#         chance_of_playing_this_round,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints,
#         ROUND(mins_pred) as mins_pred
#     FROM predictions_status
#     WHERE latest_my_team = 1
#         AND event BETWEEN {current_gw+1} AND 38
# """)

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(current_gw + 1, current_gw + 11):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW7...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 53.17
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.34
 ✅        Martinez                       Chelsea      £5.0     3.64

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.53
 🪑        Mykolenko                      Everton      £4.6     3.69
 ✅        Khusanov                       Man City     £5.4     4.68
 ✅        Matheus N.                     Man City     £5.9     5.41
 ✅        Calafiori                      Arsenal      £5.9     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.94
 ✅        Xhaka                          Sunderland   £5.4     4.56
 ✅        Barnes                         Newcastle    £6.1     4.75
 ✅        Tavernier                      Bournemouth  £6.1     4.50
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.98

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.02
 ✅        Haaland                        Man City     £15.6    6.27
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW8...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 51.37
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.33
 ✅        Martinez                       Chelsea      £5.0     3.68

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.69
 🪑        Mykolenko                      Everton      £4.6     3.07
 ✅        Khusanov                       Man City     £5.4     4.10
 ✅        Matheus N.                     Man City     £5.9     4.16
 ✅        Calafiori                      Arsenal      £5.9     4.54

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.84
 ✅        Xhaka                          Sunderland   £5.4     4.63
 ✅        Barnes                         Newcastle    £6.1     4.88
 ✅        Tavernier                      Bournemouth  £6.1     4.31
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.58

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.18
 ✅        Haaland                        Man City     £15.6    5.98
 ✅        Thiago                         Brentford    £7.8     4.37

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 51.17
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.33
 ✅        Martinez                       Chelsea      £5.0     3.63

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     3.74
 ✅        Khusanov                       Man City     £5.4     4.10
 ✅        Khalaili                       Crystal Palace £5.0     3.82
 ✅        Matheus N.                     Man City     £5.9     4.16
 ✅        Calafiori                      Arsenal      £5.9     4.27

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.69
 ✅        Xhaka                          Sunderland   £5.4     4.90
 ✅        Barnes                         Newcastle    £6.1     4.90
 ✅        Tavernier                      Bournemouth  £6.1     4.39
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.18

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.16
 ✅        Haaland                        Man City     £15.6    6.04
 ✅        Thiago                         Brentford    £7.8     4.38

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 52.85
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.60
 ✅        Martinez                       Chelsea      £5.0     3.66

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.37
 ✅        Khusanov                       Man City     £5.4     4.37
 ✅        Matheus N.                     Man City     £5.9     4.70
 ✅        Calafiori                      Arsenal      £5.9     4.74
 ✅        Mykolenko                      Everton      £4.6     4.27

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     4.06
 ✅        Xhaka                          Sunderland   £5.4     4.67
 ✅        Barnes                         Newcastle    £6.1     5.04
 ✅        Tavernier                      Bournemouth  £6.1     4.62
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.97

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.09
 ✅        Haaland                        Man City     £15.6    6.01
 ✅        Thiago                         Brentford    £7.8     4.38

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 52.75
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.41
 ✅        Martinez                       Chelsea      £5.0     3.65

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.67
 🪑        Mykolenko                      Everton      £4.6     3.67
 ✅        Khusanov                       Man City     £5.4     4.81
 ✅        Matheus N.                     Man City     £5.9     5.14
 ✅        Calafiori                      Arsenal      £5.9     4.51

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.94
 ✅        Xhaka                          Sunderland   £5.4     4.57
 ✅        Barnes                         Newcastle    £6.1     4.64
 ✅        Tavernier                      Bournemouth  £6.1     4.44
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.24

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.21
 ✅        Haaland                        Man City     £15.6    6.04
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 49.79
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.55
 ✅        Martinez                       Chelsea      £5.0     3.71

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khusanov                       Man City     £5.4     3.52
 🪑        Mykolenko                      Everton      £4.6     3.63
 ✅        Khalaili                       Crystal Palace £5.0     3.73
 ✅        Matheus N.                     Man City     £5.9     3.90
 ✅        Calafiori                      Arsenal      £5.9     3.74

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.99
 ✅        Xhaka                          Sunderland   £5.4     4.97
 ✅        Barnes                         Newcastle    £6.1     4.71
 ✅        Tavernier                      Bournemouth  £6.1     4.51
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.35

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.15
 ✅        Haaland                        Man City     £15.6    5.43
 ✅        Thiago                         Brentford    £7.8     4.36

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 51.45
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.60
 ✅        Martinez                       Chelsea      £5.0     3.68

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.61
 🪑        Mykolenko                      Everton      £4.6     3.65
 ✅        Khusanov                       Man City     £5.4     4.16
 ✅        Matheus N.                     Man City     £5.9     4.34
 ✅        Calafiori                      Arsenal      £5.9     4.56

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.05
 ✅        Xhaka                          Sunderland   £5.4     4.48
 ✅        Barnes                         Newcastle    £6.1     4.79
 ✅        Tavernier                      Bournemouth  £6.1     4.21
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.41

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.19
 ✅        Haaland                        Man City     £15.6    6.03
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 52.02
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.46
 ✅        Martinez                       Chelsea      £5.0     3.60

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------

event     web_name position  7  8  9  10  11  12  13  14  15  16
2        Calafiori      DEF  1  1  1   1   1   1   1   1   1   1
7         Khalaili      DEF  0  0  1   0   0   1   0   0   0   0
8         Khusanov      DEF  1  1  1   1   1   0   1   0   1   1
10      Matheus N.      DEF  1  1  1   1   1   1   1   1   1   1
11       Mykolenko      DEF  0  0  0   1   0   0   0   1   0   0
3         Emersonn      FWD  0  0  0   0   0   0   0   0   0   0
6          Haaland      FWD  1  1  1   1   1   1   1   1   1   1
13          Thiago      FWD  1  1  1   1   1   1   1   1   1   1
0         A.Becker       GK  0  0  0   0   0   0   0   0   0   1
9         Martinez       GK  1  1  1   1   1   1   1   1   1   0
1           Barnes      MID  1  1  1   1   1   1   1   1   1   1
4            Gakpo      MID  1  1  0   0   1   1   1   1   1   1
5      Gibbs-White      MID  1  1  1   1   1   1   1   1   1   1
12       Tavernier      MID  1  1  1   1   1   1   1   1   1   1
14           Xhaka      MID  1  1  1   1   1   1   1   1   1   1

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{current_gw+1} to GW{current_gw+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.5 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {current_gw+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN xpoints * {initial_weight}
                WHEN event = {current_gw+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {current_gw+1} AND {current_gw+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'FWD'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW7 to GW11
Decay factor: 0.5, Weights: [0.52, 0.26, 0.13, 0.06, 0.03]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Erling Haaland,a,1,FWD,Man City,1048.2,6.14,79.3,0.829,1.163,0.193,2.898,1.161
1,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1169.9,5.17,85.2,0.240,1.000,0.352,1.896,1.506
2,Bobby Thomas,a,0,DEF,Coventry City,997.8,4.89,84.7,0.052,1.000,0.031,1.000,1.261
3,Matheus Nunes,a,1,DEF,Man City,1048.2,4.87,81.3,0.040,1.000,0.214,2.580,1.060
4,Phil Foden,a,0,MID,Man City,1048.2,4.85,52.1,0.756,1.604,0.206,1.000,0.993
5,Harvey Barnes,a,1,MID,Newcastle,1077.4,4.82,82.6,0.337,1.372,0.159,1.000,1.517
6,Rico Lewis,a,0,DEF,Man City,1048.2,4.82,61.2,0.133,1.000,0.153,1.000,1.200
7,Rayan Aït-Nouri,a,0,DEF,Man City,1048.2,4.77,63.8,0.089,1.000,0.092,1.000,1.007
8,Jack Rudoni,a,0,MID,Coventry City,997.8,4.71,74.7,0.277,1.000,0.253,1.000,1.253
9,Riccardo Calafiori,a,1,DEF,Arsenal,1048.7,4.63,76.9,0.076,1.000,0.129,1.860,1.017
10,Granit Xhaka,a,1,MID,Sunderland,1059.4,4.63,84.3,0.122,1.662,0.266,1.779,1.345
11,Luka Vušković,a,0,DEF,Brighton,1093.0,4.48,86.2,0.067,1.000,0.032,1.000,1.414
12,Jun'ai Byfield,a,0,DEF,Spurs,1028.4,4.45,49.4,0.105,1.000,0.095,1.000,0.610
13,James Hill,a,0,DEF,Bournemouth,1054.1,4.45,84.3,0.037,1.000,0.090,1.506,1.359
14,Marcus Tavernier,a,1,MID,Bournemouth,1054.1,4.44,73.0,0.240,1.000,0.225,1.308,1.391
15,Abdukodir Khusanov,a,1,DEF,Man City,1048.2,4.44,67.8,0.058,1.000,0.080,1.000,1.060
16,Anton Stach,a,0,MID,Leeds,1081.5,4.40,85.4,0.178,1.000,0.132,1.000,1.328
17,John McGinn,a,0,MID,Aston Villa,1109.0,4.39,84.5,0.214,1.000,0.187,1.349,1.416
18,Igor Thiago Nascimento Rodrigues,a,1,FWD,Brentford,1091.5,4.35,86.5,0.469,1.000,0.051,1.000,1.330
19,Harry Amass,a,0,DEF,Man Utd,1061.2,4.32,66.4,0.173,1.000,0.155,1.000,1.746
20,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1054.1,4.30,82.4,0.208,1.000,0.123,1.000,1.434
21,Timothy Castagne,a,0,DEF,Fulham,1035.7,4.26,77.0,0.058,1.000,0.144,2.052,1.465
22,Diego Gómez Amarilla,a,0,MID,Brighton,1093.0,4.25,81.9,0.182,1.000,0.141,1.000,1.420
23,Diego Coppola,a,0,DEF,Brighton,1093.0,4.24,63.8,0.197,1.000,0.138,1.000,1.698
24,Jack Hinshelwood,d,0,MID,Brighton,1093.0,4.24,51.1,0.601,1.000,0.242,1.640,1.521
25,Vitaly Janelt,a,0,MID,Brentford,1091.5,4.22,84.7,0.126,1.410,0.096,1.000,1.331
26,Sávio Moreira de Oliveira,a,0,MID,Spurs,1028.4,4.21,83.1,0.148,1.000,0.178,1.000,1.386
27,António João Pereira de Albuquerque Tavares da...,a,0,DEF,Bournemouth,1054.1,4.20,70.8,0.094,1.000,0.087,1.000,1.548
28,Nobel Mendy,a,0,DEF,Hull City,1051.6,4.19,72.5,0.083,1.000,0.023,1.000,1.471
29,Adrien Truffert,a,0,DEF,Bournemouth,1054.1,4.18,86.7,0.056,1.000,0.121,1.441,1.395
30,Quinten Timber,a,0,MID,Crystal Palace,1075.6,4.18,83.9,0.174,1.000,0.110,1.000,1.475
31,Jaouen Hadjam,a,0,DEF,Brighton,1093.0,4.16,46.1,0.207,1.000,0.090,1.000,0.996
32,Harry Maguire,a,0,DEF,Man Utd,1061.2,4.15,86.6,0.060,1.000,0.124,2.707,1.458
33,Jay Dasilva,a,0,DEF,Coventry City,997.8,4.15,87.1,0.071,1.000,0.106,1.000,1.341
34,Alex Iwobi,a,0,MID,Fulham,1035.7,4.13,78.6,0.175,1.397,0.169,1.000,1.473
35,Kaden Braithwaite,a,0,DEF,Man City,1048.2,4.12,47.2,0.075,1.000,0.043,1.000,0.686
36,Kepa Arrizabalaga Revuelta,a,0,GK,Arsenal,1048.7,4.12,89.6,NaN,1.000,NaN,1.000,1.119
37,Dan Bentley,a,0,GK,Coventry City,997.8,4.11,89.6,NaN,1.000,NaN,1.000,1.170
38,Enzo Fernández,a,0,MID,Man City,1048.2,4.10,77.8,0.107,1.000,0.136,1.000,1.074
39,Semi Ajayi,a,0,DEF,Hull City,1051.6,4.10,85.6,0.073,1.000,0.032,1.000,1.516
40,Daichi Kamada,a,0,MID,Crystal Palace,1075.6,4.09,83.5,0.150,1.000,0.110,1.000,1.403
41,James Justin,a,0,DEF,Leeds,1081.5,4.08,86.8,0.060,1.000,0.099,1.865,1.359
42,Ben Wilson,a,0,GK,Coventry City,997.8,4.08,89.6,NaN,1.000,NaN,1.000,1.181
43,Ryan Sessegnon,a,0,DEF,Fulham,1035.7,4.08,59.9,0.142,2.075,0.087,1.389,1.488
44,Antonee Robinson,d,0,DEF,Fulham,1035.7,4.07,86.2,0.054,1.000,0.134,1.572,1.524
45,Ethan Ampadu,a,0,MID,Leeds,1081.5,4.07,85.7,0.064,1.000,0.106,1.670,1.315
46,Sven Botman,a,0,DEF,Newcastle,1077.4,4.06,81.7,0.066,1.000,0.047,1.000,1.498
47,Julio Enciso,a,0,MID,Ipswich Town,1150.7,4.05,77.2,0.191,1.000,0.219,1.527,1.481
48,Ferdi Kadıoğlu,a,0,DEF,Brighton,1093.0,4.05,86.0,0.053,1.000,0.037,1.000,1.393
49,Jannik Schuster,d,0,DEF,Brentford,1091.5,4.04,72.8,0.040,1.000,0.145,1.000,1.435

In [13]:
print(f"Best players to pick for the rest of the season: GW{current_gw+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    -- AND position IN ('MID')
    -- AND team_name = 'Liverpool'
  AND event BETWEEN {current_gw+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW7 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Erling Haaland,a,1,FWD,Man City,1064.8,191.78,79.2,1.163,0.807,2.898,0.193,1.192
1,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1083.9,168.92,85.2,1.000,0.242,1.896,0.368,1.397
2,Harvey Barnes,a,1,MID,Newcastle,1082.8,154.58,82.6,1.372,0.335,1.000,0.157,1.493
3,Phil Foden,a,0,MID,Man City,1064.8,154.16,52.0,1.604,0.754,1.000,0.208,1.037
4,Jack Rudoni,a,0,MID,Coventry City,1071.1,149.50,74.5,1.000,0.277,1.000,0.245,1.324
5,Granit Xhaka,a,1,MID,Sunderland,1068.7,149.32,84.3,1.662,0.122,1.779,0.267,1.383
6,Rico Lewis,a,0,DEF,Man City,1064.8,148.27,61.3,1.000,0.134,1.000,0.152,1.289
7,Rayan Aït-Nouri,a,0,DEF,Man City,1064.8,147.58,63.9,1.000,0.090,1.000,0.092,1.096
8,Riccardo Calafiori,a,1,DEF,Arsenal,1066.4,147.03,76.9,1.000,0.075,1.860,0.129,1.014
9,Matheus Nunes,a,1,DEF,Man City,1064.8,145.22,81.3,1.000,0.040,2.580,0.206,1.144
10,Bobby Thomas,a,0,DEF,Coventry City,1071.1,143.34,84.6,1.000,0.052,1.000,0.031,1.424
11,Luka Vušković,a,0,DEF,Brighton,1071.3,143.17,86.2,1.000,0.067,1.000,0.032,1.354
12,John McGinn,a,0,MID,Aston Villa,1073.1,142.22,84.6,1.000,0.215,1.349,0.192,1.367
13,Marcus Tavernier,a,1,MID,Bournemouth,1067.5,141.74,73.0,1.000,0.239,1.308,0.222,1.411
14,Anton Stach,a,0,MID,Leeds,1074.3,141.62,85.4,1.000,0.176,1.000,0.133,1.382
15,James Hill,a,0,DEF,Bournemouth,1067.5,140.71,84.3,1.000,0.037,1.506,0.089,1.405
16,Jun'ai Byfield,a,0,DEF,Spurs,1082.1,140.11,48.3,1.000,0.105,1.000,0.094,0.613
17,Igor Thiago Nascimento Rodrigues,a,1,FWD,Brentford,1079.3,139.57,86.5,1.000,0.468,1.000,0.051,1.336
18,Harry Amass,a,0,DEF,Man Utd,1076.1,138.64,66.8,1.000,0.174,1.000,0.155,1.627
19,Diego Coppola,a,0,DEF,Brighton,1071.3,138.43,63.7,1.000,0.196,1.000,0.139,1.616
20,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1067.5,137.96,82.5,1.000,0.207,1.000,0.123,1.438
21,Diego Gómez Amarilla,a,0,MID,Brighton,1071.3,136.29,81.9,1.000,0.185,1.000,0.149,1.386
22,Abdukodir Khusanov,a,1,DEF,Man City,1064.8,135.81,67.8,1.000,0.058,1.000,0.080,1.168
23,Jack Hinshelwood,d,0,MID,Brighton,1071.3,135.50,51.0,1.000,0.595,1.640,0.255,1.518
24,Vitaly Janelt,a,0,MID,Brentford,1079.3,135.49,84.7,1.410,0.132,1.000,0.096,1.363
25,António João Pereira de Albuquerque Tavares da...,a,0,DEF,Bournemouth,1067.5,135.33,70.8,1.000,0.093,1.000,0.088,1.574
26,Quinten Timber,a,0,MID,Crystal Palace,1079.6,134.50,83.9,1.000,0.171,1.000,0.106,1.490
27,Jaouen Hadjam,a,0,DEF,Brighton,1071.3,134.26,46.5,1.000,0.207,1.000,0.088,0.994
28,Jeremy Jacquet,a,0,DEF,Liverpool,1071.0,134.22,87.3,1.000,0.062,1.000,0.045,1.393
29,Adrien Truffert,a,0,DEF,Bournemouth,1067.5,133.18,86.7,1.000,0.056,1.441,0.120,1.435
30,Harry Maguire,a,0,DEF,Man Utd,1076.1,132.90,86.6,1.000,0.059,2.707,0.124,1.422
31,Kaden Braithwaite,a,0,DEF,Man City,1064.8,132.64,47.7,1.000,0.075,1.000,0.043,0.690
32,Julio Enciso,a,0,MID,Ipswich Town,1081.1,131.81,77.3,1.000,0.188,1.527,0.215,1.480
33,Daichi Kamada,a,0,MID,Crystal Palace,1079.6,131.62,83.5,1.000,0.147,1.000,0.107,1.459
34,James Justin,a,0,DEF,Leeds,1074.3,130.90,86.8,1.000,0.060,1.865,0.102,1.427
35,Issa Diop,a,0,DEF,Ipswich Town,1081.1,130.86,84.6,1.000,0.056,1.000,0.030,1.490
36,Ethan Ampadu,a,0,MID,Leeds,1074.3,130.69,85.7,1.000,0.063,1.670,0.107,1.363
37,Sávio Moreira de Oliveira,a,0,MID,Spurs,1082.1,130.26,83.3,1.000,0.143,1.000,0.154,1.484
38,Sven Botman,a,0,DEF,Newcastle,1082.8,130.17,81.7,1.000,0.066,1.000,0.046,1.496
39,Timothy Castagne,a,0,DEF,Fulham,1080.1,130.16,76.7,1.000,0.058,2.052,0.142,1.436
40,Vitor de Oliveira Nunes dos Reis,a,0,DEF,Man City,1064.8,130.08,44.9,1.000,0.060,1.000,0.085,0.606
41,Jannik Schuster,d,0,DEF,Brentford,1079.3,130.04,72.7,1.000,0.040,1.000,0.148,1.450
42,Jaidon Anthony,a,0,MID,Brentford,1079.3,130.01,74.3,1.410,0.255,1.000,0.105,1.328
43,Ben Davies,a,0,DEF,Spurs,1082.1,129.78,49.6,1.000,0.209,1.916,0.606,2.082
44,Nobel Mendy,a,0,DEF,Hull City,1079.8,129.60,72.7,1.000,0.083,1.000,0.023,1.449
45,Ferdi Kadıoğlu,a,0,DEF,Brighton,1071.3,129.53,86.0,1.000,0.053,1.000,0.038,1.334
46,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1083.9,129.14,87.0,1.000,0.057,1.000,0.040,1.471
47,Youri Tielemans,a,0,MID,Man Utd,1076.1,128.86,71.8,1.000,0.119,1.488,0.208,1.374
48,Enzo Fernández,a,0,MID,Man City,1064.8,128.68,77.7,1.000,0.108,1.000,0.135,1.109
49,Alex Iwobi,a,0,MID,Fulham,1080.1,128.60,78.7,1.397,0.173,1.000,0.166,1.443

In [14]:
# print(f"Best available players to pick for the next 5 gameweeks: GW{current_gw+1} AND {current_gw+5}")
# view = db_creator.run_sql(f"""
# WITH predictions_status AS (
#     SELECT 
#         p.player_name_id,
#         p.element,
#         ps.status,
#         p.latest_my_team,
#         p.position,
#         p.team_name,
#         p.opp_team_elo,
#         p.xpoints,
#         p.mins_pred,
#         p.xgp90_pred,
#         p.xg_overperf_factor,
#         p.xap90_pred,
#         p.xa_overperf_factor,
#         p.xgcp90_pred,
#         p.event,
#         p.latest_any_team
#     FROM predictions p
#     LEFT JOIN player_status ps ON p.element = ps.id
# )  
# SELECT
#         player_name_id,
#         status,
#         latest_my_team,
#         position,
#         team_name,
#         ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
#         ROUND(SUM(xpoints),2) AS total_xpoints,
#         ROUND(AVG(mins_pred),1) AS avg_mins_pred,
#         ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
#         ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
#         ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
#         ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
#         ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
#     FROM predictions_status
#     WHERE (latest_any_team = 0 OR latest_my_team = 1)
#       AND event BETWEEN {current_gw+1} AND {current_gw+5}
#       AND status IN ('a','d')
#         --AND position = 'FWD'
#       -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
#     GROUP BY player_name_id, status, position, team_name, latest_my_team
#     ORDER BY total_xpoints DESC
# """)
# view.head(50)

In [15]:
print(f"\nBest available players to replace worst in my team: {current_gw+1} to {current_gw+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 7 to 11

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Man City,a,Rico Lewis,23.813448,Anan Khalaili,18.079280,5.734168
1,DEF,Man City,a,Rayan Aït-Nouri,23.715691,Anan Khalaili,18.079280,5.636410
2,DEF,Coventry City,a,Bobby Thomas,23.713698,Anan Khalaili,18.079280,5.634417
3,DEF,Bournemouth,a,James Hill,22.399669,Anan Khalaili,18.079280,4.320389
4,DEF,Spurs,a,Jun'ai Byfield,22.297266,Anan Khalaili,18.079280,4.217986
5,GK,Coventry City,a,Dan Bentley,20.844540,Alisson Becker,17.019507,3.825034
6,DEF,Brighton,a,Luka Vušković,21.829701,Anan Khalaili,18.079280,3.750421
7,GK,Coventry City,a,Ben Wilson,20.673073,Alisson Becker,17.019507,3.653566
8,DEF,Bournemouth,a,António João Pereira de Albuquerque Tavares da...,21.341595,Anan Khalaili,18.079280,3.262315
9,DEF,Bournemouth,a,Adrien Truffert,21.099016,Anan Khalaili,18.079280,3.019736
10,DEF,Brighton,a,Diego Coppola,21.071924,Anan Khalaili,18.079280,2.992644
11,GK,Arsenal,a,Kepa Arrizabalaga Revuelta,19.994692,Alisson Becker,17.019507,2.975186
12,DEF,Leeds,a,James Justin,20.994854,Anan Khalaili,18.079280,2.915573
13,DEF,Brighton,a,Jaouen Hadjam,20.792516,Anan Khalaili,18.079280,2.713235
14,DEF,Man Utd,a,Harry Amass,20.739378,Anan Khalaili,18.079280,2.660097
15,GK,Arsenal,a,Illan Meslier,19.632303,Alisson Becker,17.019507,2.612796
16,GK,Man City,a,Marcus Bettinelli,19.573257,Alisson Becker,17.019507,2.553751
17,GK,Ipswich Town,a,David Button,19.538439,Alisson Becker,17.019507,2.518933
18,DEF,Man City,a,Kaden Braithwaite,20.572992,Anan Khalaili,18.079280,2.493711
19,DEF,Coventry City,a,Jay Dasilva,20.553255,Anan Khalaili,18.079280,2.473975

In [16]:
player_name = 'Erling Haaland'
print(f"\n {player_name} xPoints between {current_gw+1} and {current_gw+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
        AND player_name_id = '{player_name}'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Erling Haaland xPoints between 7 and 11:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,7.0,FWD,Man City,Ipswich Town,15.6,1011.173789,6.266831,79.576594,0.880257,0.193560,1.085087
1,Erling Haaland,8.0,FWD,Man City,Aston Villa,15.6,1102.752173,5.978863,79.306594,0.804103,0.189274,1.324214
2,Erling Haaland,9.0,FWD,Man City,Brighton,15.6,1107.157728,6.041624,79.123260,0.809894,0.200166,1.279965
3,Erling Haaland,10.0,FWD,Man City,Nott'm Forest,15.6,1024.135411,6.010695,79.576594,0.814663,0.190955,1.113544
4,Erling Haaland,11.0,FWD,Man City,Fulham,15.6,1014.967048,6.038867,78.799725,0.834554,0.191689,1.001131

# Chip Decisions

### Triple Captain

In [17]:
print("When to use TRIPLE CAPTAIN chip (gws1-18)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {current_gw} AND 18
    ORDER BY xpoints DESC
""")
view.head(10)

When to use TRIPLE CAPTAIN chip (gws1-18)

   player_name_id  event position team_name  opp_team_name   xpoints
0  Erling Haaland    7.0      FWD  Man City   Ipswich Town  6.266831
1  Erling Haaland   17.0      FWD  Man City      Newcastle  6.059746
2  Erling Haaland    9.0      FWD  Man City       Brighton  6.041624
3  Erling Haaland   18.0      FWD  Man City        Everton  6.040015
4  Erling Haaland   11.0      FWD  Man City         Fulham  6.038867
5  Erling Haaland   15.0      FWD  Man City        Chelsea  6.035980
6  Erling Haaland   13.0      FWD  Man City          Leeds  6.033915
7  Erling Haaland   10.0      FWD  Man City  Nott'm Forest  6.010695
8  Erling Haaland   16.0      FWD  Man City      Hull City  6.004408
9  Erling Haaland    8.0      FWD  Man City    Aston Villa  5.978863

### Bench Boost

In [18]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(current_gw+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=999.9,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW7 to GW38...

Optimizing team selection for GW7...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 53.17
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.34
 ✅        Martinez                       Chelsea      £5.0     3.64

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.53
 🪑        Mykolenko                      Everton      £4.6     3.69
 ✅        Khusanov                       Man City     £5.4     4.68
 ✅        Matheus N.                     Man City     £5.9     5.41
 ✅        Calafiori                      Arsenal      £5.9     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.94
 ✅        Xhaka                          Sunderland   £5.4     4.56
 ✅        Barnes                         Newcastle    £6.1     4.75
 ✅        Tavernier                      Bournemouth  £6.1     4.50
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.98

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.02
 ✅        Haaland                        Man City     £15.6    6.27
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW8...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 51.37
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.33
 ✅        Martinez                       Chelsea      £5.0     3.68

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.69
 🪑        Mykolenko                      Everton      £4.6     3.07
 ✅        Khusanov                       Man City     £5.4     4.10
 ✅        Matheus N.                     Man City     £5.9     4.16
 ✅        Calafiori                      Arsenal      £5.9     4.54

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.84
 ✅        Xhaka                          Sunderland   £5.4     4.63
 ✅        Barnes                         Newcastle    £6.1     4.88
 ✅        Tavernier                      Bournemouth  £6.1     4.31
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.58

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.18
 ✅        Haaland                        Man City     £15.6    5.98
 ✅        Thiago                         Brentford    £7.8     4.37

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 51.17
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.33
 ✅        Martinez                       Chelsea      £5.0     3.63

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     3.74
 ✅        Khusanov                       Man City     £5.4     4.10
 ✅        Khalaili                       Crystal Palace £5.0     3.82
 ✅        Matheus N.                     Man City     £5.9     4.16
 ✅        Calafiori                      Arsenal      £5.9     4.27

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.69
 ✅        Xhaka                          Sunderland   £5.4     4.90
 ✅        Barnes                         Newcastle    £6.1     4.90
 ✅        Tavernier                      Bournemouth  £6.1     4.39
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.18

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.16
 ✅        Haaland                        Man City     £15.6    6.04
 ✅        Thiago                         Brentford    £7.8     4.38

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 52.85
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.60
 ✅        Martinez                       Chelsea      £5.0     3.66

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.37
 ✅        Khusanov                       Man City     £5.4     4.37
 ✅        Matheus N.                     Man City     £5.9     4.70
 ✅        Calafiori                      Arsenal      £5.9     4.74
 ✅        Mykolenko                      Everton      £4.6     4.27

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     4.06
 ✅        Xhaka                          Sunderland   £5.4     4.67
 ✅        Barnes                         Newcastle    £6.1     5.04
 ✅        Tavernier                      Bournemouth  £6.1     4.62
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.97

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.09
 ✅        Haaland                        Man City     £15.6    6.01
 ✅        Thiago                         Brentford    £7.8     4.38

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 52.75
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.41
 ✅        Martinez                       Chelsea      £5.0     3.65

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.67
 🪑        Mykolenko                      Everton      £4.6     3.67
 ✅        Khusanov                       Man City     £5.4     4.81
 ✅        Matheus N.                     Man City     £5.9     5.14
 ✅        Calafiori                      Arsenal      £5.9     4.51

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.94
 ✅        Xhaka                          Sunderland   £5.4     4.57
 ✅        Barnes                         Newcastle    £6.1     4.64
 ✅        Tavernier                      Bournemouth  £6.1     4.44
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.24

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.21
 ✅        Haaland                        Man City     £15.6    6.04
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 49.79
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.55
 ✅        Martinez                       Chelsea      £5.0     3.71

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khusanov                       Man City     £5.4     3.52
 🪑        Mykolenko                      Everton      £4.6     3.63
 ✅        Khalaili                       Crystal Palace £5.0     3.73
 ✅        Matheus N.                     Man City     £5.9     3.90
 ✅        Calafiori                      Arsenal      £5.9     3.74

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.99
 ✅        Xhaka                          Sunderland   £5.4     4.97
 ✅        Barnes                         Newcastle    £6.1     4.71
 ✅        Tavernier                      Bournemouth  £6.1     4.51
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.35

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.15
 ✅        Haaland                        Man City     £15.6    5.43
 ✅        Thiago                         Brentford    £7.8     4.36

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 51.45
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.60
 ✅        Martinez                       Chelsea      £5.0     3.68

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.61
 🪑        Mykolenko                      Everton      £4.6     3.65
 ✅        Khusanov                       Man City     £5.4     4.16
 ✅        Matheus N.                     Man City     £5.9     4.34
 ✅        Calafiori                      Arsenal      £5.9     4.56

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.05
 ✅        Xhaka                          Sunderland   £5.4     4.48
 ✅        Barnes                         Newcastle    £6.1     4.79
 ✅        Tavernier                      Bournemouth  £6.1     4.21
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.41

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.19
 ✅        Haaland                        Man City     £15.6    6.03
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.0m / £999.9m
Total Weighted Expected Points: 52.02
Remaining Budget: £900.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.46
 ✅        Martinez                       Chelsea      £5.0     3.60

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khusanov                       Man City     £5.4     3.96
 🪑        Khalaili                       Crystal Palace £5.0     3.65
 ✅        Matheus N.                     Man City     £5.9     4.16
 ✅        Calafiori                      Arsenal      £5.9     5.12

In [19]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

    event  bench_boost_gain
23     30         13.204294
19     26         12.929618
9      16         12.839788
20     27         12.839788
27     34         12.791880
7      14         12.791880
14     21         12.716106
3      10         12.716106
12     19         12.666201
18     25         12.666201
15     22         12.662145
6      13         12.643093
13     20         12.643093
24     31         12.609059
31     38         12.586808
22     29         12.568972
4      11         12.566379
2       9         12.529159
17     24         12.508688
26     33         12.465743
8      15         12.465743
5      12         12.464621
16     23         12.464621
28     35         12.340272
29     36         12.231674
0       7         12.231674
10     17         12.203333
1       8         11.941174
30     37         11.941174
11     18         11.810987
25     32         11.792095
21     28         11.094537

In [20]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.12 minute(s)