In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 35
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
# Reece James goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT player_name_id, season, event, fixture, goals_scored, expected_goals, expected_assists, assists
                          FROM playergw_transformed
                          WHERE player_name_id= 'Reece James'
                            AND expected_goals IS NOT NULL
                          ORDER BY season, event, fixture
""")
view.pivot_table(index=['season'], values=['goals_scored', 'expected_goals', 'expected_assists', 'assists'], aggfunc='sum',margins=True,dropna=False)

            assists  expected_assists  expected_goals  goals_scored
season
20222023.0      2.0           1.71236          0.3974           1.0
20232024.0      2.0           1.36000          0.3000           0.0
20242025.0      2.0           1.15000          0.4500           1.0
20252026.0      6.0           3.15000          1.0200           2.0
All            12.0           7.37236          2.1674           4.0

In [6]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        -- AND latest_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 36
Squad Points: 91.24

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Matheus N.,a,100.0,36.0,DEF,Man City,Crystal Palace; Brentford,9.791620,168.0
1,Bernardo,a,100.0,36.0,MID,Man City,Crystal Palace; Brentford,8.807415,163.0
2,Khusanov,a,100.0,36.0,DEF,Man City,Crystal Palace; Brentford,8.476194,152.0
3,Richards,a,100.0,36.0,DEF,Crystal Palace,Man City; Everton,6.292583,153.0
4,Gabriel,a,100.0,36.0,DEF,Arsenal,West Ham,5.903599,85.0
5,B.Fernandes,a,100.0,36.0,MID,Man Utd,Sunderland,4.908119,84.0
6,Raya,a,NaN,36.0,GK,Arsenal,West Ham,4.604387,87.0
7,Gibbs-White,d,100.0,36.0,MID,Nott'm Forest,Newcastle,4.520846,67.0
8,Martinez,a,100.0,36.0,GK,Aston Villa,Burnley,4.457411,88.0
9,Szoboszlai,a,100.0,36.0,MID,Liverpool,Chelsea,4.351834,86.0
10,Van Hecke,a,100.0,36.0,DEF,Brighton,Wolves,4.167796,87.0
11,Bruno G.,a,100.0,36.0,MID,Newcastle,Nott'm Forest,4.064110,71.0
12,Flemming,a,100.0,36.0,FWD,Burnley,Aston Villa,3.935908,74.0
13,Brobbey,a,100.0,36.0,FWD,Sunderland,Man Utd,3.721128,72.0
14,Isak,d,100.0,36.0,FWD,Liverpool,Chelsea,3.441880,64.0

In [7]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW36 AND 40

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1085.4,10.22,64.0,0.334,1.0,0.070,1.597,1.178
1,Brian Brobbey,1,FWD,Sunderland,1088.0,11.03,72.3,0.362,1.0,0.047,1.000,1.351
2,Emiliano Martínez Romero,1,GK,Aston Villa,1089.6,11.46,87.9,NaN,1.0,NaN,1.000,1.372
3,Zian Flemming,1,FWD,Burnley,1092.2,11.85,74.1,0.425,1.0,0.039,1.000,1.696
4,Jan Paul van Hecke,1,DEF,Brighton,1022.2,11.97,86.7,0.044,1.0,0.041,1.000,1.281
5,Chris Richards,1,DEF,Crystal Palace,1155.6,12.20,98.6,0.038,1.0,0.030,1.000,1.665
6,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1033.7,12.22,71.4,0.186,1.0,0.144,1.000,1.234
7,Dominik Szoboszlai,1,MID,Liverpool,1085.4,12.98,86.2,0.163,1.0,0.147,1.000,1.540
8,David Raya Martín,1,GK,Arsenal,969.6,13.46,87.3,NaN,1.0,NaN,1.000,0.653
9,Morgan Gibbs-White,1,MID,Nott'm Forest,1097.4,13.58,66.6,0.292,1.0,0.292,2.015,1.380
10,Bruno Borges Fernandes,1,MID,Man Utd,1056.2,14.50,83.8,0.192,1.0,0.236,1.333,1.289
11,Abdukodir Khusanov,1,DEF,Man City,1088.5,16.82,98.2,0.045,1.0,0.036,1.000,1.081
12,Gabriel dos Santos Magalhães,1,DEF,Arsenal,969.6,17.18,84.6,0.060,1.0,0.077,1.000,0.585
13,Bernardo Mota Veiga de Carvalho e Silva,1,MID,Man City,1088.5,17.57,107.6,0.154,1.0,0.164,1.000,0.971
14,Matheus Nunes,1,DEF,Man City,1088.5,19.79,110.3,0.044,1.0,0.246,2.785,1.069

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    --AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW36 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Matheus Nunes,a,1,DEF,Man City,1088.5,19.79,110.3,1.000,0.044,2.785,0.246,1.069
1,Jérémy Doku,a,0,MID,Man City,1088.5,19.06,108.8,1.000,0.203,1.000,0.191,0.974
2,Max Alleyne,a,0,DEF,Man City,1088.5,17.59,78.7,1.000,0.191,1.000,0.038,1.113
3,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1088.5,17.57,107.6,1.000,0.154,1.000,0.164,0.971
4,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,969.6,17.18,84.6,1.000,0.060,1.000,0.077,0.585
5,John Stones,a,0,DEF,Man City,1088.5,17.08,76.2,1.000,0.184,1.000,0.044,1.161
6,Abdukodir Khusanov,a,1,DEF,Man City,1088.5,16.82,98.2,1.000,0.045,1.000,0.036,1.081
7,Benjamin White,a,0,DEF,Arsenal,969.6,16.51,78.8,1.000,0.049,1.000,0.076,0.624
8,Rayan Aït-Nouri,a,0,DEF,Man City,1088.5,16.34,71.5,1.000,0.063,1.000,0.081,0.963
9,Rico Lewis,a,0,DEF,Man City,1088.5,15.85,75.3,1.000,0.210,1.000,0.056,1.307
10,Bruno Borges Fernandes,a,1,MID,Man Utd,1056.2,14.50,83.8,1.000,0.192,1.333,0.236,1.289
11,Mathias Jensen,a,0,MID,Brentford,1147.9,14.48,84.1,2.031,0.280,1.000,0.135,1.438
12,Walter Benítez,a,0,GK,Crystal Palace,1155.6,14.38,111.0,1.000,NaN,1.000,NaN,1.626
13,Brennan Johnson,a,0,MID,Crystal Palace,1155.6,14.32,80.6,1.000,0.153,2.452,0.253,1.683
14,Evann Guessand,d,0,MID,Crystal Palace,1155.6,14.29,73.9,1.000,0.294,1.000,0.106,1.736
15,Riccardo Calafiori,a,0,DEF,Arsenal,969.6,14.16,52.9,1.000,0.119,1.000,0.087,0.772
16,Jaydee Canvot,a,0,DEF,Crystal Palace,1155.6,14.05,112.7,1.000,0.037,1.000,0.048,1.486
17,James Trafford,a,0,GK,Man City,1088.5,14.04,115.0,1.000,NaN,1.000,NaN,1.595
18,Justin Kluivert,d,0,MID,Bournemouth,1113.5,13.79,56.1,1.000,0.547,1.000,0.150,1.568
19,Morgan Gibbs-White,d,1,MID,Nott'm Forest,1097.4,13.58,66.6,1.000,0.292,2.015,0.292,1.380
20,Eberechi Eze,a,0,MID,Arsenal,969.6,13.57,67.5,1.000,0.259,1.000,0.150,0.624
21,Myles Lewis-Skelly,a,0,DEF,Arsenal,969.6,13.56,57.9,1.000,0.037,1.000,0.039,0.752
22,Leandro Trossard,a,0,MID,Arsenal,969.6,13.50,55.8,1.416,0.305,1.826,0.313,0.637
23,David Raya Martín,a,1,GK,Arsenal,969.6,13.46,87.3,1.000,NaN,1.000,NaN,0.653
24,Adam Wharton,a,0,MID,Crystal Palace,1155.6,13.32,89.2,1.000,0.080,1.000,0.107,1.541
25,Lisandro Martínez,a,0,DEF,Man Utd,1056.2,13.17,61.9,1.000,0.326,1.000,0.081,1.549
26,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1088.5,13.07,76.2,1.000,0.091,1.000,0.084,1.074
27,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1155.6,13.04,84.4,1.000,0.121,1.000,0.110,1.648
28,Jack Hinshelwood,a,0,MID,Brighton,1022.2,13.03,78.7,1.000,0.170,1.832,0.185,1.231
29,Dominik Szoboszlai,a,1,MID,Liverpool,1085.4,12.98,86.2,1.000,0.163,1.000,0.147,1.540
30,Marcus Tavernier,a,0,MID,Bournemouth,1113.5,12.87,82.0,1.000,0.164,1.483,0.162,1.310
31,James Justin,a,0,DEF,Leeds,1023.9,12.82,86.7,1.000,0.049,1.000,0.046,1.127
32,Martin Ødegaard,a,0,MID,Arsenal,969.6,12.78,72.2,1.000,0.130,1.000,0.185,0.690
33,Reece James,a,0,DEF,Chelsea,1055.6,12.76,63.4,1.000,0.182,1.000,0.253,1.508
34,Nathan Aké,a,0,DEF,Man City,1088.5,12.70,39.2,1.000,0.045,1.000,0.034,1.173
35,Jaka Bijol,a,0,DEF,Leeds,1023.9,12.67,80.4,1.000,0.038,1.000,0.056,1.097
36,Cristhian Mosquera,a,0,DEF,Arsenal,969.6,12.58,44.2,1.000,0.035,1.000,0.040,0.745
37,Justin Devenny,a,0,MID,Crystal Palace,1155.6,12.57,82.4,1.000,0.129,1.000,0.056,1.635
38,Vitalii Mykolenko,a,0,DEF,Everton,1015.4,12.54,87.2,1.000,0.040,1.000,0.049,1.150
39,Nico González Iglesias,a,0,MID,Man City,1088.5,12.46,76.0,1.000,0.069,1.000,0.076,0.993
40,Enzo Fernández,a,0,MID,Chelsea,1055.6,12.40,82.1,1.000,0.148,1.000,0.134,1.412
41,Chadi Riad Dnanou,a,0,DEF,Crystal Palace,1155.6,12.33,99.5,1.000,0.032,1.000,0.040,1.662
42,Granit Xhaka,a,0,MID,Sunderland,1088.0,12.30,81.9,1.000,0.102,2.216,0.240,1.767
43,William Osula,a,0,FWD,Newcastle,1033.7,12.25,63.6,1.000,0.505,1.000,0.127,1.407
44,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1113.5,12.24,74.3,1.000,0.215,1.000,0.090,1.408
45,Jake O'Brien,a,0,DEF,Everton,1015.4,12.24,85.6,1.000,0.038,1.000,0.042,1.156
46,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1033.7,12.22,71.4,1.000,0.186,1.000,0.144,1.234
47,Chris Richards,a,1,DEF,Crystal Palace,1155.6,12.20,98.6,1.000,0.038,1.000,0.030,1.665
48,Youri Tielemans,a,0,MID,Aston Villa,1089.6,12.20,76.8,1.000,0.116,1.627,0.217,1.625
49,Kevin Schade,a,0,MID,Brentford,1147.9,12.19,75.2,1.000,0.179,2.066,0.154,1.434

In [9]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW36 AND 40

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Matheus Nunes,a,1,DEF,Man City,1088.5,19.79,110.3,0.044,1.000,0.246,2.785,1.069
1,Jérémy Doku,a,0,MID,Man City,1088.5,19.06,108.8,0.203,1.000,0.191,1.000,0.974
2,Max Alleyne,a,0,DEF,Man City,1088.5,17.59,78.7,0.191,1.000,0.038,1.000,1.113
3,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1088.5,17.57,107.6,0.154,1.000,0.164,1.000,0.971
4,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,969.6,17.18,84.6,0.060,1.000,0.077,1.000,0.585
5,John Stones,a,0,DEF,Man City,1088.5,17.08,76.2,0.184,1.000,0.044,1.000,1.161
6,Abdukodir Khusanov,a,1,DEF,Man City,1088.5,16.82,98.2,0.045,1.000,0.036,1.000,1.081
7,Benjamin White,a,0,DEF,Arsenal,969.6,16.51,78.8,0.049,1.000,0.076,1.000,0.624
8,Rayan Aït-Nouri,a,0,DEF,Man City,1088.5,16.34,71.5,0.063,1.000,0.081,1.000,0.963
9,Rico Lewis,a,0,DEF,Man City,1088.5,15.85,75.3,0.210,1.000,0.056,1.000,1.307
10,Bruno Borges Fernandes,a,1,MID,Man Utd,1056.2,14.50,83.8,0.192,1.000,0.236,1.333,1.289
11,Mathias Jensen,a,0,MID,Brentford,1147.9,14.48,84.1,0.280,2.031,0.135,1.000,1.438
12,Walter Benítez,a,0,GK,Crystal Palace,1155.6,14.38,111.0,NaN,1.000,NaN,1.000,1.626
13,Brennan Johnson,a,0,MID,Crystal Palace,1155.6,14.32,80.6,0.153,1.000,0.253,2.452,1.683
14,Evann Guessand,d,0,MID,Crystal Palace,1155.6,14.29,73.9,0.294,1.000,0.106,1.000,1.736
15,Riccardo Calafiori,a,0,DEF,Arsenal,969.6,14.16,52.9,0.119,1.000,0.087,1.000,0.772
16,Jaydee Canvot,a,0,DEF,Crystal Palace,1155.6,14.05,112.7,0.037,1.000,0.048,1.000,1.486
17,James Trafford,a,0,GK,Man City,1088.5,14.04,115.0,NaN,1.000,NaN,1.000,1.595
18,Justin Kluivert,d,0,MID,Bournemouth,1113.5,13.79,56.1,0.547,1.000,0.150,1.000,1.568
19,Morgan Gibbs-White,d,1,MID,Nott'm Forest,1097.4,13.58,66.6,0.292,1.000,0.292,2.015,1.380
20,Eberechi Eze,a,0,MID,Arsenal,969.6,13.57,67.5,0.259,1.000,0.150,1.000,0.624
21,Myles Lewis-Skelly,a,0,DEF,Arsenal,969.6,13.56,57.9,0.037,1.000,0.039,1.000,0.752
22,Leandro Trossard,a,0,MID,Arsenal,969.6,13.50,55.8,0.305,1.416,0.313,1.826,0.637
23,David Raya Martín,a,1,GK,Arsenal,969.6,13.46,87.3,NaN,1.000,NaN,1.000,0.653
24,Adam Wharton,a,0,MID,Crystal Palace,1155.6,13.32,89.2,0.080,1.000,0.107,1.000,1.541
25,Lisandro Martínez,a,0,DEF,Man Utd,1056.2,13.17,61.9,0.326,1.000,0.081,1.000,1.549
26,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1088.5,13.07,76.2,0.091,1.000,0.084,1.000,1.074
27,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1155.6,13.04,84.4,0.121,1.000,0.110,1.000,1.648
28,Jack Hinshelwood,a,0,MID,Brighton,1022.2,13.03,78.7,0.170,1.000,0.185,1.832,1.231
29,Dominik Szoboszlai,a,1,MID,Liverpool,1085.4,12.98,86.2,0.163,1.000,0.147,1.000,1.540
30,Marcus Tavernier,a,0,MID,Bournemouth,1113.5,12.87,82.0,0.164,1.000,0.162,1.483,1.310
31,James Justin,a,0,DEF,Leeds,1023.9,12.82,86.7,0.049,1.000,0.046,1.000,1.127
32,Martin Ødegaard,a,0,MID,Arsenal,969.6,12.78,72.2,0.130,1.000,0.185,1.000,0.690
33,Reece James,a,0,DEF,Chelsea,1055.6,12.76,63.4,0.182,1.000,0.253,1.000,1.508
34,Nathan Aké,a,0,DEF,Man City,1088.5,12.70,39.2,0.045,1.000,0.034,1.000,1.173
35,Jaka Bijol,a,0,DEF,Leeds,1023.9,12.67,80.4,0.038,1.000,0.056,1.000,1.097
36,Cristhian Mosquera,a,0,DEF,Arsenal,969.6,12.58,44.2,0.035,1.000,0.040,1.000,0.745
37,Justin Devenny,a,0,MID,Crystal Palace,1155.6,12.57,82.4,0.129,1.000,0.056,1.000,1.635
38,Vitalii Mykolenko,a,0,DEF,Everton,1015.4,12.54,87.2,0.040,1.000,0.049,1.000,1.150
39,Nico González Iglesias,a,0,MID,Man City,1088.5,12.46,76.0,0.069,1.000,0.076,1.000,0.993
40,Enzo Fernández,a,0,MID,Chelsea,1055.6,12.40,82.1,0.148,1.000,0.134,1.000,1.412
41,Chadi Riad Dnanou,a,0,DEF,Crystal Palace,1155.6,12.33,99.5,0.032,1.000,0.040,1.000,1.662
42,Granit Xhaka,a,0,MID,Sunderland,1088.0,12.30,81.9,0.102,1.000,0.240,2.216,1.767
43,William Osula,a,0,FWD,Newcastle,1033.7,12.25,63.6,0.505,1.000,0.127,1.000,1.407
44,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1113.5,12.24,74.3,0.215,1.000,0.090,1.000,1.408
45,Jake O'Brien,a,0,DEF,Everton,1015.4,12.24,85.6,0.038,1.000,0.042,1.000,1.156
46,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1033.7,12.22,71.4,0.186,1.000,0.144,1.000,1.234
47,Chris Richards,a,1,DEF,Crystal Palace,1155.6,12.20,98.6,0.038,1.000,0.030,1.000,1.665
48,Youri Tielemans,a,0,MID,Aston Villa,1089.6,12.20,76.8,0.116,1.000,0.217,1.627,1.625
49,Kevin Schade,a,0,MID,Brentford,1147.9,12.19,75.2,0.179,1.000,0.154,2.066,1.434

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 36 to 40

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Man City,a,Jérémy Doku,19.059938,Bruno Guimarães Rodriguez Moura,12.217948,6.841991
1,DEF,Man City,a,Max Alleyne,17.585066,Jan Paul van Hecke,11.973627,5.611439
2,DEF,Man City,a,John Stones,17.076853,Jan Paul van Hecke,11.973627,5.103226
3,DEF,Arsenal,a,Benjamin White,16.508210,Jan Paul van Hecke,11.973627,4.534583
4,DEF,Man City,a,Rayan Aït-Nouri,16.337665,Jan Paul van Hecke,11.973627,4.364038
5,DEF,Man City,a,Rico Lewis,15.850161,Jan Paul van Hecke,11.973627,3.876534
6,GK,Crystal Palace,a,Walter Benítez,14.376041,Emiliano Martínez Romero,11.459571,2.916470
7,GK,Man City,a,James Trafford,14.037715,Emiliano Martínez Romero,11.459571,2.578144
8,MID,Brentford,a,Mathias Jensen,14.478581,Bruno Guimarães Rodriguez Moura,12.217948,2.260633
9,DEF,Arsenal,a,Riccardo Calafiori,14.156174,Jan Paul van Hecke,11.973627,2.182547
10,MID,Crystal Palace,a,Brennan Johnson,14.324444,Bruno Guimarães Rodriguez Moura,12.217948,2.106496
11,DEF,Crystal Palace,a,Jaydee Canvot,14.045601,Jan Paul van Hecke,11.973627,2.071974
12,MID,Crystal Palace,d,Evann Guessand,14.287495,Bruno Guimarães Rodriguez Moura,12.217948,2.069547
13,FWD,Newcastle,a,William Osula,12.253002,Alexander Isak,10.220244,2.032758
14,FWD,Nott'm Forest,a,Igor Jesus Maciel da Cruz,12.043027,Alexander Isak,10.220244,1.822783
15,DEF,Arsenal,a,Myles Lewis-Skelly,13.561406,Jan Paul van Hecke,11.973627,1.587779
16,MID,Bournemouth,d,Justin Kluivert,13.787374,Bruno Guimarães Rodriguez Moura,12.217948,1.569426
17,MID,Arsenal,a,Eberechi Eze,13.567040,Bruno Guimarães Rodriguez Moura,12.217948,1.349092
18,MID,Arsenal,a,Leandro Trossard,13.497292,Bruno Guimarães Rodriguez Moura,12.217948,1.279344
19,DEF,Man Utd,a,Lisandro Martínez,13.167069,Jan Paul van Hecke,11.973627,1.193442

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 36 and 40:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,36.0,FWD,Man City,Crystal Palace; Brentford,14.6,1056.580966,11.417322,140.021338,0.858617,0.243302,1.255665
1,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.6,1099.093598,5.662728,64.895109,0.913698,0.283159,1.116525
2,Erling Haaland,38.0,FWD,Man City,Aston Villa,14.6,1109.774484,5.720583,64.895109,0.933757,0.283159,1.115786

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'DEF'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW36 to GW40
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Matheus Nunes,a,1,DEF,Man City,821.2,5.36,110.3,0.044,1.000,0.246,2.785,1.069
1,Jérémy Doku,a,0,MID,Man City,821.2,5.18,108.8,0.203,1.000,0.191,1.000,0.974
2,Max Alleyne,a,0,DEF,Man City,821.2,4.80,78.7,0.191,1.000,0.038,1.000,1.113
3,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,821.2,4.77,107.6,0.154,1.000,0.164,1.000,0.971
4,John Stones,a,0,DEF,Man City,821.2,4.65,76.2,0.184,1.000,0.044,1.000,1.161
5,Abdukodir Khusanov,a,1,DEF,Man City,821.2,4.57,98.2,0.045,1.000,0.036,1.000,1.081
6,Rayan Aït-Nouri,a,0,DEF,Man City,821.2,4.44,71.5,0.063,1.000,0.081,1.000,0.963
7,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,733.1,4.38,84.6,0.060,1.000,0.077,1.000,0.585
8,Rico Lewis,a,0,DEF,Man City,821.2,4.31,75.3,0.210,1.000,0.056,1.000,1.307
9,Benjamin White,a,0,DEF,Arsenal,733.1,4.22,78.8,0.049,1.000,0.076,1.000,0.624
10,Brennan Johnson,a,0,MID,Crystal Palace,870.1,3.90,80.6,0.153,1.000,0.253,2.452,1.683
11,Walter Benítez,a,0,GK,Crystal Palace,870.1,3.89,111.0,NaN,1.000,NaN,1.000,1.626
12,Evann Guessand,d,0,MID,Crystal Palace,870.1,3.85,73.9,0.294,1.000,0.106,1.000,1.736
13,James Trafford,a,0,GK,Man City,821.2,3.83,115.0,NaN,1.000,NaN,1.000,1.595
14,Jaydee Canvot,a,0,DEF,Crystal Palace,870.1,3.83,112.7,0.037,1.000,0.048,1.000,1.486
15,Bruno Borges Fernandes,a,1,MID,Man Utd,796.0,3.68,83.8,0.192,1.000,0.236,1.333,1.289
16,Mathias Jensen,a,0,MID,Brentford,876.9,3.64,84.1,0.280,2.031,0.135,1.000,1.438
17,Riccardo Calafiori,a,0,DEF,Arsenal,733.1,3.62,52.9,0.119,1.000,0.087,1.000,0.772
18,Adam Wharton,a,0,MID,Crystal Palace,870.1,3.61,89.2,0.080,1.000,0.107,1.000,1.541
19,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,821.2,3.56,76.2,0.091,1.000,0.084,1.000,1.074
20,Jefferson Lerma Solís,a,0,MID,Crystal Palace,870.1,3.56,84.4,0.121,1.000,0.110,1.000,1.648
21,Justin Kluivert,d,0,MID,Bournemouth,842.8,3.48,56.1,0.547,1.000,0.150,1.000,1.568
22,Myles Lewis-Skelly,a,0,DEF,Arsenal,733.1,3.46,57.9,0.037,1.000,0.039,1.000,0.752
23,Nathan Aké,a,0,DEF,Man City,821.2,3.46,39.2,0.045,1.000,0.034,1.000,1.173
24,David Raya Martín,a,1,GK,Arsenal,733.1,3.44,87.3,NaN,1.000,NaN,1.000,0.653
25,Eberechi Eze,a,0,MID,Arsenal,733.1,3.43,67.5,0.259,1.000,0.150,1.000,0.624
26,Morgan Gibbs-White,d,1,MID,Nott'm Forest,829.0,3.43,66.6,0.292,1.000,0.292,2.015,1.380
27,Leandro Trossard,a,0,MID,Arsenal,733.1,3.42,55.8,0.305,1.416,0.313,1.826,0.637
28,Justin Devenny,a,0,MID,Crystal Palace,870.1,3.40,82.4,0.129,1.000,0.056,1.000,1.635
29,Nico González Iglesias,a,0,MID,Man City,821.2,3.38,76.0,0.069,1.000,0.076,1.000,0.993
30,Chadi Riad Dnanou,a,0,DEF,Crystal Palace,870.1,3.37,99.5,0.032,1.000,0.040,1.000,1.662
31,Lisandro Martínez,a,0,DEF,Man Utd,796.0,3.35,61.9,0.326,1.000,0.081,1.000,1.549
32,Chris Richards,a,1,DEF,Crystal Palace,870.1,3.34,98.6,0.038,1.000,0.030,1.000,1.665
33,Jack Hinshelwood,a,0,MID,Brighton,760.1,3.31,78.7,0.170,1.000,0.185,1.832,1.231
34,Daichi Kamada,a,0,MID,Crystal Palace,870.1,3.31,91.1,0.047,1.000,0.049,1.000,1.693
35,Dominik Szoboszlai,a,1,MID,Liverpool,822.7,3.28,86.2,0.163,1.000,0.147,1.000,1.540
36,Marcus Tavernier,a,0,MID,Bournemouth,842.8,3.25,82.0,0.164,1.000,0.162,1.483,1.310
37,Martin Ødegaard,a,0,MID,Arsenal,733.1,3.24,72.2,0.130,1.000,0.185,1.000,0.690
38,James Justin,a,0,DEF,Leeds,773.8,3.24,86.7,0.049,1.000,0.046,1.000,1.127
39,Cristhian Mosquera,a,0,DEF,Arsenal,733.1,3.23,44.2,0.035,1.000,0.040,1.000,0.745
40,Reece James,a,0,DEF,Chelsea,810.6,3.21,63.4,0.182,1.000,0.253,1.000,1.508
41,Jaka Bijol,a,0,DEF,Leeds,773.8,3.21,80.4,0.038,1.000,0.056,1.000,1.097
42,Nathaniel Clyne,a,0,DEF,Crystal Palace,870.1,3.16,83.2,0.131,1.000,0.033,1.000,1.917
43,Tijjani Reijnders,a,0,MID,Man City,821.2,3.15,43.0,0.235,1.000,0.103,1.000,1.048
44,Vitalii Mykolenko,a,0,DEF,Everton,774.1,3.15,87.2,0.040,1.000,0.049,1.000,1.150
45,Youri Tielemans,a,0,MID,Aston Villa,798.3,3.14,76.8,0.116,1.000,0.217,1.627,1.625
46,Enzo Fernández,a,0,MID,Chelsea,810.6,3.12,82.1,0.148,1.000,0.134,1.000,1.412
47,Granit Xhaka,a,0,MID,Sunderland,828.9,3.10,81.9,0.102,1.000,0.240,2.216,1.767
48,William Osula,a,0,FWD,Newcastle,783.9,3.10,63.6,0.505,1.000,0.127,1.000,1.407
49,Ferdi Kadıoğlu,a,0,DEF,Brighton,760.1,3.09,87.1,0.044,1.000,0.039,1.000,1.283

# Multi-week optimizer

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [15]:
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(picks_current_gameweek + 1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 67.33
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.46
 ✅        Raya                           Arsenal      £6.1     4.60

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     5.90
 ✅        Van Hecke                      Brighton     £4.6     4.17
 ✅        Richards                       Crystal Palace £4.4     6.29
 ✅        Khusanov                       Man City     £5.4     8.48
 ✅        Matheus N.                     Man City     £5.3     9.79

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     4.06
 ✅        Szoboszlai                     Liverpool    £7.0     4.35
 ✅        Bernardo                       Man City     £6.2     8.81
 ✅        B.Fernandes                    Man Utd      £10.4    4.91
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.52

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.44
 🪑        Brobbey                        Sunderland   £5.3     3.72
 ✅        Flemming                       Burnley      £5.3     3.94

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 51.59
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.72
 ✅        Raya                           Arsenal      £6.1     4.83

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     3.05
 ✅        Gabriel                        Arsenal      £7.2     6.03
 ✅        Van Hecke                      Brighton     £4.6     4.10
 ✅        Khusanov                       Man City     £5.4     4.17
 ✅        Matheus N.                     Man City     £5.3     4.99

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.28
 ✅        Bernardo                       Man City     £6.2     4.38
 ✅        B.Fernandes                    Man Utd      £10.4    4.93
 ✅        Bruno G.                       Newcastle    £6.8     4.09
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.51

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.34
 🪑        Brobbey                        Sunderland   £5.3     3.65
 ✅        Flemming                       Burnley      £5.3     3.90

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 49.49
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.28
 ✅        Raya                           Arsenal      £6.1     4.03

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     2.85
 ✅        Gabriel                        Arsenal      £7.2     5.24
 ✅        Van Hecke                      Brighton     £4.6     3.70
 ✅        Khusanov                       Man City     £5.4     4.18
 ✅        Matheus N.                     Man City     £5.3     5.00

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.35
 ✅        Bernardo                       Man City     £6.2     4.38
 ✅        B.Fernandes                    Man Utd      £10.4    4.66
 ✅        Bruno G.                       Newcastle    £6.8     4.06
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.55

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.44
 🪑        Brobbey                        Sunderland   £5.3     3.66
 ✅        Flemming                       Burnley      £5.3     4.01

================================================================================
Optimization Status: Optimal

Optimization complete. Final DataFrame created.

event     web_name position  36  37  38
5          Gabriel      DEF   1   1   1
8         Khusanov      DEF   1   1   1
10      Matheus N.      DEF   1   1   1
12        Richards      DEF   1   0   0
14       Van Hecke      DEF   1   1   1
2          Brobbey      FWD   0   0   0
4         Flemming      FWD   1   1   1
7             Isak      FWD   0   0   0
9         Martinez       GK   0   0   0
11            Raya       GK   1   1   1
0      B.Fernandes      MID   1   1   1
1         Bernardo      MID   1   1   1
3         Bruno G.      MID   0   1   1
6      Gibbs-White      MID   1   1   1
13      Szoboszlai      MID   1   1   1

In [16]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [17]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [18]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [19]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW36 to GW38...

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 67.33
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.46
 ✅        Raya                           Arsenal      £6.1     4.60

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     5.90
 ✅        Van Hecke                      Brighton     £4.6     4.17
 ✅        Richards                       Crystal Palace £4.4     6.29
 ✅        Khusanov                       Man City     £5.4     8.48
 ✅        Matheus N.                     Man City     £5.3     9.79

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     4.06
 ✅        Szoboszlai                     Liverpool    £7.0     4.35
 ✅        Bernardo                       Man City     £6.2     8.81
 ✅        B.Fernandes                    Man Utd      £10.4    4.91
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.52

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.44
 🪑        Brobbey                        Sunderland   £5.3     3.72
 ✅        Flemming                       Burnley      £5.3     3.94

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 51.59
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.72
 ✅        Raya                           Arsenal      £6.1     4.83

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     3.05
 ✅        Gabriel                        Arsenal      £7.2     6.03
 ✅        Van Hecke                      Brighton     £4.6     4.10
 ✅        Khusanov                       Man City     £5.4     4.17
 ✅        Matheus N.                     Man City     £5.3     4.99

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.28
 ✅        Bernardo                       Man City     £6.2     4.38
 ✅        B.Fernandes                    Man Utd      £10.4    4.93
 ✅        Bruno G.                       Newcastle    £6.8     4.09
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.51

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.34
 🪑        Brobbey                        Sunderland   £5.3     3.65
 ✅        Flemming                       Burnley      £5.3     3.90

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 49.49
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.28
 ✅        Raya                           Arsenal      £6.1     4.03

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     2.85
 ✅        Gabriel                        Arsenal      £7.2     5.24
 ✅        Van Hecke                      Brighton     £4.6     3.70
 ✅        Khusanov                       Man City     £5.4     4.18
 ✅        Matheus N.                     Man City     £5.3     5.00

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.35
 ✅        Bernardo                       Man City     £6.2     4.38
 ✅        B.Fernandes                    Man Utd      £10.4    4.66
 ✅        Bruno G.                       Newcastle    £6.8     4.06
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.55

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.44
 🪑        Brobbey                        Sunderland   £5.3     3.66
 ✅        Flemming                       Burnley      £5.3     4.01

================================================================================
Optimization Status: Optimal

In [20]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
0     36         14.116075
1     37         12.389648
2     38         11.908950

In [21]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.04 minute(s)