In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 27
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 28
Squad Points: 71.57

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Matheus N.,a,100.0,28.0,DEF,Man City,Leeds,5.286943,82.0
1,Mings,a,100.0,28.0,DEF,Aston Villa,Wolves,5.040009,83.0
2,Konaté,a,100.0,28.0,DEF,Liverpool,West Ham,4.881866,87.0
3,Martinez,a,100.0,28.0,GK,Aston Villa,Wolves,4.872950,90.0
4,B.Fernandes,a,100.0,28.0,MID,Man Utd,Crystal Palace,4.858434,84.0
5,Gabriel,a,100.0,28.0,DEF,Arsenal,Chelsea,4.787220,84.0
6,Szoboszlai,a,100.0,28.0,MID,Liverpool,West Ham,4.727053,84.0
7,Maatsen,a,NaN,28.0,DEF,Aston Villa,Wolves,4.726399,75.0
8,Trossard,a,100.0,28.0,MID,Arsenal,Chelsea,4.471374,78.0
9,Brobbey,d,100.0,28.0,FWD,Sunderland,Bournemouth,4.173851,77.0
10,Gibbs-White,a,100.0,28.0,MID,Nott'm Forest,Brighton,4.108974,84.0
11,Raúl,a,100.0,28.0,FWD,Fulham,Spurs,4.009967,77.0
12,Amad,a,100.0,28.0,MID,Man Utd,Crystal Palace,3.866212,69.0
13,Raya,a,NaN,28.0,GK,Arsenal,Chelsea,3.473711,90.0
14,Igor Jesus,a,100.0,28.0,FWD,Nott'm Forest,Brighton,2.996935,67.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW28 AND 32

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1098.5,14.74,66.5,0.193,0.051,1.406
1,David Raya Martín,1,GK,Arsenal,1081.5,15.32,90.0,NaN,NaN,1.119
2,Leandro Trossard,1,MID,Arsenal,1081.5,18.33,78.0,0.214,0.155,1.008
3,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1081.5,19.24,83.9,0.053,0.090,0.974
4,Amad Diallo,1,MID,Man Utd,1071.4,19.40,69.1,0.178,0.123,1.433
5,Raúl Jiménez Rodríguez,1,FWD,Fulham,1009.4,19.86,76.1,0.392,0.050,1.100
6,Matheus Nunes,1,DEF,Man City,1029.2,20.11,81.9,0.040,0.065,0.818
7,Morgan Gibbs-White,1,MID,Nott'm Forest,1098.5,20.46,83.9,0.135,0.107,1.363
8,Brian Brobbey,1,FWD,Sunderland,1037.9,21.01,77.2,0.426,0.087,1.215
9,Emiliano Martínez Romero,1,GK,Aston Villa,1027.8,21.84,89.9,NaN,NaN,0.969
10,Ian Maatsen,1,DEF,Aston Villa,1027.8,22.69,76.1,0.038,0.055,0.927
11,Dominik Szoboszlai,1,MID,Liverpool,996.8,23.29,83.6,0.162,0.189,1.039
12,Tyrone Mings,1,DEF,Aston Villa,1027.8,23.35,83.4,0.040,0.052,0.917
13,Bruno Borges Fernandes,1,MID,Man Utd,1071.4,23.98,84.3,0.215,0.195,1.387
14,Ibrahima Konaté,1,DEF,Liverpool,996.8,24.03,86.9,0.042,0.048,0.918

In [7]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW28 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1077.5,52.67,84.3,0.214,0.189,1.364
1,Ibrahima Konaté,a,1,DEF,Liverpool,1051.2,51.71,86.9,0.041,0.046,0.950
2,Alexis Mac Allister,a,0,MID,Liverpool,1051.2,51.33,79.2,0.225,0.165,1.163
3,Tyrone Mings,a,1,DEF,Aston Villa,1045.9,51.07,83.4,0.039,0.051,0.925
4,Dominik Szoboszlai,a,1,MID,Liverpool,1051.2,49.76,83.6,0.159,0.177,1.238
5,Ian Maatsen,a,1,DEF,Aston Villa,1045.9,49.74,76.0,0.038,0.054,0.927
6,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1061.4,49.17,83.9,0.054,0.095,0.932
7,Andrew Robertson,a,0,DEF,Liverpool,1051.2,48.99,61.1,0.038,0.065,0.838
8,Lamare Bogarde,a,0,DEF,Aston Villa,1045.9,48.77,65.4,0.036,0.056,0.870
9,Enzo Le Fée,a,0,MID,Sunderland,1051.3,48.56,85.7,0.145,0.181,1.360
10,Alex Iwobi,a,0,MID,Fulham,1053.4,47.94,84.1,0.171,0.149,1.386
11,Alex Scott,a,0,MID,Bournemouth,1069.1,47.87,84.4,0.167,0.129,1.351
12,Mathias Jensen,a,0,MID,Brentford,1047.6,47.75,80.0,0.160,0.147,1.161
13,Matheus Nunes,a,1,DEF,Man City,1061.9,47.66,81.8,0.040,0.060,0.933
14,Moisés Caicedo Corozo,a,0,MID,Chelsea,1103.7,47.42,84.4,0.125,0.200,1.499
15,Emiliano Martínez Romero,a,1,GK,Aston Villa,1045.9,47.30,89.9,NaN,NaN,1.021
16,Vitaly Janelt,a,0,MID,Brentford,1047.6,47.25,78.6,0.156,0.148,1.162
17,Pau Torres,a,0,DEF,Aston Villa,1045.9,47.23,66.6,0.087,0.046,1.054
18,Anton Stach,a,0,MID,Leeds,1036.2,46.99,69.8,0.216,0.193,1.321
19,Abdukodir Khusanov,a,0,DEF,Man City,1061.9,46.79,74.2,0.041,0.051,0.874
20,Leandro Trossard,a,1,MID,Arsenal,1061.4,46.51,77.9,0.217,0.153,0.905
21,Jayden Bogle,a,0,DEF,Leeds,1036.2,46.27,84.5,0.090,0.048,1.345
22,Pascal Groß,a,0,MID,Brighton,1050.3,46.04,85.1,0.129,0.111,1.237
23,Brian Brobbey,d,1,FWD,Sunderland,1051.3,46.04,77.0,0.425,0.090,1.226
24,Rayan Aït-Nouri,a,0,DEF,Man City,1061.9,45.72,76.6,0.042,0.058,0.959
25,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1073.2,45.51,83.9,0.137,0.116,1.306
26,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1093.3,45.30,85.3,0.124,0.126,1.463
27,Pascal Struijk,a,0,DEF,Leeds,1036.2,45.29,85.4,0.061,0.060,1.328
28,Max Alleyne,d,0,DEF,Man City,1061.9,45.09,62.9,0.147,0.052,1.075
29,Ferdi Kadıoğlu,a,0,DEF,Brighton,1050.3,44.51,86.1,0.043,0.045,1.289
30,Michael Kayode,d,0,DEF,Brentford,1047.6,44.45,85.4,0.040,0.046,1.238
31,Rico Henry,a,0,DEF,Brentford,1047.6,44.42,79.5,0.057,0.048,1.213
32,Lewis Dunk,a,0,DEF,Brighton,1050.3,44.38,86.9,0.040,0.043,1.270
33,Lucas Digne,a,0,DEF,Aston Villa,1045.9,44.26,55.5,0.052,0.065,0.972
34,Piero Hincapié,a,0,DEF,Arsenal,1061.4,44.25,80.4,0.043,0.053,1.048
35,Sepp van den Berg,a,0,DEF,Brentford,1047.6,44.23,84.4,0.043,0.042,1.242
36,Ryan Gravenberch,a,0,MID,Liverpool,1051.2,44.10,85.7,0.081,0.117,1.171
37,Ethan Pinnock,a,0,DEF,Brentford,1047.6,44.07,61.0,0.209,0.057,1.409
38,Marc Guiu Paz,a,0,FWD,Chelsea,1103.7,44.00,43.8,0.741,0.283,1.624
39,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1045.9,43.93,72.3,0.129,0.141,1.148
40,Reiss Nelson,a,0,MID,Brentford,1047.6,43.74,36.2,0.668,0.244,1.572
41,Jeremie Frimpong,d,0,DEF,Liverpool,1051.2,43.66,64.5,0.089,0.050,1.253
42,Amine Adli,a,0,MID,Bournemouth,1069.1,43.66,75.7,0.154,0.109,1.390
43,Jan Paul van Hecke,a,0,DEF,Brighton,1050.3,43.63,78.4,0.050,0.049,1.289
44,John Stones,a,0,DEF,Man City,1061.9,43.61,57.1,0.255,0.109,1.362
45,Mitoma Kaoru,a,0,MID,Brighton,1050.3,43.61,78.6,0.125,0.111,1.260
46,Kristoffer Ajer,a,0,DEF,Brentford,1047.6,43.54,77.8,0.040,0.048,1.218
47,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1073.2,43.36,85.6,0.127,0.074,1.374
48,Raúl Jiménez Rodríguez,a,1,FWD,Fulham,1053.4,43.27,75.8,0.385,0.049,1.246
49,Rico Lewis,a,0,DEF,Man City,1061.9,43.22,63.2,0.166,0.057,1.219

In [9]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW28 AND 32

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ibrahima Konaté,a,1,DEF,Liverpool,996.8,24.03,86.9,0.042,0.048,0.918
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1071.4,23.98,84.3,0.215,0.195,1.387
2,Alexis Mac Allister,a,0,MID,Liverpool,996.8,23.96,79.3,0.227,0.177,0.996
3,Tyrone Mings,a,1,DEF,Aston Villa,1027.8,23.35,83.4,0.040,0.052,0.917
4,Dominik Szoboszlai,a,1,MID,Liverpool,996.8,23.29,83.6,0.162,0.189,1.039
5,Andrew Robertson,a,0,DEF,Liverpool,996.8,22.90,60.2,0.039,0.072,0.794
6,Ian Maatsen,a,1,DEF,Aston Villa,1027.8,22.69,76.1,0.038,0.055,0.927
7,Mathias Jensen,a,0,MID,Brentford,984.9,22.49,79.9,0.166,0.165,1.078
8,Alex Iwobi,a,0,MID,Fulham,1009.4,22.23,84.1,0.176,0.155,1.254
9,Lamare Bogarde,a,0,DEF,Aston Villa,1027.8,22.22,65.3,0.037,0.058,0.872
10,Enzo Le Fée,a,0,MID,Sunderland,1037.9,22.18,85.7,0.144,0.186,1.341
11,Vitaly Janelt,a,0,MID,Brentford,984.9,22.06,78.4,0.165,0.163,1.083
12,Alex Scott,a,0,MID,Bournemouth,1069.2,21.90,84.4,0.172,0.131,1.356
13,Emiliano Martínez Romero,a,1,GK,Aston Villa,1027.8,21.84,89.9,NaN,NaN,0.969
14,Pau Torres,a,0,DEF,Aston Villa,1027.8,21.79,66.5,0.086,0.047,1.019
15,Jeremie Frimpong,d,0,DEF,Liverpool,996.8,21.77,64.5,0.087,0.053,1.048
16,Michael Kayode,d,0,DEF,Brentford,984.9,21.37,85.4,0.040,0.048,1.135
17,Moisés Caicedo Corozo,a,0,MID,Chelsea,1154.0,21.34,84.4,0.123,0.201,1.598
18,Sepp van den Berg,a,0,DEF,Brentford,984.9,21.27,84.4,0.044,0.044,1.143
19,Rico Henry,a,0,DEF,Brentford,984.9,21.18,79.5,0.058,0.052,1.137
20,Brian Brobbey,d,1,FWD,Sunderland,1037.9,21.01,77.2,0.426,0.087,1.215
21,Ethan Pinnock,a,0,DEF,Brentford,984.9,20.93,60.9,0.210,0.060,1.316
22,Pascal Groß,a,0,MID,Brighton,1071.6,20.83,85.1,0.130,0.109,1.273
23,Kenny Tete,a,0,DEF,Fulham,1009.4,20.80,77.7,0.041,0.051,1.179
24,Kristoffer Ajer,a,0,DEF,Brentford,984.9,20.71,77.9,0.041,0.050,1.149
25,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1107.3,20.52,85.3,0.123,0.119,1.503
26,Ryan Gravenberch,a,0,MID,Liverpool,996.8,20.49,85.7,0.083,0.121,1.019
27,Calvin Bassey,a,0,DEF,Fulham,1009.4,20.46,78.4,0.055,0.052,1.238
28,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1098.5,20.46,83.9,0.135,0.107,1.363
29,Reiss Nelson,a,0,MID,Brentford,984.9,20.31,36.3,0.666,0.261,1.446
30,Lucas Digne,a,0,DEF,Aston Villa,1027.8,20.26,55.3,0.051,0.066,0.962
31,Anton Stach,a,0,MID,Leeds,1098.5,20.21,70.2,0.198,0.155,1.505
32,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1027.8,20.15,72.3,0.131,0.146,1.090
33,Matheus Nunes,a,1,DEF,Man City,1029.2,20.11,81.9,0.040,0.065,0.818
34,Lewis Dunk,a,0,DEF,Brighton,1071.6,20.02,86.9,0.040,0.042,1.278
35,Amine Adli,a,0,MID,Bournemouth,1069.2,19.95,75.6,0.158,0.109,1.380
36,Ferdi Kadıoğlu,a,0,DEF,Brighton,1071.6,19.92,86.1,0.042,0.044,1.318
37,Raúl Jiménez Rodríguez,a,1,FWD,Fulham,1009.4,19.86,76.1,0.392,0.050,1.100
38,Marc Guiu Paz,a,0,FWD,Chelsea,1154.0,19.85,43.8,0.745,0.276,1.759
39,Emiliano Buendía Stati,a,0,MID,Aston Villa,1027.8,19.84,63.9,0.204,0.123,1.087
40,Abdukodir Khusanov,a,0,DEF,Man City,1029.2,19.73,74.3,0.041,0.053,0.766
41,Daniel Ballard,a,0,DEF,Sunderland,1037.9,19.67,82.1,0.045,0.042,1.277
42,Mitoma Kaoru,a,0,MID,Brighton,1071.6,19.65,78.5,0.124,0.110,1.298
43,Jan Paul van Hecke,a,0,DEF,Brighton,1071.6,19.57,78.4,0.049,0.049,1.311
44,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1098.5,19.48,85.6,0.124,0.071,1.437
45,Harvey Barnes,a,0,MID,Newcastle,1073.6,19.48,64.9,0.205,0.116,1.295
46,Kiernan Dewsbury-Hall,a,0,MID,Everton,1084.7,19.42,82.0,0.106,0.114,1.375
47,Diego Gómez Amarilla,a,0,MID,Brighton,1071.6,19.42,75.2,0.138,0.105,1.283
48,Amad Diallo,a,1,MID,Man Utd,1071.4,19.40,69.1,0.178,0.123,1.433
49,Ryan Sessegnon,a,0,MID,Fulham,1009.4,19.34,72.3,0.145,0.096,1.200

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 28 to 32

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Liverpool,a,Alexis Mac Allister,23.959506,Leandro Trossard,18.331063,5.628442
1,FWD,Chelsea,a,Marc Guiu Paz,19.848940,Igor Jesus Maciel da Cruz,14.735760,5.113181
2,MID,Brentford,a,Mathias Jensen,22.492364,Leandro Trossard,18.331063,4.161301
3,MID,Fulham,a,Alex Iwobi,22.232414,Leandro Trossard,18.331063,3.901351
4,MID,Sunderland,a,Enzo Le Fée,22.177578,Leandro Trossard,18.331063,3.846515
5,MID,Brentford,a,Vitaly Janelt,22.064693,Leandro Trossard,18.331063,3.733630
6,DEF,Liverpool,a,Andrew Robertson,22.902943,Gabriel dos Santos Magalhães,19.239773,3.663170
7,MID,Bournemouth,a,Alex Scott,21.900525,Leandro Trossard,18.331063,3.569462
8,MID,Chelsea,a,Moisés Caicedo Corozo,21.340093,Leandro Trossard,18.331063,3.009030
9,DEF,Aston Villa,a,Lamare Bogarde,22.215133,Gabriel dos Santos Magalhães,19.239773,2.975360
10,GK,Spurs,a,Guglielmo Vicario,18.287850,David Raya Martín,15.316979,2.970871
11,GK,Bournemouth,a,Đorđe Petrović,18.063643,David Raya Martín,15.316979,2.746665
12,GK,Liverpool,a,Giorgi Mamardashvili,18.002888,David Raya Martín,15.316979,2.685909
13,DEF,Aston Villa,a,Pau Torres,21.793794,Gabriel dos Santos Magalhães,19.239773,2.554022
14,DEF,Liverpool,d,Jeremie Frimpong,21.765289,Gabriel dos Santos Magalhães,19.239773,2.525516
15,MID,Brighton,a,Pascal Groß,20.828861,Leandro Trossard,18.331063,2.497798
16,MID,West Ham,a,Mateus Gonçalo Espanha Fernandes,20.524019,Leandro Trossard,18.331063,2.192956
17,MID,Liverpool,a,Ryan Gravenberch,20.494644,Leandro Trossard,18.331063,2.163581
18,DEF,Brentford,d,Michael Kayode,21.365896,Gabriel dos Santos Magalhães,19.239773,2.126123
19,FWD,Wolves,a,Tolu Arokodare,16.772888,Igor Jesus Maciel da Cruz,14.735760,2.037128

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Leandro Trossard'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 28 and 32:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Leandro Trossard,28.0,MID,Arsenal,Chelsea,6.8,1132.600027,4.471374,78.014024,0.211832,0.137819,1.149095
1,Leandro Trossard,29.0,MID,Arsenal,Brighton,6.8,1068.385456,4.628223,77.938468,0.214681,0.160539,0.939900
2,Leandro Trossard,30.0,MID,Arsenal,Everton,6.8,1052.379469,4.654912,77.938468,0.214681,0.160539,0.862272
3,Leandro Trossard,32.0,MID,Arsenal,Bournemouth,6.8,1072.740568,4.576554,77.938468,0.215395,0.160539,1.078813

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW28 to GW32
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ibrahima Konaté,a,1,DEF,Liverpool,996.8,4.84,86.9,0.042,0.048,0.918
1,Alexis Mac Allister,a,0,MID,Liverpool,996.8,4.83,79.3,0.227,0.177,0.996
2,Bruno Borges Fernandes,a,1,MID,Man Utd,1071.4,4.78,84.3,0.215,0.195,1.387
3,Dominik Szoboszlai,a,1,MID,Liverpool,996.8,4.70,83.6,0.162,0.189,1.039
4,Tyrone Mings,a,1,DEF,Aston Villa,1027.8,4.68,83.4,0.040,0.052,0.917
5,Andrew Robertson,a,0,DEF,Liverpool,996.8,4.61,60.2,0.039,0.072,0.794
6,Ian Maatsen,a,1,DEF,Aston Villa,1027.8,4.55,76.1,0.038,0.055,0.927
7,Mathias Jensen,a,0,MID,Brentford,984.9,4.53,79.9,0.166,0.165,1.078
8,Jeremie Frimpong,d,0,DEF,Liverpool,996.8,4.52,64.5,0.087,0.053,1.048
9,Alex Iwobi,a,0,MID,Fulham,1009.4,4.47,84.1,0.176,0.155,1.254
10,Vitaly Janelt,a,0,MID,Brentford,984.9,4.45,78.4,0.165,0.163,1.083
11,Lamare Bogarde,a,0,DEF,Aston Villa,1027.8,4.44,65.3,0.037,0.058,0.872
12,Enzo Le Fée,a,0,MID,Sunderland,1037.9,4.43,85.7,0.144,0.186,1.341
13,Matheus Nunes,a,1,DEF,Man City,1029.2,4.43,81.9,0.040,0.065,0.818
14,Alex Scott,a,0,MID,Bournemouth,1069.2,4.41,84.4,0.172,0.131,1.356
15,Emiliano Martínez Romero,a,1,GK,Aston Villa,1027.8,4.39,89.9,NaN,NaN,0.969
16,Pau Torres,a,0,DEF,Aston Villa,1027.8,4.38,66.5,0.086,0.047,1.019
17,Michael Kayode,d,0,DEF,Brentford,984.9,4.35,85.4,0.040,0.048,1.135
18,Abdukodir Khusanov,a,0,DEF,Man City,1029.2,4.35,74.3,0.041,0.053,0.766
19,Sepp van den Berg,a,0,DEF,Brentford,984.9,4.32,84.4,0.044,0.044,1.143
20,Rico Henry,a,0,DEF,Brentford,984.9,4.30,79.5,0.058,0.052,1.137
21,Max Alleyne,d,0,DEF,Man City,1029.2,4.28,63.0,0.149,0.053,0.917
22,Moisés Caicedo Corozo,a,0,MID,Chelsea,1154.0,4.26,84.4,0.123,0.201,1.598
23,Ethan Pinnock,a,0,DEF,Brentford,984.9,4.25,60.9,0.210,0.060,1.316
24,Kenny Tete,a,0,DEF,Fulham,1009.4,4.23,77.7,0.041,0.051,1.179
25,Rayan Aït-Nouri,a,0,DEF,Man City,1029.2,4.21,76.7,0.042,0.058,0.864
26,Kristoffer Ajer,a,0,DEF,Brentford,984.9,4.20,77.9,0.041,0.050,1.149
27,Brian Brobbey,d,1,FWD,Sunderland,1037.9,4.20,77.2,0.426,0.087,1.215
28,Calvin Bassey,a,0,DEF,Fulham,1009.4,4.16,78.4,0.055,0.052,1.238
29,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1081.5,4.14,83.9,0.053,0.090,0.974
30,Ryan Gravenberch,a,0,MID,Liverpool,996.8,4.14,85.7,0.083,0.121,1.019
31,Pascal Groß,a,0,MID,Brighton,1071.6,4.13,85.1,0.130,0.109,1.273
32,Rico Lewis,a,0,DEF,Man City,1029.2,4.08,63.3,0.164,0.059,1.063
33,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1098.5,4.08,83.9,0.135,0.107,1.363
34,Lucas Digne,a,0,DEF,Aston Villa,1027.8,4.07,55.3,0.051,0.066,0.962
35,Reiss Nelson,a,0,MID,Brentford,984.9,4.06,36.3,0.666,0.261,1.446
36,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1027.8,4.04,72.3,0.131,0.146,1.090
37,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1107.3,4.04,85.3,0.123,0.119,1.503
38,Amine Adli,a,0,MID,Bournemouth,1069.2,4.03,75.6,0.158,0.109,1.380
39,Anton Stach,a,0,MID,Leeds,1098.5,4.02,70.2,0.198,0.155,1.505
40,John Stones,a,0,DEF,Man City,1029.2,4.01,57.4,0.255,0.110,1.241
41,Emiliano Buendía Stati,a,0,MID,Aston Villa,1027.8,4.00,63.9,0.204,0.123,1.087
42,Raúl Jiménez Rodríguez,a,1,FWD,Fulham,1009.4,3.99,76.1,0.392,0.050,1.100
43,Lewis Dunk,a,0,DEF,Brighton,1071.6,3.98,86.9,0.040,0.042,1.278
44,Marc Guiu Paz,a,0,FWD,Chelsea,1154.0,3.97,43.8,0.745,0.276,1.759
45,Ferdi Kadıoğlu,a,0,DEF,Brighton,1071.6,3.97,86.1,0.042,0.044,1.318
46,Leandro Trossard,a,1,MID,Arsenal,1081.5,3.94,78.0,0.214,0.155,1.008
47,Mitoma Kaoru,a,0,MID,Brighton,1071.6,3.91,78.5,0.124,0.110,1.298
48,Harvey Barnes,a,0,MID,Newcastle,1073.6,3.90,64.9,0.205,0.116,1.295
49,Kiernan Dewsbury-Hall,a,0,MID,Everton,1084.7,3.90,82.0,0.106,0.114,1.375

In [13]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [14]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [15]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.05 minute(s)