In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 37
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
# Reece James goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT player_name_id, season, event, fixture, goals_scored, expected_goals, expected_assists, assists
                          FROM playergw_transformed
                          WHERE expected_goals IS NOT NULL
                            AND player_name_id = 'Erling Haaland'
                          ORDER BY season, event, fixture
""")
view.pivot_table(index=['season'], values=['goals_scored', 'expected_goals', 'expected_assists', 'assists'], aggfunc='sum',margins=True,dropna=False)

            assists  expected_assists  expected_goals  goals_scored
season
20222023.0      9.0           1.33591         17.4943          36.0
20232024.0      8.0           2.18000         29.5700          27.0
20242025.0      3.0           2.04000         21.9000          22.0
20252026.0      8.0           2.67000         25.5000          27.0
All            28.0           8.22591         94.4643         112.0

In [6]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        -- AND latest_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
# print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 38

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,38.0,DEF,Arsenal,Crystal Palace,5.467884,85.0
1,B.Fernandes,a,100.0,38.0,MID,Man Utd,Brighton,5.051865,84.0
2,Gibbs-White,a,75.0,38.0,MID,Nott'm Forest,Bournemouth,4.705208,67.0
3,Bruno G.,a,100.0,38.0,MID,Newcastle,Fulham,4.550595,81.0
4,Szoboszlai,a,100.0,38.0,MID,Liverpool,Brentford,4.436372,86.0
5,Lewis-Skelly,a,NaN,38.0,DEF,Arsenal,Crystal Palace,4.142422,62.0
6,Khusanov,a,100.0,38.0,DEF,Man City,Aston Villa,4.088761,69.0
7,Bernardo,a,100.0,38.0,MID,Man City,Aston Villa,4.066230,74.0
8,Matheus N.,a,100.0,38.0,DEF,Man City,Aston Villa,3.939715,69.0
9,Van Hecke,a,100.0,38.0,DEF,Brighton,Man Utd,3.859833,87.0
10,Raya,a,NaN,38.0,GK,Arsenal,Crystal Palace,3.764194,88.0
11,Flemming,a,100.0,38.0,FWD,Burnley,Wolves,3.707480,69.0
12,Brobbey,a,100.0,38.0,FWD,Sunderland,Chelsea,3.460284,74.0
13,Martinez,a,100.0,38.0,GK,Aston Villa,Man City,3.048074,90.0
14,Isak,d,100.0,38.0,FWD,Liverpool,Brentford,2.825935,49.0

In [7]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW38 AND 42

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1065.8,2.83,49.1,0.374,1.0,0.071,1.596,1.331
1,Emiliano Martínez Romero,1,GK,Aston Villa,1247.2,3.05,89.8,NaN,1.0,NaN,1.000,2.121
2,Brian Brobbey,1,FWD,Sunderland,1084.1,3.46,74.3,0.271,1.0,0.040,1.000,1.282
3,Zian Flemming,1,FWD,Burnley,920.6,3.71,69.4,0.398,1.0,0.054,1.000,1.510
4,David Raya Martín,1,GK,Arsenal,1037.7,3.76,88.5,NaN,1.0,NaN,1.000,1.057
5,Jan Paul van Hecke,1,DEF,Brighton,1134.2,3.86,86.9,0.050,1.0,0.036,1.000,1.362
6,Matheus Nunes,1,DEF,Man City,1115.3,3.94,68.8,0.040,1.0,0.175,2.758,1.329
7,Bernardo Mota Veiga de Carvalho e Silva,1,MID,Man City,1115.3,4.07,74.3,0.145,1.0,0.159,1.000,1.211
8,Abdukodir Khusanov,1,DEF,Man City,1115.3,4.09,69.0,0.047,1.0,0.212,1.000,1.304
9,Myles Lewis-Skelly,1,DEF,Arsenal,1037.7,4.14,62.1,0.040,1.0,0.036,1.000,0.913
10,Dominik Szoboszlai,1,MID,Liverpool,1065.8,4.44,86.0,0.171,1.0,0.166,1.000,1.426
11,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1037.9,4.55,81.5,0.239,1.0,0.135,1.000,1.325
12,Morgan Gibbs-White,1,MID,Nott'm Forest,1111.6,4.71,67.0,0.310,1.0,0.328,2.011,1.958
13,Bruno Borges Fernandes,1,MID,Man Utd,1085.1,5.05,84.4,0.216,1.0,0.310,1.348,1.416
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1037.7,5.47,84.6,0.136,1.0,0.104,1.000,0.874

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    --AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW38 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1037.7,5.47,84.6,1.000,0.136,1.000,0.104,0.874
1,Jurriën Timber,d,0,DEF,Arsenal,1037.7,5.38,62.6,1.000,0.222,1.000,0.260,0.970
2,Leandro Trossard,a,0,MID,Arsenal,1037.7,5.24,75.1,1.426,0.271,1.811,0.330,0.891
3,Bruno Borges Fernandes,a,1,MID,Man Utd,1085.1,5.05,84.4,1.000,0.216,1.348,0.310,1.416
4,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1111.6,4.71,67.0,1.000,0.310,2.011,0.328,1.958
5,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1037.9,4.55,81.5,1.000,0.239,1.000,0.135,1.325
6,Mathias Jensen,a,0,MID,Brentford,1147.6,4.55,76.0,2.030,0.294,1.000,0.101,1.319
7,Marcus Tavernier,a,0,MID,Bournemouth,1042.2,4.51,82.2,1.000,0.206,1.000,0.141,1.210
8,Ladislav Krejcí,a,0,DEF,Wolves,870.1,4.45,79.5,1.000,0.048,1.000,0.048,0.955
9,Dominik Szoboszlai,a,1,MID,Liverpool,1065.8,4.44,86.0,1.000,0.171,1.000,0.166,1.426
10,Nathan Patterson,a,0,DEF,Everton,972.1,4.44,54.1,1.000,0.122,1.000,0.351,1.206
11,Enzo Fernández,a,0,MID,Chelsea,1040.6,4.44,86.2,1.000,0.187,1.000,0.132,1.258
12,James Justin,a,0,DEF,Leeds,989.4,4.38,87.2,1.000,0.034,1.000,0.047,1.051
13,Michael Keane,a,0,DEF,Everton,972.1,4.35,83.6,1.000,0.062,1.000,0.039,1.140
14,Vitalii Mykolenko,a,0,DEF,Everton,972.1,4.34,84.9,1.000,0.054,1.000,0.038,1.102
15,Jake O'Brien,a,0,DEF,Everton,972.1,4.33,83.0,1.000,0.050,1.000,0.038,1.093
16,Santiago Ignacio Bueno,a,0,DEF,Wolves,870.1,4.32,87.0,1.000,0.044,1.000,0.047,1.055
17,Jaka Bijol,a,0,DEF,Leeds,989.4,4.32,80.8,1.000,0.033,1.000,0.053,1.015
18,Anton Stach,d,0,MID,Leeds,989.4,4.19,81.0,1.000,0.167,1.000,0.114,1.108
19,Joe Rodon,a,0,DEF,Leeds,989.4,4.18,84.0,1.000,0.033,1.000,0.026,1.087
20,Toti Gomes,a,0,DEF,Wolves,870.1,4.15,79.4,1.000,0.040,1.000,0.027,1.057
21,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1042.2,4.15,72.9,1.000,0.220,1.000,0.108,1.225
22,Myles Lewis-Skelly,a,1,DEF,Arsenal,1037.7,4.14,62.1,1.000,0.040,1.000,0.036,0.913
23,Alexis Mac Allister,a,0,MID,Liverpool,1065.8,4.14,74.5,1.000,0.209,1.000,0.108,1.442
24,Yerson Mosquera Valdelamar,a,0,DEF,Wolves,870.1,4.10,77.8,1.000,0.035,1.000,0.029,1.045
25,Cristhian Mosquera,a,0,DEF,Arsenal,1037.7,4.10,61.4,1.000,0.039,1.000,0.065,0.962
26,Abdukodir Khusanov,a,1,DEF,Man City,1115.3,4.09,69.0,1.000,0.047,1.000,0.212,1.304
27,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1115.3,4.07,74.3,1.000,0.145,1.000,0.159,1.211
28,El Hadji Malick Diouf,a,0,DEF,West Ham,1026.2,4.07,86.2,1.000,0.036,1.923,0.121,1.309
29,Jaidon Anthony,a,0,MID,Burnley,920.6,4.07,83.7,1.000,0.166,1.000,0.109,1.888
30,Granit Xhaka,a,0,MID,Sunderland,1084.1,4.05,84.4,1.000,0.082,2.123,0.208,1.421
31,Pedro Lomba Neto,a,0,MID,Chelsea,1040.6,4.02,65.0,1.000,0.187,1.531,0.255,1.385
32,Joško Gvardiol,a,0,DEF,Man City,1115.3,4.01,73.0,1.000,0.085,1.000,0.045,1.304
33,Jack Hinshelwood,a,0,MID,Brighton,1134.2,4.01,81.8,1.000,0.156,1.000,0.099,1.315
34,Kai Havertz,a,0,FWD,Arsenal,1037.7,4.00,59.6,1.000,0.455,1.842,0.233,0.935
35,Maxim De Cuyper,a,0,DEF,Brighton,1134.2,3.97,70.9,1.000,0.138,1.000,0.192,1.625
36,Adam Smith,a,0,DEF,Bournemouth,1042.2,3.97,75.6,1.000,0.042,1.000,0.038,1.206
37,Rodrigo Martins Gomes,a,0,DEF,Wolves,870.1,3.96,48.8,1.000,0.147,1.000,0.037,0.951
38,Matheus Nunes,a,1,DEF,Man City,1115.3,3.94,68.8,1.000,0.040,2.758,0.175,1.329
39,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1026.2,3.94,85.7,1.000,0.113,1.000,0.076,1.127
40,Alex Scott,a,0,MID,Bournemouth,1042.2,3.93,86.5,1.000,0.108,1.000,0.069,1.217
41,Mathys Tel,a,0,MID,Spurs,1049.1,3.88,79.9,1.000,0.148,1.000,0.068,1.253
42,Hugo Bueno López,a,0,DEF,Wolves,870.1,3.87,61.9,1.000,0.035,1.000,0.060,1.023
43,Gabriel Gudmundsson,d,0,DEF,Leeds,989.4,3.86,60.7,1.000,0.067,1.000,0.046,1.085
44,Jan Paul van Hecke,a,1,DEF,Brighton,1134.2,3.86,86.9,1.000,0.050,1.000,0.036,1.362
45,Merlin Röhl,a,0,MID,Everton,972.1,3.85,76.7,1.000,0.132,1.000,0.077,1.134
46,Conor Gallagher,a,0,MID,Spurs,1049.1,3.85,83.0,1.000,0.100,1.793,0.116,1.284
47,Ferdi Kadıoğlu,a,0,DEF,Brighton,1134.2,3.84,86.9,1.000,0.042,1.000,0.055,1.377
48,David Møller Wolfe,a,0,DEF,Wolves,870.1,3.84,64.4,1.000,0.047,1.000,0.125,1.204
49,Mikkel Damsgaard,a,0,MID,Brentford,1147.6,3.82,81.7,1.000,0.093,1.000,0.115,1.328

In [9]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 1 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW38 AND 42

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Erling Haaland,a,0,FWD,Man City,1115.3,6.17,77.4,0.586,1.165,0.547,3.141,1.322
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1037.7,5.47,84.6,0.136,1.000,0.104,1.000,0.874
2,Declan Rice,a,0,MID,Arsenal,1037.7,5.35,78.6,0.288,1.607,0.269,1.403,0.841
3,Bruno Borges Fernandes,a,1,MID,Man Utd,1085.1,5.05,84.4,0.216,1.000,0.310,1.348,1.416
4,Bryan Mbeumo,a,0,MID,Man Utd,1085.1,4.94,70.8,0.453,1.000,0.103,1.000,1.362
5,Riccardo Calafiori,a,0,DEF,Arsenal,1037.7,4.93,69.5,0.143,1.000,0.102,1.000,0.935
6,Anthony Gordon,a,0,MID,Newcastle,1037.9,4.80,53.2,0.434,1.000,0.492,1.697,1.396
7,William Saliba,a,0,DEF,Arsenal,1037.7,4.76,86.2,0.049,1.000,0.058,1.000,0.911
8,Nico O'Reilly,a,0,DEF,Man City,1115.3,4.71,83.1,0.156,1.000,0.045,1.000,1.212
9,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1111.6,4.71,67.0,0.310,1.000,0.328,2.011,1.958
10,Bukayo Saka,a,0,MID,Arsenal,1037.7,4.71,69.9,0.230,1.000,0.241,1.439,0.768
11,William Osula,a,0,FWD,Newcastle,1037.9,4.68,69.9,0.508,1.000,0.149,1.000,1.441
12,Dominic Calvert-Lewin,a,0,FWD,Leeds,989.4,4.67,86.5,0.404,1.000,0.162,1.918,1.062
13,Eberechi Eze,a,0,MID,Arsenal,1037.7,4.66,70.6,0.270,1.000,0.163,1.000,0.829
14,Antoine Semenyo,a,0,MID,Man City,1115.3,4.61,66.2,0.307,1.354,0.260,1.653,1.209
15,Cole Palmer,a,0,MID,Chelsea,1040.6,4.60,85.5,0.243,1.000,0.116,1.000,1.337
16,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1037.9,4.55,81.5,0.239,1.000,0.135,1.000,1.325
17,Morgan Rogers,a,0,MID,Aston Villa,1247.2,4.48,86.1,0.190,1.000,0.240,1.858,2.644
18,Karl Darlow,a,0,GK,Leeds,989.4,4.44,89.9,NaN,1.000,NaN,1.000,0.918
19,Dominik Szoboszlai,a,1,MID,Liverpool,1065.8,4.44,86.0,0.171,1.000,0.166,1.000,1.426
20,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1085.1,4.43,85.5,0.197,1.000,0.130,1.000,1.383
21,James Tarkowski,a,0,DEF,Everton,972.1,4.39,86.8,0.065,1.000,0.042,1.000,1.165
22,Dango Ouattara,a,0,MID,Brentford,1147.6,4.30,75.4,0.209,1.000,0.159,1.563,1.435
23,Adrien Truffert,a,0,DEF,Bournemouth,1042.2,4.28,86.9,0.058,1.000,0.077,1.000,1.244
24,Ollie Watkins,a,0,FWD,Aston Villa,1247.2,4.28,78.7,0.349,1.000,0.226,4.193,1.786
25,Yankuba Minteh,a,0,MID,Brighton,1134.2,4.27,84.8,0.184,1.000,0.114,1.000,1.305
26,Marc Guéhi,a,0,DEF,Man City,1115.3,4.26,86.1,0.051,1.000,0.053,1.000,1.240
27,Mohamed Salah,a,0,MID,Liverpool,1065.8,4.25,55.6,0.411,1.000,0.219,1.780,1.353
28,Piero Hincapié,a,0,DEF,Arsenal,1037.7,4.24,57.1,0.051,1.000,0.089,1.000,0.896
29,João Pedro Junqueira de Jesus,d,0,FWD,Chelsea,1040.6,4.23,82.3,0.405,1.000,0.048,1.000,1.388
30,Jérémy Doku,a,0,MID,Man City,1115.3,4.19,71.0,0.179,1.000,0.191,1.000,1.213
31,Phil Foden,a,0,MID,Man City,1115.3,4.18,58.3,0.351,1.729,0.173,1.000,1.247
32,Crysencio Summerville,a,0,MID,West Ham,1026.2,4.17,85.0,0.173,1.000,0.084,1.000,1.250
33,Marcos Senesi Barón,a,0,DEF,Bournemouth,1042.2,4.17,86.0,0.044,1.000,0.068,1.000,1.242
34,Myles Lewis-Skelly,a,1,DEF,Arsenal,1037.7,4.14,62.1,0.040,1.000,0.036,1.000,0.913
35,Cody Gakpo,a,0,MID,Liverpool,1065.8,4.10,70.0,0.240,1.000,0.106,1.000,1.343
36,Abdukodir Khusanov,a,1,DEF,Man City,1115.3,4.09,69.0,0.047,1.000,0.212,1.000,1.304
37,Pascal Groß,a,0,MID,Brighton,1134.2,4.09,86.1,0.108,1.000,0.128,1.000,1.313
38,James Hill,a,0,DEF,Bournemouth,1042.2,4.08,82.6,0.044,1.000,0.059,1.000,1.233
39,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1115.3,4.07,74.3,0.145,1.000,0.159,1.000,1.211
40,Francisco Evanilson de Lima Barbosa,a,0,FWD,Bournemouth,1042.2,4.07,73.7,0.370,1.000,0.162,3.155,1.087
41,Kiernan Dewsbury-Hall,a,0,MID,Everton,972.1,4.04,86.7,0.100,1.000,0.106,1.000,1.147
42,Virgil van Dijk,a,0,DEF,Liverpool,1065.8,4.02,83.2,0.116,1.000,0.045,1.000,1.619
43,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,1147.6,4.02,86.7,0.360,1.000,0.043,1.000,1.469
44,Matheus Nunes,a,1,DEF,Man City,1115.3,3.94,68.8,0.040,1.000,0.175,2.758,1.329
45,Pascal Struijk,d,0,DEF,Leeds,989.4,3.93,68.0,0.058,1.000,0.036,1.000,1.131
46,John McGinn,a,0,MID,Aston Villa,1247.2,3.91,81.3,0.167,1.000,0.111,1.000,2.273
47,Jordan Pickford,a,0,GK,Everton,972.1,3.91,89.4,NaN,1.000,NaN,1.000,1.014
48,Richarlison de Andrade,a,0,FWD,Spurs,1049.1,3.89,80.3,0.286,1.000,0.136,3.055,1.247
49,Iliman Ndiaye,a,0,MID,Everton,972.1,3.89,84.6,0.100,1.000,0.079,1.000,1.179

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 38 to 42

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Arsenal,d,Jurriën Timber,5.383644,Jan Paul van Hecke,3.859833,1.523811
1,FWD,Arsenal,a,Kai Havertz,4.004181,Alexander Isak,2.825935,1.178246
2,MID,Arsenal,a,Leandro Trossard,5.240438,Bernardo Mota Veiga de Carvalho e Silva,4.066230,1.174207
3,FWD,Wolves,a,Adam Armstrong,3.633451,Alexander Isak,2.825935,0.807516
4,GK,Wolves,a,José Malheiro de Sá,3.728071,Emiliano Martínez Romero,3.048074,0.679998
5,GK,Wolves,a,Daniel Bentley,3.712920,Emiliano Martínez Romero,3.048074,0.664846
6,GK,Brentford,a,Hákon Rafn Valdimarsson,3.705024,Emiliano Martínez Romero,3.048074,0.656951
7,GK,Crystal Palace,a,Walter Benítez,3.700038,Emiliano Martínez Romero,3.048074,0.651964
8,GK,West Ham,a,Mads Hermansen,3.695584,Emiliano Martínez Romero,3.048074,0.647510
9,FWD,Chelsea,a,Liam Delap,3.472011,Alexander Isak,2.825935,0.646075
10,GK,Spurs,a,Guglielmo Vicario,3.688604,Emiliano Martínez Romero,3.048074,0.640531
11,FWD,Spurs,d,Dominic Solanke-Mitchell,3.430646,Alexander Isak,2.825935,0.604711
12,DEF,Wolves,a,Ladislav Krejcí,4.446666,Jan Paul van Hecke,3.859833,0.586833
13,DEF,Everton,a,Nathan Patterson,4.435246,Jan Paul van Hecke,3.859833,0.575413
14,FWD,Wolves,a,Mateus Mané,3.358235,Alexander Isak,2.825935,0.532300
15,DEF,Leeds,a,James Justin,4.380545,Jan Paul van Hecke,3.859833,0.520712
16,GK,Liverpool,d,Alisson Becker,3.565735,Emiliano Martínez Romero,3.048074,0.517662
17,GK,Leeds,a,Lucas Estella Perri,3.544558,Emiliano Martínez Romero,3.048074,0.496484
18,GK,Sunderland,a,Melker Ellborg,3.541192,Emiliano Martínez Romero,3.048074,0.493119
19,GK,Spurs,a,Antonín Kinský,3.540202,Emiliano Martínez Romero,3.048074,0.492128

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 38 and 42:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,38.0,FWD,Man City,Aston Villa,14.7,1115.304922,6.167373,77.404438,0.586279,0.546868,1.322333

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'DEF'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW38 to GW42
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,340.2,1.79,84.6,0.136,1.000,0.104,1.000,0.874
1,Jurriën Timber,d,0,DEF,Arsenal,340.2,1.76,62.6,0.222,1.000,0.260,1.000,0.970
2,Leandro Trossard,a,0,MID,Arsenal,340.2,1.72,75.1,0.271,1.426,0.330,1.811,0.891
3,Bruno Borges Fernandes,a,1,MID,Man Utd,355.7,1.66,84.4,0.216,1.000,0.310,1.348,1.416
4,Morgan Gibbs-White,a,1,MID,Nott'm Forest,364.4,1.54,67.0,0.310,1.000,0.328,2.011,1.958
5,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,340.2,1.49,81.5,0.239,1.000,0.135,1.000,1.325
6,Mathias Jensen,a,0,MID,Brentford,376.2,1.49,76.0,0.294,2.030,0.101,1.000,1.319
7,Marcus Tavernier,a,0,MID,Bournemouth,341.6,1.48,82.2,0.206,1.000,0.141,1.000,1.210
8,Ladislav Krejcí,a,0,DEF,Wolves,285.2,1.46,79.5,0.048,1.000,0.048,1.000,0.955
9,Enzo Fernández,a,0,MID,Chelsea,341.1,1.46,86.2,0.187,1.000,0.132,1.000,1.258
10,Dominik Szoboszlai,a,1,MID,Liverpool,349.3,1.45,86.0,0.171,1.000,0.166,1.000,1.426
11,Nathan Patterson,a,0,DEF,Everton,318.6,1.45,54.1,0.122,1.000,0.351,1.000,1.206
12,James Justin,a,0,DEF,Leeds,324.3,1.44,87.2,0.034,1.000,0.047,1.000,1.051
13,Michael Keane,a,0,DEF,Everton,318.6,1.43,83.6,0.062,1.000,0.039,1.000,1.140
14,Jake O'Brien,a,0,DEF,Everton,318.6,1.42,83.0,0.050,1.000,0.038,1.000,1.093
15,Vitalii Mykolenko,a,0,DEF,Everton,318.6,1.42,84.9,0.054,1.000,0.038,1.000,1.102
16,Jaka Bijol,a,0,DEF,Leeds,324.3,1.42,80.8,0.033,1.000,0.053,1.000,1.015
17,Santiago Ignacio Bueno,a,0,DEF,Wolves,285.2,1.42,87.0,0.044,1.000,0.047,1.000,1.055
18,Anton Stach,d,0,MID,Leeds,324.3,1.37,81.0,0.167,1.000,0.114,1.000,1.108
19,Joe Rodon,a,0,DEF,Leeds,324.3,1.37,84.0,0.033,1.000,0.026,1.000,1.087
20,Alexis Mac Allister,a,0,MID,Liverpool,349.3,1.36,74.5,0.209,1.000,0.108,1.000,1.442
21,Toti Gomes,a,0,DEF,Wolves,285.2,1.36,79.4,0.040,1.000,0.027,1.000,1.057
22,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,341.6,1.36,72.9,0.220,1.000,0.108,1.000,1.225
23,Myles Lewis-Skelly,a,1,DEF,Arsenal,340.2,1.36,62.1,0.040,1.000,0.036,1.000,0.913
24,Yerson Mosquera Valdelamar,a,0,DEF,Wolves,285.2,1.34,77.8,0.035,1.000,0.029,1.000,1.045
25,Abdukodir Khusanov,a,1,DEF,Man City,365.6,1.34,69.0,0.047,1.000,0.212,1.000,1.304
26,Cristhian Mosquera,a,0,DEF,Arsenal,340.2,1.34,61.4,0.039,1.000,0.065,1.000,0.962
27,El Hadji Malick Diouf,a,0,DEF,West Ham,336.4,1.33,86.2,0.036,1.000,0.121,1.923,1.309
28,Granit Xhaka,a,0,MID,Sunderland,355.4,1.33,84.4,0.082,1.000,0.208,2.123,1.421
29,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,365.6,1.33,74.3,0.145,1.000,0.159,1.000,1.211
30,Jaidon Anthony,a,0,MID,Burnley,301.8,1.33,83.7,0.166,1.000,0.109,1.000,1.888
31,Joško Gvardiol,a,0,DEF,Man City,365.6,1.32,73.0,0.085,1.000,0.045,1.000,1.304
32,Pedro Lomba Neto,a,0,MID,Chelsea,341.1,1.32,65.0,0.187,1.000,0.255,1.531,1.385
33,Kai Havertz,a,0,FWD,Arsenal,340.2,1.31,59.6,0.455,1.000,0.233,1.842,0.935
34,Jack Hinshelwood,a,0,MID,Brighton,371.8,1.31,81.8,0.156,1.000,0.099,1.000,1.315
35,Maxim De Cuyper,a,0,DEF,Brighton,371.8,1.30,70.9,0.138,1.000,0.192,1.000,1.625
36,Adam Smith,a,0,DEF,Bournemouth,341.6,1.30,75.6,0.042,1.000,0.038,1.000,1.206
37,Rodrigo Martins Gomes,a,0,DEF,Wolves,285.2,1.30,48.8,0.147,1.000,0.037,1.000,0.951
38,Alex Scott,a,0,MID,Bournemouth,341.6,1.29,86.5,0.108,1.000,0.069,1.000,1.217
39,Matheus Nunes,a,1,DEF,Man City,365.6,1.29,68.8,0.040,1.000,0.175,2.758,1.329
40,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,336.4,1.29,85.7,0.113,1.000,0.076,1.000,1.127
41,Jan Paul van Hecke,a,1,DEF,Brighton,371.8,1.27,86.9,0.050,1.000,0.036,1.000,1.362
42,Mathys Tel,a,0,MID,Spurs,343.9,1.27,79.9,0.148,1.000,0.068,1.000,1.253
43,Hugo Bueno López,a,0,DEF,Wolves,285.2,1.27,61.9,0.035,1.000,0.060,1.000,1.023
44,Ferdi Kadıoğlu,a,0,DEF,Brighton,371.8,1.26,86.9,0.042,1.000,0.055,1.000,1.377
45,Merlin Röhl,a,0,MID,Everton,318.6,1.26,76.7,0.132,1.000,0.077,1.000,1.134
46,Gabriel Gudmundsson,d,0,DEF,Leeds,324.3,1.26,60.7,0.067,1.000,0.046,1.000,1.085
47,Conor Gallagher,a,0,MID,Spurs,343.9,1.26,83.0,0.100,1.000,0.116,1.793,1.284
48,David Møller Wolfe,a,0,DEF,Wolves,285.2,1.26,64.4,0.047,1.000,0.125,1.000,1.204
49,Ethan Ampadu,a,0,MID,Leeds,324.3,1.25,86.3,0.059,1.000,0.077,1.000,0.841

# Multi-week optimizer

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [15]:
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(picks_current_gameweek + 1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.9m / £102.4m
Total Weighted Expected Points: 49.24
Remaining Budget: £4.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.0     3.05
 ✅        Raya                           Arsenal      £6.2     3.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Van Hecke                      Brighton     £4.7     3.86
 ✅        Gabriel                        Arsenal      £7.3     5.47
 ✅        Lewis-Skelly                   Arsenal      £5.0     4.14
 ✅        Khusanov                       Man City     £5.4     4.09
 ✅        Matheus N.                     Man City     £5.3     3.94

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.1     4.44
 ✅        Bernardo                       Man City     £6.2     4.07
 ✅        B.Fernandes                    Man Utd      £10.4    5.05
 ✅        Bruno G.                       Newcastle    £6.9     4.55
 ✅        Gibbs-White                    Nott'm Forest £7.5     4.71

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.83
 🪑        Brobbey                        Sunderland   £5.3     3.46
 ✅        Flemming                       Burnley      £5.3     3.71

================================================================================
Optimization Status: Optimal

Optimization complete. Final DataFrame created.

event      web_name position  38
5           Gabriel      DEF   1
8          Khusanov      DEF   1
9      Lewis-Skelly      DEF   1
11       Matheus N.      DEF   1
14        Van Hecke      DEF   0
2           Brobbey      FWD   0
4          Flemming      FWD   1
7              Isak      FWD   0
10         Martinez       GK   0
12             Raya       GK   1
0       B.Fernandes      MID   1
1          Bernardo      MID   1
3          Bruno G.      MID   1
6       Gibbs-White      MID   1
13       Szoboszlai      MID   1

In [16]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [17]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [18]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [19]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW38 to GW38...

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.9m / £102.4m
Total Weighted Expected Points: 49.24
Remaining Budget: £4.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.0     3.05
 ✅        Raya                           Arsenal      £6.2     3.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Van Hecke                      Brighton     £4.7     3.86
 ✅        Gabriel                        Arsenal      £7.3     5.47
 ✅        Lewis-Skelly                   Arsenal      £5.0     4.14
 ✅        Khusanov                       Man City     £5.4     4.09
 ✅        Matheus N.                     Man City     £5.3     3.94

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.1     4.44
 ✅        Bernardo                       Man City     £6.2     4.07
 ✅        B.Fernandes                    Man Utd      £10.4    5.05
 ✅        Bruno G.                       Newcastle    £6.9     4.55
 ✅        Gibbs-White                    Nott'm Forest £7.5     4.71

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.83
 🪑        Brobbey                        Sunderland   £5.3     3.46
 ✅        Flemming                       Burnley      £5.3     3.71

================================================================================
Optimization Status: Optimal

In [20]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
0     38         11.874713

In [21]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.04 minute(s)