In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 25
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 26
Squad Points: 69.85

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,26.0,DEF,Arsenal,Brentford,5.134039,84.0
1,B.Fernandes,a,100.0,26.0,MID,Man Utd,West Ham,4.997050,78.0
2,Matheus N.,a,100.0,26.0,DEF,Man City,Fulham,4.815088,87.0
3,Szoboszlai,s,100.0,26.0,MID,Liverpool,Sunderland,4.773334,86.0
4,Gibbs-White,a,100.0,26.0,MID,Nott'm Forest,Wolves,4.560251,84.0
5,Trossard,d,100.0,26.0,MID,Arsenal,Brentford,4.398986,72.0
6,Amad,a,100.0,26.0,MID,Man Utd,West Ham,4.370828,84.0
7,Khusanov,d,100.0,26.0,DEF,Man City,Fulham,4.358540,77.0
8,Raya,a,NaN,26.0,GK,Arsenal,Brentford,4.339246,90.0
9,Konaté,a,100.0,26.0,DEF,Liverpool,Sunderland,4.280005,87.0
10,Martinez,a,100.0,26.0,GK,Aston Villa,Brighton,4.117136,89.0
11,Brobbey,a,100.0,26.0,FWD,Sunderland,Liverpool,3.967872,85.0
12,Raúl,a,100.0,26.0,FWD,Fulham,Man City,3.863410,82.0
13,Tarkowski,a,NaN,26.0,DEF,Everton,Bournemouth,3.447949,87.0
14,Igor Jesus,a,100.0,26.0,FWD,Nott'm Forest,Wolves,3.287519,69.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW26 AND 30

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1081.1,15.65,69.1,0.222,0.042,1.427
1,James Tarkowski,1,DEF,Everton,1073.4,18.38,87.3,0.040,0.042,1.507
2,Raúl Jiménez Rodríguez,1,FWD,Fulham,1050.2,19.99,82.3,0.357,0.052,1.246
3,Brian Brobbey,1,FWD,Sunderland,1065.1,20.17,84.7,0.333,0.067,1.193
4,Amad Diallo,1,MID,Man Utd,1068.3,21.02,84.5,0.147,0.131,1.355
5,Morgan Gibbs-White,1,MID,Nott'm Forest,1081.1,21.11,83.6,0.158,0.116,1.426
6,Emiliano Martínez Romero,1,GK,Aston Villa,1039.3,21.62,88.8,NaN,NaN,1.087
7,Leandro Trossard,1,MID,Arsenal,1070.0,22.33,71.8,0.190,0.171,0.937
8,David Raya Martín,1,GK,Arsenal,1070.0,22.33,89.8,NaN,NaN,0.774
9,Abdukodir Khusanov,1,DEF,Man City,1019.5,23.54,77.1,0.040,0.052,0.905
10,Ibrahima Konaté,1,DEF,Liverpool,986.6,23.86,86.7,0.041,0.045,0.909
11,Bruno Borges Fernandes,1,MID,Man Utd,1068.3,23.86,78.4,0.234,0.192,1.309
12,Dominik Szoboszlai,1,MID,Liverpool,986.6,24.90,86.4,0.203,0.204,1.004
13,Matheus Nunes,1,DEF,Man City,1019.5,25.69,86.8,0.040,0.114,0.875
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1070.0,27.03,83.6,0.065,0.151,0.800

In [7]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
        -- AND position IN ('MID','FWD')
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 26

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Clyne,a,100.0,26.0,DEF,Crystal Palace,Burnley,5.126226
1,Richards,a,100.0,26.0,DEF,Crystal Palace,Burnley,4.826595
2,Zubimendi,a,100.0,26.0,MID,Arsenal,Brentford,4.739167
3,Milenković,a,NaN,26.0,DEF,Nott'm Forest,Wolves,4.627379
4,Dalot,a,100.0,26.0,DEF,Man Utd,West Ham,4.625154
5,Aina,a,100.0,26.0,DEF,Nott'm Forest,Wolves,4.548275
6,Canvot,a,100.0,26.0,DEF,Crystal Palace,Burnley,4.537655
7,Jair Cunha,a,NaN,26.0,DEF,Nott'm Forest,Wolves,4.522252
8,Bernardo,a,75.0,26.0,MID,Man City,Fulham,4.514228
9,Caicedo,a,100.0,26.0,MID,Chelsea,Leeds,4.509036

In [8]:
print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 38
    ORDER BY xpoints DESC
""")
view.head(10)

When to use second TRIPLE CAPTAIN chip (gws19-38)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,37.0,DEF,Arsenal,Burnley,6.342897
1,Gabriel dos Santos Magalhães,36.0,DEF,Arsenal,West Ham,6.090700
2,Gabriel dos Santos Magalhães,27.0,DEF,Arsenal,Spurs,6.055029
3,Matheus Nunes,34.0,DEF,Man City,Burnley,5.841881
4,Matheus Nunes,28.0,DEF,Man City,Leeds,5.546214
5,Matheus Nunes,30.0,DEF,Man City,West Ham,5.536699
6,Abdukodir Khusanov,34.0,DEF,Man City,Burnley,5.435477
7,Gabriel dos Santos Magalhães,32.0,DEF,Arsenal,Bournemouth,5.406691
8,Gabriel dos Santos Magalhães,29.0,DEF,Arsenal,Brighton,5.405086
9,Gabriel dos Santos Magalhães,30.0,DEF,Arsenal,Everton,5.387198

In [9]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status  -- Changed this to use your CTE
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW26 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1055.6,65.68,83.5,0.066,0.152,0.772
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1070.2,62.18,78.4,0.233,0.194,1.289
2,Matheus Nunes,a,1,DEF,Man City,1062.1,59.41,86.8,0.040,0.108,0.952
3,Lucas Digne,a,0,DEF,Aston Villa,1041.2,59.23,69.3,0.048,0.080,0.913
4,Vitaly Janelt,a,0,MID,Brentford,1060.3,58.48,86.3,0.169,0.148,1.321
5,Martín Zubimendi Ibáñez,a,0,MID,Arsenal,1055.6,57.79,77.6,0.199,0.196,0.826
6,Ibrahima Konaté,a,1,DEF,Liverpool,1050.5,57.78,86.7,0.041,0.044,1.063
7,Ethan Pinnock,a,0,DEF,Brentford,1060.3,57.48,71.0,0.227,0.060,1.474
8,Pau Torres,a,0,DEF,Aston Villa,1041.2,56.71,80.2,0.038,0.043,1.049
9,Moisés Caicedo Corozo,a,0,MID,Chelsea,1079.1,56.44,85.1,0.122,0.194,1.395
10,Pascal Groß,a,0,MID,Brighton,1061.4,56.43,83.8,0.175,0.112,1.282
11,Ian Maatsen,a,0,DEF,Aston Villa,1041.2,56.40,70.9,0.038,0.063,0.988
12,Maxim De Cuyper,a,0,DEF,Brighton,1061.4,56.17,67.0,0.085,0.140,1.223
13,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1091.3,56.13,85.3,0.141,0.149,1.495
14,Emiliano Martínez Romero,a,1,GK,Aston Villa,1041.2,56.12,88.8,NaN,NaN,1.084
15,Jaka Bijol,a,0,DEF,Leeds,1052.7,55.93,70.5,0.234,0.038,1.452
16,Pascal Struijk,a,0,DEF,Leeds,1052.7,55.90,86.4,0.077,0.059,1.244
17,Alex Scott,a,0,MID,Bournemouth,1061.6,55.78,83.5,0.166,0.117,1.336
18,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1066.2,55.47,83.6,0.159,0.120,1.297
19,Cristhian Mosquera,a,0,DEF,Arsenal,1055.6,55.08,54.9,0.275,0.085,1.157
20,Conor Gallagher,a,0,MID,Spurs,1076.1,55.05,85.0,0.152,0.109,1.372
21,Amad Diallo,a,1,MID,Man Utd,1070.2,54.69,84.4,0.147,0.132,1.338
22,Jayden Bogle,a,0,DEF,Leeds,1052.7,54.62,84.6,0.070,0.047,1.237
23,Tyrone Mings,a,0,DEF,Aston Villa,1041.2,54.23,68.8,0.036,0.043,1.053
24,David Raya Martín,a,1,GK,Arsenal,1055.6,54.05,89.7,NaN,NaN,0.748
25,Emiliano Buendía Stati,a,0,MID,Aston Villa,1041.2,53.99,71.4,0.192,0.127,1.176
26,Abdukodir Khusanov,d,1,DEF,Man City,1062.1,53.96,77.0,0.040,0.051,1.001
27,Lamare Bogarde,a,0,DEF,Aston Villa,1041.2,53.95,56.3,0.037,0.053,0.877
28,Piero Hincapié,a,0,DEF,Arsenal,1055.6,53.94,75.6,0.040,0.054,0.951
29,Leandro Trossard,d,1,MID,Arsenal,1055.6,53.78,71.6,0.191,0.170,0.890
30,Mathias Jensen,a,0,MID,Brentford,1060.3,53.73,75.4,0.151,0.141,1.335
31,Emile Smith Rowe,a,0,MID,Fulham,1064.2,53.60,78.3,0.156,0.116,1.297
32,Anton Stach,d,0,MID,Leeds,1052.7,53.47,79.6,0.102,0.176,1.282
33,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1070.2,53.41,87.2,0.039,0.112,1.338
34,John Stones,d,0,DEF,Man City,1062.1,53.32,57.3,0.233,0.113,1.308
35,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1062.1,53.27,83.4,0.116,0.190,0.974
36,Amadou Onana,a,0,MID,Aston Villa,1041.2,53.07,73.9,0.148,0.128,1.148
37,Enzo Le Fée,a,0,MID,Sunderland,1060.9,52.64,85.6,0.107,0.120,1.390
38,Victor Lindelöf,a,0,DEF,Aston Villa,1041.2,52.34,46.1,0.070,0.068,0.889
39,Brian Brobbey,a,1,FWD,Sunderland,1060.9,52.32,84.7,0.333,0.067,1.174
40,Gabriel Gudmundsson,a,0,DEF,Leeds,1052.7,52.30,85.0,0.034,0.046,1.229
41,Raúl Jiménez Rodríguez,a,1,FWD,Fulham,1064.2,52.16,82.2,0.365,0.052,1.302
42,Ryan Gravenberch,a,0,MID,Liverpool,1050.5,52.13,85.6,0.069,0.146,1.268
43,Michael Kayode,a,0,DEF,Brentford,1060.3,51.70,87.0,0.038,0.046,1.287
44,Max Alleyne,a,0,DEF,Man City,1062.1,51.62,67.6,0.091,0.051,1.113
45,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1041.2,51.44,71.8,0.129,0.140,1.162
46,Alex Iwobi,a,0,MID,Fulham,1064.2,51.42,82.7,0.115,0.117,1.402
47,Mitoma Kaoru,a,0,MID,Brighton,1061.4,51.42,80.5,0.125,0.103,1.300
48,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1066.2,51.31,84.3,0.119,0.090,1.315
49,Murillo Costa dos Santos,d,0,DEF,Nott'm Forest,1066.2,51.22,86.7,0.034,0.043,1.300

In [10]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW26 AND 30

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1070.0,27.03,83.6,0.065,0.151,0.800
1,Joško Gvardiol,0,DEF,Man City,1019.5,25.74,61.5,0.224,0.131,0.970
2,Matheus Nunes,1,DEF,Man City,1019.5,25.69,86.8,0.040,0.114,0.875
3,Dominik Szoboszlai,1,MID,Liverpool,986.6,24.90,86.4,0.203,0.204,1.004
4,Conor Bradley,0,DEF,Liverpool,986.6,24.02,66.0,0.092,0.152,0.953
5,Martín Zubimendi Ibáñez,0,MID,Arsenal,1070.0,23.93,77.6,0.199,0.195,0.870
6,Bruno Borges Fernandes,1,MID,Man Utd,1068.3,23.86,78.4,0.234,0.192,1.309
7,Ibrahima Konaté,1,DEF,Liverpool,986.6,23.86,86.7,0.041,0.045,0.909
8,Abdukodir Khusanov,1,DEF,Man City,1019.5,23.54,77.1,0.040,0.052,0.905
9,John Stones,0,DEF,Man City,1019.5,23.00,57.5,0.230,0.116,1.225
10,Nathaniel Clyne,0,DEF,Crystal Palace,970.7,22.78,58.0,0.308,0.052,1.249
11,Cristhian Mosquera,0,DEF,Arsenal,1070.0,22.75,55.0,0.275,0.078,1.181
12,Vitaly Janelt,0,MID,Brentford,1032.3,22.75,86.3,0.169,0.154,1.280
13,Ethan Pinnock,0,DEF,Brentford,1032.3,22.72,70.6,0.228,0.064,1.418
14,Lucas Digne,0,DEF,Aston Villa,1039.3,22.72,69.3,0.048,0.079,0.920
15,Max Alleyne,0,DEF,Man City,1019.5,22.69,67.6,0.090,0.053,0.990
16,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1019.5,22.55,83.4,0.116,0.195,0.860
17,Fábio Freitas Gouveia Carvalho,0,MID,Brentford,1032.3,22.49,41.0,0.680,0.248,1.696
18,Rayan Aït-Nouri,0,DEF,Man City,1019.5,22.48,76.2,0.041,0.055,1.002
19,Leandro Trossard,1,MID,Arsenal,1070.0,22.33,71.8,0.190,0.171,0.937
20,David Raya Martín,1,GK,Arsenal,1070.0,22.33,89.8,NaN,NaN,0.774
21,Piero Hincapié,0,DEF,Arsenal,1070.0,22.15,75.8,0.040,0.054,0.985
22,Moisés Caicedo Corozo,0,MID,Chelsea,1069.3,21.91,85.0,0.124,0.193,1.328
23,Alex Scott,0,MID,Bournemouth,1009.4,21.91,83.4,0.170,0.125,1.219
24,Pau Torres,0,DEF,Aston Villa,1039.3,21.86,80.2,0.038,0.043,1.050
25,Andrew Robertson,0,DEF,Liverpool,986.6,21.76,61.6,0.037,0.102,0.960
26,Oleksandr Zinchenko,0,DEF,Nott'm Forest,1081.1,21.68,63.8,0.291,0.049,1.488
27,Emiliano Martínez Romero,1,GK,Aston Villa,1039.3,21.62,88.8,NaN,NaN,1.087
28,Ian Maatsen,0,DEF,Aston Villa,1039.3,21.49,70.9,0.038,0.063,1.014
29,Chris Richards,0,DEF,Crystal Palace,970.7,21.36,86.1,0.047,0.042,1.163
30,Pascal Groß,0,MID,Brighton,1111.3,21.30,83.9,0.177,0.097,1.389
31,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1120.0,21.21,85.3,0.139,0.143,1.678
32,Jeremie Frimpong,0,DEF,Liverpool,986.6,21.16,60.8,0.042,0.058,0.942
33,Diego Coppola,0,DEF,Brighton,1111.3,21.16,68.0,0.260,0.054,1.593
34,Adam Armstrong,0,FWD,Wolves,1143.8,21.15,68.7,0.505,0.095,2.056
35,Morgan Gibbs-White,1,MID,Nott'm Forest,1081.1,21.11,83.6,0.158,0.116,1.426
36,Matthijs de Ligt,0,DEF,Man Utd,1068.3,21.10,69.1,0.254,0.052,1.598
37,Amad Diallo,1,MID,Man Utd,1068.3,21.02,84.5,0.147,0.131,1.355
38,Mathias Jensen,0,MID,Brentford,1032.3,20.86,74.4,0.153,0.151,1.286
39,Conor Gallagher,0,MID,Spurs,1119.2,20.84,84.9,0.150,0.103,1.498
40,Tyrone Mings,0,DEF,Aston Villa,1039.3,20.81,68.8,0.035,0.042,1.063
41,Ryan Gravenberch,0,MID,Liverpool,986.6,20.79,85.6,0.071,0.160,0.999
42,Emile Smith Rowe,0,MID,Fulham,1050.2,20.75,78.4,0.156,0.116,1.251
43,Emiliano Buendía Stati,0,MID,Aston Villa,1039.3,20.70,71.4,0.192,0.128,1.235
44,Julio Soler Barreto,0,DEF,Bournemouth,1009.4,20.68,54.9,0.327,0.067,1.512
45,Michael Kayode,0,DEF,Brentford,1032.3,20.58,87.0,0.041,0.047,1.235
46,Lamare Bogarde,0,DEF,Aston Villa,1039.3,20.58,56.0,0.037,0.053,0.892
47,Álex Jiménez Sánchez,0,DEF,Bournemouth,1009.4,20.55,85.2,0.040,0.052,1.173
48,Kevin Schade,0,MID,Brentford,1032.3,20.53,61.5,0.263,0.127,1.290
49,Maxim De Cuyper,0,DEF,Brighton,1111.3,20.52,67.6,0.084,0.136,1.322

In [11]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 26 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Man City,Joško Gvardiol,59.793329,James Tarkowski,47.900135,11.893193
1,DEF,Aston Villa,Lucas Digne,59.226270,James Tarkowski,47.900135,11.326135
2,DEF,Liverpool,Conor Bradley,58.424990,James Tarkowski,47.900135,10.524855
3,FWD,Chelsea,Marc Guiu Paz,51.159508,Igor Jesus Maciel da Cruz,40.839823,10.319685
4,FWD,Wolves,Adam Armstrong,51.026718,Igor Jesus Maciel da Cruz,40.839823,10.186895
5,DEF,Brighton,Diego Coppola,57.742787,James Tarkowski,47.900135,9.842652
6,FWD,Leeds,Dominic Calvert-Lewin,50.655007,Igor Jesus Maciel da Cruz,40.839823,9.815184
7,DEF,Brentford,Ethan Pinnock,57.483282,James Tarkowski,47.900135,9.583146
8,DEF,Nott'm Forest,Oleksandr Zinchenko,56.744724,James Tarkowski,47.900135,8.844588
9,DEF,Aston Villa,Pau Torres,56.705671,James Tarkowski,47.900135,8.805535
10,DEF,Aston Villa,Ian Maatsen,56.399769,James Tarkowski,47.900135,8.499634
11,DEF,Brighton,Maxim De Cuyper,56.173130,James Tarkowski,47.900135,8.272994
12,FWD,West Ham,Niclas Füllkrug,48.891585,Igor Jesus Maciel da Cruz,40.839823,8.051762
13,DEF,Leeds,Jaka Bijol,55.934766,James Tarkowski,47.900135,8.034631
14,DEF,Leeds,Pascal Struijk,55.897684,James Tarkowski,47.900135,7.997549
15,DEF,Arsenal,Cristhian Mosquera,55.079460,James Tarkowski,47.900135,7.179325
16,DEF,Man Utd,Matthijs de Ligt,54.988518,James Tarkowski,47.900135,7.088382
17,DEF,Leeds,Jayden Bogle,54.623252,James Tarkowski,47.900135,6.723117
18,DEF,Aston Villa,Tyrone Mings,54.230962,James Tarkowski,47.900135,6.330827
19,DEF,Aston Villa,Lamare Bogarde,53.948730,James Tarkowski,47.900135,6.048595

In [12]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Amad Diallo'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 26 and 30:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Amad Diallo,26.0,MID,Man Utd,West Ham,6.2,973.988320,4.370828,84.312912,0.151048,0.159040,1.144067
1,Amad Diallo,27.0,MID,Man Utd,Everton,6.2,1071.560644,4.192892,84.498703,0.147487,0.134415,1.439655
2,Amad Diallo,28.0,MID,Man Utd,Crystal Palace,6.2,1058.529332,4.176558,84.498703,0.148056,0.127109,1.433052
3,Amad Diallo,29.0,MID,Man Utd,Newcastle,6.2,1076.267410,4.192892,84.498703,0.147487,0.134415,1.439655
4,Amad Diallo,30.0,MID,Man Utd,Aston Villa,6.2,1161.137041,4.083880,84.498703,0.143043,0.101115,1.319188

In [13]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.25 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW26 to GW30

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1070.0,5.31,83.6,0.065,0.151,0.800
1,Nathaniel Clyne,0,DEF,Crystal Palace,970.7,5.03,58.0,0.308,0.052,1.249
2,Bruno Borges Fernandes,1,MID,Man Utd,1068.3,4.92,78.4,0.234,0.192,1.309
3,Joško Gvardiol,0,DEF,Man City,1019.5,4.86,61.5,0.224,0.131,0.970
4,Matheus Nunes,1,DEF,Man City,1019.5,4.83,86.8,0.040,0.114,0.875
5,Dominik Szoboszlai,1,MID,Liverpool,986.6,4.82,86.4,0.203,0.204,1.004
6,Martín Zubimendi Ibáñez,0,MID,Arsenal,1070.0,4.78,77.6,0.199,0.195,0.870
7,Oleksandr Zinchenko,0,DEF,Nott'm Forest,1081.1,4.75,63.8,0.291,0.049,1.488
8,Chris Richards,0,DEF,Crystal Palace,970.7,4.72,86.1,0.047,0.042,1.163
9,Murillo Costa dos Santos,0,DEF,Nott'm Forest,1081.1,4.60,86.7,0.033,0.044,1.352
10,Moisés Caicedo Corozo,0,MID,Chelsea,1069.3,4.53,85.0,0.124,0.193,1.328
11,Matthijs de Ligt,0,DEF,Man Utd,1068.3,4.52,69.1,0.254,0.052,1.598
12,John Stones,0,DEF,Man City,1019.5,4.49,57.5,0.230,0.116,1.225
13,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1019.5,4.49,83.4,0.116,0.195,0.860
14,David Raya Martín,1,GK,Arsenal,1070.0,4.47,89.8,NaN,NaN,0.774
15,Diogo Dalot Teixeira,0,DEF,Man Utd,1068.3,4.46,87.2,0.039,0.112,1.352
16,Lucas Digne,0,DEF,Aston Villa,1039.3,4.45,69.3,0.048,0.079,0.920
17,Jaydee Canvot,0,DEF,Crystal Palace,970.7,4.45,72.8,0.040,0.077,1.195
18,Leandro Trossard,1,MID,Arsenal,1070.0,4.45,71.8,0.190,0.171,0.937
19,Morgan Gibbs-White,1,MID,Nott'm Forest,1081.1,4.45,83.6,0.158,0.116,1.426
20,Cristhian Mosquera,0,DEF,Arsenal,1070.0,4.45,55.0,0.275,0.078,1.181
21,Filip Jörgensen,0,GK,Chelsea,1069.3,4.44,89.7,NaN,NaN,1.502
22,Conor Bradley,0,DEF,Liverpool,986.6,4.42,66.0,0.092,0.152,0.953
23,Abdukodir Khusanov,1,DEF,Man City,1019.5,4.38,77.1,0.040,0.052,0.905
24,Ibrahima Konaté,1,DEF,Liverpool,986.6,4.38,86.7,0.041,0.045,0.909
25,Alex Scott,0,MID,Bournemouth,1009.4,4.34,83.4,0.170,0.125,1.219
26,Amad Diallo,1,MID,Man Utd,1068.3,4.33,84.5,0.147,0.131,1.355
27,Piero Hincapié,0,DEF,Arsenal,1070.0,4.33,75.8,0.040,0.054,0.985
28,Vitaly Janelt,0,MID,Brentford,1032.3,4.32,86.3,0.169,0.154,1.280
29,Nikola Milenković,0,DEF,Nott'm Forest,1081.1,4.32,86.2,0.043,0.044,1.428
30,Ola Aina,0,DEF,Nott'm Forest,1081.1,4.31,86.5,0.038,0.036,1.369
31,Jair Paula da Cunha Filho,0,DEF,Nott'm Forest,1081.1,4.30,58.2,0.283,0.052,1.661
32,Pascal Groß,0,MID,Brighton,1111.3,4.29,83.9,0.177,0.097,1.389
33,Fábio Freitas Gouveia Carvalho,0,MID,Brentford,1032.3,4.29,41.0,0.680,0.248,1.696
34,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1120.0,4.27,85.3,0.139,0.143,1.678
35,Pau Torres,0,DEF,Aston Villa,1039.3,4.27,80.2,0.038,0.043,1.050
36,Emiliano Martínez Romero,1,GK,Aston Villa,1039.3,4.26,88.8,NaN,NaN,1.087
37,Luke Shaw,0,DEF,Man Utd,1068.3,4.24,87.4,0.039,0.048,1.369
38,Max Alleyne,0,DEF,Man City,1019.5,4.24,67.6,0.090,0.053,0.990
39,Adam Armstrong,0,FWD,Wolves,1143.8,4.23,68.7,0.505,0.095,2.056
40,Nicolò Savona,0,DEF,Nott'm Forest,1081.1,4.23,53.7,0.235,0.053,1.579
41,Ian Maatsen,0,DEF,Aston Villa,1039.3,4.22,70.9,0.038,0.063,1.014
42,Maxim De Cuyper,0,DEF,Brighton,1111.3,4.19,67.6,0.084,0.136,1.322
43,Conor Gallagher,0,MID,Spurs,1119.2,4.19,84.9,0.150,0.103,1.498
44,Wesley Fofana,0,DEF,Chelsea,1069.3,4.18,73.6,0.035,0.049,1.410
45,Emil Krafth,0,DEF,Newcastle,1105.3,4.17,59.5,0.311,0.056,1.662
46,Diego Coppola,0,DEF,Brighton,1111.3,4.16,68.0,0.260,0.054,1.593
47,Rayan Aït-Nouri,0,DEF,Man City,1019.5,4.16,76.2,0.041,0.055,1.002
48,Ethan Pinnock,0,DEF,Brentford,1032.3,4.13,70.6,0.228,0.064,1.418
49,Emiliano Buendía Stati,0,MID,Aston Villa,1039.3,4.11,71.4,0.192,0.128,1.235

In [14]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [15]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [16]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.02 minute(s)