In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 26
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 27
Squad Points: 70.63

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,27.0,DEF,Arsenal,Spurs,5.752827,85.0
1,Konaté,a,100.0,27.0,DEF,Liverpool,Nott'm Forest,4.882875,87.0
2,Raya,a,NaN,27.0,GK,Arsenal,Spurs,4.797991,90.0
3,Trossard,d,75.0,27.0,MID,Arsenal,Spurs,4.779146,76.0
4,B.Fernandes,a,100.0,27.0,MID,Man Utd,Everton,4.684832,86.0
5,Martinez,a,100.0,27.0,GK,Aston Villa,Leeds,4.678378,87.0
6,Szoboszlai,a,0.0,27.0,MID,Liverpool,Nott'm Forest,4.669761,84.0
7,Matheus N.,a,100.0,27.0,DEF,Man City,Newcastle,4.482644,83.0
8,Khusanov,a,100.0,27.0,DEF,Man City,Newcastle,4.303230,82.0
9,Amad,a,100.0,27.0,MID,Man Utd,Everton,4.225260,85.0
10,Gibbs-White,a,100.0,27.0,MID,Nott'm Forest,Liverpool,4.029896,82.0
11,Raúl,a,100.0,27.0,FWD,Fulham,Sunderland,3.877037,66.0
12,Brobbey,a,100.0,27.0,FWD,Sunderland,Fulham,3.583833,78.0
13,Tarkowski,a,NaN,27.0,DEF,Everton,Man Utd,3.409208,87.0
14,Igor Jesus,a,100.0,27.0,FWD,Nott'm Forest,Liverpool,2.718219,57.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW27 AND 31

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1096.2,13.96,56.7,0.233,0.056,1.441
1,David Raya Martín,1,GK,Arsenal,1059.8,16.45,89.7,NaN,NaN,0.909
2,Brian Brobbey,1,FWD,Sunderland,1048.5,17.82,77.8,0.250,0.072,1.261
3,Leandro Trossard,1,MID,Arsenal,1059.8,18.09,76.8,0.187,0.160,1.023
4,James Tarkowski,1,DEF,Everton,1089.5,18.39,87.5,0.040,0.043,1.489
5,Raúl Jiménez Rodríguez,1,FWD,Fulham,980.9,19.39,65.8,0.500,0.048,1.096
6,Abdukodir Khusanov,1,DEF,Man City,1016.5,20.01,81.8,0.038,0.055,0.802
7,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1059.8,20.37,84.9,0.057,0.110,0.885
8,Matheus Nunes,1,DEF,Man City,1016.5,20.48,83.3,0.039,0.126,0.867
9,Amad Diallo,1,MID,Man Utd,1086.6,21.03,84.5,0.154,0.127,1.474
10,Morgan Gibbs-White,1,MID,Nott'm Forest,1096.2,21.06,82.4,0.156,0.123,1.445
11,Emiliano Martínez Romero,1,GK,Aston Villa,1023.2,21.81,87.2,NaN,NaN,0.948
12,Dominik Szoboszlai,1,MID,Liverpool,989.9,23.30,84.4,0.162,0.193,0.963
13,Bruno Borges Fernandes,1,MID,Man Utd,1086.6,23.35,85.7,0.200,0.172,1.384
14,Ibrahima Konaté,1,DEF,Liverpool,989.9,24.96,87.5,0.049,0.048,0.844

In [17]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status IN ('a', 'd')
        -- AND position IN ('MID','FWD')
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 27

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Caicedo,a,100.0,27.0,MID,Chelsea,Burnley,5.067684
1,Hincapie,a,100.0,27.0,DEF,Arsenal,Spurs,4.997840
2,Mings,a,100.0,27.0,DEF,Aston Villa,Leeds,4.910874
3,Bogarde,a,100.0,27.0,DEF,Aston Villa,Leeds,4.805507
4,Pinnock,a,100.0,27.0,DEF,Brentford,Brighton,4.624388
5,Robertson,a,NaN,27.0,DEF,Liverpool,Nott'm Forest,4.623197
6,Richards,a,100.0,27.0,DEF,Crystal Palace,Wolves,4.594497
7,Lewis-Skelly,a,NaN,27.0,DEF,Arsenal,Spurs,4.550721
8,Pau,a,100.0,27.0,DEF,Aston Villa,Leeds,4.549004
9,Maatsen,a,NaN,27.0,DEF,Aston Villa,Leeds,4.527293

In [8]:
print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 38
    ORDER BY xpoints DESC
""")
view.head(10)

When to use second TRIPLE CAPTAIN chip (gws19-38)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,37.0,DEF,Arsenal,Burnley,5.998791
1,Gabriel dos Santos Magalhães,36.0,DEF,Arsenal,West Ham,5.757126
2,Gabriel dos Santos Magalhães,27.0,DEF,Arsenal,Spurs,5.752827
3,Matheus Nunes,34.0,DEF,Man City,Burnley,5.595272
4,Abdukodir Khusanov,34.0,DEF,Man City,Burnley,5.487520
5,Matheus Nunes,28.0,DEF,Man City,Leeds,5.419331
6,Matheus Nunes,30.0,DEF,Man City,West Ham,5.401848
7,Abdukodir Khusanov,28.0,DEF,Man City,Leeds,5.381776
8,Abdukodir Khusanov,30.0,DEF,Man City,West Ham,5.358338
9,Gabriel dos Santos Magalhães,35.0,DEF,Arsenal,Fulham,5.273086

In [ ]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW27 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ibrahima Konaté,a,1,DEF,Liverpool,1048.5,57.21,87.5,0.049,0.046,0.931
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1077.7,56.53,85.7,0.201,0.172,1.323
2,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1052.5,56.52,84.6,0.059,0.112,0.866
3,Lamare Bogarde,a,0,DEF,Aston Villa,1040.4,56.02,71.9,0.035,0.058,0.830
4,Ethan Pinnock,a,0,DEF,Brentford,1045.7,55.66,65.8,0.271,0.053,1.307
5,Tyrone Mings,a,0,DEF,Aston Villa,1040.4,55.34,81.2,0.039,0.047,0.951
6,Dominik Szoboszlai,a,1,MID,Liverpool,1048.5,54.63,84.4,0.164,0.177,1.162
7,Vitaly Janelt,a,0,MID,Brentford,1045.7,53.82,86.2,0.143,0.168,1.215
8,Andrew Robertson,a,0,DEF,Liverpool,1048.5,53.67,69.6,0.044,0.058,0.936
9,Moisés Caicedo Corozo,a,0,MID,Chelsea,1086.3,53.45,85.9,0.141,0.188,1.310
10,Ian Maatsen,a,0,DEF,Aston Villa,1040.4,53.15,68.4,0.037,0.063,0.907
11,Matheus Nunes,a,1,DEF,Man City,1065.9,52.68,83.1,0.038,0.116,1.011
12,Lucas Digne,a,0,DEF,Aston Villa,1040.4,51.98,62.0,0.051,0.071,0.919
13,Pau Torres,a,0,DEF,Aston Villa,1040.4,51.62,71.9,0.039,0.042,0.998
14,Emiliano Martínez Romero,a,1,GK,Aston Villa,1040.4,51.21,87.2,NaN,NaN,1.014
15,Dango Ouattara,a,0,MID,Brentford,1045.7,51.13,73.1,0.203,0.133,1.244
16,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1081.0,50.92,82.4,0.158,0.127,1.397
17,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1060.4,50.90,72.5,0.198,0.148,1.314
18,Abdukodir Khusanov,a,1,DEF,Man City,1065.9,50.71,81.7,0.037,0.052,0.974
19,Amad Diallo,a,1,MID,Man Utd,1077.7,50.68,84.5,0.154,0.127,1.427
20,Mathias Jensen,a,0,MID,Brentford,1045.7,50.50,75.6,0.155,0.153,1.253
21,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1091.8,50.49,86.7,0.123,0.150,1.509
22,Marc Guiu Paz,a,0,FWD,Chelsea,1086.3,50.34,44.8,0.787,0.325,1.551
23,Alex Scott,a,0,MID,Bournemouth,1060.4,50.33,83.8,0.146,0.110,1.279
24,Habib Diarra,a,0,MID,Sunderland,1051.8,50.30,81.5,0.157,0.124,1.297
25,Michael Kayode,a,0,DEF,Brentford,1045.7,50.24,87.3,0.046,0.051,1.193
26,Leandro Trossard,d,1,MID,Arsenal,1052.5,50.03,76.8,0.189,0.159,0.991
27,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1040.4,50.02,77.1,0.143,0.127,1.110
28,Pascal Groß,a,0,MID,Brighton,1054.0,49.86,85.0,0.129,0.110,1.293
29,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1077.7,49.82,87.0,0.039,0.068,1.235
30,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1081.0,49.39,85.0,0.165,0.078,1.433
31,Alex Iwobi,a,0,MID,Fulham,1053.9,49.34,84.0,0.140,0.122,1.447
32,Ryan Gravenberch,a,0,MID,Liverpool,1048.5,49.04,86.5,0.072,0.154,1.191
33,Jayden Bogle,a,0,DEF,Leeds,1046.6,48.84,85.0,0.067,0.050,1.343
34,Piero Hincapié,a,0,DEF,Arsenal,1052.5,48.78,76.2,0.040,0.059,1.012
35,Matthijs de Ligt,d,0,DEF,Man Utd,1077.7,48.75,66.6,0.243,0.046,1.571
36,Sepp van den Berg,a,0,DEF,Brentford,1045.7,48.65,83.5,0.042,0.040,1.204
37,Emiliano Buendía Stati,a,0,MID,Aston Villa,1040.4,48.57,69.3,0.169,0.129,1.065
38,Enzo Le Fée,a,0,MID,Sunderland,1051.8,48.53,85.5,0.090,0.133,1.255
39,Reiss Nelson,a,0,MID,Brentford,1045.7,48.39,44.4,0.508,0.248,1.549
40,Rico Henry,a,0,DEF,Brentford,1045.7,48.36,81.9,0.037,0.051,1.196
41,Jaka Bijol,a,0,DEF,Leeds,1046.6,48.31,80.2,0.109,0.038,1.426
42,Kristoffer Ajer,a,0,DEF,Brentford,1045.7,48.24,78.0,0.039,0.056,1.184
43,Pascal Struijk,a,0,DEF,Leeds,1046.6,48.21,86.8,0.058,0.054,1.368
44,John Stones,a,0,DEF,Man City,1065.9,48.08,54.0,0.271,0.094,1.322
45,Amine Adli,a,0,MID,Bournemouth,1060.4,47.95,73.8,0.148,0.123,1.287
46,Alexis Mac Allister,a,0,MID,Liverpool,1048.5,47.85,71.1,0.152,0.123,1.148
47,Luke Shaw,a,0,DEF,Man Utd,1077.7,47.49,87.5,0.040,0.047,1.296
48,Lisandro Martínez,a,0,DEF,Man Utd,1077.7,47.45,83.7,0.041,0.048,1.291
49,Amadou Onana,a,0,MID,Aston Villa,1040.4,47.45,70.9,0.134,0.126,1.056

In [10]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW27 AND 31

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ibrahima Konaté,1,DEF,Liverpool,989.9,24.96,87.5,0.049,0.048,0.844
1,Ethan Pinnock,0,DEF,Brentford,985.6,24.01,66.0,0.271,0.062,1.223
2,Andrew Robertson,0,DEF,Liverpool,989.9,23.36,69.6,0.044,0.064,0.862
3,Lamare Bogarde,0,DEF,Aston Villa,1023.2,23.35,71.8,0.036,0.056,0.836
4,Bruno Borges Fernandes,1,MID,Man Utd,1086.6,23.35,85.7,0.200,0.172,1.384
5,Tyrone Mings,0,DEF,Aston Villa,1023.2,23.31,81.3,0.040,0.045,0.933
6,Dominik Szoboszlai,1,MID,Liverpool,989.9,23.30,84.4,0.162,0.193,0.963
7,Vitaly Janelt,0,MID,Brentford,985.6,23.16,86.2,0.148,0.185,1.120
8,Moisés Caicedo Corozo,0,MID,Chelsea,1088.5,22.42,85.9,0.148,0.182,1.303
9,Ian Maatsen,0,DEF,Aston Villa,1023.2,22.20,68.3,0.037,0.059,0.904
10,Michael Kayode,0,DEF,Brentford,985.6,22.13,87.2,0.046,0.052,1.083
11,Dango Ouattara,0,MID,Brentford,985.6,22.11,73.0,0.216,0.145,1.118
12,Pau Torres,0,DEF,Aston Villa,1023.2,21.82,71.9,0.040,0.040,0.975
13,Emiliano Martínez Romero,1,GK,Aston Villa,1023.2,21.81,87.2,NaN,NaN,0.948
14,Rayan Vitor Simplício Rocha,0,MID,Bournemouth,1017.6,21.72,72.4,0.203,0.161,1.171
15,Mathias Jensen,0,MID,Brentford,985.6,21.68,75.3,0.166,0.166,1.139
16,Lucas Digne,0,DEF,Aston Villa,1023.2,21.64,62.1,0.051,0.066,0.926
17,Rico Henry,0,DEF,Brentford,985.6,21.35,81.8,0.038,0.053,1.099
18,Alex Scott,0,MID,Bournemouth,1017.6,21.28,83.8,0.148,0.117,1.202
19,Sepp van den Berg,0,DEF,Brentford,985.6,21.18,83.5,0.041,0.044,1.121
20,Kristoffer Ajer,0,DEF,Brentford,985.6,21.16,78.1,0.040,0.060,1.102
21,Ryan Gravenberch,0,MID,Liverpool,989.9,21.07,86.5,0.073,0.171,0.998
22,Morgan Gibbs-White,1,MID,Nott'm Forest,1096.2,21.06,82.4,0.156,0.123,1.445
23,Amad Diallo,1,MID,Man Utd,1086.6,21.03,84.5,0.154,0.127,1.474
24,Douglas Luiz Soares de Paulo,0,MID,Aston Villa,1023.2,20.96,76.8,0.143,0.126,1.041
25,Alex Iwobi,0,MID,Fulham,980.9,20.95,84.0,0.138,0.133,1.250
26,Marc Guiu Paz,0,FWD,Chelsea,1088.5,20.94,44.8,0.791,0.322,1.541
27,Habib Diarra,0,MID,Sunderland,1048.5,20.92,81.7,0.156,0.121,1.274
28,Reiss Nelson,0,MID,Brentford,985.6,20.49,44.4,0.510,0.261,1.417
29,Matheus Nunes,1,DEF,Man City,1016.5,20.48,83.3,0.039,0.126,0.867
30,Alexis Mac Allister,0,MID,Liverpool,989.9,20.46,70.3,0.157,0.132,0.948
31,Diogo Dalot Teixeira,0,DEF,Man Utd,1086.6,20.46,87.0,0.039,0.068,1.264
32,Amine Adli,0,MID,Bournemouth,1017.6,20.41,73.6,0.151,0.132,1.177
33,Harrison Reed,0,MID,Fulham,980.9,20.41,36.7,0.519,0.332,1.158
34,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1137.1,20.41,86.7,0.120,0.131,1.717
35,Emiliano Buendía Stati,0,MID,Aston Villa,1023.2,20.41,69.3,0.170,0.131,1.024
36,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1059.8,20.37,84.9,0.057,0.110,0.885
37,Pascal Groß,0,MID,Brighton,1110.6,20.34,85.0,0.127,0.099,1.387
38,Ibrahim Sangaré,0,MID,Nott'm Forest,1096.2,20.34,85.1,0.162,0.072,1.482
39,Enzo Le Fée,0,MID,Sunderland,1048.5,20.21,85.5,0.091,0.132,1.247
40,Matthijs de Ligt,0,DEF,Man Utd,1086.6,20.16,66.7,0.244,0.046,1.581
41,Timothy Castagne,0,DEF,Fulham,980.9,20.03,78.6,0.036,0.043,1.173
42,Abdukodir Khusanov,1,DEF,Man City,1016.5,20.01,81.8,0.038,0.055,0.802
43,Antonee Robinson,0,DEF,Fulham,980.9,19.92,69.5,0.037,0.048,1.129
44,Amadou Onana,0,MID,Aston Villa,1023.2,19.84,70.6,0.134,0.126,1.019
45,Álex Jiménez Sánchez,0,DEF,Bournemouth,1017.6,19.78,86.5,0.050,0.051,1.330
46,Emile Smith Rowe,0,MID,Fulham,980.9,19.54,69.2,0.149,0.121,1.036
47,Kevin Schade,0,MID,Brentford,985.6,19.53,47.8,0.349,0.186,1.172
48,James Hill,0,DEF,Bournemouth,1017.6,19.49,79.2,0.043,0.060,1.307
49,Lisandro Martínez,0,DEF,Man Utd,1086.6,19.44,83.8,0.041,0.048,1.334

In [11]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 27 to 31

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,Chelsea,a,Marc Guiu Paz,20.941311,Igor Jesus Maciel da Cruz,13.955287,6.986025
1,DEF,Brentford,a,Ethan Pinnock,24.011936,James Tarkowski,18.394543,5.617393
2,MID,Brentford,a,Vitaly Janelt,23.156334,Leandro Trossard,18.093444,5.062890
3,DEF,Liverpool,a,Andrew Robertson,23.361555,James Tarkowski,18.394543,4.967013
4,DEF,Aston Villa,a,Lamare Bogarde,23.351043,James Tarkowski,18.394543,4.956500
5,DEF,Aston Villa,a,Tyrone Mings,23.307892,James Tarkowski,18.394543,4.913350
6,MID,Chelsea,a,Moisés Caicedo Corozo,22.423839,Leandro Trossard,18.093444,4.330395
7,MID,Brentford,a,Dango Ouattara,22.107673,Leandro Trossard,18.093444,4.014229
8,DEF,Aston Villa,a,Ian Maatsen,22.196877,James Tarkowski,18.394543,3.802334
9,DEF,Brentford,a,Michael Kayode,22.134682,James Tarkowski,18.394543,3.740139
10,MID,Bournemouth,a,Rayan Vitor Simplício Rocha,21.720093,Leandro Trossard,18.093444,3.626649
11,MID,Brentford,a,Mathias Jensen,21.678483,Leandro Trossard,18.093444,3.585039
12,DEF,Aston Villa,a,Pau Torres,21.821097,James Tarkowski,18.394543,3.426554
13,DEF,Aston Villa,a,Lucas Digne,21.639803,James Tarkowski,18.394543,3.245260
14,MID,Bournemouth,a,Alex Scott,21.275771,Leandro Trossard,18.093444,3.182327
15,MID,Liverpool,a,Ryan Gravenberch,21.072262,Leandro Trossard,18.093444,2.978818
16,DEF,Brentford,a,Rico Henry,21.349283,James Tarkowski,18.394543,2.954740
17,MID,Aston Villa,a,Douglas Luiz Soares de Paulo,20.964337,Leandro Trossard,18.093444,2.870893
18,MID,Fulham,a,Alex Iwobi,20.945515,Leandro Trossard,18.093444,2.852071
19,MID,Sunderland,a,Habib Diarra,20.919049,Leandro Trossard,18.093444,2.825605

In [12]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Leandro Trossard'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 27 and 31:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Leandro Trossard,27.0,MID,Arsenal,Spurs,6.8,981.604056,4.779146,76.071445,0.195297,0.169517,0.658842
1,Leandro Trossard,28.0,MID,Arsenal,Chelsea,6.8,1138.726728,4.294317,77.586352,0.172710,0.143705,1.351340
2,Leandro Trossard,29.0,MID,Arsenal,Brighton,6.8,1057.578227,4.531653,76.734029,0.190497,0.163070,0.977930
3,Leandro Trossard,30.0,MID,Arsenal,Everton,6.8,1061.380748,4.488327,76.774843,0.190497,0.163070,1.103926

In [18]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW27 to GW31
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ibrahima Konaté,a,1,DEF,Liverpool,989.9,5.01,87.5,0.049,0.048,0.844
1,Ethan Pinnock,a,0,DEF,Brentford,985.6,4.80,66.0,0.271,0.062,1.223
2,Tyrone Mings,a,0,DEF,Aston Villa,1023.2,4.72,81.3,0.040,0.045,0.933
3,Andrew Robertson,a,0,DEF,Liverpool,989.9,4.69,69.6,0.044,0.064,0.862
4,Lamare Bogarde,a,0,DEF,Aston Villa,1023.2,4.69,71.8,0.036,0.056,0.836
5,Bruno Borges Fernandes,a,1,MID,Man Utd,1086.6,4.68,85.7,0.200,0.172,1.384
6,Dominik Szoboszlai,a,1,MID,Liverpool,989.9,4.67,84.4,0.162,0.193,0.963
7,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1059.8,4.65,84.9,0.057,0.110,0.885
8,Vitaly Janelt,a,0,MID,Brentford,985.6,4.60,86.2,0.148,0.185,1.120
9,Moisés Caicedo Corozo,a,0,MID,Chelsea,1088.5,4.55,85.9,0.148,0.182,1.303
10,Matheus Nunes,a,1,DEF,Man City,1016.5,4.50,83.3,0.039,0.126,0.867
11,Ian Maatsen,a,0,DEF,Aston Villa,1023.2,4.45,68.3,0.037,0.059,0.904
12,Emiliano Martínez Romero,a,1,GK,Aston Villa,1023.2,4.42,87.2,NaN,NaN,0.948
13,Michael Kayode,a,0,DEF,Brentford,985.6,4.41,87.2,0.046,0.052,1.083
14,Pau Torres,a,0,DEF,Aston Villa,1023.2,4.41,71.9,0.040,0.040,0.975
15,Abdukodir Khusanov,a,1,DEF,Man City,1016.5,4.39,81.8,0.038,0.055,0.802
16,Dango Ouattara,a,0,MID,Brentford,985.6,4.39,73.0,0.216,0.145,1.118
17,Lucas Digne,a,0,DEF,Aston Villa,1023.2,4.36,62.1,0.051,0.066,0.926
18,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1017.6,4.34,72.4,0.203,0.161,1.171
19,Mathias Jensen,a,0,MID,Brentford,985.6,4.32,75.3,0.166,0.166,1.139
20,Alex Scott,a,0,MID,Bournemouth,1017.6,4.26,83.8,0.148,0.117,1.202
21,Rico Henry,a,0,DEF,Brentford,985.6,4.24,81.8,0.038,0.053,1.099
22,Ryan Gravenberch,a,0,MID,Liverpool,989.9,4.23,86.5,0.073,0.171,0.998
23,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1023.2,4.22,76.8,0.143,0.126,1.041
24,Sepp van den Berg,a,0,DEF,Brentford,985.6,4.21,83.5,0.041,0.044,1.121
25,Amad Diallo,a,1,MID,Man Utd,1086.6,4.21,84.5,0.154,0.127,1.474
26,Kristoffer Ajer,a,0,DEF,Brentford,985.6,4.21,78.1,0.040,0.060,1.102
27,Marc Guiu Paz,a,0,FWD,Chelsea,1088.5,4.20,44.8,0.791,0.322,1.541
28,Habib Diarra,a,0,MID,Sunderland,1048.5,4.20,81.7,0.156,0.121,1.274
29,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1096.2,4.17,82.4,0.156,0.123,1.445
30,Alex Iwobi,a,0,MID,Fulham,980.9,4.17,84.0,0.138,0.133,1.250
31,John Stones,a,0,DEF,Man City,1016.5,4.15,53.2,0.271,0.107,1.113
32,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1137.1,4.12,86.7,0.120,0.131,1.717
33,Emiliano Buendía Stati,a,0,MID,Aston Villa,1023.2,4.12,69.3,0.170,0.131,1.024
34,Alexis Mac Allister,a,0,MID,Liverpool,989.9,4.11,70.3,0.157,0.132,0.948
35,Amine Adli,a,0,MID,Bournemouth,1017.6,4.10,73.6,0.151,0.132,1.177
36,Leandro Trossard,d,1,MID,Arsenal,1059.8,4.08,76.8,0.187,0.160,1.023
37,Pascal Groß,a,0,MID,Brighton,1110.6,4.08,85.0,0.127,0.099,1.387
38,Reiss Nelson,a,0,MID,Brentford,985.6,4.08,44.4,0.510,0.261,1.417
39,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1086.6,4.08,87.0,0.039,0.068,1.264
40,Harrison Reed,a,0,MID,Fulham,980.9,4.06,36.7,0.519,0.332,1.158
41,Enzo Le Fée,a,0,MID,Sunderland,1048.5,4.05,85.5,0.091,0.132,1.247
42,Piero Hincapié,a,0,DEF,Arsenal,1059.8,4.04,76.2,0.040,0.058,1.021
43,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1096.2,4.03,85.1,0.162,0.072,1.482
44,Matthijs de Ligt,d,0,DEF,Man Utd,1086.6,4.02,66.7,0.244,0.046,1.581
45,Álex Jiménez Sánchez,a,0,DEF,Bournemouth,1017.6,4.01,86.5,0.050,0.051,1.330
46,Rayan Aït-Nouri,a,0,DEF,Man City,1016.5,4.00,70.8,0.038,0.075,0.951
47,Amadou Onana,a,0,MID,Aston Villa,1023.2,3.99,70.6,0.134,0.126,1.019
48,James Hill,a,0,DEF,Bournemouth,1017.6,3.94,79.2,0.043,0.060,1.307
49,Timothy Castagne,a,0,DEF,Fulham,980.9,3.93,78.6,0.036,0.043,1.173

In [14]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [15]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [16]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.05 minute(s)