In [21]:
import pandas as pd
import time
from datetime import datetime
import os

In [22]:
start=time.perf_counter()

In [23]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [24]:
#add this info to a settings dict?
current_gw = 34
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [25]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        -- AND latest_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 35
Squad Points: 67.64

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Matheus N.,a,100.0,35.0,DEF,Man City,Everton,5.146735,86.0
1,Gibbs-White,a,100.0,35.0,MID,Nott'm Forest,Chelsea,4.891479,84.0
2,B.Fernandes,a,100.0,35.0,MID,Man Utd,Liverpool,4.861333,84.0
3,Gabriel,a,100.0,35.0,DEF,Arsenal,Fulham,4.754641,87.0
4,Szoboszlai,a,100.0,35.0,MID,Liverpool,Man Utd,4.226323,86.0
5,Brobbey,a,100.0,35.0,FWD,Sunderland,Wolves,4.134814,79.0
6,Martinez,a,100.0,35.0,GK,Aston Villa,Spurs,4.084512,90.0
7,Diouf,a,100.0,35.0,DEF,West Ham,Brentford,4.074388,87.0
8,Raya,a,NaN,35.0,GK,Arsenal,Fulham,3.977589,89.0
9,F.Kadıoğlu,a,NaN,35.0,DEF,Brighton,Newcastle,3.896597,86.0
10,Van Hecke,a,100.0,35.0,DEF,Brighton,Newcastle,3.895737,87.0
11,Mac Allister,a,100.0,35.0,MID,Liverpool,Man Utd,3.775700,60.0
12,Flemming,a,100.0,35.0,FWD,Burnley,Leeds,3.754979,71.0
13,Bruno G.,a,100.0,35.0,MID,Newcastle,Brighton,3.669349,61.0
14,Isak,a,100.0,35.0,FWD,Liverpool,Man Utd,3.353275,67.0

In [26]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW35 AND 39

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1097.8,13.65,67.5,0.313,1.000,0.069,1.597,1.405
1,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1051.7,14.90,61.2,0.205,1.000,0.125,1.000,1.204
2,Emiliano Martínez Romero,1,GK,Aston Villa,1063.9,15.13,89.8,NaN,1.000,NaN,1.000,1.324
3,Alexis Mac Allister,1,MID,Liverpool,1097.8,15.21,59.6,0.255,1.456,0.129,1.000,1.325
4,Zian Flemming,1,FWD,Burnley,1072.8,15.23,71.1,0.411,1.000,0.035,1.000,1.588
5,Brian Brobbey,1,FWD,Sunderland,1044.6,16.10,78.9,0.383,1.000,0.062,1.000,1.244
6,Ferdi Kadıoğlu,1,DEF,Brighton,1024.6,16.33,86.2,0.045,1.000,0.040,1.000,1.241
7,Jan Paul van Hecke,1,DEF,Brighton,1024.6,16.37,86.6,0.043,1.000,0.038,1.000,1.197
8,El Hadji Malick Diouf,1,DEF,West Ham,1090.9,16.41,86.7,0.036,1.000,0.187,2.053,1.427
9,Dominik Szoboszlai,1,MID,Liverpool,1097.8,17.00,85.6,0.136,1.000,0.155,1.000,1.348
10,David Raya Martín,1,GK,Arsenal,996.8,17.46,88.9,NaN,1.000,NaN,1.000,0.829
11,Morgan Gibbs-White,1,MID,Nott'm Forest,1086.5,19.54,84.4,0.219,1.000,0.286,2.027,1.378
12,Bruno Borges Fernandes,1,MID,Man Utd,1086.2,19.77,84.3,0.221,1.000,0.235,1.339,1.297
13,Gabriel dos Santos Magalhães,1,DEF,Arsenal,996.8,21.04,86.8,0.065,1.000,0.075,1.000,0.784
14,Matheus Nunes,1,DEF,Man City,1081.6,25.46,107.0,0.043,1.000,0.246,2.810,1.044

In [27]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    --AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW35 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1081.6,40.20,103.9,4.687,0.582,4.522,0.734,1.003
1,John Stones,a,0,DEF,Man City,1081.6,35.84,74.2,3.577,0.954,1.000,0.043,1.286
2,Matheus Nunes,a,1,DEF,Man City,1081.6,25.46,107.0,1.000,0.043,2.810,0.246,1.044
3,Abdukodir Khusanov,a,0,DEF,Man City,1081.6,22.75,102.5,1.000,0.042,1.000,0.031,0.974
4,James Ward-Prowse,a,0,MID,Burnley,1072.8,21.90,78.1,2.527,0.455,1.774,0.236,2.062
5,Max Alleyne,a,0,DEF,Man City,1081.6,21.86,77.8,1.000,0.238,1.000,0.035,1.327
6,Mathias Jensen,a,0,MID,Brentford,1119.7,21.54,84.8,2.067,0.362,1.000,0.184,1.434
7,Jérémy Doku,a,0,MID,Man City,1081.6,21.13,95.5,1.000,0.133,1.000,0.161,0.989
8,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,996.8,21.04,86.8,1.000,0.065,1.000,0.075,0.784
9,Rico Lewis,a,0,DEF,Man City,1081.6,20.86,70.4,1.000,0.248,1.000,0.096,1.365
10,Rayan Aït-Nouri,a,0,DEF,Man City,1081.6,20.58,72.4,1.000,0.041,1.000,0.077,0.991
11,Benjamin White,a,0,DEF,Arsenal,996.8,19.81,80.9,1.000,0.043,1.000,0.070,0.805
12,Bruno Borges Fernandes,a,1,MID,Man Utd,1086.2,19.77,84.3,1.000,0.221,1.339,0.235,1.297
13,Youri Tielemans,a,0,MID,Aston Villa,1063.9,19.67,73.2,2.718,0.271,2.299,0.345,1.466
14,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1086.5,19.54,84.4,1.000,0.219,2.027,0.286,1.378
15,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1081.6,18.61,99.9,1.000,0.059,1.000,0.084,1.022
16,Reece James,d,0,DEF,Chelsea,1051.4,18.46,61.6,4.135,0.177,2.957,0.529,1.580
17,Eberechi Eze,d,0,MID,Arsenal,996.8,18.32,59.2,1.377,0.320,1.973,0.290,0.784
18,Marcus Tavernier,a,0,MID,Bournemouth,1097.3,18.27,84.4,1.000,0.210,1.486,0.165,1.323
19,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1135.9,18.10,99.9,1.000,0.081,1.000,0.100,1.492
20,Walter Benítez,a,0,GK,Crystal Palace,1135.9,17.90,109.2,1.000,NaN,1.000,NaN,1.695
21,Mats Wieffer,a,0,MID,Brighton,1024.6,17.83,76.6,1.000,0.110,2.463,0.332,1.129
22,Dwight McNeil,a,0,MID,Everton,1072.4,17.79,66.5,1.775,0.294,1.565,0.224,1.269
23,Granit Xhaka,a,0,MID,Sunderland,1044.6,17.76,84.4,2.288,0.177,2.942,0.193,1.628
24,Leandro Trossard,a,0,MID,Arsenal,996.8,17.75,44.8,1.982,0.497,2.533,0.393,0.819
25,John McGinn,a,0,MID,Aston Villa,1063.9,17.73,79.5,1.000,0.144,2.026,0.272,1.376
26,Pascal Groß,a,0,MID,Brighton,1024.6,17.62,85.5,1.000,0.126,1.000,0.191,1.131
27,James Trafford,a,0,GK,Man City,1081.6,17.54,110.0,1.000,NaN,1.000,NaN,1.486
28,Brennan Johnson,a,0,MID,Crystal Palace,1135.9,17.51,71.2,1.000,0.159,2.474,0.255,1.439
29,Martin Ødegaard,a,0,MID,Arsenal,996.8,17.51,73.4,1.000,0.161,1.000,0.196,0.826
30,David Raya Martín,a,1,GK,Arsenal,996.8,17.46,88.9,1.000,NaN,1.000,NaN,0.829
31,Jack Hinshelwood,a,0,MID,Brighton,1024.6,17.43,76.7,1.000,0.201,1.836,0.152,1.130
32,Kevin Schade,a,0,MID,Brentford,1119.7,17.42,77.1,1.000,0.226,2.064,0.158,1.398
33,Chris Richards,a,0,DEF,Crystal Palace,1135.9,17.29,108.2,1.000,0.042,1.000,0.029,1.536
34,Ryan Sessegnon,d,0,MID,Fulham,1075.3,17.23,65.4,2.189,0.300,2.315,0.175,1.341
35,Brenden Aaronson,a,0,MID,Leeds,987.5,17.12,77.1,1.000,0.115,2.383,0.255,1.076
36,James Justin,a,0,DEF,Leeds,987.5,17.01,86.5,1.000,0.041,1.000,0.047,1.139
37,Dominik Szoboszlai,a,1,MID,Liverpool,1097.8,17.00,85.6,1.000,0.136,1.000,0.155,1.348
38,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,1051.4,16.90,62.3,1.000,0.339,1.000,0.033,1.646
39,Martín Zubimendi Ibáñez,a,0,MID,Arsenal,996.8,16.84,77.7,1.000,0.151,1.000,0.084,0.762
40,Jaydee Canvot,a,0,DEF,Crystal Palace,1135.9,16.84,105.7,1.000,0.037,1.000,0.035,1.571
41,Emile Smith Rowe,a,0,MID,Fulham,1075.3,16.81,63.2,1.781,0.268,3.430,0.240,1.342
42,Gabriel Gudmundsson,d,0,DEF,Leeds,987.5,16.80,80.4,1.000,0.036,1.000,0.051,1.087
43,Tomáš Souček,a,0,MID,West Ham,1090.9,16.78,85.6,1.000,0.186,1.000,0.065,1.433
44,Jaka Bijol,a,0,DEF,Leeds,987.5,16.71,76.6,1.000,0.040,1.000,0.048,1.089
45,Harvey Barnes,a,0,MID,Newcastle,1051.7,16.63,49.8,1.988,0.434,2.451,0.299,1.307
46,Lucas Digne,a,0,DEF,Aston Villa,1063.9,16.58,73.9,1.000,0.064,2.216,0.227,1.496
47,Amadou Onana,d,0,MID,Aston Villa,1063.9,16.48,81.0,1.000,0.178,1.000,0.072,1.449
48,Enzo Fernández,a,0,MID,Chelsea,1051.4,16.45,80.6,1.000,0.153,1.000,0.115,1.288
49,Adam Wharton,a,0,MID,Crystal Palace,1135.9,16.42,81.8,1.000,0.086,1.000,0.100,1.494

In [28]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW35 AND 39

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1081.6,40.20,103.9,0.582,4.687,0.734,4.522,1.003
1,John Stones,a,0,DEF,Man City,1081.6,35.84,74.2,0.954,3.577,0.043,1.000,1.286
2,Matheus Nunes,a,1,DEF,Man City,1081.6,25.46,107.0,0.043,1.000,0.246,2.810,1.044
3,Abdukodir Khusanov,a,0,DEF,Man City,1081.6,22.75,102.5,0.042,1.000,0.031,1.000,0.974
4,James Ward-Prowse,a,0,MID,Burnley,1072.8,21.90,78.1,0.455,2.527,0.236,1.774,2.062
5,Max Alleyne,a,0,DEF,Man City,1081.6,21.86,77.8,0.238,1.000,0.035,1.000,1.327
6,Mathias Jensen,a,0,MID,Brentford,1119.7,21.54,84.8,0.362,2.067,0.184,1.000,1.434
7,Jérémy Doku,a,0,MID,Man City,1081.6,21.13,95.5,0.133,1.000,0.161,1.000,0.989
8,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,996.8,21.04,86.8,0.065,1.000,0.075,1.000,0.784
9,Rico Lewis,a,0,DEF,Man City,1081.6,20.86,70.4,0.248,1.000,0.096,1.000,1.365
10,Rayan Aït-Nouri,a,0,DEF,Man City,1081.6,20.58,72.4,0.041,1.000,0.077,1.000,0.991
11,Benjamin White,a,0,DEF,Arsenal,996.8,19.81,80.9,0.043,1.000,0.070,1.000,0.805
12,Bruno Borges Fernandes,a,1,MID,Man Utd,1086.2,19.77,84.3,0.221,1.000,0.235,1.339,1.297
13,Youri Tielemans,a,0,MID,Aston Villa,1063.9,19.67,73.2,0.271,2.718,0.345,2.299,1.466
14,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1086.5,19.54,84.4,0.219,1.000,0.286,2.027,1.378
15,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1081.6,18.61,99.9,0.059,1.000,0.084,1.000,1.022
16,Reece James,d,0,DEF,Chelsea,1051.4,18.46,61.6,0.177,4.135,0.529,2.957,1.580
17,Eberechi Eze,d,0,MID,Arsenal,996.8,18.32,59.2,0.320,1.377,0.290,1.973,0.784
18,Marcus Tavernier,a,0,MID,Bournemouth,1097.3,18.27,84.4,0.210,1.000,0.165,1.486,1.323
19,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1135.9,18.10,99.9,0.081,1.000,0.100,1.000,1.492
20,Walter Benítez,a,0,GK,Crystal Palace,1135.9,17.90,109.2,NaN,1.000,NaN,1.000,1.695
21,Mats Wieffer,a,0,MID,Brighton,1024.6,17.83,76.6,0.110,1.000,0.332,2.463,1.129
22,Dwight McNeil,a,0,MID,Everton,1072.4,17.79,66.5,0.294,1.775,0.224,1.565,1.269
23,Granit Xhaka,a,0,MID,Sunderland,1044.6,17.76,84.4,0.177,2.288,0.193,2.942,1.628
24,Leandro Trossard,a,0,MID,Arsenal,996.8,17.75,44.8,0.497,1.982,0.393,2.533,0.819
25,John McGinn,a,0,MID,Aston Villa,1063.9,17.73,79.5,0.144,1.000,0.272,2.026,1.376
26,Pascal Groß,a,0,MID,Brighton,1024.6,17.62,85.5,0.126,1.000,0.191,1.000,1.131
27,James Trafford,a,0,GK,Man City,1081.6,17.54,110.0,NaN,1.000,NaN,1.000,1.486
28,Brennan Johnson,a,0,MID,Crystal Palace,1135.9,17.51,71.2,0.159,1.000,0.255,2.474,1.439
29,Martin Ødegaard,a,0,MID,Arsenal,996.8,17.51,73.4,0.161,1.000,0.196,1.000,0.826
30,David Raya Martín,a,1,GK,Arsenal,996.8,17.46,88.9,NaN,1.000,NaN,1.000,0.829
31,Jack Hinshelwood,a,0,MID,Brighton,1024.6,17.43,76.7,0.201,1.000,0.152,1.836,1.130
32,Kevin Schade,a,0,MID,Brentford,1119.7,17.42,77.1,0.226,1.000,0.158,2.064,1.398
33,Chris Richards,a,0,DEF,Crystal Palace,1135.9,17.29,108.2,0.042,1.000,0.029,1.000,1.536
34,Ryan Sessegnon,d,0,MID,Fulham,1075.3,17.23,65.4,0.300,2.189,0.175,2.315,1.341
35,Brenden Aaronson,a,0,MID,Leeds,987.5,17.12,77.1,0.115,1.000,0.255,2.383,1.076
36,James Justin,a,0,DEF,Leeds,987.5,17.01,86.5,0.041,1.000,0.047,1.000,1.139
37,Dominik Szoboszlai,a,1,MID,Liverpool,1097.8,17.00,85.6,0.136,1.000,0.155,1.000,1.348
38,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,1051.4,16.90,62.3,0.339,1.000,0.033,1.000,1.646
39,Martín Zubimendi Ibáñez,a,0,MID,Arsenal,996.8,16.84,77.7,0.151,1.000,0.084,1.000,0.762
40,Jaydee Canvot,a,0,DEF,Crystal Palace,1135.9,16.84,105.7,0.037,1.000,0.035,1.000,1.571
41,Emile Smith Rowe,a,0,MID,Fulham,1075.3,16.81,63.2,0.268,1.781,0.240,3.430,1.342
42,Gabriel Gudmundsson,d,0,DEF,Leeds,987.5,16.80,80.4,0.036,1.000,0.051,1.000,1.087
43,Tomáš Souček,a,0,MID,West Ham,1090.9,16.78,85.6,0.186,1.000,0.065,1.000,1.433
44,Jaka Bijol,a,0,DEF,Leeds,987.5,16.71,76.6,0.040,1.000,0.048,1.000,1.089
45,Harvey Barnes,a,0,MID,Newcastle,1051.7,16.63,49.8,0.434,1.988,0.299,2.451,1.307
46,Lucas Digne,a,0,DEF,Aston Villa,1063.9,16.58,73.9,0.064,1.000,0.227,2.216,1.496
47,Amadou Onana,d,0,MID,Aston Villa,1063.9,16.48,81.0,0.178,1.000,0.072,1.000,1.449
48,Enzo Fernández,a,0,MID,Chelsea,1051.4,16.45,80.6,0.153,1.000,0.115,1.000,1.288
49,Adam Wharton,a,0,MID,Crystal Palace,1135.9,16.42,81.8,0.086,1.000,0.100,1.000,1.494

In [29]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 35 to 39

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Man City,a,Bernardo Mota Veiga de Carvalho e Silva,40.196846,Bruno Guimarães Rodriguez Moura,14.895923,25.300923
1,DEF,Man City,a,John Stones,35.844522,Ferdi Kadıoğlu,16.333675,19.510847
2,MID,Burnley,a,James Ward-Prowse,21.896873,Bruno Guimarães Rodriguez Moura,14.895923,7.000951
3,MID,Brentford,a,Mathias Jensen,21.535886,Bruno Guimarães Rodriguez Moura,14.895923,6.639963
4,DEF,Man City,a,Abdukodir Khusanov,22.749777,Ferdi Kadıoğlu,16.333675,6.416102
5,MID,Man City,a,Jérémy Doku,21.134434,Bruno Guimarães Rodriguez Moura,14.895923,6.238511
6,DEF,Man City,a,Max Alleyne,21.858516,Ferdi Kadıoğlu,16.333675,5.524841
7,MID,Aston Villa,a,Youri Tielemans,19.667022,Bruno Guimarães Rodriguez Moura,14.895923,4.771099
8,DEF,Man City,a,Rico Lewis,20.860255,Ferdi Kadıoğlu,16.333675,4.526580
9,DEF,Man City,a,Rayan Aït-Nouri,20.575257,Ferdi Kadıoğlu,16.333675,4.241582
10,MID,Man City,d,Rodrigo 'Rodri' Hernandez Cascante,18.606200,Bruno Guimarães Rodriguez Moura,14.895923,3.710277
11,DEF,Arsenal,a,Benjamin White,19.812546,Ferdi Kadıoğlu,16.333675,3.478871
12,MID,Arsenal,d,Eberechi Eze,18.324170,Bruno Guimarães Rodriguez Moura,14.895923,3.428247
13,MID,Bournemouth,a,Marcus Tavernier,18.272859,Bruno Guimarães Rodriguez Moura,14.895923,3.376936
14,MID,Crystal Palace,a,Jefferson Lerma Solís,18.096856,Bruno Guimarães Rodriguez Moura,14.895923,3.200933
15,MID,Brighton,a,Mats Wieffer,17.825557,Bruno Guimarães Rodriguez Moura,14.895923,2.929635
16,MID,Everton,a,Dwight McNeil,17.793548,Bruno Guimarães Rodriguez Moura,14.895923,2.897626
17,MID,Sunderland,a,Granit Xhaka,17.759454,Bruno Guimarães Rodriguez Moura,14.895923,2.863532
18,MID,Arsenal,a,Leandro Trossard,17.751650,Bruno Guimarães Rodriguez Moura,14.895923,2.855727
19,MID,Aston Villa,a,John McGinn,17.727158,Bruno Guimarães Rodriguez Moura,14.895923,2.831235

In [30]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 35 and 39:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,35.0,FWD,Man City,Everton,14.5,1055.499286,5.219351,83.688193,0.585317,0.151990,1.043573
1,Erling Haaland,36.0,FWD,Man City,Crystal Palace; Brentford,14.5,1056.769334,10.469812,167.376385,0.589499,0.151990,1.045704
2,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.5,1090.250199,5.306407,83.688193,0.609126,0.152034,1.069050
3,Erling Haaland,38.0,FWD,Man City,Aston Villa,14.5,1124.080741,5.234634,83.797738,0.588681,0.152034,1.066072

In [31]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'DEF'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW35 to GW39
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,962.2,9.23,103.9,0.582,4.687,0.734,4.522,1.003
1,John Stones,a,0,DEF,Man City,962.2,8.21,74.2,0.954,3.577,0.043,1.000,1.286
2,Matheus Nunes,a,1,DEF,Man City,962.2,5.83,107.0,0.043,1.000,0.246,2.810,1.044
3,Abdukodir Khusanov,a,0,DEF,Man City,962.2,5.21,102.5,0.042,1.000,0.031,1.000,0.974
4,Max Alleyne,a,0,DEF,Man City,962.2,5.04,77.8,0.238,1.000,0.035,1.000,1.327
5,James Ward-Prowse,a,0,MID,Burnley,962.5,4.90,78.1,0.455,2.527,0.236,1.774,2.062
6,Jérémy Doku,a,0,MID,Man City,962.2,4.85,95.5,0.133,1.000,0.161,1.000,0.989
7,Mathias Jensen,a,0,MID,Brentford,993.1,4.84,84.8,0.362,2.067,0.184,1.000,1.434
8,Rico Lewis,a,0,DEF,Man City,962.2,4.79,70.4,0.248,1.000,0.096,1.000,1.365
9,Rayan Aït-Nouri,a,0,DEF,Man City,962.2,4.76,72.4,0.041,1.000,0.077,1.000,0.991
10,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,900.2,4.68,86.8,0.065,1.000,0.075,1.000,0.784
11,Youri Tielemans,a,0,MID,Aston Villa,919.1,4.51,73.2,0.271,2.718,0.345,2.299,1.466
12,Bruno Borges Fernandes,a,1,MID,Man Utd,981.8,4.43,84.3,0.221,1.000,0.235,1.339,1.297
13,Benjamin White,a,0,DEF,Arsenal,900.2,4.41,80.9,0.043,1.000,0.070,1.000,0.805
14,Morgan Gibbs-White,a,1,MID,Nott'm Forest,971.5,4.38,84.4,0.219,1.000,0.286,2.027,1.378
15,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,962.2,4.25,99.9,0.059,1.000,0.084,1.000,1.022
16,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1007.7,4.14,99.9,0.081,1.000,0.100,1.000,1.492
17,Reece James,d,0,DEF,Chelsea,948.9,4.11,61.6,0.177,4.135,0.529,2.957,1.580
18,Walter Benítez,a,0,GK,Crystal Palace,1007.7,4.10,109.2,NaN,1.000,NaN,1.000,1.695
19,Marcus Tavernier,a,0,MID,Bournemouth,976.8,4.10,84.4,0.210,1.000,0.165,1.486,1.323
20,Eberechi Eze,d,0,MID,Arsenal,900.2,4.09,59.2,0.320,1.377,0.290,1.973,0.784
21,John McGinn,a,0,MID,Aston Villa,919.1,4.05,79.5,0.144,1.000,0.272,2.026,1.376
22,James Trafford,a,0,GK,Man City,962.2,4.02,110.0,NaN,1.000,NaN,1.000,1.486
23,Granit Xhaka,a,0,MID,Sunderland,920.9,4.02,84.4,0.177,2.288,0.193,2.942,1.628
24,Mats Wieffer,a,0,MID,Brighton,911.6,4.01,76.6,0.110,1.000,0.332,2.463,1.129
25,Brennan Johnson,a,0,MID,Crystal Palace,1007.7,4.01,71.2,0.159,1.000,0.255,2.474,1.439
26,Chris Richards,a,0,DEF,Crystal Palace,1007.7,3.98,108.2,0.042,1.000,0.029,1.000,1.536
27,Dwight McNeil,a,0,MID,Everton,989.7,3.97,66.5,0.294,1.775,0.224,1.565,1.269
28,Pascal Groß,a,0,MID,Brighton,911.6,3.96,85.5,0.126,1.000,0.191,1.000,1.131
29,Leandro Trossard,a,0,MID,Arsenal,900.2,3.95,44.8,0.497,1.982,0.393,2.533,0.819
30,Kevin Schade,a,0,MID,Brentford,993.1,3.92,77.1,0.226,1.000,0.158,2.064,1.398
31,Jack Hinshelwood,a,0,MID,Brighton,911.6,3.91,76.7,0.201,1.000,0.152,1.836,1.130
32,Lucas Digne,a,0,DEF,Aston Villa,919.1,3.91,73.9,0.064,1.000,0.227,2.216,1.496
33,Martin Ødegaard,a,0,MID,Arsenal,900.2,3.91,73.4,0.161,1.000,0.196,1.000,0.826
34,Brenden Aaronson,a,0,MID,Leeds,866.1,3.89,77.1,0.115,1.000,0.255,2.383,1.076
35,David Raya Martín,a,1,GK,Arsenal,900.2,3.88,88.9,NaN,1.000,NaN,1.000,0.829
36,James Justin,a,0,DEF,Leeds,866.1,3.88,86.5,0.041,1.000,0.047,1.000,1.139
37,Jaydee Canvot,a,0,DEF,Crystal Palace,1007.7,3.87,105.7,0.037,1.000,0.035,1.000,1.571
38,Gabriel Gudmundsson,d,0,DEF,Leeds,866.1,3.85,80.4,0.036,1.000,0.051,1.000,1.087
39,Tyrone Mings,a,0,DEF,Aston Villa,919.1,3.84,79.7,0.080,1.000,0.047,1.000,1.340
40,Ryan Sessegnon,d,0,MID,Fulham,989.2,3.82,65.4,0.300,2.189,0.175,2.315,1.341
41,Jaka Bijol,a,0,DEF,Leeds,866.1,3.81,76.6,0.040,1.000,0.048,1.000,1.089
42,Dominik Szoboszlai,a,1,MID,Liverpool,987.6,3.81,85.6,0.136,1.000,0.155,1.000,1.348
43,Nathan Aké,a,0,DEF,Man City,962.2,3.78,37.1,0.047,1.000,0.042,1.000,1.162
44,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,948.9,3.77,62.3,0.339,1.000,0.033,1.000,1.646
45,Martín Zubimendi Ibáñez,a,0,MID,Arsenal,900.2,3.77,77.7,0.151,1.000,0.084,1.000,0.762
46,Adam Wharton,a,0,MID,Crystal Palace,1007.7,3.75,81.8,0.086,1.000,0.100,1.000,1.494
47,Tomáš Souček,a,0,MID,West Ham,986.8,3.74,85.6,0.186,1.000,0.065,1.000,1.433
48,Amadou Onana,d,0,MID,Aston Villa,919.1,3.74,81.0,0.178,1.000,0.072,1.000,1.449
49,Emile Smith Rowe,a,0,MID,Fulham,989.2,3.73,63.2,0.268,1.781,0.240,3.430,1.342

# Multi-week optimizer

In [32]:
from FPL_Optimizer import FPLOptimizer

In [33]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [34]:
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(picks_current_gameweek + 1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 49.22
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.98
 ✅        Martinez                       Aston Villa  £5.1     4.08

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     4.75
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.90
 ✅        Van Hecke                      Brighton     £4.6     3.90
 ✅        Matheus N.                     Man City     £5.3     5.15
 ✅        Diouf                          West Ham     £4.1     4.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.67
 ✅        Mac Allister                   Liverpool    £6.2     3.78
 ✅        Szoboszlai                     Liverpool    £7.1     4.23
 ✅        B.Fernandes                    Man Utd      £10.4    4.86
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.89

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Flemming                       Burnley      £5.3     3.75
 🪑        Isak                           Liverpool    £10.3    3.35
 ✅        Brobbey                        Sunderland   £5.3     4.13

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 56.23
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.16
 ✅        Raya                           Arsenal      £6.0     4.57

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Diouf                          West Ham     £4.1     3.41
 ✅        Gabriel                        Arsenal      £7.2     5.50
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.38
 ✅        Van Hecke                      Brighton     £4.6     4.33
 ✅        Matheus N.                     Man City     £5.3    10.25

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.75
 ✅        Mac Allister                   Liverpool    £6.2     3.82
 ✅        Szoboszlai                     Liverpool    £7.1     4.28
 ✅        B.Fernandes                    Man Utd      £10.4    5.03
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.91

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.42
 ✅        Flemming                       Burnley      £5.3     3.77
 ✅        Brobbey                        Sunderland   £5.3     3.92

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-3-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 52.08
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.75
 ✅        Raya                           Arsenal      £6.0     4.77

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     6.01
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.29
 ✅        Van Hecke                      Brighton     £4.6     4.29
 ✅        Matheus N.                     Man City     £5.3     5.07
 ✅        Diouf                          West Ham     £4.1     4.20

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mac Allister                   Liverpool    £6.2     3.79
 🪑        Bruno G.                       Newcastle    £6.8     3.77
 ✅        Szoboszlai                     Liverpool    £7.1     4.21
 ✅        B.Fernandes                    Man Utd      £10.4    5.02
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.87

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.39
 ✅        Flemming                       Burnley      £5.3     3.82
 ✅        Brobbey                        Sunderland   £5.3     4.07

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 49.61
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.14
 ✅        Raya                           Arsenal      £6.0     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        F.Kadıoğlu                     Brighton     £4.4     3.76
 ✅        Gabriel                        Arsenal      £7.2     4.78
 ✅        Van Hecke                      Brighton     £4.6     3.86
 ✅        Matheus N.                     Man City     £5.3     5.00
 ✅        Diouf                          West Ham     £4.1     4.72

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.70
 ✅        Mac Allister                   Liverpool    £6.2     3.83
 ✅        Szoboszlai                     Liverpool    £7.1     4.29
 ✅        B.Fernandes                    Man Utd      £10.4    4.86
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.87

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.49
 ✅        Flemming                       Burnley      £5.3     3.88
 ✅        Brobbey                        Sunderland   £5.3     3.97

================================================================================
Optimization Status: Optimal

Optimization complete. Final DataFrame created.

event      web_name position  35  36  37  38
3             Diouf      DEF   1   0   1   1
4        F.Kadıoğlu      DEF   1   1   1   0
6           Gabriel      DEF   1   1   1   1
11       Matheus N.      DEF   1   1   1   1
14        Van Hecke      DEF   1   1   1   1
1           Brobbey      FWD   1   1   1   1
5          Flemming      FWD   0   1   1   1
8              Isak      FWD   0   0   0   0
10         Martinez       GK   1   0   0   0
12             Raya       GK   0   1   1   1
0       B.Fernandes      MID   1   1   1   1
2          Bruno G.      MID   0   0   0   0
7       Gibbs-White      MID   1   1   1   1
9      Mac Allister      MID   1   1   0   1
13       Szoboszlai      MID   1   1   1   1

In [35]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [36]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [37]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [38]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW35 to GW38...

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 49.22
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.98
 ✅        Martinez                       Aston Villa  £5.1     4.08

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     4.75
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.90
 ✅        Van Hecke                      Brighton     £4.6     3.90
 ✅        Matheus N.                     Man City     £5.3     5.15
 ✅        Diouf                          West Ham     £4.1     4.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.67
 ✅        Mac Allister                   Liverpool    £6.2     3.78
 ✅        Szoboszlai                     Liverpool    £7.1     4.23
 ✅        B.Fernandes                    Man Utd      £10.4    4.86
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.89

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Flemming                       Burnley      £5.3     3.75
 🪑        Isak                           Liverpool    £10.3    3.35
 ✅        Brobbey                        Sunderland   £5.3     4.13

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 56.23
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.16
 ✅        Raya                           Arsenal      £6.0     4.57

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Diouf                          West Ham     £4.1     3.41
 ✅        Gabriel                        Arsenal      £7.2     5.50
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.38
 ✅        Van Hecke                      Brighton     £4.6     4.33
 ✅        Matheus N.                     Man City     £5.3    10.25

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.75
 ✅        Mac Allister                   Liverpool    £6.2     3.82
 ✅        Szoboszlai                     Liverpool    £7.1     4.28
 ✅        B.Fernandes                    Man Utd      £10.4    5.03
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.91

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.42
 ✅        Flemming                       Burnley      £5.3     3.77
 ✅        Brobbey                        Sunderland   £5.3     3.92

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-3-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 52.08
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.75
 ✅        Raya                           Arsenal      £6.0     4.77

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     6.01
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.29
 ✅        Van Hecke                      Brighton     £4.6     4.29
 ✅        Matheus N.                     Man City     £5.3     5.07
 ✅        Diouf                          West Ham     £4.1     4.20

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mac Allister                   Liverpool    £6.2     3.79
 🪑        Bruno G.                       Newcastle    £6.8     3.77
 ✅        Szoboszlai                     Liverpool    £7.1     4.21
 ✅        B.Fernandes                    Man Utd      £10.4    5.02
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.87

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.39
 ✅        Flemming                       Burnley      £5.3     3.82
 ✅        Brobbey                        Sunderland   £5.3     4.07

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 49.61
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.14
 ✅        Raya                           Arsenal      £6.0     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        F.Kadıoğlu                     Brighton     £4.4     3.76
 ✅        Gabriel                        Arsenal      £7.2     4.78
 ✅        Van Hecke                      Brighton     £4.6     3.86
 ✅        Matheus N.                     Man City     £5.3     5.00
 ✅        Diouf                          West Ham     £4.1     4.72

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.70
 ✅        Mac Allister                   Liverpool    £6.2     3.83
 ✅        Szoboszlai                     Liverpool    £7.1     4.29
 ✅        B.Fernandes                    Man Utd      £10.4    4.86
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.87

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.49
 ✅        Flemming                       Burnley      £5.3     3.88
 ✅        Brobbey                        Sunderland   £5.3     3.97

================================================================================
Optimization Status: Optimal

In [39]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
0     35         13.279673
1     36         13.271493
2     37         13.230727
3     38         12.678984

In [40]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.03 minute(s)