In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

# Load TRDL Data

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 7
current_season = 20262027

In [5]:
#fpl_picks_history:
#combine fpl_picks and fpl_picks2 into a single sql table in the database
#add fpl_picks_{current_season} and fpl_picks_2_{current_season} into a single sql table in the database

In [6]:
# Erling Haaland goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT player_name_id, season, event, fixture, goals_scored, expected_goals, expected_assists, assists
                          FROM playergw_transformed
                          WHERE expected_goals IS NOT NULL
                            AND player_name_id = 'Erling Haaland'
                          ORDER BY season, event, fixture
""")
view.pivot_table(index=['season'], values=['goals_scored', 'expected_goals', 'expected_assists', 'assists'], aggfunc='sum',margins=True,dropna=False)

            assists  expected_assists  expected_goals  goals_scored
season
20222023.0      9.0           1.33591         17.4943          36.0
20232024.0      8.0           2.18000         29.5700          27.0
20242025.0      3.0           2.04000         21.9000          22.0
20252026.0      8.0           2.67000         25.5000          27.0
20262027.0      0.0           0.91000          5.6700           8.0
All            28.0           9.13591        100.1343         120.0

In [7]:
# Erling Haaland goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT *
FROM predictions
""")
view.columns

Index(['player_name_id', 'element', 'season', 'event', 'team_name', 'team_elo',
       'opp_team_name', 'opp_team_elo', 'team_attack_elo',
       'opp_team_attack_elo', 'team_defence_elo', 'opp_team_defence_elo',
       'position', 'value', 'fixture_count', 'mins_pred', 'xpoints',
       'xpoints_mins', 'xpoints_goals', 'xpoints_assists',
       'xg_overperf_factor', 'xa_overperf_factor', 'xpoints_clean_sheets',
       'xpoints_shots_saved', 'xpoints_goals_conceded', 'xpoints_defcon',
       'xpoints_bonus', 'xgp90_pred', 'xap90_pred', 'xgcp90_pred',
       'in_any_team', 'in_my_team', 'latest_any_team', 'latest_my_team',
       'prediction_timestamp', 'prediction_gameweek'],
      dtype='str')

In [8]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

from FPL_Optimizer import FPLOptimizer

remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {current_gw+1} AND 38
""")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=remaining_gw_predictions[remaining_gw_predictions['event']==current_gw+1],
        budget=999.9,
        column_mapping=custom_columns
    )
    optimizer.optimize()

    # Get results as DataFrames
    # squad = optimizer.get_squad_dataframe()
    # starting_xi = optimizer.get_starting_xi_dataframe()
    result = optimizer.calculate_bench_boost_xpoints()
    result['event'] = current_gw+1

Optimizing team selection for GW8 to GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 52.87
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.43
 ✅        Martinez                       Chelsea      £5.0     3.73

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     2.87
 ✅        Khalaili                       Crystal Palace £5.0     3.83
 ✅        Vuskovic                       Brighton     £5.1     4.26
 ✅        Matheus N.                     Man City     £5.9     4.37
 ✅        Calafiori                      Arsenal      £6.0     5.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.82
 ✅        Xhaka                          Sunderland   £5.4     4.63
 ✅        Barnes                         Newcastle    £6.1     5.12
 ✅        Tavernier                      Bournemouth  £6.1     4.57
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.63

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.36
 ✅        Haaland                        Man City     £15.7    5.97
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

In [9]:
print(f"Team Selection Details - GW {current_gw+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        xpoints,
        CAST(ROUND(mins_pred) as INT) as mins_pred,
        CAST(ROUND(team_elo) as INT) as team_elo,
        CAST(ROUND(team_attack_elo) as INT) as team_attack_elo,
        CAST(ROUND(team_defence_elo) as INT) as team_defence_elo,
        opp_team_name,
        CAST(ROUND(opp_team_elo) as INT) as opp_team_elo,
        CAST(ROUND(opp_team_attack_elo) as INT) as opp_team_attack_elo,
        CAST(ROUND(opp_team_defence_elo) as INT) as opp_team_defence_elo,
        ROUND(xgp90_pred, 2) as xgp90_pred,
        ROUND(xg_overperf_factor, 2) as xg_overperf_factor,
        ROUND(xap90_pred, 2) as xap90_pred,
        ROUND(xa_overperf_factor, 2) as xa_overperf_factor,
        ROUND(xgcp90_pred, 2) as xgcp90_pred
        

    FROM predictions_status
    WHERE latest_my_team = 1
        AND event = {current_gw+1}
    ORDER BY xpoints DESC
""")
# print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view#.head(15)

Team Selection Details - GW 8

,web_name,status,chance_of_playing_this_round,event,position,team_name,xpoints,mins_pred,team_elo,team_attack_elo,team_defence_elo,opp_team_name,opp_team_elo,opp_team_attack_elo,opp_team_defence_elo,xgp90_pred,xg_overperf_factor,xap90_pred,xa_overperf_factor,xgcp90_pred
0,Haaland,a,NaN,8.0,FWD,Man City,5.971916,73,1270,1378,1278,Aston Villa,1111,1081,1096,0.76,1.17,0.32,2.79,1.78
1,Gibbs-White,d,75.0,8.0,MID,Nott'm Forest,5.632450,84,1020,1005,1162,Ipswich Town,1007,1052,956,0.28,1.00,0.45,1.90,1.24
2,Barnes,a,NaN,8.0,MID,Newcastle,5.115450,85,1048,1093,1006,Crystal Palace,1022,994,974,0.36,1.36,0.16,1.00,1.32
3,Calafiori,a,NaN,8.0,DEF,Arsenal,5.065727,77,1268,1189,1361,Everton,1047,989,1158,0.12,1.00,0.14,1.79,0.94
4,Xhaka,a,NaN,8.0,MID,Sunderland,4.633307,86,1025,956,1051,Leeds,1037,1043,1173,0.10,1.66,0.28,1.76,1.60
5,Tavernier,a,NaN,8.0,MID,Bournemouth,4.570461,75,1089,1096,1127,Man Utd,1117,1181,1147,0.26,1.00,0.24,1.30,1.51
6,Matheus N.,a,100.0,8.0,DEF,Man City,4.368376,82,1270,1378,1278,Aston Villa,1111,1081,1096,0.04,1.00,0.20,2.56,1.18
7,Thiago,a,NaN,8.0,FWD,Brentford,4.338902,86,1077,1130,1151,Hull City,1010,981,1074,0.44,1.00,0.06,1.00,1.14
8,Vuskovic,a,NaN,8.0,DEF,Brighton,4.264589,83,1115,1298,1241,Liverpool,1153,1150,1146,0.08,1.00,0.16,1.00,1.59
9,Khalaili,a,100.0,8.0,DEF,Crystal Palace,3.833905,86,1022,994,974,Newcastle,1048,1093,1006,0.06,1.00,0.07,1.00,1.41
10,Gakpo,a,25.0,8.0,MID,Liverpool,3.815869,70,1153,1150,1146,Brighton,1115,1298,1241,0.19,1.00,0.21,1.35,1.48
11,Martinez,i,NaN,8.0,GK,Chelsea,3.730241,87,1095,1210,1044,Spurs,971,922,1049,NaN,1.00,NaN,1.00,1.27
12,A.Becker,a,NaN,8.0,GK,Liverpool,3.425592,90,1153,1150,1146,Brighton,1115,1298,1241,NaN,1.00,NaN,1.00,1.50
13,Emersonn,a,100.0,8.0,FWD,Ipswich Town,3.363644,68,1007,1052,956,Nott'm Forest,1020,1005,1162,0.39,1.00,0.05,1.00,1.46
14,Mykolenko,a,50.0,8.0,DEF,Everton,2.874491,86,1047,989,1158,Arsenal,1268,1189,1361,0.04,1.00,0.06,1.00,1.91

In [10]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{current_gw+1} AND {current_gw+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {current_gw+1} AND {current_gw+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW8 AND 12

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Emersonn Correia da Silva,1,FWD,Ipswich Town,1040.2,16.94,67.9,0.401,1.000,0.048,1.000,1.401
1,Alisson Becker,1,GK,Liverpool,1113.7,17.37,90.0,NaN,1.000,NaN,1.000,1.476
2,Vitalii Mykolenko,1,DEF,Everton,1109.2,17.66,86.1,0.038,1.000,0.059,1.000,1.550
3,Emiliano Martínez Romero,1,GK,Chelsea,1034.1,18.64,87.5,NaN,1.000,NaN,1.000,1.323
4,Anan Khalaili,1,DEF,Crystal Palace,1036.3,19.16,85.8,0.063,1.000,0.072,1.000,1.428
5,Cody Gakpo,1,MID,Liverpool,1113.7,19.53,69.6,0.201,1.000,0.230,1.349,1.411
6,Luka Vušković,1,DEF,Brighton,1111.6,20.76,83.1,0.078,1.000,0.155,1.000,1.816
7,Matheus Nunes,1,DEF,Man City,1107.9,21.30,82.3,0.040,1.000,0.207,2.564,1.280
8,Igor Thiago Nascimento Rodrigues,1,FWD,Brentford,1061.7,21.52,86.1,0.428,1.000,0.058,1.000,1.238
9,Marcus Tavernier,1,MID,Bournemouth,1041.4,23.23,75.5,0.267,1.000,0.244,1.296,1.297
10,Harvey Barnes,1,MID,Newcastle,1095.3,23.37,84.8,0.293,1.359,0.146,1.000,1.527
11,Granit Xhaka,1,MID,Sunderland,1042.9,23.79,85.7,0.104,1.664,0.299,1.759,1.392
12,Riccardo Calafiori,1,DEF,Arsenal,1105.7,24.10,77.1,0.120,1.000,0.133,1.788,1.067
13,Morgan Gibbs-White,1,MID,Nott'm Forest,1107.7,25.90,83.6,0.259,1.000,0.348,1.896,1.490
14,Erling Haaland,1,FWD,Man City,1107.9,29.48,72.9,0.715,1.172,0.351,2.788,1.808

In [11]:
## Multi-week Optimizer

# from FPL_Optimizer import FPLOptimizer

# remaining_gw_predictions = db_creator.run_sql(f"""
    
#     WITH predictions_status AS (
#     SELECT *
#     FROM predictions
#     LEFT JOIN player_status ON predictions.element = player_status.id
#     )
#     SELECT
#         web_name,
#         status,
#         now_cost/10 as value,
#         chance_of_playing_this_round,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints,
#         ROUND(mins_pred) as mins_pred
#     FROM predictions_status
#     WHERE latest_my_team = 1
#         AND event BETWEEN {current_gw+1} AND 38
# """)

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(current_gw + 1, current_gw + 11):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW8...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 52.87
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.43
 ✅        Martinez                       Chelsea      £5.0     3.73

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     2.87
 ✅        Khalaili                       Crystal Palace £5.0     3.83
 ✅        Vuskovic                       Brighton     £5.1     4.26
 ✅        Matheus N.                     Man City     £5.9     4.37
 ✅        Calafiori                      Arsenal      £6.0     5.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.82
 ✅        Xhaka                          Sunderland   £5.4     4.63
 ✅        Barnes                         Newcastle    £6.1     5.12
 ✅        Tavernier                      Bournemouth  £6.1     4.57
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.63

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.36
 ✅        Haaland                        Man City     £15.7    5.97
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 50.80
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.23
 ✅        Martinez                       Chelsea      £5.0     3.57

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     3.71
 ✅        Khalaili                       Crystal Palace £5.0     4.12
 ✅        Vuskovic                       Brighton     £5.1     3.81
 ✅        Matheus N.                     Man City     £5.9     4.02
 ✅        Calafiori                      Arsenal      £6.0     4.45

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.63
 ✅        Xhaka                          Sunderland   £5.4     4.89
 ✅        Barnes                         Newcastle    £6.1     4.70
 ✅        Tavernier                      Bournemouth  £6.1     4.62
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.09

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.40
 ✅        Haaland                        Man City     £15.7    5.76
 ✅        Thiago                         Brentford    £7.8     4.36

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 52.65
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.59
 ✅        Martinez                       Chelsea      £5.0     3.80

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.58
 🪑        Mykolenko                      Everton      £4.6     3.89
 ✅        Vuskovic                       Brighton     £5.1     4.30
 ✅        Matheus N.                     Man City     £5.9     4.31
 ✅        Calafiori                      Arsenal      £6.0     5.39

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.20
 ✅        Xhaka                          Sunderland   £5.4     4.67
 ✅        Barnes                         Newcastle    £6.1     4.75
 ✅        Tavernier                      Bournemouth  £6.1     4.75
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.79

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.40
 ✅        Haaland                        Man City     £15.7    6.18
 ✅        Thiago                         Brentford    £7.8     4.06

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 52.26
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.51
 ✅        Martinez                       Chelsea      £5.0     3.78

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.83
 🪑        Mykolenko                      Everton      £4.6     3.63
 ✅        Vuskovic                       Brighton     £5.1     4.31
 ✅        Matheus N.                     Man City     £5.9     4.60
 ✅        Calafiori                      Arsenal      £6.0     5.02

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.93
 ✅        Xhaka                          Sunderland   £5.4     4.62
 ✅        Barnes                         Newcastle    £6.1     4.37
 ✅        Tavernier                      Bournemouth  £6.1     4.65
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.09

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.36
 ✅        Haaland                        Man City     £15.7    6.10
 ✅        Thiago                         Brentford    £7.8     4.37

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 50.60
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.60
 ✅        Martinez                       Chelsea      £5.0     3.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.80
 🪑        Mykolenko                      Everton      £4.6     3.55
 ✅        Vuskovic                       Brighton     £5.1     4.08
 ✅        Matheus N.                     Man City     £5.9     4.01
 ✅        Calafiori                      Arsenal      £6.0     4.17

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.96
 ✅        Xhaka                          Sunderland   £5.4     4.97
 ✅        Barnes                         Newcastle    £6.1     4.43
 ✅        Tavernier                      Bournemouth  £6.1     4.64
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.30

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.42
 ✅        Haaland                        Man City     £15.7    5.47
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 52.32
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.65
 ✅        Martinez                       Chelsea      £5.0     3.79

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.76
 🪑        Mykolenko                      Everton      £4.6     3.68
 ✅        Vuskovic                       Brighton     £5.1     4.31
 ✅        Matheus N.                     Man City     £5.9     4.23
 ✅        Calafiori                      Arsenal      £6.0     4.91

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.09
 ✅        Xhaka                          Sunderland   £5.4     4.59
 ✅        Barnes                         Newcastle    £6.1     4.60
 ✅        Tavernier                      Bournemouth  £6.1     4.49
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.49

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.41
 ✅        Haaland                        Man City     £15.7    5.98
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 51.60
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.48
 ✅        A.Becker                       Liverpool    £5.5     3.61

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.71
 🪑        Vuskovic                       Brighton     £5.1     3.75
 ✅        Matheus N.                     Man City     £5.9     4.19
 ✅        Calafiori                      Arsenal      £6.0     5.45
 ✅        Mykolenko                      Everton      £4.6     3.82

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.98
 ✅        Xhaka                          Sunderland   £5.4     4.68
 ✅        Barnes                         Newcastle    £6.1     4.90
 ✅        Tavernier                      Bournemouth  £6.1     4.71
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.88

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.37
 ✅        Haaland                        Man City     £15.7    5.88
 ✅        Thiago                         Brentford    £7.8     4.08

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW15...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £102.4m
Total Weighted Expected Points: 51.73
Remaining Budget: £3.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.05
 ✅        A.Becker                       Liverpool    £5.5     3.62

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------

event     web_name position  8  9  10  11  12  13  14  15  16  17
2        Calafiori      DEF  1  1   1   1   1   1   1   1   1   1
7         Khalaili      DEF  1  1   0   0   0   0   0   0   0   0
9       Matheus N.      DEF  1  1   1   1   1   1   1   1   1   1
10       Mykolenko      DEF  0  0   0   0   0   0   1   0   0   0
13        Vuskovic      DEF  1  1   1   1   1   1   0   1   1   1
3         Emersonn      FWD  0  0   0   0   0   0   0   0   0   0
6          Haaland      FWD  1  1   1   1   1   1   1   1   1   1
12          Thiago      FWD  1  1   1   1   1   1   1   1   1   1
0         A.Becker       GK  0  0   0   0   0   0   1   1   1   0
8         Martinez       GK  1  1   1   1   1   1   0   0   0   1
1           Barnes      MID  1  1   1   1   1   1   1   1   1   1
4            Gakpo      MID  0  0   1   1   1   1   1   1   1   1
5      Gibbs-White      MID  1  1   1   1   1   1   1   1   1   1
11       Tavernier      MID  1  1   1   1   1   1   1   1   1   1
14           Xhaka      MID  1  1   1   1   1   1   1   1   1   1

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{current_gw+1} to GW{current_gw+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.5 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {current_gw+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN xpoints * {initial_weight}
                WHEN event = {current_gw+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {current_gw+1} AND {current_gw+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'FWD'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW8 to GW12
Decay factor: 0.5, Weights: [0.52, 0.26, 0.13, 0.06, 0.03]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Erling Haaland,a,1,FWD,Man City,1100.0,5.94,72.9,0.715,1.172,0.351,2.788,1.808
1,Morgan Gibbs-White,d,1,MID,Nott'm Forest,1067.4,5.34,83.6,0.259,1.000,0.348,1.896,1.490
2,Riccardo Calafiori,a,1,DEF,Arsenal,1076.8,4.92,77.1,0.120,1.000,0.133,1.788,1.067
3,Harvey Barnes,a,1,MID,Newcastle,1047.5,4.89,84.8,0.293,1.359,0.146,1.000,1.527
4,Granit Xhaka,a,1,MID,Sunderland,1037.7,4.72,85.7,0.104,1.664,0.299,1.759,1.392
5,Marcus Tavernier,a,1,MID,Bournemouth,1073.0,4.61,75.5,0.267,1.000,0.244,1.296,1.297
6,Alex Iwobi,a,0,MID,Fulham,1055.3,4.56,77.8,0.245,1.434,0.200,1.000,1.458
7,Phil Foden,a,0,MID,Man City,1100.0,4.55,56.5,0.550,1.603,0.215,1.000,1.045
8,Anton Stach,a,0,MID,Leeds,1038.3,4.51,84.0,0.210,1.000,0.149,1.000,1.256
9,Pedro Lomba Neto,a,0,MID,Chelsea,1021.4,4.41,83.5,0.157,1.000,0.251,1.531,1.277
10,Enzo Fernández,a,0,MID,Man City,1100.0,4.40,69.1,0.285,1.000,0.166,1.000,1.190
11,James Justin,a,0,DEF,Leeds,1038.3,4.35,86.5,0.058,1.000,0.095,1.807,1.260
12,Jannik Schuster,d,0,DEF,Brentford,1031.8,4.35,77.2,0.041,1.000,0.145,1.000,1.358
13,Diego Gómez Amarilla,a,0,MID,Brighton,1160.7,4.32,84.2,0.195,1.000,0.145,1.000,1.504
14,Igor Thiago Nascimento Rodrigues,a,1,FWD,Brentford,1031.8,4.31,86.1,0.428,1.000,0.058,1.000,1.238
15,Matheus Nunes,a,1,DEF,Man City,1100.0,4.27,82.3,0.040,1.000,0.207,2.564,1.280
16,Bobby Thomas,a,0,DEF,Coventry City,1028.1,4.26,84.9,0.049,1.000,0.032,1.000,1.352
17,Jaidon Anthony,a,0,MID,Brentford,1031.8,4.26,77.4,0.259,1.384,0.109,1.000,1.358
18,Sven Botman,a,0,DEF,Newcastle,1047.5,4.26,86.5,0.047,1.000,0.081,2.182,1.506
19,Leif Davis,a,0,DEF,Ipswich Town,1026.1,4.26,86.0,0.087,1.000,0.078,1.000,1.380
20,Issa Diop,a,0,DEF,Ipswich Town,1026.1,4.25,87.0,0.054,1.000,0.031,1.000,1.310
21,Youri Tielemans,a,0,MID,Man Utd,1097.1,4.24,79.1,0.115,1.000,0.233,1.512,1.417
22,Rico Lewis,a,0,DEF,Man City,1100.0,4.22,61.4,0.138,1.000,0.125,1.000,1.488
23,Levi Samuels Colwill,a,0,DEF,Chelsea,1021.4,4.21,86.1,0.034,1.000,0.027,1.000,1.310
24,James Hill,a,0,DEF,Bournemouth,1073.0,4.20,87.2,0.038,1.000,0.053,1.000,1.364
25,Chris Richards,a,0,DEF,Crystal Palace,1037.5,4.19,86.9,0.054,1.000,0.034,1.000,1.376
26,Dara O'Shea,a,0,DEF,Ipswich Town,1026.1,4.18,87.8,0.050,1.000,0.042,1.000,1.357
27,Jaydee Canvot,a,0,DEF,Crystal Palace,1037.5,4.17,87.4,0.046,1.000,0.032,1.000,1.383
28,António João Pereira de Albuquerque Tavares da...,a,0,DEF,Bournemouth,1073.0,4.17,74.6,0.074,1.000,0.064,1.000,1.456
29,Timothy Castagne,a,0,DEF,Fulham,1055.3,4.15,83.8,0.063,1.000,0.117,2.015,1.514
30,Luka Vušković,a,1,DEF,Brighton,1160.7,4.15,83.1,0.078,1.000,0.155,1.000,1.816
31,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1073.0,4.15,84.0,0.200,1.000,0.121,1.000,1.320
32,Jack Rudoni,a,0,MID,Coventry City,1028.1,4.15,70.5,0.229,1.000,0.160,1.000,1.252
33,Jay Dasilva,a,0,DEF,Coventry City,1028.1,4.14,84.8,0.060,1.000,0.088,1.000,1.310
34,Emiliano Buendía Stati,a,0,MID,Aston Villa,1163.0,4.12,75.7,0.252,1.000,0.104,1.000,1.400
35,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1067.4,4.11,87.7,0.059,1.000,0.045,1.000,1.474
36,John McGinn,a,0,MID,Aston Villa,1163.0,4.06,77.6,0.213,1.000,0.192,1.348,1.387
37,Adam Wharton,a,0,MID,Crystal Palace,1037.5,4.06,84.9,0.066,1.000,0.176,1.000,1.384
38,Adrien Truffert,a,0,DEF,Bournemouth,1073.0,4.05,87.3,0.055,1.000,0.128,1.414,1.366
39,Antonee Robinson,a,0,DEF,Fulham,1055.3,4.04,85.9,0.056,1.000,0.127,1.570,1.525
40,Josh King,a,0,MID,Fulham,1055.3,4.03,76.3,0.191,1.000,0.127,1.000,1.431
41,Tyrick Mitchell,a,0,DEF,Crystal Palace,1037.5,4.03,83.2,0.058,1.000,0.089,1.418,1.377
42,Bafodé Diakité,a,0,DEF,Bournemouth,1073.0,4.01,43.3,0.057,1.000,0.056,1.000,0.632
43,Kristoffer Ajer,a,0,DEF,Brentford,1031.8,3.99,87.3,0.046,1.000,0.040,1.000,1.397
44,Jordan Henderson,a,0,MID,Chelsea,1021.4,3.98,83.9,0.108,1.000,0.108,1.000,1.265
45,Ethan Ampadu,a,0,MID,Leeds,1038.3,3.97,85.4,0.060,1.000,0.094,1.654,1.276
46,Matthijs de Ligt,a,0,DEF,Man Utd,1097.1,3.97,68.3,0.150,1.000,0.148,1.000,1.854
47,Harry Maguire,a,0,DEF,Man Utd,1097.1,3.96,87.6,0.057,1.000,0.125,2.701,1.560
48,Thomas Meunier,d,0,DEF,Sunderland,1037.7,3.95,64.6,0.080,1.000,0.174,1.000,1.421
49,Keane Lewis-Potter,a,0,MID,Brentford,1031.8,3.95,74.5,0.156,1.000,0.124,1.000,1.300

In [13]:
print(f"Best players to pick for the rest of the season: GW{current_gw+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    -- AND position IN ('MID')
    -- AND team_name = 'Liverpool'
  AND event BETWEEN {current_gw+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW8 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Erling Haaland,a,1,FWD,Man City,1066.5,188.12,73.0,1.172,0.742,2.788,0.379,1.760
1,Morgan Gibbs-White,d,1,MID,Nott'm Forest,1077.8,161.69,83.7,1.000,0.259,1.896,0.357,1.442
2,Riccardo Calafiori,a,1,DEF,Arsenal,1067.0,154.14,77.1,1.000,0.122,1.788,0.135,0.983
3,Harvey Barnes,a,1,MID,Newcastle,1082.2,146.49,84.7,1.359,0.299,1.000,0.149,1.487
4,Granit Xhaka,a,1,MID,Sunderland,1068.2,145.83,85.7,1.664,0.103,1.759,0.291,1.454
5,Phil Foden,a,0,MID,Man City,1066.5,144.80,56.7,1.603,0.559,1.000,0.232,0.968
6,Marcus Tavernier,a,1,MID,Bournemouth,1068.4,142.94,75.1,1.000,0.267,1.296,0.243,1.370
7,Enzo Fernández,a,0,MID,Man City,1066.5,141.78,69.8,1.000,0.307,1.000,0.180,1.116
8,Diego Gómez Amarilla,a,0,MID,Brighton,1071.8,138.33,84.2,1.000,0.190,1.000,0.153,1.411
9,Alex Iwobi,a,0,MID,Fulham,1081.8,138.17,77.8,1.434,0.247,1.000,0.197,1.405
10,Anton Stach,a,0,MID,Leeds,1073.3,137.40,84.0,1.000,0.205,1.000,0.143,1.402
11,Matheus Nunes,a,1,DEF,Man City,1066.5,136.19,82.3,1.000,0.040,2.564,0.221,1.216
12,Rico Lewis,a,0,DEF,Man City,1066.5,135.23,61.8,1.000,0.139,1.000,0.126,1.327
13,Igor Thiago Nascimento Rodrigues,a,1,FWD,Brentford,1076.8,133.98,86.1,1.000,0.432,1.000,0.058,1.310
14,Pedro Lomba Neto,a,0,MID,Chelsea,1070.8,133.55,83.5,1.000,0.157,1.531,0.245,1.364
15,James Hill,a,0,DEF,Bournemouth,1068.4,133.47,87.2,1.000,0.038,1.000,0.053,1.367
16,Youri Tielemans,a,0,MID,Man Utd,1077.8,132.92,79.0,1.000,0.119,1.512,0.236,1.327
17,Emiliano Buendía Stati,a,0,MID,Aston Villa,1073.7,131.79,75.8,1.000,0.252,1.000,0.102,1.368
18,António João Pereira de Albuquerque Tavares da...,a,0,DEF,Bournemouth,1068.4,131.75,74.6,1.000,0.074,1.000,0.063,1.445
19,Harry Maguire,a,0,DEF,Man Utd,1077.8,131.45,87.6,1.000,0.057,2.701,0.127,1.422
20,Taylor Harwood-Bellis,a,0,DEF,Aston Villa,1073.7,130.53,70.2,1.000,0.183,1.000,0.038,1.721
21,John McGinn,a,0,MID,Aston Villa,1073.7,130.49,77.5,1.000,0.216,1.348,0.193,1.370
22,Jannik Schuster,d,0,DEF,Brentford,1076.8,130.48,77.2,1.000,0.041,1.000,0.148,1.369
23,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1068.4,130.39,83.9,1.000,0.202,1.000,0.119,1.374
24,Matthijs de Ligt,a,0,DEF,Man Utd,1077.8,129.82,68.4,1.000,0.149,1.000,0.149,1.697
25,Sven Botman,a,0,DEF,Newcastle,1082.2,129.40,86.5,1.000,0.048,2.182,0.081,1.474
26,James Justin,a,0,DEF,Leeds,1073.3,128.86,86.5,1.000,0.058,1.807,0.093,1.391
27,Jaidon Anthony,a,0,MID,Brentford,1076.8,128.47,77.3,1.384,0.259,1.000,0.108,1.374
28,Leif Davis,a,0,DEF,Ipswich Town,1075.5,128.11,86.0,1.000,0.087,1.000,0.076,1.517
29,Luka Vušković,a,1,DEF,Brighton,1071.8,127.93,83.1,1.000,0.078,1.000,0.158,1.900
30,Jack Rudoni,a,0,MID,Coventry City,1074.6,127.71,70.4,1.000,0.230,1.000,0.157,1.356
31,Adrien Truffert,a,0,DEF,Bournemouth,1068.4,127.55,87.3,1.000,0.055,1.414,0.129,1.368
32,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1077.8,127.55,87.7,1.000,0.059,1.000,0.046,1.411
33,Alexis Mac Allister,a,0,MID,Liverpool,1070.1,127.49,79.1,1.000,0.148,1.000,0.137,1.293
34,Issa Diop,a,0,DEF,Ipswich Town,1075.5,127.47,86.8,1.000,0.054,1.000,0.030,1.423
35,Victor Lindelöf,a,0,DEF,Aston Villa,1073.7,127.35,87.5,1.000,0.060,1.000,0.031,1.408
36,Harry Amass,a,0,DEF,Man Utd,1077.8,127.01,66.3,1.000,0.175,1.000,0.099,1.735
37,Dara O'Shea,a,0,DEF,Ipswich Town,1075.5,125.59,87.8,1.000,0.050,1.000,0.041,1.468
38,Rayan Aït-Nouri,a,0,DEF,Man City,1066.5,125.06,55.5,1.000,0.093,1.000,0.079,1.243
39,Timothy Castagne,a,0,DEF,Fulham,1081.8,124.90,83.8,1.000,0.063,2.015,0.117,1.479
40,Adam Wharton,a,0,MID,Crystal Palace,1079.0,124.31,85.0,1.000,0.065,1.000,0.167,1.479
41,Cody Gakpo,a,1,MID,Liverpool,1070.1,123.83,69.5,1.000,0.211,1.349,0.241,1.306
42,Chris Richards,a,0,DEF,Crystal Palace,1079.0,123.75,86.9,1.000,0.054,1.000,0.033,1.501
43,Tyrone Mings,a,0,DEF,Aston Villa,1073.7,123.62,83.5,1.000,0.047,1.000,0.036,1.401
44,Bafodé Diakité,a,0,DEF,Bournemouth,1068.4,123.18,44.6,1.000,0.056,1.000,0.057,0.642
45,Josh King,a,0,MID,Fulham,1081.8,123.13,76.3,1.000,0.192,1.000,0.131,1.365
46,Bobby Thomas,a,0,DEF,Coventry City,1074.6,122.97,84.9,1.000,0.049,1.000,0.031,1.490
47,Jaydee Canvot,a,0,DEF,Crystal Palace,1079.0,122.94,87.4,1.000,0.046,1.000,0.030,1.509
48,Yasin Ayari,a,0,MID,Brighton,1071.8,122.92,78.9,1.000,0.138,1.000,0.075,1.357
49,Levi Samuels Colwill,a,0,DEF,Chelsea,1070.8,122.31,86.2,1.000,0.034,1.000,0.027,1.361

In [14]:
# print(f"Best available players to pick for the next 5 gameweeks: GW{current_gw+1} AND {current_gw+5}")
# view = db_creator.run_sql(f"""
# WITH predictions_status AS (
#     SELECT 
#         p.player_name_id,
#         p.element,
#         ps.status,
#         p.latest_my_team,
#         p.position,
#         p.team_name,
#         p.opp_team_elo,
#         p.xpoints,
#         p.mins_pred,
#         p.xgp90_pred,
#         p.xg_overperf_factor,
#         p.xap90_pred,
#         p.xa_overperf_factor,
#         p.xgcp90_pred,
#         p.event,
#         p.latest_any_team
#     FROM predictions p
#     LEFT JOIN player_status ps ON p.element = ps.id
# )  
# SELECT
#         player_name_id,
#         status,
#         latest_my_team,
#         position,
#         team_name,
#         ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
#         ROUND(SUM(xpoints),2) AS total_xpoints,
#         ROUND(AVG(mins_pred),1) AS avg_mins_pred,
#         ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
#         ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
#         ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
#         ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
#         ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
#     FROM predictions_status
#     WHERE (latest_any_team = 0 OR latest_my_team = 1)
#       AND event BETWEEN {current_gw+1} AND {current_gw+5}
#       AND status IN ('a','d')
#         --AND position = 'FWD'
#       -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
#     GROUP BY player_name_id, status, position, team_name, latest_my_team
#     ORDER BY total_xpoints DESC
# """)
# view.head(50)

In [15]:
print(f"\nBest available players to replace worst in my team: {current_gw+1} to {current_gw+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 8 to 12

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Leeds,a,James Justin,21.930121,Vitalii Mykolenko,17.662517,4.267604
1,DEF,Bournemouth,a,James Hill,21.674365,Vitalii Mykolenko,17.662517,4.011847
2,DEF,Ipswich Town,a,Leif Davis,21.624085,Vitalii Mykolenko,17.662517,3.961568
3,DEF,Ipswich Town,a,Issa Diop,21.438342,Vitalii Mykolenko,17.662517,3.775825
4,DEF,Bournemouth,a,António João Pereira de Albuquerque Tavares da...,21.295229,Vitalii Mykolenko,17.662517,3.632712
5,DEF,Ipswich Town,a,Dara O'Shea,21.115615,Vitalii Mykolenko,17.662517,3.453098
6,DEF,Brentford,d,Jannik Schuster,21.088905,Vitalii Mykolenko,17.662517,3.426388
7,DEF,Aston Villa,a,Taylor Harwood-Bellis,21.016769,Vitalii Mykolenko,17.662517,3.354252
8,DEF,Crystal Palace,a,Chris Richards,21.001249,Vitalii Mykolenko,17.662517,3.338732
9,MID,Man City,a,Phil Foden,22.829467,Cody Gakpo,19.533403,3.296064
10,DEF,Crystal Palace,a,Jaydee Canvot,20.921029,Vitalii Mykolenko,17.662517,3.258512
11,DEF,Coventry City,a,Bobby Thomas,20.911732,Vitalii Mykolenko,17.662517,3.249215
12,MID,Leeds,a,Anton Stach,22.599084,Cody Gakpo,19.533403,3.065681
13,DEF,Bournemouth,a,Adrien Truffert,20.676425,Vitalii Mykolenko,17.662517,3.013908
14,DEF,Aston Villa,a,Victor Lindelöf,20.642449,Vitalii Mykolenko,17.662517,2.979932
15,DEF,Man City,a,Rico Lewis,20.635612,Vitalii Mykolenko,17.662517,2.973095
16,DEF,Newcastle,a,Sven Botman,20.551764,Vitalii Mykolenko,17.662517,2.889247
17,DEF,Coventry City,a,Jay Dasilva,20.466201,Vitalii Mykolenko,17.662517,2.803684
18,MID,Fulham,a,Alex Iwobi,22.172896,Cody Gakpo,19.533403,2.639494
19,DEF,Chelsea,a,Levi Samuels Colwill,20.279947,Vitalii Mykolenko,17.662517,2.617430

In [16]:
player_name = 'Erling Haaland'
print(f"\n {player_name} xPoints between {current_gw+1} and {current_gw+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
        AND player_name_id = '{player_name}'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Erling Haaland xPoints between 8 and 12:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,8.0,FWD,Man City,Aston Villa,15.7,1111.444722,5.971916,73.214581,0.757109,0.323815,1.775116
1,Erling Haaland,9.0,FWD,Man City,Brighton,15.7,1114.954967,5.761959,73.337564,0.694997,0.323983,1.811966
2,Erling Haaland,10.0,FWD,Man City,Nott'm Forest,15.7,1020.114514,6.180373,73.214581,0.747944,0.397387,1.690469
3,Erling Haaland,11.0,FWD,Man City,Fulham,15.7,1025.102019,6.100731,72.806248,0.742310,0.386514,1.728774
4,Erling Haaland,12.0,FWD,Man City,Arsenal,15.7,1267.848107,5.467483,72.074107,0.631031,0.323983,2.035953

# Chip Decisions

### Triple Captain

In [17]:
print("When to use TRIPLE CAPTAIN chip (gws1-18)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {current_gw} AND 18
    ORDER BY xpoints DESC
""")
view.head(10)

When to use TRIPLE CAPTAIN chip (gws1-18)

   player_name_id  event position team_name  opp_team_name   xpoints
0  Erling Haaland   16.0      FWD  Man City      Hull City  6.434093
1  Erling Haaland   10.0      FWD  Man City  Nott'm Forest  6.180373
2  Erling Haaland   11.0      FWD  Man City         Fulham  6.100731
3  Erling Haaland   17.0      FWD  Man City      Newcastle  6.067110
4  Erling Haaland   18.0      FWD  Man City        Everton  6.053763
5  Erling Haaland   15.0      FWD  Man City        Chelsea  6.006198
6  Erling Haaland   13.0      FWD  Man City          Leeds  5.978275
7  Erling Haaland    8.0      FWD  Man City    Aston Villa  5.971916
8  Erling Haaland   14.0      FWD  Man City      Brentford  5.875787
9  Erling Haaland    9.0      FWD  Man City       Brighton  5.761959

### Bench Boost

In [18]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(current_gw+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=999.9,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW8 to GW38...

Optimizing team selection for GW8...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 52.87
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.43
 ✅        Martinez                       Chelsea      £5.0     3.73

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     2.87
 ✅        Khalaili                       Crystal Palace £5.0     3.83
 ✅        Vuskovic                       Brighton     £5.1     4.26
 ✅        Matheus N.                     Man City     £5.9     4.37
 ✅        Calafiori                      Arsenal      £6.0     5.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.82
 ✅        Xhaka                          Sunderland   £5.4     4.63
 ✅        Barnes                         Newcastle    £6.1     5.12
 ✅        Tavernier                      Bournemouth  £6.1     4.57
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.63

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.36
 ✅        Haaland                        Man City     £15.7    5.97
 ✅        Thiago                         Brentford    £7.8     4.34

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 50.80
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.23
 ✅        Martinez                       Chelsea      £5.0     3.57

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mykolenko                      Everton      £4.6     3.71
 ✅        Khalaili                       Crystal Palace £5.0     4.12
 ✅        Vuskovic                       Brighton     £5.1     3.81
 ✅        Matheus N.                     Man City     £5.9     4.02
 ✅        Calafiori                      Arsenal      £6.0     4.45

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.63
 ✅        Xhaka                          Sunderland   £5.4     4.89
 ✅        Barnes                         Newcastle    £6.1     4.70
 ✅        Tavernier                      Bournemouth  £6.1     4.62
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.09

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.40
 ✅        Haaland                        Man City     £15.7    5.76
 ✅        Thiago                         Brentford    £7.8     4.36

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 52.65
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.59
 ✅        Martinez                       Chelsea      £5.0     3.80

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.58
 🪑        Mykolenko                      Everton      £4.6     3.89
 ✅        Vuskovic                       Brighton     £5.1     4.30
 ✅        Matheus N.                     Man City     £5.9     4.31
 ✅        Calafiori                      Arsenal      £6.0     5.39

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.20
 ✅        Xhaka                          Sunderland   £5.4     4.67
 ✅        Barnes                         Newcastle    £6.1     4.75
 ✅        Tavernier                      Bournemouth  £6.1     4.75
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.79

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.40
 ✅        Haaland                        Man City     £15.7    6.18
 ✅        Thiago                         Brentford    £7.8     4.06

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 52.26
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.51
 ✅        Martinez                       Chelsea      £5.0     3.78

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.83
 🪑        Mykolenko                      Everton      £4.6     3.63
 ✅        Vuskovic                       Brighton     £5.1     4.31
 ✅        Matheus N.                     Man City     £5.9     4.60
 ✅        Calafiori                      Arsenal      £6.0     5.02

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.93
 ✅        Xhaka                          Sunderland   £5.4     4.62
 ✅        Barnes                         Newcastle    £6.1     4.37
 ✅        Tavernier                      Bournemouth  £6.1     4.65
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.09

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.36
 ✅        Haaland                        Man City     £15.7    6.10
 ✅        Thiago                         Brentford    £7.8     4.37

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 50.60
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.60
 ✅        Martinez                       Chelsea      £5.0     3.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.80
 🪑        Mykolenko                      Everton      £4.6     3.55
 ✅        Vuskovic                       Brighton     £5.1     4.08
 ✅        Matheus N.                     Man City     £5.9     4.01
 ✅        Calafiori                      Arsenal      £6.0     4.17

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.96
 ✅        Xhaka                          Sunderland   £5.4     4.97
 ✅        Barnes                         Newcastle    £6.1     4.43
 ✅        Tavernier                      Bournemouth  £6.1     4.64
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.30

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.42
 ✅        Haaland                        Man City     £15.7    5.47
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 52.32
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.65
 ✅        Martinez                       Chelsea      £5.0     3.79

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.76
 🪑        Mykolenko                      Everton      £4.6     3.68
 ✅        Vuskovic                       Brighton     £5.1     4.31
 ✅        Matheus N.                     Man City     £5.9     4.23
 ✅        Calafiori                      Arsenal      £6.0     4.91

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.09
 ✅        Xhaka                          Sunderland   £5.4     4.59
 ✅        Barnes                         Newcastle    £6.1     4.60
 ✅        Tavernier                      Bournemouth  £6.1     4.49
 ✅        Gibbs-White                    Nott'm Forest £8.0     5.49

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.41
 ✅        Haaland                        Man City     £15.7    5.98
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 51.60
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.48
 ✅        A.Becker                       Liverpool    £5.5     3.61

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.71
 🪑        Vuskovic                       Brighton     £5.1     3.75
 ✅        Matheus N.                     Man City     £5.9     4.19
 ✅        Calafiori                      Arsenal      £6.0     5.45
 ✅        Mykolenko                      Everton      £4.6     3.82

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     3.98
 ✅        Xhaka                          Sunderland   £5.4     4.68
 ✅        Barnes                         Newcastle    £6.1     4.90
 ✅        Tavernier                      Bournemouth  £6.1     4.71
 ✅        Gibbs-White                    Nott'm Forest £8.0     4.88

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.6     3.37
 ✅        Haaland                        Man City     £15.7    5.88
 ✅        Thiago                         Brentford    £7.8     4.08

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW15...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.9m / £999.9m
Total Weighted Expected Points: 51.73
Remaining Budget: £901.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.05
 ✅        A.Becker                       Liverpool    £5.5     3.62

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts

In [19]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

    event  bench_boost_gain
22     30         13.410675
18     26         13.184291
5      13         13.051721
12     20         13.051721
2      10         13.017424
13     21         13.017424
11     19         12.977735
17     25         12.977735
15     23         12.938372
4      12         12.938372
23     31         12.922426
14     22         12.914226
30     38         12.893381
3      11         12.893038
8      16         12.878994
19     27         12.878994
6      14         12.875718
26     34         12.875718
1       9         12.580806
16     24         12.540905
9      17         12.535029
28     36         12.527985
27     35         12.482177
21     29         12.300513
25     33         12.222431
7      15         12.222431
24     32         12.179303
29     37         12.131637
0       8         12.131637
10     18         12.123817
20     28         11.474556

In [20]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.12 minute(s)