In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

# Load TRDL Data

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 8
current_season = 20262027

In [5]:
#fpl_picks_history:
#combine fpl_picks and fpl_picks2 into a single sql table in the database
#add fpl_picks_{current_season} and fpl_picks_2_{current_season} into a single sql table in the database

In [6]:
# Erling Haaland goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT player_name_id, season, event, fixture, goals_scored, expected_goals, expected_assists, assists
                          FROM playergw_transformed
                          WHERE expected_goals IS NOT NULL
                            AND player_name_id = 'Erling Haaland'
                          ORDER BY season, event, fixture
""")
view.pivot_table(index=['season'], values=['goals_scored', 'expected_goals', 'expected_assists', 'assists'], aggfunc='sum',margins=True,dropna=False)

            assists  expected_assists  expected_goals  goals_scored
season
20222023.0      9.0           1.33591         17.4943          36.0
20232024.0      8.0           2.18000         29.5700          27.0
20242025.0      3.0           2.04000         21.9000          22.0
20252026.0      8.0           2.67000         25.5000          27.0
20262027.0      0.0           0.77000          6.0900           9.0
All            28.0           8.99591        100.5543         121.0

In [7]:
# Erling Haaland goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT *
FROM predictions
""")
view.columns

Index(['player_name_id', 'element', 'season', 'event', 'team_name', 'team_elo',
       'opp_team_name', 'opp_team_elo', 'team_attack_elo',
       'opp_team_attack_elo', 'team_defence_elo', 'opp_team_defence_elo',
       'position', 'value', 'fixture_count', 'mins_pred', 'xpoints',
       'xpoints_mins', 'xpoints_goals', 'xpoints_assists',
       'xg_overperf_factor', 'xa_overperf_factor', 'xpoints_clean_sheets',
       'xpoints_shots_saved', 'xpoints_goals_conceded', 'xpoints_defcon',
       'xpoints_bonus', 'xgp90_pred', 'xap90_pred', 'xgcp90_pred',
       'in_any_team', 'in_my_team', 'latest_any_team', 'latest_my_team',
       'prediction_timestamp', 'prediction_gameweek'],
      dtype='str')

In [8]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

from FPL_Optimizer import FPLOptimizer

remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {current_gw+1} AND 38
""")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=remaining_gw_predictions[remaining_gw_predictions['event']==current_gw+1],
        budget=999.9,
        column_mapping=custom_columns
    )
    optimizer.optimize()

    # Get results as DataFrames
    # squad = optimizer.get_squad_dataframe()
    # starting_xi = optimizer.get_starting_xi_dataframe()
    result = optimizer.calculate_bench_boost_xpoints()
    result['event'] = current_gw+1

Optimizing team selection for GW9 to GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 50.33
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.18
 ✅        Martinez                       Chelsea      £5.0     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Justin                         Leeds        £4.5     4.02
 ✅        Khalaili                       Crystal Palace £5.0     4.02
 ✅        Vuskovic                       Brighton     £5.1     4.06
 ✅        Matheus N.                     Man City     £5.9     4.18
 ✅        Calafiori                      Arsenal      £6.0     4.35

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.83
 ✅        Xhaka                          Sunderland   £5.4     4.05
 ✅        Barnes                         Newcastle    £6.1     4.44
 ✅        Tavernier                      Bournemouth  £6.3     4.74
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.23

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.35
 ✅        Haaland                        Man City     £15.7    5.77
 ✅        Thiago                         Brentford    £7.8     4.35

================================================================================
Optimization Status: Optimal

In [9]:
print(f"Team Selection Details - GW {current_gw+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        xpoints,
        CAST(ROUND(mins_pred) as INT) as mins_pred,
        CAST(ROUND(team_elo) as INT) as team_elo,
        CAST(ROUND(team_attack_elo) as INT) as team_attack_elo,
        CAST(ROUND(team_defence_elo) as INT) as team_defence_elo,
        opp_team_name,
        CAST(ROUND(opp_team_elo) as INT) as opp_team_elo,
        CAST(ROUND(opp_team_attack_elo) as INT) as opp_team_attack_elo,
        CAST(ROUND(opp_team_defence_elo) as INT) as opp_team_defence_elo,
        ROUND(xgp90_pred, 2) as xgp90_pred,
        ROUND(xg_overperf_factor, 2) as xg_overperf_factor,
        ROUND(xap90_pred, 2) as xap90_pred,
        ROUND(xa_overperf_factor, 2) as xa_overperf_factor,
        ROUND(xgcp90_pred, 2) as xgcp90_pred
        

    FROM predictions_status
    WHERE latest_my_team = 1
        AND event = {current_gw+1}
    ORDER BY xpoints DESC
""")
# print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view#.head(15)

Team Selection Details - GW 9

,web_name,status,chance_of_playing_this_round,event,position,team_name,xpoints,mins_pred,team_elo,team_attack_elo,team_defence_elo,opp_team_name,opp_team_elo,opp_team_attack_elo,opp_team_defence_elo,xgp90_pred,xg_overperf_factor,xap90_pred,xa_overperf_factor,xgcp90_pred
0,Haaland,a,100.0,9.0,FWD,Man City,5.768060,80,1256,1354,1258,Brighton,1106,1260,1226,0.65,1.18,0.22,2.83,1.24
1,Gibbs-White,a,100.0,9.0,MID,Nott'm Forest,5.228777,84,1020,992,1166,Brentford,1075,1118,1153,0.28,1.00,0.32,1.88,1.40
2,Tavernier,a,NaN,9.0,MID,Bournemouth,4.740298,77,1100,1129,1160,Leeds,1037,1043,1173,0.26,1.00,0.23,1.28,1.22
3,Barnes,a,NaN,9.0,MID,Newcastle,4.443351,82,1058,1097,1035,Everton,1043,977,1150,0.24,1.18,0.15,1.00,1.35
4,Calafiori,d,NaN,9.0,DEF,Arsenal,4.353286,73,1272,1197,1373,Liverpool,1162,1165,1183,0.10,1.00,0.18,1.68,1.28
5,Thiago,a,NaN,9.0,FWD,Brentford,4.348093,85,1075,1118,1153,Nott'm Forest,1020,992,1166,0.38,1.00,0.08,1.00,1.63
6,Matheus N.,d,75.0,9.0,DEF,Man City,4.182840,77,1256,1354,1258,Brighton,1106,1260,1226,0.04,1.00,0.20,2.56,1.34
7,Vuskovic,a,NaN,9.0,DEF,Brighton,4.057507,87,1106,1260,1226,Man City,1256,1354,1258,0.08,1.00,0.08,1.00,1.75
8,Xhaka,a,NaN,9.0,MID,Sunderland,4.051785,80,1025,956,1051,Coventry City,980,958,983,0.07,1.00,0.16,1.00,1.11
9,Khalaili,a,100.0,9.0,DEF,Crystal Palace,4.019697,83,1012,965,970,Spurs,995,971,1093,0.06,1.00,0.07,1.00,1.31
10,Justin,a,NaN,9.0,DEF,Leeds,4.016372,79,1037,1043,1173,Bournemouth,1100,1129,1160,0.05,1.00,0.05,1.00,1.43
11,Gakpo,a,100.0,9.0,MID,Liverpool,3.826652,70,1162,1165,1183,Arsenal,1272,1197,1373,0.22,1.00,0.18,1.35,1.45
12,Martinez,i,0.0,9.0,GK,Chelsea,3.703021,89,1081,1172,1030,Man Utd,1106,1148,1115,NaN,1.00,NaN,1.00,1.39
13,Emersonn,a,100.0,9.0,FWD,Ipswich Town,3.345296,69,1008,1047,969,Hull City,1011,980,1087,0.39,1.00,0.05,1.00,1.26
14,A.Becker,a,NaN,9.0,GK,Liverpool,3.179114,89,1162,1165,1183,Arsenal,1272,1197,1373,NaN,1.00,NaN,1.00,1.72

In [10]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{current_gw+1} AND {current_gw+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {current_gw+1} AND {current_gw+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW9 AND 13

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Emersonn Correia da Silva,1,FWD,Ipswich Town,1042.4,16.60,68.5,0.391,1.000,0.048,1.000,1.334
1,Alisson Becker,1,GK,Liverpool,1091.7,17.81,89.1,NaN,1.000,NaN,1.000,1.367
2,Emiliano Martínez Romero,1,GK,Chelsea,1040.1,18.81,88.8,NaN,1.000,NaN,1.000,1.306
3,Granit Xhaka,1,MID,Sunderland,1068.8,19.30,79.6,0.061,1.000,0.140,1.000,1.328
4,Anan Khalaili,1,DEF,Crystal Palace,1045.9,19.35,83.2,0.062,1.000,0.068,1.000,1.407
5,James Justin,1,DEF,Leeds,1082.5,19.94,78.1,0.054,1.000,0.050,1.000,1.459
6,Cody Gakpo,1,MID,Liverpool,1091.7,20.92,71.8,0.242,1.000,0.216,1.346,1.302
7,Harvey Barnes,1,MID,Newcastle,1112.2,21.44,82.2,0.231,1.176,0.138,1.000,1.520
8,Igor Thiago Nascimento Rodrigues,1,FWD,Brentford,1109.4,21.72,84.5,0.381,1.000,0.079,1.000,1.754
9,Luka Vušković,1,DEF,Brighton,1100.0,21.99,86.3,0.078,1.000,0.084,1.000,1.489
10,Matheus Nunes,1,DEF,Man City,1093.9,22.15,77.3,0.037,1.000,0.209,2.564,1.215
11,Riccardo Calafiori,1,DEF,Arsenal,1112.4,23.03,72.3,0.100,1.000,0.176,1.683,1.139
12,Marcus Tavernier,1,MID,Bournemouth,1041.0,23.88,77.1,0.260,1.000,0.246,1.279,1.258
13,Morgan Gibbs-White,1,MID,Nott'm Forest,1104.8,26.06,84.2,0.277,1.000,0.322,1.880,1.437
14,Erling Haaland,1,FWD,Man City,1093.9,30.49,79.4,0.734,1.176,0.225,2.831,1.247

In [11]:
## Multi-week Optimizer

# from FPL_Optimizer import FPLOptimizer

# remaining_gw_predictions = db_creator.run_sql(f"""
    
#     WITH predictions_status AS (
#     SELECT *
#     FROM predictions
#     LEFT JOIN player_status ON predictions.element = player_status.id
#     )
#     SELECT
#         web_name,
#         status,
#         now_cost/10 as value,
#         chance_of_playing_this_round,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints,
#         ROUND(mins_pred) as mins_pred
#     FROM predictions_status
#     WHERE latest_my_team = 1
#         AND event BETWEEN {current_gw+1} AND 38
# """)

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(current_gw + 1, current_gw + 11):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 50.33
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.18
 ✅        Martinez                       Chelsea      £5.0     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Justin                         Leeds        £4.5     4.02
 ✅        Khalaili                       Crystal Palace £5.0     4.02
 ✅        Vuskovic                       Brighton     £5.1     4.06
 ✅        Matheus N.                     Man City     £5.9     4.18
 ✅        Calafiori                      Arsenal      £6.0     4.35

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.83
 ✅        Xhaka                          Sunderland   £5.4     4.05
 ✅        Barnes                         Newcastle    £6.1     4.44
 ✅        Tavernier                      Bournemouth  £6.3     4.74
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.23

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.35
 ✅        Haaland                        Man City     £15.7    5.77
 ✅        Thiago                         Brentford    £7.8     4.35

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 53.55
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.70
 ✅        Martinez                       Chelsea      £5.0     3.90

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.36
 ✅        Justin                         Leeds        £4.5     4.37
 ✅        Vuskovic                       Brighton     £5.1     4.39
 ✅        Matheus N.                     Man City     £5.9     4.73
 ✅        Calafiori                      Arsenal      £6.0     5.14

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.77
 ✅        Gakpo                          Liverpool    £7.1     4.40
 ✅        Barnes                         Newcastle    £6.1     4.41
 ✅        Tavernier                      Bournemouth  £6.3     5.07
 ✅        Gibbs-White                    Nott'm Forest £7.9     4.85

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.27
 ✅        Haaland                        Man City     £15.7    6.59
 ✅        Thiago                         Brentford    £7.8     4.28

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-3-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 53.09
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.54
 ✅        Martinez                       Chelsea      £5.0     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Khalaili                       Crystal Palace £5.0     4.15
 ✅        Justin                         Leeds        £4.5     4.14
 ✅        Vuskovic                       Brighton     £5.1     4.92
 ✅        Matheus N.                     Man City     £5.9     4.85
 ✅        Calafiori                      Arsenal      £6.0     4.88

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.76
 🪑        Barnes                         Newcastle    £6.1     4.03
 ✅        Gakpo                          Liverpool    £7.1     4.15
 ✅        Tavernier                      Bournemouth  £6.3     4.81
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.20

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.34
 ✅        Haaland                        Man City     £15.7    6.45
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 50.07
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.65
 ✅        Martinez                       Chelsea      £5.0     3.74

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus N.                     Man City     £5.9     3.77
 🪑        Calafiori                      Arsenal      £6.0     3.93
 ✅        Khalaili                       Crystal Palace £5.0     4.01
 ✅        Justin                         Leeds        £4.5     4.34
 ✅        Vuskovic                       Brighton     £5.1     4.44

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.22
 ✅        Xhaka                          Sunderland   £5.4     3.95
 ✅        Barnes                         Newcastle    £6.1     4.20
 ✅        Tavernier                      Bournemouth  £6.3     4.76
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.32

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.30
 ✅        Haaland                        Man City     £15.7    5.33
 ✅        Thiago                         Brentford    £7.8     4.30

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 51.90
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.74
 ✅        Martinez                       Chelsea      £5.0     3.77

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Justin                         Leeds        £4.5     3.09
 ✅        Khalaili                       Crystal Palace £5.0     3.80
 ✅        Vuskovic                       Brighton     £5.1     4.18
 ✅        Matheus N.                     Man City     £5.9     4.63
 ✅        Calafiori                      Arsenal      £6.0     4.73

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.77
 ✅        Gakpo                          Liverpool    £7.1     4.33
 ✅        Barnes                         Newcastle    £6.1     4.36
 ✅        Tavernier                      Bournemouth  £6.3     4.51
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.46

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.34
 ✅        Haaland                        Man City     £15.7    6.35
 ✅        Thiago                         Brentford    £7.8     4.40

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 52.57
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.46
 ✅        A.Becker                       Liverpool    £5.5     3.55

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.66
 ✅        Justin                         Leeds        £4.5     4.35
 ✅        Vuskovic                       Brighton     £5.1     4.71
 ✅        Matheus N.                     Man City     £5.9     4.37
 ✅        Calafiori                      Arsenal      £6.0     5.13

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.78
 ✅        Gakpo                          Liverpool    £7.1     4.16
 ✅        Barnes                         Newcastle    £6.1     4.56
 ✅        Tavernier                      Bournemouth  £6.3     4.91
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.01

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.32
 ✅        Haaland                        Man City     £15.7    6.09
 ✅        Thiago                         Brentford    £7.8     4.30

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW15...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 52.00
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.09
 ✅        A.Becker                       Liverpool    £5.5     3.54

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.75
 🪑        Justin                         Leeds        £4.5     3.82
 ✅        Vuskovic                       Brighton     £5.1     4.86
 ✅        Matheus N.                     Man City     £5.9     4.57
 ✅        Calafiori                      Arsenal      £6.0     4.63

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.17
 ✅        Xhaka                          Sunderland   £5.4     3.90
 ✅        Barnes                         Newcastle    £6.1     4.66
 ✅        Tavernier                      Bournemouth  £6.3     4.33
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.46

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.35
 ✅        Haaland                        Man City     £15.7    6.11
 ✅        Thiago                         Brentford    £7.8     4.36

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW16...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £102.4m
Total Weighted Expected Points: 53.95
Remaining Budget: £3.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.61
 ✅        A.Becker                       Liverpool    £5.5     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------

event     web_name position  9  10  11  12  13  14  15  16  17  18
2        Calafiori      DEF  1   1   1   0   1   1   1   1   1   1
7           Justin      DEF  0   1   1   1   0   1   0   1   1   1
8         Khalaili      DEF  1   0   1   1   1   0   0   0   0   0
10      Matheus N.      DEF  1   1   1   0   1   1   1   1   1   1
13        Vuskovic      DEF  1   1   1   1   1   1   1   1   1   1
3         Emersonn      FWD  0   0   0   0   0   0   0   0   0   0
6          Haaland      FWD  1   1   1   1   1   1   1   1   1   1
12          Thiago      FWD  1   1   1   1   1   1   1   1   1   1
0         A.Becker       GK  0   0   0   0   0   1   1   1   0   0
9         Martinez       GK  1   1   1   1   1   0   0   0   1   1
1           Barnes      MID  1   1   0   1   1   1   1   1   1   1
4            Gakpo      MID  0   1   1   1   1   1   1   1   1   1
5      Gibbs-White      MID  1   1   1   1   1   1   1   1   1   1
11       Tavernier      MID  1   1   1   1   1   1   1   1   1   1
14           Xhaka      MID  1   0   0   1   0   0   1   0   0   0

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{current_gw+1} to GW{current_gw+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.5 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {current_gw+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN xpoints * {initial_weight}
                WHEN event = {current_gw+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {current_gw+1} AND {current_gw+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'FWD'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW9 to GW13
Decay factor: 0.5, Weights: [0.52, 0.26, 0.13, 0.06, 0.03]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Erling Haaland,a,1,FWD,Man City,1083.0,6.06,79.4,0.734,1.176,0.225,2.831,1.247
1,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1123.3,5.14,84.2,0.277,1.000,0.322,1.880,1.437
2,James Hill,a,0,DEF,Bournemouth,1029.5,4.93,86.6,0.038,1.000,0.053,1.000,1.330
3,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1029.5,4.88,84.4,0.268,1.000,0.144,1.000,1.230
4,Marcus Tavernier,a,1,MID,Bournemouth,1029.5,4.83,77.1,0.260,1.000,0.246,1.279,1.258
5,Mats Wieffer,d,0,DEF,Brighton,1160.0,4.82,60.3,0.225,1.000,0.461,2.266,1.642
6,Jack Rudoni,a,0,MID,Coventry City,1028.2,4.79,83.8,0.238,1.000,0.167,1.000,1.307
7,Riccardo Calafiori,d,1,DEF,Arsenal,1112.8,4.61,72.3,0.100,1.000,0.176,1.683,1.139
8,António João Pereira de Albuquerque Tavares da...,a,0,DEF,Bournemouth,1029.5,4.57,83.9,0.059,1.000,0.072,1.000,1.385
9,Adrien Truffert,a,0,DEF,Bournemouth,1029.5,4.50,84.5,0.043,1.000,0.177,1.497,1.325
10,Phil Foden,a,0,MID,Man City,1083.0,4.50,60.4,0.463,1.601,0.202,1.000,1.075
11,Matthijs de Ligt,a,0,DEF,Man Utd,1102.0,4.45,68.3,0.147,1.000,0.268,1.000,1.587
12,Matheus Nunes,d,1,DEF,Man City,1083.0,4.40,77.3,0.037,1.000,0.209,2.564,1.215
13,Oscar Bobb,a,0,MID,Fulham,1119.1,4.39,72.4,0.307,1.000,0.139,1.000,1.433
14,Harvey Barnes,a,1,MID,Newcastle,1076.3,4.36,82.2,0.231,1.176,0.138,1.000,1.520
15,Anton Stach,d,0,MID,Leeds,1067.8,4.36,81.6,0.171,1.000,0.140,1.000,1.406
16,Igor Thiago Nascimento Rodrigues,a,1,FWD,Brentford,1058.7,4.34,84.5,0.381,1.000,0.079,1.000,1.754
17,Sven Botman,a,0,DEF,Newcastle,1076.3,4.31,85.8,0.048,1.000,0.089,2.182,1.585
18,Luka Vušković,a,1,DEF,Brighton,1160.0,4.28,86.3,0.078,1.000,0.084,1.000,1.489
19,Mamadou Sangaré,a,0,MID,Brentford,1058.7,4.25,73.6,0.132,1.000,0.134,1.000,1.460
20,Alex Iwobi,a,0,MID,Fulham,1119.1,4.25,73.6,0.246,1.493,0.172,1.000,1.399
21,Trai Hume,a,0,DEF,Sunderland,1031.9,4.21,77.4,0.108,1.000,0.091,1.000,1.389
22,Enzo Fernández,a,0,MID,Man City,1083.0,4.20,72.1,0.202,1.000,0.196,1.000,1.155
23,Issa Diop,a,0,DEF,Ipswich Town,1038.5,4.19,87.0,0.053,1.000,0.031,1.000,1.364
24,Tyrone Mings,a,0,DEF,Aston Villa,1050.1,4.18,79.2,0.048,1.000,0.036,1.000,1.306
25,Micky van de Ven,a,0,DEF,Spurs,1019.7,4.18,84.1,0.080,1.404,0.030,1.000,1.269
26,Abdukodir Khusanov,a,0,DEF,Man City,1083.0,4.17,72.3,0.043,1.000,0.048,1.000,1.189
27,Adam Smith,a,0,DEF,Bournemouth,1029.5,4.15,77.1,0.060,1.000,0.083,1.523,1.307
28,Harry Maguire,a,0,DEF,Man Utd,1102.0,4.15,86.9,0.056,1.000,0.128,2.650,1.399
29,Victor Lindelöf,a,0,DEF,Aston Villa,1050.1,4.15,87.2,0.072,1.000,0.027,1.000,1.344
30,Taylor Harwood-Bellis,a,0,DEF,Aston Villa,1050.1,4.14,65.1,0.142,1.000,0.033,1.000,1.486
31,James Justin,a,1,DEF,Leeds,1067.8,4.11,78.1,0.054,1.000,0.050,1.000,1.459
32,Daichi Kamada,a,0,MID,Crystal Palace,1039.9,4.11,84.8,0.121,1.000,0.112,1.000,1.304
33,Chris Richards,a,0,DEF,Crystal Palace,1039.9,4.09,85.4,0.042,1.000,0.038,1.000,1.369
34,Mohammed Kudus,a,0,MID,Spurs,1019.7,4.09,73.5,0.136,1.000,0.289,1.874,1.243
35,Jaouen Hadjam,a,0,DEF,Brighton,1160.0,4.09,38.6,0.166,1.000,0.087,1.000,0.554
36,James Wright,a,0,GK,Aston Villa,1050.1,4.08,89.8,NaN,1.000,NaN,1.000,1.123
37,Pedro Lomba Neto,a,0,MID,Chelsea,1067.7,4.08,81.9,0.173,1.000,0.159,1.000,1.326
38,Marco Bizot,a,0,GK,Aston Villa,1050.1,4.06,89.4,NaN,1.000,NaN,1.000,1.153
39,Harry Amass,a,0,DEF,Man Utd,1102.0,4.06,63.1,0.221,1.000,0.136,1.000,1.758
40,Cody Gakpo,a,1,MID,Liverpool,1160.9,4.06,71.8,0.242,1.000,0.216,1.346,1.302
41,John McGinn,a,0,MID,Aston Villa,1050.1,4.02,74.6,0.183,1.000,0.201,1.390,1.231
42,Dan Bentley,a,0,GK,Coventry City,1028.2,4.01,90.0,NaN,1.000,NaN,1.000,1.439
43,Tyrick Mitchell,a,0,DEF,Crystal Palace,1039.9,4.01,84.0,0.053,1.000,0.091,1.413,1.339
44,Jaydee Canvot,a,0,DEF,Crystal Palace,1039.9,4.01,87.0,0.042,1.000,0.032,1.000,1.395
45,Kristoffer Ajer,a,0,DEF,Brentford,1058.7,4.01,85.5,0.053,1.000,0.042,1.000,1.418
46,Ben Wilson,a,0,GK,Coventry City,1028.2,4.01,90.0,NaN,1.000,NaN,1.000,1.435
47,Fabian Schär,a,0,DEF,Newcastle,1076.3,4.00,65.8,0.133,1.000,0.035,1.000,1.654
48,Alexis Mac Allister,a,0,MID,Liverpool,1160.9,4.00,77.9,0.146,1.000,0.140,1.000,1.264
49,Michael Kayode,a,0,DEF,Brentford,1058.7,3.99,83.1,0.055,1.000,0.072,1.000,1.402

In [13]:
print(f"Best players to pick for the rest of the season: GW{current_gw+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    -- AND position IN ('DEF')
    -- AND team_name = 'Liverpool'
  AND event BETWEEN {current_gw+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW9 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Erling Haaland,a,1,FWD,Man City,1066.1,187.33,79.7,1.176,0.761,2.831,0.236,1.201
1,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1079.4,157.92,84.2,1.000,0.279,1.880,0.328,1.373
2,Mats Wieffer,d,0,DEF,Brighton,1070.2,150.90,60.4,1.000,0.223,2.266,0.472,1.584
3,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1067.0,145.57,84.4,1.000,0.270,1.000,0.142,1.281
4,Riccardo Calafiori,d,1,DEF,Arsenal,1068.4,143.77,72.1,1.000,0.100,1.683,0.179,1.037
5,Marcus Tavernier,a,1,MID,Bournemouth,1067.0,143.22,77.0,1.000,0.262,1.279,0.251,1.305
6,James Hill,a,0,DEF,Bournemouth,1067.0,142.49,86.5,1.000,0.038,1.000,0.053,1.357
7,Jack Rudoni,a,0,MID,Coventry City,1076.7,140.96,83.7,1.000,0.233,1.000,0.165,1.452
8,Phil Foden,a,0,MID,Man City,1066.1,138.63,60.6,1.601,0.478,1.000,0.214,1.016
9,Matheus Nunes,d,1,DEF,Man City,1066.1,137.54,77.5,1.000,0.037,2.564,0.213,1.131
10,Luka Vušković,a,1,DEF,Brighton,1070.2,137.52,86.1,1.000,0.079,1.000,0.085,1.395
11,Matthijs de Ligt,a,0,DEF,Man Utd,1077.3,134.15,68.2,1.000,0.149,1.000,0.270,1.616
12,Oscar Bobb,a,0,MID,Fulham,1085.4,132.31,72.4,1.000,0.305,1.000,0.146,1.353
13,António João Pereira de Albuquerque Tavares da...,a,0,DEF,Bournemouth,1067.0,131.39,83.9,1.000,0.059,1.000,0.071,1.410
14,Harvey Barnes,a,1,MID,Newcastle,1082.5,131.23,82.3,1.176,0.241,1.000,0.146,1.458
15,Anton Stach,d,0,MID,Leeds,1075.5,130.86,81.6,1.000,0.171,1.000,0.140,1.372
16,Igor Thiago Nascimento Rodrigues,a,1,FWD,Brentford,1077.6,130.72,84.5,1.000,0.385,1.000,0.080,1.698
17,Enzo Fernández,a,0,MID,Man City,1066.1,129.56,73.3,1.000,0.208,1.000,0.215,1.090
18,Sven Botman,a,0,DEF,Newcastle,1082.5,129.26,86.0,1.000,0.047,2.182,0.091,1.511
19,Harry Maguire,a,0,DEF,Man Utd,1077.3,129.00,86.9,1.000,0.056,2.650,0.131,1.363
20,Adrien Truffert,a,0,DEF,Bournemouth,1067.0,128.60,84.5,1.000,0.042,1.497,0.180,1.355
21,Alex Iwobi,a,0,MID,Fulham,1085.4,128.07,73.6,1.493,0.246,1.000,0.174,1.336
22,Mamadou Sangaré,a,0,MID,Brentford,1077.6,127.48,73.7,1.000,0.135,1.000,0.143,1.370
23,Abdukodir Khusanov,a,0,DEF,Man City,1066.1,126.95,72.1,1.000,0.042,1.000,0.049,1.131
24,Harry Amass,a,0,DEF,Man Utd,1077.3,126.81,62.9,1.000,0.221,1.000,0.138,1.714
25,Cody Gakpo,a,1,MID,Liverpool,1067.8,126.15,72.0,1.000,0.242,1.346,0.217,1.297
26,Diego Coppola,a,0,DEF,Brighton,1070.2,124.49,61.9,1.000,0.181,1.000,0.149,1.687
27,Alexis Mac Allister,a,0,MID,Liverpool,1067.8,124.32,78.3,1.000,0.146,1.000,0.141,1.272
28,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1079.4,122.95,86.5,1.000,0.057,1.000,0.047,1.413
29,Tyrone Mings,a,0,DEF,Aston Villa,1065.7,122.63,79.2,1.000,0.048,1.000,0.036,1.347
30,Victor Lindelöf,a,0,DEF,Aston Villa,1065.7,122.45,87.2,1.000,0.071,1.000,0.026,1.386
31,James Justin,a,1,DEF,Leeds,1075.5,122.34,78.2,1.000,0.055,1.000,0.051,1.389
32,Pedro Lomba Neto,a,0,MID,Chelsea,1073.9,121.83,81.9,1.000,0.170,1.000,0.152,1.402
33,Issa Diop,a,0,DEF,Ipswich Town,1078.1,121.70,86.9,1.000,0.052,1.000,0.030,1.441
34,Taylor Harwood-Bellis,a,0,DEF,Aston Villa,1065.7,121.66,65.3,1.000,0.144,1.000,0.034,1.564
35,Rico Lewis,a,0,DEF,Man City,1066.1,121.43,63.3,1.000,0.054,1.000,0.091,1.236
36,Timothy Castagne,a,0,DEF,Fulham,1085.4,121.23,78.7,1.000,0.058,1.580,0.093,1.434
37,Kristoffer Ajer,a,0,DEF,Brentford,1077.6,121.18,85.6,1.000,0.054,1.000,0.044,1.351
38,Antonee Robinson,a,0,DEF,Fulham,1085.4,120.92,85.5,1.000,0.056,1.568,0.157,1.474
39,Trai Hume,a,0,DEF,Sunderland,1069.2,120.54,77.3,1.000,0.109,1.000,0.091,1.430
40,Daichi Kamada,a,0,MID,Crystal Palace,1081.0,120.33,84.8,1.000,0.120,1.000,0.103,1.460
41,John McGinn,a,0,MID,Aston Villa,1065.7,120.12,74.5,1.000,0.181,1.390,0.199,1.297
42,Noni Madueke,a,0,MID,Arsenal,1068.4,119.96,71.7,1.000,0.174,1.000,0.194,0.936
43,Adam Smith,a,0,DEF,Bournemouth,1067.0,119.68,77.0,1.000,0.059,1.523,0.082,1.323
44,Michael Kayode,a,0,DEF,Brentford,1077.6,119.06,83.2,1.000,0.056,1.000,0.075,1.353
45,Semi Ajayi,a,0,DEF,Hull City,1083.0,118.93,86.4,1.000,0.077,1.000,0.026,1.524
46,Jaouen Hadjam,a,0,DEF,Brighton,1070.2,118.86,38.0,1.000,0.169,1.000,0.087,0.555
47,Mohammed Kudus,a,0,MID,Spurs,1084.6,118.80,73.4,1.000,0.136,1.874,0.268,1.353
48,James Garner,a,0,MID,Everton,1078.1,118.60,84.7,1.000,0.062,1.000,0.097,1.363
49,Boubacar Kamara,a,0,MID,Aston Villa,1065.7,118.46,84.5,1.000,0.047,1.000,0.064,1.292

In [14]:
# print(f"Best available players to pick for the next 5 gameweeks: GW{current_gw+1} AND {current_gw+5}")
# view = db_creator.run_sql(f"""
# WITH predictions_status AS (
#     SELECT 
#         p.player_name_id,
#         p.element,
#         ps.status,
#         p.latest_my_team,
#         p.position,
#         p.team_name,
#         p.opp_team_elo,
#         p.xpoints,
#         p.mins_pred,
#         p.xgp90_pred,
#         p.xg_overperf_factor,
#         p.xap90_pred,
#         p.xa_overperf_factor,
#         p.xgcp90_pred,
#         p.event,
#         p.latest_any_team
#     FROM predictions p
#     LEFT JOIN player_status ps ON p.element = ps.id
# )  
# SELECT
#         player_name_id,
#         status,
#         latest_my_team,
#         position,
#         team_name,
#         ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
#         ROUND(SUM(xpoints),2) AS total_xpoints,
#         ROUND(AVG(mins_pred),1) AS avg_mins_pred,
#         ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
#         ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
#         ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
#         ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
#         ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
#     FROM predictions_status
#     WHERE (latest_any_team = 0 OR latest_my_team = 1)
#       AND event BETWEEN {current_gw+1} AND {current_gw+5}
#       AND status IN ('a','d')
#         --AND position = 'FWD'
#       -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
#     GROUP BY player_name_id, status, position, team_name, latest_my_team
#     ORDER BY total_xpoints DESC
# """)
# view.head(50)

In [15]:
print(f"\nBest available players to replace worst in my team: {current_gw+1} to {current_gw+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 9 to 13

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Brighton,d,Mats Wieffer,24.733634,Anan Khalaili,19.348812,5.384822
1,MID,Bournemouth,a,Rayan Vitor Simplício Rocha,24.334643,Granit Xhaka,19.301312,5.033331
2,DEF,Bournemouth,a,James Hill,24.069623,Anan Khalaili,19.348812,4.720811
3,MID,Coventry City,a,Jack Rudoni,23.990092,Granit Xhaka,19.301312,4.688779
4,MID,Man City,a,Phil Foden,22.559382,Granit Xhaka,19.301312,3.258070
5,DEF,Man Utd,a,Matthijs de Ligt,22.335082,Anan Khalaili,19.348812,2.986270
6,DEF,Bournemouth,a,António João Pereira de Albuquerque Tavares da...,22.316275,Anan Khalaili,19.348812,2.967463
7,GK,Aston Villa,a,James Wright,20.448782,Alisson Becker,17.807019,2.641763
8,MID,Fulham,a,Oscar Bobb,21.898499,Granit Xhaka,19.301312,2.597187
9,GK,Aston Villa,a,Marco Bizot,20.306504,Alisson Becker,17.807019,2.499485
10,MID,Leeds,d,Anton Stach,21.750449,Granit Xhaka,19.301312,2.449137
11,DEF,Bournemouth,a,Adrien Truffert,21.790031,Anan Khalaili,19.348812,2.441219
12,MID,Fulham,a,Alex Iwobi,21.193063,Granit Xhaka,19.301312,1.891751
13,GK,Liverpool,a,Giorgi Mamardashvili,19.632409,Alisson Becker,17.807019,1.825391
14,GK,Liverpool,a,Harvey Davies,19.623744,Alisson Becker,17.807019,1.816725
15,GK,Chelsea,a,Teddy Sharman-Lowe,19.584939,Alisson Becker,17.807019,1.777920
16,MID,Brentford,a,Mamadou Sangaré,20.924465,Granit Xhaka,19.301312,1.623153
17,DEF,Ipswich Town,a,Issa Diop,20.940872,Anan Khalaili,19.348812,1.592061
18,DEF,Spurs,a,Micky van de Ven,20.936636,Anan Khalaili,19.348812,1.587824
19,MID,Man City,a,Enzo Fernández,20.836277,Granit Xhaka,19.301312,1.534965

In [16]:
player_name = 'Erling Haaland'
print(f"\n {player_name} xPoints between {current_gw+1} and {current_gw+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
        AND player_name_id = '{player_name}'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Erling Haaland xPoints between 9 and 13:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,9.0,FWD,Man City,Brighton,15.7,1106.038000,5.768060,79.712302,0.647801,0.216608,1.244068
1,Erling Haaland,10.0,FWD,Man City,Nott'm Forest,15.7,1019.749815,6.593870,79.906739,0.851183,0.241784,1.135889
2,Erling Haaland,11.0,FWD,Man City,Fulham,15.7,1034.071518,6.451987,79.906739,0.821308,0.227209,1.145473
3,Erling Haaland,12.0,FWD,Man City,Arsenal,15.7,1272.232293,5.327281,77.710761,0.548770,0.216053,1.499004
4,Erling Haaland,13.0,FWD,Man City,Leeds,15.7,1037.394609,6.347676,79.890752,0.798805,0.222771,1.211026

# Chip Decisions

### Triple Captain

In [17]:
print("When to use TRIPLE CAPTAIN chip (gws1-18)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {current_gw} AND 18
    ORDER BY xpoints DESC
""")
view.head(10)

When to use TRIPLE CAPTAIN chip (gws1-18)

       player_name_id  event position      team_name  opp_team_name   xpoints
0      Erling Haaland   16.0      FWD       Man City      Hull City  6.636854
1      Erling Haaland   10.0      FWD       Man City  Nott'm Forest  6.593870
2      Erling Haaland   11.0      FWD       Man City         Fulham  6.451987
3      Erling Haaland   18.0      FWD       Man City        Everton  6.402681
4      Erling Haaland   13.0      FWD       Man City          Leeds  6.347676
5      Erling Haaland   17.0      FWD       Man City      Newcastle  6.335990
6      Erling Haaland   15.0      FWD       Man City        Chelsea  6.112950
7      Erling Haaland   14.0      FWD       Man City      Brentford  6.087219
8      Erling Haaland    9.0      FWD       Man City       Brighton  5.768060
9  Morgan Gibbs-White   15.0      MID  Nott'm Forest     Sunderland  5.460332

### Bench Boost

In [18]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(current_gw+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=999.9,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW9 to GW38...

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 50.33
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.18
 ✅        Martinez                       Chelsea      £5.0     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Justin                         Leeds        £4.5     4.02
 ✅        Khalaili                       Crystal Palace £5.0     4.02
 ✅        Vuskovic                       Brighton     £5.1     4.06
 ✅        Matheus N.                     Man City     £5.9     4.18
 ✅        Calafiori                      Arsenal      £6.0     4.35

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gakpo                          Liverpool    £7.1     3.83
 ✅        Xhaka                          Sunderland   £5.4     4.05
 ✅        Barnes                         Newcastle    £6.1     4.44
 ✅        Tavernier                      Bournemouth  £6.3     4.74
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.23

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.35
 ✅        Haaland                        Man City     £15.7    5.77
 ✅        Thiago                         Brentford    £7.8     4.35

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 53.55
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.70
 ✅        Martinez                       Chelsea      £5.0     3.90

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.36
 ✅        Justin                         Leeds        £4.5     4.37
 ✅        Vuskovic                       Brighton     £5.1     4.39
 ✅        Matheus N.                     Man City     £5.9     4.73
 ✅        Calafiori                      Arsenal      £6.0     5.14

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.77
 ✅        Gakpo                          Liverpool    £7.1     4.40
 ✅        Barnes                         Newcastle    £6.1     4.41
 ✅        Tavernier                      Bournemouth  £6.3     5.07
 ✅        Gibbs-White                    Nott'm Forest £7.9     4.85

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.27
 ✅        Haaland                        Man City     £15.7    6.59
 ✅        Thiago                         Brentford    £7.8     4.28

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-3-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 53.09
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.54
 ✅        Martinez                       Chelsea      £5.0     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Khalaili                       Crystal Palace £5.0     4.15
 ✅        Justin                         Leeds        £4.5     4.14
 ✅        Vuskovic                       Brighton     £5.1     4.92
 ✅        Matheus N.                     Man City     £5.9     4.85
 ✅        Calafiori                      Arsenal      £6.0     4.88

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.76
 🪑        Barnes                         Newcastle    £6.1     4.03
 ✅        Gakpo                          Liverpool    £7.1     4.15
 ✅        Tavernier                      Bournemouth  £6.3     4.81
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.20

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.34
 ✅        Haaland                        Man City     £15.7    6.45
 ✅        Thiago                         Brentford    £7.8     4.39

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 50.07
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.65
 ✅        Martinez                       Chelsea      £5.0     3.74

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus N.                     Man City     £5.9     3.77
 🪑        Calafiori                      Arsenal      £6.0     3.93
 ✅        Khalaili                       Crystal Palace £5.0     4.01
 ✅        Justin                         Leeds        £4.5     4.34
 ✅        Vuskovic                       Brighton     £5.1     4.44

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.22
 ✅        Xhaka                          Sunderland   £5.4     3.95
 ✅        Barnes                         Newcastle    £6.1     4.20
 ✅        Tavernier                      Bournemouth  £6.3     4.76
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.32

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.30
 ✅        Haaland                        Man City     £15.7    5.33
 ✅        Thiago                         Brentford    £7.8     4.30

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 51.90
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        A.Becker                       Liverpool    £5.5     3.74
 ✅        Martinez                       Chelsea      £5.0     3.77

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Justin                         Leeds        £4.5     3.09
 ✅        Khalaili                       Crystal Palace £5.0     3.80
 ✅        Vuskovic                       Brighton     £5.1     4.18
 ✅        Matheus N.                     Man City     £5.9     4.63
 ✅        Calafiori                      Arsenal      £6.0     4.73

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.77
 ✅        Gakpo                          Liverpool    £7.1     4.33
 ✅        Barnes                         Newcastle    £6.1     4.36
 ✅        Tavernier                      Bournemouth  £6.3     4.51
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.46

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.34
 ✅        Haaland                        Man City     £15.7    6.35
 ✅        Thiago                         Brentford    £7.8     4.40

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 52.57
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.46
 ✅        A.Becker                       Liverpool    £5.5     3.55

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.66
 ✅        Justin                         Leeds        £4.5     4.35
 ✅        Vuskovic                       Brighton     £5.1     4.71
 ✅        Matheus N.                     Man City     £5.9     4.37
 ✅        Calafiori                      Arsenal      £6.0     5.13

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Xhaka                          Sunderland   £5.4     3.78
 ✅        Gakpo                          Liverpool    £7.1     4.16
 ✅        Barnes                         Newcastle    £6.1     4.56
 ✅        Tavernier                      Bournemouth  £6.3     4.91
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.01

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.32
 ✅        Haaland                        Man City     £15.7    6.09
 ✅        Thiago                         Brentford    £7.8     4.30

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW15...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 52.00
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.09
 ✅        A.Becker                       Liverpool    £5.5     3.54

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Khalaili                       Crystal Palace £5.0     3.75
 🪑        Justin                         Leeds        £4.5     3.82
 ✅        Vuskovic                       Brighton     £5.1     4.86
 ✅        Matheus N.                     Man City     £5.9     4.57
 ✅        Calafiori                      Arsenal      £6.0     4.63

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gakpo                          Liverpool    £7.1     4.17
 ✅        Xhaka                          Sunderland   £5.4     3.90
 ✅        Barnes                         Newcastle    £6.1     4.66
 ✅        Tavernier                      Bournemouth  £6.3     4.33
 ✅        Gibbs-White                    Nott'm Forest £7.9     5.46

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emersonn                       Ipswich Town £5.5     3.35
 ✅        Haaland                        Man City     £15.7    6.11
 ✅        Thiago                         Brentford    £7.8     4.36

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW16...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £999.9m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £98.8m / £999.9m
Total Weighted Expected Points: 53.95
Remaining Budget: £901.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Chelsea      £5.0     3.61
 ✅        A.Becker                       Liverpool    £5.5     3.70

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts

In [19]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

    event  bench_boost_gain
7      16         13.443180
18     27         13.443180
13     22         13.437692
22     31         13.352570
21     30         13.251608
3      12         13.191852
14     23         13.191852
2      11         13.191165
10     19         13.099560
16     25         13.099560
28     37         13.018517
0       9         12.930691
17     26         12.890335
29     38         12.817839
25     34         12.801262
5      14         12.801262
20     29         12.701441
9      18         12.692904
1      10         12.691852
12     21         12.691852
15     24         12.687156
6      15         12.603751
24     33         12.603751
4      13         12.546588
11     20         12.546588
27     36         12.488329
8      17         12.296494
26     35         12.222326
23     32         12.197109
19     28         11.994550

In [20]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.1 minute(s)