In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 35
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        -- AND latest_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 36
Squad Points: 104.01

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Bernardo,a,100.0,36.0,MID,Man City,Crystal Palace; Brentford,15.336449,137.0
1,Matheus N.,a,100.0,36.0,DEF,Man City,Crystal Palace; Brentford,9.831155,144.0
2,Khusanov,a,100.0,36.0,DEF,Man City,Crystal Palace; Brentford,8.376191,149.0
3,Gabriel,a,100.0,36.0,DEF,Arsenal,West Ham,6.709742,86.0
4,Richards,a,100.0,36.0,DEF,Crystal Palace,Man City; Everton,6.408291,154.0
5,B.Fernandes,a,100.0,36.0,MID,Man Utd,Sunderland,4.998102,84.0
6,Raya,a,NaN,36.0,GK,Arsenal,West Ham,4.919990,89.0
7,Gibbs-White,a,100.0,36.0,MID,Nott'm Forest,Newcastle,4.693254,69.0
8,Martinez,a,100.0,36.0,GK,Aston Villa,Burnley,4.449407,90.0
9,Szoboszlai,a,100.0,36.0,MID,Liverpool,Chelsea,4.397152,86.0
10,Van Hecke,a,100.0,36.0,DEF,Brighton,Wolves,4.227628,86.0
11,Bruno G.,a,100.0,36.0,MID,Newcastle,Nott'm Forest,3.990595,69.0
12,Flemming,a,100.0,36.0,FWD,Burnley,Aston Villa,3.586804,67.0
13,Isak,d,100.0,36.0,FWD,Liverpool,Chelsea,3.376486,67.0
14,Brobbey,a,100.0,36.0,FWD,Sunderland,Man Utd,3.369668,69.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW36 AND 40

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Brian Brobbey,1,FWD,Sunderland,1086.4,10.19,68.5,0.321,1.000,0.047,1.000,1.377
1,Alexander Isak,1,FWD,Liverpool,1085.4,10.19,66.4,0.323,1.000,0.072,1.597,1.268
2,Zian Flemming,1,FWD,Burnley,1092.2,10.73,66.2,0.421,1.000,0.039,1.000,1.787
3,Emiliano Martínez Romero,1,GK,Aston Villa,1091.2,11.39,89.9,NaN,1.000,NaN,1.000,1.372
4,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1033.7,12.06,69.0,0.205,1.000,0.134,1.000,1.230
5,Jan Paul van Hecke,1,DEF,Brighton,1022.2,12.12,86.3,0.042,1.000,0.035,1.000,1.234
6,Chris Richards,1,DEF,Crystal Palace,1155.6,12.39,97.9,0.042,1.000,0.028,1.000,1.602
7,Dominik Szoboszlai,1,MID,Liverpool,1085.4,13.12,86.1,0.176,1.000,0.140,1.000,1.497
8,Morgan Gibbs-White,1,MID,Nott'm Forest,1097.4,14.14,69.5,0.290,1.000,0.296,2.018,1.452
9,David Raya Martín,1,GK,Arsenal,969.6,14.22,88.5,NaN,1.000,NaN,1.000,0.590
10,Bruno Borges Fernandes,1,MID,Man Utd,1056.2,14.77,83.8,0.226,1.000,0.240,1.333,1.330
11,Abdukodir Khusanov,1,DEF,Man City,1088.5,16.58,95.1,0.047,1.000,0.056,1.000,1.089
12,Matheus Nunes,1,DEF,Man City,1088.5,18.60,87.6,0.049,1.000,0.312,2.810,1.038
13,Gabriel dos Santos Magalhães,1,DEF,Arsenal,969.6,19.46,86.3,0.153,1.000,0.078,1.000,0.532
14,Bernardo Mota Veiga de Carvalho e Silva,1,MID,Man City,1088.5,28.41,83.1,0.685,4.687,0.879,4.522,1.064

In [7]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    --AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW36 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1088.5,28.41,83.1,4.687,0.685,4.522,0.879,1.064
1,Reece James,d,0,DEF,Chelsea,1055.6,23.34,60.8,4.135,0.740,2.957,0.940,1.490
2,John Stones,a,0,DEF,Man City,1088.5,21.63,71.8,3.577,0.608,1.000,0.036,1.269
3,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,969.6,19.46,86.3,1.000,0.153,1.000,0.078,0.532
4,Matheus Nunes,a,1,DEF,Man City,1088.5,18.60,87.6,1.000,0.049,2.810,0.312,1.038
5,Vitaly Janelt,a,0,MID,Brentford,1149.5,17.62,60.0,1.947,0.941,1.000,0.094,1.675
6,Abdukodir Khusanov,a,1,DEF,Man City,1088.5,16.58,95.1,1.000,0.047,1.000,0.056,1.089
7,Benjamin White,a,0,DEF,Arsenal,969.6,16.51,78.2,1.000,0.056,1.000,0.082,0.601
8,Max Alleyne,a,0,DEF,Man City,1088.5,16.51,79.8,1.000,0.168,1.000,0.038,1.175
9,Rayan Aït-Nouri,a,0,DEF,Man City,1088.5,15.92,73.7,1.000,0.049,1.000,0.073,0.939
10,Youri Tielemans,a,0,MID,Aston Villa,1091.2,15.48,75.7,2.719,0.342,2.297,0.301,1.683
11,Rico Lewis,a,0,DEF,Man City,1088.5,15.38,71.9,1.000,0.180,1.000,0.077,1.270
12,Granit Xhaka,a,0,MID,Sunderland,1086.4,15.21,83.8,2.248,0.246,2.970,0.325,1.691
13,Omar Marmoush,a,0,MID,Man City,1088.5,14.89,63.9,1.000,0.364,1.000,0.104,1.062
14,Eberechi Eze,a,0,MID,Arsenal,969.6,14.87,63.4,1.368,0.328,1.964,0.321,0.607
15,Bruno Borges Fernandes,a,1,MID,Man Utd,1056.2,14.77,83.8,1.000,0.226,1.333,0.240,1.330
16,Conor Gallagher,a,0,MID,Spurs,1048.2,14.55,76.6,2.628,0.272,3.286,0.266,1.349
17,Mathias Jensen,a,0,MID,Brentford,1149.5,14.25,83.6,2.057,0.267,1.000,0.133,1.453
18,Brennan Johnson,a,0,MID,Crystal Palace,1155.6,14.25,77.7,1.000,0.176,2.452,0.256,1.653
19,David Raya Martín,a,1,GK,Arsenal,969.6,14.22,88.5,1.000,NaN,1.000,NaN,0.590
20,Evann Guessand,d,0,MID,Crystal Palace,1155.6,14.18,72.1,1.000,0.310,1.000,0.097,1.718
21,James Trafford,a,0,GK,Man City,1088.5,14.15,115.6,1.000,NaN,1.000,NaN,1.556
22,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1097.4,14.14,69.5,1.000,0.290,2.018,0.296,1.452
23,Walter Benítez,a,0,GK,Crystal Palace,1155.6,14.06,111.9,1.000,NaN,1.000,NaN,1.670
24,James Ward-Prowse,a,0,MID,Burnley,1092.2,14.04,72.0,2.520,0.348,1.773,0.200,2.047
25,Leandro Trossard,a,0,MID,Arsenal,969.6,14.01,49.0,1.973,0.447,2.490,0.404,0.643
26,Myles Lewis-Skelly,a,0,DEF,Arsenal,969.6,13.87,59.0,1.000,0.040,1.000,0.042,0.706
27,Jérémy Doku,a,0,MID,Man City,1088.5,13.84,69.9,1.000,0.148,1.000,0.215,1.087
28,Jaydee Canvot,a,0,DEF,Crystal Palace,1155.6,13.83,113.6,1.000,0.038,1.000,0.029,1.490
29,Jack Hinshelwood,a,0,MID,Brighton,1022.2,13.45,81.8,1.000,0.191,1.832,0.166,1.220
30,Riccardo Calafiori,a,0,DEF,Arsenal,969.6,13.35,49.3,1.000,0.133,1.000,0.084,0.827
31,Nathan Aké,a,0,DEF,Man City,1088.5,13.23,37.6,1.000,0.076,1.000,0.046,1.086
32,Cristhian Mosquera,a,0,DEF,Arsenal,969.6,13.14,50.8,1.000,0.039,1.000,0.042,0.692
33,Marcus Tavernier,a,0,MID,Bournemouth,1115.2,13.13,84.2,1.000,0.180,1.483,0.160,1.361
34,Dominik Szoboszlai,a,1,MID,Liverpool,1085.4,13.12,86.1,1.000,0.176,1.000,0.140,1.497
35,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1088.5,13.10,76.8,1.000,0.090,1.000,0.068,1.071
36,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1155.6,13.07,82.8,1.000,0.121,1.000,0.132,1.605
37,Dwight McNeil,a,0,MID,Everton,1015.4,13.06,59.4,1.775,0.327,1.565,0.272,1.117
38,Adam Wharton,a,0,MID,Crystal Palace,1155.6,12.80,86.7,1.000,0.070,1.000,0.106,1.569
39,John McGinn,d,0,MID,Aston Villa,1091.2,12.58,73.0,1.000,0.157,2.026,0.257,1.490
40,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1115.2,12.57,72.7,1.000,0.239,1.000,0.104,1.392
41,Tijjani Reijnders,a,0,MID,Man City,1088.5,12.55,48.2,1.000,0.331,1.000,0.090,1.073
42,Kevin Schade,a,0,MID,Brentford,1149.5,12.55,76.2,1.000,0.210,2.066,0.147,1.443
43,Martin Ødegaard,d,0,MID,Arsenal,969.6,12.50,70.3,1.000,0.126,1.000,0.182,0.645
44,Emile Smith Rowe,a,0,MID,Fulham,1028.6,12.50,64.1,1.773,0.219,3.417,0.268,1.245
45,Timothy Castagne,a,0,DEF,Fulham,1028.6,12.46,85.9,1.000,0.038,2.758,0.139,1.305
46,Nathaniel Clyne,a,0,DEF,Crystal Palace,1155.6,12.46,86.6,1.000,0.152,1.000,0.032,1.873
47,Lisandro Martínez,a,0,DEF,Man Utd,1056.2,12.44,63.9,1.000,0.255,1.000,0.090,1.564
48,Enzo Fernández,a,0,MID,Chelsea,1055.6,12.43,84.5,1.000,0.126,1.000,0.152,1.387
49,James Justin,a,0,DEF,Leeds,1023.9,12.40,86.7,1.000,0.034,1.000,0.049,1.168

In [8]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW36 AND 40

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1088.5,28.41,83.1,0.685,4.687,0.879,4.522,1.064
1,Reece James,d,0,DEF,Chelsea,1055.6,23.34,60.8,0.740,4.135,0.940,2.957,1.490
2,John Stones,a,0,DEF,Man City,1088.5,21.63,71.8,0.608,3.577,0.036,1.000,1.269
3,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,969.6,19.46,86.3,0.153,1.000,0.078,1.000,0.532
4,Matheus Nunes,a,1,DEF,Man City,1088.5,18.60,87.6,0.049,1.000,0.312,2.810,1.038
5,Vitaly Janelt,a,0,MID,Brentford,1149.5,17.62,60.0,0.941,1.947,0.094,1.000,1.675
6,Abdukodir Khusanov,a,1,DEF,Man City,1088.5,16.58,95.1,0.047,1.000,0.056,1.000,1.089
7,Benjamin White,a,0,DEF,Arsenal,969.6,16.51,78.2,0.056,1.000,0.082,1.000,0.601
8,Max Alleyne,a,0,DEF,Man City,1088.5,16.51,79.8,0.168,1.000,0.038,1.000,1.175
9,Rayan Aït-Nouri,a,0,DEF,Man City,1088.5,15.92,73.7,0.049,1.000,0.073,1.000,0.939
10,Youri Tielemans,a,0,MID,Aston Villa,1091.2,15.48,75.7,0.342,2.719,0.301,2.297,1.683
11,Rico Lewis,a,0,DEF,Man City,1088.5,15.38,71.9,0.180,1.000,0.077,1.000,1.270
12,Granit Xhaka,a,0,MID,Sunderland,1086.4,15.21,83.8,0.246,2.248,0.325,2.970,1.691
13,Omar Marmoush,a,0,MID,Man City,1088.5,14.89,63.9,0.364,1.000,0.104,1.000,1.062
14,Eberechi Eze,a,0,MID,Arsenal,969.6,14.87,63.4,0.328,1.368,0.321,1.964,0.607
15,Bruno Borges Fernandes,a,1,MID,Man Utd,1056.2,14.77,83.8,0.226,1.000,0.240,1.333,1.330
16,Conor Gallagher,a,0,MID,Spurs,1048.2,14.55,76.6,0.272,2.628,0.266,3.286,1.349
17,Mathias Jensen,a,0,MID,Brentford,1149.5,14.25,83.6,0.267,2.057,0.133,1.000,1.453
18,Brennan Johnson,a,0,MID,Crystal Palace,1155.6,14.25,77.7,0.176,1.000,0.256,2.452,1.653
19,David Raya Martín,a,1,GK,Arsenal,969.6,14.22,88.5,NaN,1.000,NaN,1.000,0.590
20,Evann Guessand,d,0,MID,Crystal Palace,1155.6,14.18,72.1,0.310,1.000,0.097,1.000,1.718
21,James Trafford,a,0,GK,Man City,1088.5,14.15,115.6,NaN,1.000,NaN,1.000,1.556
22,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1097.4,14.14,69.5,0.290,1.000,0.296,2.018,1.452
23,Walter Benítez,a,0,GK,Crystal Palace,1155.6,14.06,111.9,NaN,1.000,NaN,1.000,1.670
24,James Ward-Prowse,a,0,MID,Burnley,1092.2,14.04,72.0,0.348,2.520,0.200,1.773,2.047
25,Leandro Trossard,a,0,MID,Arsenal,969.6,14.01,49.0,0.447,1.973,0.404,2.490,0.643
26,Myles Lewis-Skelly,a,0,DEF,Arsenal,969.6,13.87,59.0,0.040,1.000,0.042,1.000,0.706
27,Jérémy Doku,a,0,MID,Man City,1088.5,13.84,69.9,0.148,1.000,0.215,1.000,1.087
28,Jaydee Canvot,a,0,DEF,Crystal Palace,1155.6,13.83,113.6,0.038,1.000,0.029,1.000,1.490
29,Jack Hinshelwood,a,0,MID,Brighton,1022.2,13.45,81.8,0.191,1.000,0.166,1.832,1.220
30,Riccardo Calafiori,a,0,DEF,Arsenal,969.6,13.35,49.3,0.133,1.000,0.084,1.000,0.827
31,Nathan Aké,a,0,DEF,Man City,1088.5,13.23,37.6,0.076,1.000,0.046,1.000,1.086
32,Cristhian Mosquera,a,0,DEF,Arsenal,969.6,13.14,50.8,0.039,1.000,0.042,1.000,0.692
33,Marcus Tavernier,a,0,MID,Bournemouth,1115.2,13.13,84.2,0.180,1.000,0.160,1.483,1.361
34,Dominik Szoboszlai,a,1,MID,Liverpool,1085.4,13.12,86.1,0.176,1.000,0.140,1.000,1.497
35,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1088.5,13.10,76.8,0.090,1.000,0.068,1.000,1.071
36,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1155.6,13.07,82.8,0.121,1.000,0.132,1.000,1.605
37,Dwight McNeil,a,0,MID,Everton,1015.4,13.06,59.4,0.327,1.775,0.272,1.565,1.117
38,Adam Wharton,a,0,MID,Crystal Palace,1155.6,12.80,86.7,0.070,1.000,0.106,1.000,1.569
39,John McGinn,d,0,MID,Aston Villa,1091.2,12.58,73.0,0.157,1.000,0.257,2.026,1.490
40,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1115.2,12.57,72.7,0.239,1.000,0.104,1.000,1.392
41,Tijjani Reijnders,a,0,MID,Man City,1088.5,12.55,48.2,0.331,1.000,0.090,1.000,1.073
42,Kevin Schade,a,0,MID,Brentford,1149.5,12.55,76.2,0.210,1.000,0.147,2.066,1.443
43,Martin Ødegaard,d,0,MID,Arsenal,969.6,12.50,70.3,0.126,1.000,0.182,1.000,0.645
44,Emile Smith Rowe,a,0,MID,Fulham,1028.6,12.50,64.1,0.219,1.773,0.268,3.417,1.245
45,Timothy Castagne,a,0,DEF,Fulham,1028.6,12.46,85.9,0.038,1.000,0.139,2.758,1.305
46,Nathaniel Clyne,a,0,DEF,Crystal Palace,1155.6,12.46,86.6,0.152,1.000,0.032,1.000,1.873
47,Lisandro Martínez,a,0,DEF,Man Utd,1056.2,12.44,63.9,0.255,1.000,0.090,1.000,1.564
48,Enzo Fernández,a,0,MID,Chelsea,1055.6,12.43,84.5,0.126,1.000,0.152,1.000,1.387
49,James Justin,a,0,DEF,Leeds,1023.9,12.40,86.7,0.034,1.000,0.049,1.000,1.168

In [9]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 36 to 40

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Chelsea,d,Reece James,23.344892,Jan Paul van Hecke,12.116045,11.228847
1,DEF,Man City,a,John Stones,21.628238,Jan Paul van Hecke,12.116045,9.512193
2,MID,Brentford,a,Vitaly Janelt,17.615757,Bruno Guimarães Rodriguez Moura,12.061690,5.554068
3,DEF,Arsenal,a,Benjamin White,16.510229,Jan Paul van Hecke,12.116045,4.394185
4,DEF,Man City,a,Max Alleyne,16.507873,Jan Paul van Hecke,12.116045,4.391828
5,DEF,Man City,a,Rayan Aït-Nouri,15.920638,Jan Paul van Hecke,12.116045,3.804593
6,MID,Aston Villa,a,Youri Tielemans,15.482015,Bruno Guimarães Rodriguez Moura,12.061690,3.420325
7,DEF,Man City,a,Rico Lewis,15.380999,Jan Paul van Hecke,12.116045,3.264954
8,MID,Sunderland,a,Granit Xhaka,15.205605,Bruno Guimarães Rodriguez Moura,12.061690,3.143915
9,MID,Man City,a,Omar Marmoush,14.894985,Bruno Guimarães Rodriguez Moura,12.061690,2.833295
10,MID,Arsenal,a,Eberechi Eze,14.869178,Bruno Guimarães Rodriguez Moura,12.061690,2.807489
11,GK,Man City,a,James Trafford,14.146135,Emiliano Martínez Romero,11.388920,2.757215
12,GK,Crystal Palace,a,Walter Benítez,14.057720,Emiliano Martínez Romero,11.388920,2.668800
13,MID,Spurs,a,Conor Gallagher,14.551416,Bruno Guimarães Rodriguez Moura,12.061690,2.489726
14,MID,Crystal Palace,a,Brennan Johnson,14.251439,Bruno Guimarães Rodriguez Moura,12.061690,2.189750
15,MID,Brentford,a,Mathias Jensen,14.249503,Bruno Guimarães Rodriguez Moura,12.061690,2.187814
16,FWD,Newcastle,a,William Osula,12.354260,Brian Brobbey,10.185267,2.168994
17,MID,Crystal Palace,d,Evann Guessand,14.175633,Bruno Guimarães Rodriguez Moura,12.061690,2.113943
18,MID,Burnley,a,James Ward-Prowse,14.043169,Bruno Guimarães Rodriguez Moura,12.061690,1.981479
19,MID,Arsenal,a,Leandro Trossard,14.007688,Bruno Guimarães Rodriguez Moura,12.061690,1.945998

In [10]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 36 and 40:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,36.0,FWD,Man City,Crystal Palace; Brentford,14.6,1056.580966,10.019704,140.889428,0.668379,0.230339,1.021525
1,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.6,1099.093598,5.071399,63.466297,0.750593,0.295488,1.054685
2,Erling Haaland,38.0,FWD,Man City,Aston Villa,14.6,1109.774484,5.078915,63.466297,0.753258,0.295488,1.081523

In [11]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'DEF'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW36 to GW40
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,821.2,7.84,83.1,0.685,4.687,0.879,4.522,1.064
1,John Stones,a,0,DEF,Man City,821.2,5.88,71.8,0.608,3.577,0.036,1.000,1.269
2,Reece James,d,0,DEF,Chelsea,810.6,5.87,60.8,0.740,4.135,0.940,2.957,1.490
3,Matheus Nunes,a,1,DEF,Man City,821.2,5.12,87.6,0.049,1.000,0.312,2.810,1.038
4,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,733.1,4.97,86.3,0.153,1.000,0.078,1.000,0.532
5,Abdukodir Khusanov,a,1,DEF,Man City,821.2,4.51,95.1,0.047,1.000,0.056,1.000,1.089
6,Max Alleyne,a,0,DEF,Man City,821.2,4.50,79.8,0.168,1.000,0.038,1.000,1.175
7,Vitaly Janelt,a,0,MID,Brentford,878.5,4.45,60.0,0.941,1.947,0.094,1.000,1.675
8,Rayan Aït-Nouri,a,0,DEF,Man City,821.2,4.30,73.7,0.049,1.000,0.073,1.000,0.939
9,Benjamin White,a,0,DEF,Arsenal,733.1,4.22,78.2,0.056,1.000,0.082,1.000,0.601
10,Rico Lewis,a,0,DEF,Man City,821.2,4.19,71.9,0.180,1.000,0.077,1.000,1.270
11,Omar Marmoush,a,0,MID,Man City,821.2,4.02,63.9,0.364,1.000,0.104,1.000,1.062
12,Youri Tielemans,a,0,MID,Aston Villa,799.2,3.97,75.7,0.342,2.719,0.301,2.297,1.683
13,Brennan Johnson,a,0,MID,Crystal Palace,870.1,3.88,77.7,0.176,1.000,0.256,2.452,1.653
14,James Trafford,a,0,GK,Man City,821.2,3.87,115.6,NaN,1.000,NaN,1.000,1.556
15,Granit Xhaka,a,0,MID,Sunderland,827.7,3.84,83.8,0.246,2.248,0.325,2.970,1.691
16,Walter Benítez,a,0,GK,Crystal Palace,870.1,3.82,111.9,NaN,1.000,NaN,1.000,1.670
17,Evann Guessand,d,0,MID,Crystal Palace,870.1,3.82,72.1,0.310,1.000,0.097,1.000,1.718
18,Jérémy Doku,a,0,MID,Man City,821.2,3.78,69.9,0.148,1.000,0.215,1.000,1.087
19,Jaydee Canvot,a,0,DEF,Crystal Palace,870.1,3.78,113.6,0.038,1.000,0.029,1.000,1.490
20,Eberechi Eze,a,0,MID,Arsenal,733.1,3.76,63.4,0.328,1.368,0.321,1.964,0.607
21,Bruno Borges Fernandes,a,1,MID,Man Utd,796.0,3.74,83.8,0.226,1.000,0.240,1.333,1.330
22,Conor Gallagher,a,0,MID,Spurs,791.4,3.68,76.6,0.272,2.628,0.266,3.286,1.349
23,David Raya Martín,a,1,GK,Arsenal,733.1,3.63,88.5,NaN,1.000,NaN,1.000,0.590
24,Nathan Aké,a,0,DEF,Man City,821.2,3.60,37.6,0.076,1.000,0.046,1.000,1.086
25,Mathias Jensen,a,0,MID,Brentford,878.5,3.58,83.6,0.267,2.057,0.133,1.000,1.453
26,Jefferson Lerma Solís,a,0,MID,Crystal Palace,870.1,3.57,82.8,0.121,1.000,0.132,1.000,1.605
27,Morgan Gibbs-White,a,1,MID,Nott'm Forest,829.0,3.57,69.5,0.290,1.000,0.296,2.018,1.452
28,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,821.2,3.57,76.8,0.090,1.000,0.068,1.000,1.071
29,Leandro Trossard,a,0,MID,Arsenal,733.1,3.54,49.0,0.447,1.973,0.404,2.490,0.643
30,James Ward-Prowse,a,0,MID,Burnley,839.7,3.53,72.0,0.348,2.520,0.200,1.773,2.047
31,Myles Lewis-Skelly,a,0,DEF,Arsenal,733.1,3.52,59.0,0.040,1.000,0.042,1.000,0.706
32,Adam Wharton,a,0,MID,Crystal Palace,870.1,3.47,86.7,0.070,1.000,0.106,1.000,1.569
33,Riccardo Calafiori,a,0,DEF,Arsenal,733.1,3.41,49.3,0.133,1.000,0.084,1.000,0.827
34,Jack Hinshelwood,a,0,MID,Brighton,760.1,3.41,81.8,0.191,1.000,0.166,1.832,1.220
35,Nathaniel Clyne,a,0,DEF,Crystal Palace,870.1,3.41,86.6,0.152,1.000,0.032,1.000,1.873
36,Chris Richards,a,1,DEF,Crystal Palace,870.1,3.40,97.9,0.042,1.000,0.028,1.000,1.602
37,Tijjani Reijnders,a,0,MID,Man City,821.2,3.38,48.2,0.331,1.000,0.090,1.000,1.073
38,Cristhian Mosquera,a,0,DEF,Arsenal,733.1,3.35,50.8,0.039,1.000,0.042,1.000,0.692
39,Chadi Riad Dnanou,a,0,DEF,Crystal Palace,870.1,3.35,91.0,0.035,1.000,0.046,1.000,1.635
40,Dominik Szoboszlai,a,1,MID,Liverpool,822.7,3.32,86.1,0.176,1.000,0.140,1.000,1.497
41,Marcus Tavernier,a,0,MID,Bournemouth,844.0,3.32,84.2,0.180,1.000,0.160,1.483,1.361
42,Dwight McNeil,a,0,MID,Everton,774.1,3.29,59.4,0.327,1.775,0.272,1.565,1.117
43,Daichi Kamada,a,0,MID,Crystal Palace,870.1,3.24,87.5,0.047,1.000,0.047,1.000,1.634
44,John McGinn,d,0,MID,Aston Villa,799.2,3.24,73.0,0.157,1.000,0.257,2.026,1.490
45,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,844.0,3.18,72.7,0.239,1.000,0.104,1.000,1.392
46,Martin Ødegaard,d,0,MID,Arsenal,733.1,3.17,70.3,0.126,1.000,0.182,1.000,0.645
47,Justin Devenny,a,0,MID,Crystal Palace,870.1,3.17,74.7,0.118,1.000,0.052,1.000,1.613
48,Kevin Schade,a,0,MID,Brentford,878.5,3.16,76.2,0.210,1.000,0.147,2.066,1.443
49,Emile Smith Rowe,a,0,MID,Fulham,783.3,3.15,64.1,0.219,1.773,0.268,3.417,1.245

# Multi-week optimizer

In [12]:
from FPL_Optimizer import FPLOptimizer

In [13]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [14]:
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(picks_current_gameweek + 1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 75.00
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.45
 ✅        Raya                           Arsenal      £6.1     4.92

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     6.71
 ✅        Van Hecke                      Brighton     £4.6     4.23
 ✅        Richards                       Crystal Palace £4.4     6.41
 ✅        Khusanov                       Man City     £5.4     8.38
 ✅        Matheus N.                     Man City     £5.3     9.83

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.99
 ✅        Szoboszlai                     Liverpool    £7.0     4.40
 ✅        Bernardo                       Man City     £6.2    15.34
 ✅        B.Fernandes                    Man Utd      £10.4    5.00
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.69

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.38
 🪑        Brobbey                        Sunderland   £5.3     3.37
 ✅        Flemming                       Burnley      £5.3     3.59

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 54.07
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.65
 ✅        Raya                           Arsenal      £6.1     4.94

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     3.15
 ✅        Gabriel                        Arsenal      £7.2     6.89
 ✅        Van Hecke                      Brighton     £4.6     4.17
 ✅        Khusanov                       Man City     £5.4     4.06
 ✅        Matheus N.                     Man City     £5.3     4.52

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.33
 ✅        Bernardo                       Man City     £6.2     6.53
 ✅        B.Fernandes                    Man Utd      £10.4    4.93
 ✅        Bruno G.                       Newcastle    £6.8     4.08
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.70

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.44
 🪑        Brobbey                        Sunderland   £5.3     3.41
 ✅        Flemming                       Burnley      £5.3     3.55

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 51.72
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.29
 ✅        Raya                           Arsenal      £6.1     4.36

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     2.83
 ✅        Gabriel                        Arsenal      £7.2     5.87
 ✅        Van Hecke                      Brighton     £4.6     3.72
 ✅        Khusanov                       Man City     £5.4     4.14
 ✅        Matheus N.                     Man City     £5.3     4.25

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.40
 ✅        Bernardo                       Man City     £6.2     6.54
 ✅        B.Fernandes                    Man Utd      £10.4    4.84
 ✅        Bruno G.                       Newcastle    £6.8     3.99
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.74

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.38
 🪑        Brobbey                        Sunderland   £5.3     3.40
 ✅        Flemming                       Burnley      £5.3     3.59

================================================================================
Optimization Status: Optimal

Optimization complete. Final DataFrame created.

event     web_name position  36  37  38
5          Gabriel      DEF   1   1   1
8         Khusanov      DEF   1   1   1
10      Matheus N.      DEF   1   1   1
12        Richards      DEF   1   0   0
14       Van Hecke      DEF   1   1   1
2          Brobbey      FWD   0   0   0
4         Flemming      FWD   1   1   1
7             Isak      FWD   0   0   0
9         Martinez       GK   0   0   0
11            Raya       GK   1   1   1
0      B.Fernandes      MID   1   1   1
1         Bernardo      MID   1   1   1
3         Bruno G.      MID   0   1   1
6      Gibbs-White      MID   1   1   1
13      Szoboszlai      MID   1   1   1

In [15]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [16]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [17]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [18]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW36 to GW38...

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 75.00
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.45
 ✅        Raya                           Arsenal      £6.1     4.92

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     6.71
 ✅        Van Hecke                      Brighton     £4.6     4.23
 ✅        Richards                       Crystal Palace £4.4     6.41
 ✅        Khusanov                       Man City     £5.4     8.38
 ✅        Matheus N.                     Man City     £5.3     9.83

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.99
 ✅        Szoboszlai                     Liverpool    £7.0     4.40
 ✅        Bernardo                       Man City     £6.2    15.34
 ✅        B.Fernandes                    Man Utd      £10.4    5.00
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.69

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.38
 🪑        Brobbey                        Sunderland   £5.3     3.37
 ✅        Flemming                       Burnley      £5.3     3.59

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 54.07
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.65
 ✅        Raya                           Arsenal      £6.1     4.94

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     3.15
 ✅        Gabriel                        Arsenal      £7.2     6.89
 ✅        Van Hecke                      Brighton     £4.6     4.17
 ✅        Khusanov                       Man City     £5.4     4.06
 ✅        Matheus N.                     Man City     £5.3     4.52

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.33
 ✅        Bernardo                       Man City     £6.2     6.53
 ✅        B.Fernandes                    Man Utd      £10.4    4.93
 ✅        Bruno G.                       Newcastle    £6.8     4.08
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.70

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.44
 🪑        Brobbey                        Sunderland   £5.3     3.41
 ✅        Flemming                       Burnley      £5.3     3.55

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 51.72
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.29
 ✅        Raya                           Arsenal      £6.1     4.36

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     2.83
 ✅        Gabriel                        Arsenal      £7.2     5.87
 ✅        Van Hecke                      Brighton     £4.6     3.72
 ✅        Khusanov                       Man City     £5.4     4.14
 ✅        Matheus N.                     Man City     £5.3     4.25

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.40
 ✅        Bernardo                       Man City     £6.2     6.54
 ✅        B.Fernandes                    Man Utd      £10.4    4.84
 ✅        Bruno G.                       Newcastle    £6.8     3.99
 ✅        Gibbs-White                    Nott'm Forest £7.7     4.74

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.38
 🪑        Brobbey                        Sunderland   £5.3     3.40
 ✅        Flemming                       Burnley      £5.3     3.59

================================================================================
Optimization Status: Optimal

In [19]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
0     36         13.667541
1     37         12.288809
2     38         11.612093

In [20]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.06 minute(s)