In [1]:
import pandas as pd
import time
from datetime import datetime
import os

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 36
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [23]:
# Reece James goals vs xg in all seasons
view = db_creator.run_sql(f"""
SELECT player_name_id, season, event, fixture, goals_scored, expected_goals, expected_assists, assists
                          FROM playergw_transformed
                          WHERE expected_goals IS NOT NULL
                          ORDER BY season, event, fixture
""")
view.pivot_table(index=['season'], values=['goals_scored', 'expected_goals', 'expected_assists', 'assists'], aggfunc='sum',margins=True,dropna=False)

            assists  expected_assists  expected_goals  goals_scored
season
20222023.0    927.0         439.09678        731.5486        1038.0
20232024.0   1071.0         752.20000       1198.4800        1196.0
20242025.0    978.0         711.72000       1100.7100        1081.0
20252026.0    876.0         627.99000        988.7700         934.0
All          3852.0        2531.00678       4019.5086        4249.0

In [6]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        -- AND latest_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 37
Squad Points: 67.86

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,37.0,DEF,Arsenal,Burnley,6.231778,84.0
1,Matheus N.,a,100.0,37.0,DEF,Man City,Bournemouth,4.797124,86.0
2,Raya,a,NaN,37.0,GK,Arsenal,Burnley,4.760160,87.0
3,B.Fernandes,a,100.0,37.0,MID,Man Utd,Nott'm Forest,4.636670,84.0
4,Szoboszlai,a,100.0,37.0,MID,Liverpool,Aston Villa,4.289571,86.0
5,Bernardo,a,100.0,37.0,MID,Man City,Bournemouth,4.238904,82.0
6,Van Hecke,a,100.0,37.0,DEF,Brighton,Leeds,4.149874,87.0
7,Brobbey,a,100.0,37.0,FWD,Sunderland,Everton,4.103674,85.0
8,Gibbs-White,d,50.0,37.0,MID,Nott'm Forest,Man Utd,4.095228,61.0
9,Bruno G.,a,100.0,37.0,MID,Newcastle,West Ham,3.968042,65.0
10,Khusanov,a,100.0,37.0,DEF,Man City,Bournemouth,3.585266,67.0
11,Martinez,a,100.0,37.0,GK,Aston Villa,Liverpool,3.532314,90.0
12,Flemming,a,100.0,37.0,FWD,Burnley,Arsenal,3.344545,54.0
13,Richards,a,100.0,37.0,DEF,Crystal Palace,Brentford,3.023216,65.0
14,Isak,a,75.0,37.0,FWD,Liverpool,Aston Villa,2.867250,55.0

In [7]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW37 AND 41

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Chris Richards,1,DEF,Crystal Palace,1155.4,5.65,65.4,0.043,1.0,0.030,1.000,1.671
1,Alexander Isak,1,FWD,Liverpool,1088.2,5.81,55.0,0.311,1.0,0.068,1.596,1.286
2,Zian Flemming,1,FWD,Burnley,1080.6,6.93,55.1,0.553,1.0,0.047,1.000,1.552
3,Emiliano Martínez Romero,1,GK,Aston Villa,1202.8,7.15,89.6,NaN,1.0,NaN,1.000,1.633
4,Abdukodir Khusanov,1,DEF,Man City,1108.7,7.17,67.3,0.039,1.0,0.035,1.000,1.336
5,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1021.4,7.89,65.2,0.218,1.0,0.135,1.000,1.193
6,Jan Paul van Hecke,1,DEF,Brighton,1070.6,7.89,86.8,0.040,1.0,0.032,1.000,1.267
7,Brian Brobbey,1,FWD,Sunderland,1068.7,8.23,85.4,0.366,1.0,0.061,1.000,1.182
8,Morgan Gibbs-White,1,MID,Nott'm Forest,1117.0,8.25,60.7,0.287,1.0,0.241,2.015,1.436
9,Bernardo Mota Veiga de Carvalho e Silva,1,MID,Man City,1108.7,8.48,82.3,0.134,1.0,0.148,1.000,1.062
10,Dominik Szoboszlai,1,MID,Liverpool,1088.2,8.65,86.3,0.158,1.0,0.141,1.000,1.387
11,David Raya Martín,1,GK,Arsenal,953.6,8.92,87.1,NaN,1.0,NaN,1.000,0.722
12,Bruno Borges Fernandes,1,MID,Man Utd,1073.6,9.34,83.9,0.205,1.0,0.204,1.329,1.432
13,Matheus Nunes,1,DEF,Man City,1108.7,9.59,86.5,0.040,1.0,0.204,2.783,1.101
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,953.6,11.13,84.5,0.075,1.0,0.073,1.000,0.669

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    --AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW37 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,953.6,11.13,84.5,1.000,0.075,1.000,0.073,0.669
1,Benjamin White,a,0,DEF,Arsenal,953.6,10.83,72.8,1.000,0.053,1.000,0.084,0.611
2,Mathias Jensen,a,0,MID,Brentford,1100.1,10.09,85.7,2.029,0.278,1.000,0.177,1.236
3,Leandro Trossard,a,0,MID,Arsenal,953.6,9.69,59.7,1.416,0.334,1.826,0.330,0.658
4,Matheus Nunes,a,1,DEF,Man City,1108.7,9.59,86.5,1.000,0.040,2.783,0.204,1.101
5,Myles Lewis-Skelly,a,0,DEF,Arsenal,953.6,9.36,61.1,1.000,0.044,1.000,0.041,0.713
6,Bruno Borges Fernandes,a,1,MID,Man Utd,1073.6,9.34,83.9,1.000,0.205,1.329,0.204,1.432
7,Rúben dos Santos Gato Alves Dias,a,0,DEF,Man City,1108.7,9.22,65.8,1.000,0.260,1.000,0.036,1.296
8,Jack Hinshelwood,a,0,MID,Brighton,1070.6,8.96,83.5,1.000,0.178,1.828,0.196,1.274
9,Martin Ødegaard,a,0,MID,Arsenal,953.6,8.93,72.9,1.000,0.146,1.000,0.252,0.755
10,David Raya Martín,a,1,GK,Arsenal,953.6,8.92,87.1,1.000,NaN,1.000,NaN,0.722
11,Kenny Tete,a,0,DEF,Fulham,990.6,8.72,67.9,1.000,0.208,1.000,0.074,1.392
12,Maxim De Cuyper,a,0,DEF,Brighton,1070.6,8.69,64.3,1.000,0.151,1.000,0.138,1.223
13,Dominik Szoboszlai,a,1,MID,Liverpool,1088.2,8.65,86.3,1.000,0.158,1.000,0.141,1.387
14,Ethan Pinnock,a,0,DEF,Brentford,1100.1,8.54,66.4,1.000,0.290,1.000,0.028,1.519
15,Joško Gvardiol,d,0,DEF,Man City,1108.7,8.50,53.1,1.000,0.289,1.000,0.101,1.311
16,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1108.7,8.48,82.3,1.000,0.134,1.000,0.148,1.062
17,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,1004.0,8.47,64.1,1.000,0.273,1.000,0.028,1.484
18,Marcus Tavernier,a,0,MID,Bournemouth,1148.0,8.45,79.8,1.000,0.166,1.477,0.165,1.436
19,Granit Xhaka,a,0,MID,Sunderland,1068.7,8.41,85.1,1.000,0.078,2.094,0.251,1.297
20,Rico Lewis,a,0,DEF,Man City,1108.7,8.39,58.3,1.000,0.307,1.000,0.048,1.409
21,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1148.0,8.38,73.9,1.000,0.242,1.000,0.094,1.629
22,Timothy Castagne,a,0,DEF,Fulham,990.6,8.37,84.6,1.000,0.035,1.815,0.115,1.262
23,El Hadji Malick Diouf,a,0,DEF,West Ham,1039.4,8.29,80.6,1.000,0.032,2.042,0.103,1.203
24,Morgan Gibbs-White,d,1,MID,Nott'm Forest,1117.0,8.25,60.7,1.000,0.287,2.015,0.241,1.436
25,Brian Brobbey,a,1,FWD,Sunderland,1068.7,8.23,85.4,1.000,0.366,1.000,0.061,1.182
26,Pedro Lomba Neto,d,0,MID,Chelsea,1004.0,8.20,68.9,1.000,0.177,1.476,0.194,1.204
27,Antonee Robinson,a,0,DEF,Fulham,990.6,8.18,76.7,1.000,0.033,1.662,0.103,1.210
28,James Justin,a,0,DEF,Leeds,1049.5,8.16,86.2,1.000,0.040,1.000,0.043,1.219
29,Alexis Mac Allister,a,0,MID,Liverpool,1088.2,8.14,80.5,1.000,0.146,1.000,0.117,1.311
30,Kieran Trippier,a,0,DEF,Newcastle,1021.4,8.12,64.9,1.000,0.122,1.000,0.202,1.373
31,Kevin Schade,a,0,MID,Brentford,1100.1,8.09,74.4,1.000,0.166,2.069,0.151,1.207
32,Enzo Fernández,a,0,MID,Chelsea,1004.0,8.09,84.8,1.000,0.105,1.000,0.115,1.096
33,Max Alleyne,a,0,DEF,Man City,1108.7,8.08,56.0,1.000,0.264,1.000,0.035,1.406
34,Calvin Bassey,a,0,DEF,Fulham,990.6,8.08,86.4,1.000,0.035,1.000,0.029,1.212
35,Sebastiaan Bornauw,a,0,DEF,Leeds,1049.5,8.03,67.8,1.000,0.241,1.000,0.024,1.508
36,John Stones,a,0,DEF,Man City,1108.7,8.02,55.4,1.000,0.234,1.000,0.035,1.358
37,Malo Gusto,a,0,DEF,Chelsea,1004.0,8.01,83.1,1.000,0.042,1.000,0.078,1.332
38,Cristhian Mosquera,a,0,DEF,Arsenal,953.6,8.00,33.2,1.000,0.038,1.000,0.041,0.737
39,Tomáš Souček,a,0,MID,West Ham,1039.4,7.99,82.2,1.000,0.143,1.000,0.081,1.159
40,Sven Botman,a,0,DEF,Newcastle,1021.4,7.98,83.3,1.000,0.035,1.000,0.057,1.262
41,Kyle Walker-Peters,a,0,DEF,West Ham,1039.4,7.96,77.5,1.000,0.044,1.000,0.041,1.198
42,Maximilian Kilman,a,0,DEF,West Ham,1039.4,7.95,58.9,1.000,0.272,1.000,0.024,1.450
43,Ferdi Kadıoğlu,a,0,DEF,Brighton,1070.6,7.92,86.9,1.000,0.041,1.000,0.033,1.265
44,Reece James,a,0,DEF,Chelsea,1004.0,7.90,67.3,1.000,0.053,1.000,0.127,1.247
45,Olivier Boscagli,a,0,DEF,Brighton,1070.6,7.90,80.5,1.000,0.036,1.000,0.040,1.238
46,Jan Paul van Hecke,a,1,DEF,Brighton,1070.6,7.89,86.8,1.000,0.040,1.000,0.032,1.267
47,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1021.4,7.89,65.2,1.000,0.218,1.000,0.135,1.193
48,Axel Disasi,a,0,DEF,West Ham,1039.4,7.87,85.1,1.000,0.034,1.000,0.024,1.229
49,Filip Jörgensen,a,0,GK,Chelsea,1004.0,7.82,89.2,1.000,NaN,1.000,NaN,1.268

In [9]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW37 AND 41

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,953.6,11.13,84.5,0.075,1.000,0.073,1.000,0.669
1,Benjamin White,a,0,DEF,Arsenal,953.6,10.83,72.8,0.053,1.000,0.084,1.000,0.611
2,Mathias Jensen,a,0,MID,Brentford,1100.1,10.09,85.7,0.278,2.029,0.177,1.000,1.236
3,Leandro Trossard,a,0,MID,Arsenal,953.6,9.69,59.7,0.334,1.416,0.330,1.826,0.658
4,Matheus Nunes,a,1,DEF,Man City,1108.7,9.59,86.5,0.040,1.000,0.204,2.783,1.101
5,Myles Lewis-Skelly,a,0,DEF,Arsenal,953.6,9.36,61.1,0.044,1.000,0.041,1.000,0.713
6,Bruno Borges Fernandes,a,1,MID,Man Utd,1073.6,9.34,83.9,0.205,1.000,0.204,1.329,1.432
7,Rúben dos Santos Gato Alves Dias,a,0,DEF,Man City,1108.7,9.22,65.8,0.260,1.000,0.036,1.000,1.296
8,Jack Hinshelwood,a,0,MID,Brighton,1070.6,8.96,83.5,0.178,1.000,0.196,1.828,1.274
9,Martin Ødegaard,a,0,MID,Arsenal,953.6,8.93,72.9,0.146,1.000,0.252,1.000,0.755
10,David Raya Martín,a,1,GK,Arsenal,953.6,8.92,87.1,NaN,1.000,NaN,1.000,0.722
11,Kenny Tete,a,0,DEF,Fulham,990.6,8.72,67.9,0.208,1.000,0.074,1.000,1.392
12,Maxim De Cuyper,a,0,DEF,Brighton,1070.6,8.69,64.3,0.151,1.000,0.138,1.000,1.223
13,Dominik Szoboszlai,a,1,MID,Liverpool,1088.2,8.65,86.3,0.158,1.000,0.141,1.000,1.387
14,Ethan Pinnock,a,0,DEF,Brentford,1100.1,8.54,66.4,0.290,1.000,0.028,1.000,1.519
15,Joško Gvardiol,d,0,DEF,Man City,1108.7,8.50,53.1,0.289,1.000,0.101,1.000,1.311
16,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,1108.7,8.48,82.3,0.134,1.000,0.148,1.000,1.062
17,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,1004.0,8.47,64.1,0.273,1.000,0.028,1.000,1.484
18,Marcus Tavernier,a,0,MID,Bournemouth,1148.0,8.45,79.8,0.166,1.000,0.165,1.477,1.436
19,Granit Xhaka,a,0,MID,Sunderland,1068.7,8.41,85.1,0.078,1.000,0.251,2.094,1.297
20,Rico Lewis,a,0,DEF,Man City,1108.7,8.39,58.3,0.307,1.000,0.048,1.000,1.409
21,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1148.0,8.38,73.9,0.242,1.000,0.094,1.000,1.629
22,Timothy Castagne,a,0,DEF,Fulham,990.6,8.37,84.6,0.035,1.000,0.115,1.815,1.262
23,El Hadji Malick Diouf,a,0,DEF,West Ham,1039.4,8.29,80.6,0.032,1.000,0.103,2.042,1.203
24,Morgan Gibbs-White,d,1,MID,Nott'm Forest,1117.0,8.25,60.7,0.287,1.000,0.241,2.015,1.436
25,Brian Brobbey,a,1,FWD,Sunderland,1068.7,8.23,85.4,0.366,1.000,0.061,1.000,1.182
26,Pedro Lomba Neto,d,0,MID,Chelsea,1004.0,8.20,68.9,0.177,1.000,0.194,1.476,1.204
27,Antonee Robinson,a,0,DEF,Fulham,990.6,8.18,76.7,0.033,1.000,0.103,1.662,1.210
28,James Justin,a,0,DEF,Leeds,1049.5,8.16,86.2,0.040,1.000,0.043,1.000,1.219
29,Alexis Mac Allister,a,0,MID,Liverpool,1088.2,8.14,80.5,0.146,1.000,0.117,1.000,1.311
30,Kieran Trippier,a,0,DEF,Newcastle,1021.4,8.12,64.9,0.122,1.000,0.202,1.000,1.373
31,Kevin Schade,a,0,MID,Brentford,1100.1,8.09,74.4,0.166,1.000,0.151,2.069,1.207
32,Enzo Fernández,a,0,MID,Chelsea,1004.0,8.09,84.8,0.105,1.000,0.115,1.000,1.096
33,Max Alleyne,a,0,DEF,Man City,1108.7,8.08,56.0,0.264,1.000,0.035,1.000,1.406
34,Calvin Bassey,a,0,DEF,Fulham,990.6,8.08,86.4,0.035,1.000,0.029,1.000,1.212
35,Sebastiaan Bornauw,a,0,DEF,Leeds,1049.5,8.03,67.8,0.241,1.000,0.024,1.000,1.508
36,John Stones,a,0,DEF,Man City,1108.7,8.02,55.4,0.234,1.000,0.035,1.000,1.358
37,Malo Gusto,a,0,DEF,Chelsea,1004.0,8.01,83.1,0.042,1.000,0.078,1.000,1.332
38,Cristhian Mosquera,a,0,DEF,Arsenal,953.6,8.00,33.2,0.038,1.000,0.041,1.000,0.737
39,Tomáš Souček,a,0,MID,West Ham,1039.4,7.99,82.2,0.143,1.000,0.081,1.000,1.159
40,Sven Botman,a,0,DEF,Newcastle,1021.4,7.98,83.3,0.035,1.000,0.057,1.000,1.262
41,Kyle Walker-Peters,a,0,DEF,West Ham,1039.4,7.96,77.5,0.044,1.000,0.041,1.000,1.198
42,Maximilian Kilman,a,0,DEF,West Ham,1039.4,7.95,58.9,0.272,1.000,0.024,1.000,1.450
43,Ferdi Kadıoğlu,a,0,DEF,Brighton,1070.6,7.92,86.9,0.041,1.000,0.033,1.000,1.265
44,Reece James,a,0,DEF,Chelsea,1004.0,7.90,67.3,0.053,1.000,0.127,1.000,1.247
45,Olivier Boscagli,a,0,DEF,Brighton,1070.6,7.90,80.5,0.036,1.000,0.040,1.000,1.238
46,Jan Paul van Hecke,a,1,DEF,Brighton,1070.6,7.89,86.8,0.040,1.000,0.032,1.000,1.267
47,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1021.4,7.89,65.2,0.218,1.000,0.135,1.000,1.193
48,Axel Disasi,a,0,DEF,West Ham,1039.4,7.87,85.1,0.034,1.000,0.024,1.000,1.229
49,Filip Jörgensen,a,0,GK,Chelsea,1004.0,7.82,89.2,NaN,1.000,NaN,1.000,1.268

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 37 to 41

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Arsenal,a,Benjamin White,10.826356,Chris Richards,5.654596,5.171760
1,DEF,Arsenal,a,Myles Lewis-Skelly,9.363417,Chris Richards,5.654596,3.708821
2,DEF,Man City,a,Rúben dos Santos Gato Alves Dias,9.216951,Chris Richards,5.654596,3.562354
3,DEF,Fulham,a,Kenny Tete,8.720500,Chris Richards,5.654596,3.065903
4,DEF,Brighton,a,Maxim De Cuyper,8.691554,Chris Richards,5.654596,3.036957
5,DEF,Brentford,a,Ethan Pinnock,8.542106,Chris Richards,5.654596,2.887510
6,DEF,Man City,d,Joško Gvardiol,8.500821,Chris Richards,5.654596,2.846224
7,DEF,Chelsea,a,Benoît Badiashile Mukinayi,8.471281,Chris Richards,5.654596,2.816685
8,DEF,Man City,a,Rico Lewis,8.389068,Chris Richards,5.654596,2.734471
9,DEF,Fulham,a,Timothy Castagne,8.368492,Chris Richards,5.654596,2.713896
10,DEF,West Ham,a,El Hadji Malick Diouf,8.292750,Chris Richards,5.654596,2.638154
11,DEF,Fulham,a,Antonee Robinson,8.178637,Chris Richards,5.654596,2.524041
12,DEF,Leeds,a,James Justin,8.158163,Chris Richards,5.654596,2.503566
13,DEF,Newcastle,a,Kieran Trippier,8.120624,Chris Richards,5.654596,2.466028
14,DEF,Fulham,a,Calvin Bassey,8.081410,Chris Richards,5.654596,2.426813
15,DEF,Man City,a,Max Alleyne,8.076899,Chris Richards,5.654596,2.422302
16,DEF,Leeds,a,Sebastiaan Bornauw,8.025742,Chris Richards,5.654596,2.371146
17,DEF,Man City,a,John Stones,8.018613,Chris Richards,5.654596,2.364016
18,DEF,Chelsea,a,Malo Gusto,8.006431,Chris Richards,5.654596,2.351835
19,DEF,Arsenal,a,Cristhian Mosquera,7.999170,Chris Richards,5.654596,2.344573

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 37 and 41:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.7,1107.688648,6.061982,77.242782,0.799076,0.252684,1.059156
1,Erling Haaland,38.0,FWD,Man City,Aston Villa,14.7,1109.774484,6.061982,77.242782,0.799076,0.252684,1.059156

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND team_name IN ('Crystal Palace')
      -- AND position = 'DEF'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW37 to GW41
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,539.8,3.25,84.5,0.075,1.000,0.073,1.000,0.669
1,Benjamin White,a,0,DEF,Arsenal,539.8,3.16,72.8,0.053,1.000,0.084,1.000,0.611
2,Mathias Jensen,a,0,MID,Brentford,626.2,2.90,85.7,0.278,2.029,0.177,1.000,1.236
3,Leandro Trossard,a,0,MID,Arsenal,539.8,2.80,59.7,0.334,1.416,0.330,1.826,0.658
4,Matheus Nunes,a,1,DEF,Man City,635.9,2.75,86.5,0.040,1.000,0.204,2.783,1.101
5,Myles Lewis-Skelly,a,0,DEF,Arsenal,539.8,2.73,61.1,0.044,1.000,0.041,1.000,0.713
6,Bruno Borges Fernandes,a,1,MID,Man Utd,613.9,2.68,83.9,0.205,1.000,0.204,1.329,1.432
7,Rúben dos Santos Gato Alves Dias,a,0,DEF,Man City,635.9,2.64,65.8,0.260,1.000,0.036,1.000,1.296
8,Martin Ødegaard,a,0,MID,Arsenal,539.8,2.58,72.9,0.146,1.000,0.252,1.000,0.755
9,David Raya Martín,a,1,GK,Arsenal,539.8,2.58,87.1,NaN,1.000,NaN,1.000,0.722
10,Jack Hinshelwood,a,0,MID,Brighton,609.6,2.58,83.5,0.178,1.000,0.196,1.828,1.274
11,Kenny Tete,a,0,DEF,Fulham,562.2,2.55,67.9,0.208,1.000,0.074,1.000,1.392
12,Maxim De Cuyper,a,0,DEF,Brighton,609.6,2.51,64.3,0.151,1.000,0.138,1.000,1.223
13,Dominik Szoboszlai,a,1,MID,Liverpool,626.0,2.48,86.3,0.158,1.000,0.141,1.000,1.387
14,Ethan Pinnock,a,0,DEF,Brentford,626.2,2.46,66.4,0.290,1.000,0.028,1.000,1.519
15,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,573.8,2.45,64.1,0.273,1.000,0.028,1.000,1.484
16,Timothy Castagne,a,0,DEF,Fulham,562.2,2.44,84.6,0.035,1.000,0.115,1.815,1.262
17,Joško Gvardiol,d,0,DEF,Man City,635.9,2.44,53.1,0.289,1.000,0.101,1.000,1.311
18,Bernardo Mota Veiga de Carvalho e Silva,a,1,MID,Man City,635.9,2.43,82.3,0.134,1.000,0.148,1.000,1.062
19,Granit Xhaka,a,0,MID,Sunderland,612.3,2.42,85.1,0.078,1.000,0.251,2.094,1.297
20,Marcus Tavernier,a,0,MID,Bournemouth,666.6,2.42,79.8,0.166,1.000,0.165,1.477,1.436
21,Rico Lewis,a,0,DEF,Man City,635.9,2.41,58.3,0.307,1.000,0.048,1.000,1.409
22,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,666.6,2.39,73.9,0.242,1.000,0.094,1.000,1.629
23,Antonee Robinson,a,0,DEF,Fulham,562.2,2.37,76.7,0.033,1.000,0.103,1.662,1.210
24,El Hadji Malick Diouf,a,0,DEF,West Ham,598.2,2.36,80.6,0.032,1.000,0.103,2.042,1.203
25,Brian Brobbey,a,1,FWD,Sunderland,612.3,2.36,85.4,0.366,1.000,0.061,1.000,1.182
26,Morgan Gibbs-White,d,1,MID,Nott'm Forest,641.5,2.36,60.7,0.287,1.000,0.241,2.015,1.436
27,Calvin Bassey,a,0,DEF,Fulham,562.2,2.35,86.4,0.035,1.000,0.029,1.000,1.212
28,Pedro Lomba Neto,d,0,MID,Chelsea,573.8,2.35,68.9,0.177,1.000,0.194,1.476,1.204
29,Kieran Trippier,a,0,DEF,Newcastle,584.3,2.34,64.9,0.122,1.000,0.202,1.000,1.373
30,Alexis Mac Allister,a,0,MID,Liverpool,626.0,2.33,80.5,0.146,1.000,0.117,1.000,1.311
31,Cristhian Mosquera,a,0,DEF,Arsenal,539.8,2.33,33.2,0.038,1.000,0.041,1.000,0.737
32,Enzo Fernández,a,0,MID,Chelsea,573.8,2.32,84.8,0.105,1.000,0.115,1.000,1.096
33,Kevin Schade,a,0,MID,Brentford,626.2,2.32,74.4,0.166,1.000,0.151,2.069,1.207
34,Malo Gusto,a,0,DEF,Chelsea,573.8,2.32,83.1,0.042,1.000,0.078,1.000,1.332
35,Max Alleyne,a,0,DEF,Man City,635.9,2.32,56.0,0.264,1.000,0.035,1.000,1.406
36,Sven Botman,a,0,DEF,Newcastle,584.3,2.31,83.3,0.035,1.000,0.057,1.000,1.262
37,James Justin,a,0,DEF,Leeds,605.9,2.31,86.2,0.040,1.000,0.043,1.000,1.219
38,John Stones,a,0,DEF,Man City,635.9,2.30,55.4,0.234,1.000,0.035,1.000,1.358
39,Ferdi Kadıoğlu,a,0,DEF,Brighton,609.6,2.29,86.9,0.041,1.000,0.033,1.000,1.265
40,Tomáš Souček,a,0,MID,West Ham,598.2,2.29,82.2,0.143,1.000,0.081,1.000,1.159
41,Reece James,a,0,DEF,Chelsea,573.8,2.29,67.3,0.053,1.000,0.127,1.000,1.247
42,Olivier Boscagli,a,0,DEF,Brighton,609.6,2.29,80.5,0.036,1.000,0.040,1.000,1.238
43,Sebastiaan Bornauw,a,0,DEF,Leeds,605.9,2.28,67.8,0.241,1.000,0.024,1.000,1.508
44,Jan Paul van Hecke,a,1,DEF,Brighton,609.6,2.28,86.8,0.040,1.000,0.032,1.000,1.267
45,Maximilian Kilman,a,0,DEF,West Ham,598.2,2.27,58.9,0.272,1.000,0.024,1.000,1.450
46,Kyle Walker-Peters,a,0,DEF,West Ham,598.2,2.27,77.5,0.044,1.000,0.041,1.000,1.198
47,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,584.3,2.26,65.2,0.218,1.000,0.135,1.000,1.193
48,Filip Jörgensen,a,0,GK,Chelsea,573.8,2.26,89.2,NaN,1.000,NaN,1.000,1.268
49,Keane Lewis-Potter,a,0,DEF,Brentford,626.2,2.25,84.5,0.066,1.000,0.057,1.000,1.365

# Multi-week optimizer

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [15]:
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    
    # 1. Initialize as an empty list to store DataFrames
    all_results_list = [] 

    for event in range(picks_current_gameweek + 1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event'] == event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            squad = optimizer.get_squad_dataframe()
            squad['event'] = event
            
            # 2. Append the individual DataFrame to the list
            all_results_list.append(squad) 

        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

    # 3. Concatenate everything into one master DataFrame at the end
    if all_results_list:
        all_results = pd.concat(all_results_list, ignore_index=True)
        print("\nOptimization complete. Final DataFrame created.")
    else:
        all_results = pd.DataFrame() # Fallback if list is empty
        print("\nNo results found.")

all_results.pivot_table(index=['web_name','position'],columns='event',values='Starter',aggfunc='sum').reset_index().sort_values(by='position')

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 50.13
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.53
 ✅        Raya                           Arsenal      £6.1     4.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     3.02
 ✅        Gabriel                        Arsenal      £7.3     6.23
 ✅        Van Hecke                      Brighton     £4.6     4.15
 ✅        Khusanov                       Man City     £5.4     3.59
 ✅        Matheus N.                     Man City     £5.3     4.80

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.29
 ✅        Bernardo                       Man City     £6.2     4.24
 ✅        B.Fernandes                    Man Utd      £10.4    4.64
 ✅        Bruno G.                       Newcastle    £6.8     3.97
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.10

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Flemming                       Burnley      £5.3     3.34
 🪑        Isak                           Liverpool    £10.3    2.87
 ✅        Brobbey                        Sunderland   £5.3     4.10

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 47.95
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.62
 ✅        Raya                           Arsenal      £6.1     4.16

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     2.63
 🪑        Khusanov                       Man City     £5.4     3.58
 ✅        Gabriel                        Arsenal      £7.3     4.90
 ✅        Van Hecke                      Brighton     £4.6     3.74
 ✅        Matheus N.                     Man City     £5.3     4.80

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.36
 ✅        Bernardo                       Man City     £6.2     4.24
 ✅        B.Fernandes                    Man Utd      £10.4    4.70
 ✅        Bruno G.                       Newcastle    £6.8     3.92
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.16

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.94
 ✅        Flemming                       Burnley      £5.3     3.58
 ✅        Brobbey                        Sunderland   £5.3     4.12

================================================================================
Optimization Status: Optimal

Optimization complete. Final DataFrame created.

event     web_name position  37  38
5          Gabriel      DEF   1   1
8         Khusanov      DEF   1   0
10      Matheus N.      DEF   1   1
12        Richards      DEF   0   0
14       Van Hecke      DEF   1   1
2          Brobbey      FWD   1   1
4         Flemming      FWD   0   1
7             Isak      FWD   0   0
9         Martinez       GK   0   0
11            Raya       GK   1   1
0      B.Fernandes      MID   1   1
1         Bernardo      MID   1   1
3         Bruno G.      MID   1   1
6      Gibbs-White      MID   1   1
13      Szoboszlai      MID   1   1

In [16]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [17]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [18]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [19]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW37 to GW38...

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 50.13
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.53
 ✅        Raya                           Arsenal      £6.1     4.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     3.02
 ✅        Gabriel                        Arsenal      £7.3     6.23
 ✅        Van Hecke                      Brighton     £4.6     4.15
 ✅        Khusanov                       Man City     £5.4     3.59
 ✅        Matheus N.                     Man City     £5.3     4.80

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.29
 ✅        Bernardo                       Man City     £6.2     4.24
 ✅        B.Fernandes                    Man Utd      £10.4    4.64
 ✅        Bruno G.                       Newcastle    £6.8     3.97
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.10

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Flemming                       Burnley      £5.3     3.34
 🪑        Isak                           Liverpool    £10.3    2.87
 ✅        Brobbey                        Sunderland   £5.3     4.10

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 47.95
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.62
 ✅        Raya                           Arsenal      £6.1     4.16

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Richards                       Crystal Palace £4.4     2.63
 🪑        Khusanov                       Man City     £5.4     3.58
 ✅        Gabriel                        Arsenal      £7.3     4.90
 ✅        Van Hecke                      Brighton     £4.6     3.74
 ✅        Matheus N.                     Man City     £5.3     4.80

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Szoboszlai                     Liverpool    £7.0     4.36
 ✅        Bernardo                       Man City     £6.2     4.24
 ✅        B.Fernandes                    Man Utd      £10.4    4.70
 ✅        Bruno G.                       Newcastle    £6.8     3.92
 ✅        Gibbs-White                    Nott'm Forest £7.6     4.16

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.94
 ✅        Flemming                       Burnley      £5.3     3.58
 ✅        Brobbey                        Sunderland   £5.3     4.12

================================================================================
Optimization Status: Optimal

In [20]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
1     38         11.491872
0     37         11.490593

In [21]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.04 minute(s)