In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 29
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 30
Squad Points: 67.42

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Matheus N.,a,100.0,30.0,DEF,Man City,West Ham,5.201714,86.0
1,Konaté,a,100.0,30.0,DEF,Liverpool,Spurs,5.079709,87.0
2,Mac Allister,a,100.0,30.0,MID,Liverpool,Spurs,4.913911,83.0
3,Gabriel,a,100.0,30.0,DEF,Arsenal,Everton,4.850121,84.0
4,Szoboszlai,a,100.0,30.0,MID,Liverpool,Spurs,4.768550,86.0
5,Gibbs-White,a,100.0,30.0,MID,Nott'm Forest,Fulham,4.508857,82.0
6,B.Fernandes,a,100.0,30.0,MID,Man Utd,Aston Villa,4.473747,77.0
7,Raya,a,NaN,30.0,GK,Arsenal,Everton,4.193260,90.0
8,Brobbey,d,0.0,30.0,FWD,Sunderland,Brighton,4.077234,62.0
9,Trossard,d,100.0,30.0,MID,Arsenal,Everton,3.864222,60.0
10,Raúl,a,100.0,30.0,FWD,Fulham,Nott'm Forest,3.619333,72.0
11,Mings,a,100.0,30.0,DEF,Aston Villa,Man Utd,3.482061,79.0
12,Igor Jesus,a,100.0,30.0,FWD,Nott'm Forest,Fulham,3.115090,69.0
13,Martinez,a,100.0,30.0,GK,Aston Villa,Man Utd,3.038545,89.0
14,Maatsen,a,NaN,30.0,DEF,Aston Villa,Man Utd,3.026995,75.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW30 AND 34

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Leandro Trossard,1,MID,Arsenal,1112.8,15.17,59.6,0.190,0.147,1.131
1,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1013.3,15.78,69.0,0.174,0.128,1.310
2,David Raya Martín,1,GK,Arsenal,1112.8,16.50,89.9,NaN,NaN,0.986
3,Emiliano Martínez Romero,1,GK,Aston Villa,1036.0,17.95,89.3,NaN,NaN,1.423
4,Raúl Jiménez Rodríguez,1,FWD,Fulham,1056.2,17.99,71.6,0.332,0.051,1.277
5,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1112.8,19.01,83.7,0.061,0.094,1.033
6,Ian Maatsen,1,DEF,Aston Villa,1036.0,19.17,73.3,0.040,0.065,1.403
7,Matheus Nunes,1,DEF,Man City,1066.0,19.60,86.0,0.042,0.075,0.912
8,Brian Brobbey,1,FWD,Sunderland,1051.4,20.39,62.1,0.471,0.194,1.265
9,Tyrone Mings,1,DEF,Aston Villa,1036.0,20.81,78.6,0.040,0.041,1.167
10,Ibrahima Konaté,1,DEF,Liverpool,1039.1,22.19,86.6,0.041,0.048,1.096
11,Morgan Gibbs-White,1,MID,Nott'm Forest,1013.3,22.75,82.3,0.184,0.167,1.215
12,Dominik Szoboszlai,1,MID,Liverpool,1039.1,22.91,85.6,0.157,0.176,1.190
13,Bruno Borges Fernandes,1,MID,Man Utd,1080.9,23.45,77.1,0.205,0.230,1.324
14,Alexis Mac Allister,1,MID,Liverpool,1039.1,23.47,83.1,0.213,0.159,1.173

In [7]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW30 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1076.8,42.43,77.1,0.202,0.238,1.293
1,Alexis Mac Allister,a,1,MID,Liverpool,1072.3,41.83,83.1,0.211,0.157,1.237
2,Dominik Szoboszlai,a,1,MID,Liverpool,1072.3,40.56,85.6,0.154,0.168,1.277
3,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1050.6,40.29,82.3,0.182,0.158,1.334
4,Alex Iwobi,a,0,MID,Fulham,1069.7,40.07,85.4,0.164,0.163,1.387
5,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1052.4,39.95,83.4,0.065,0.097,0.931
6,Diego Gómez Amarilla,a,0,MID,Brighton,1032.6,39.09,80.2,0.184,0.123,1.161
7,Alex Scott,a,0,MID,Bournemouth,1070.6,38.82,85.8,0.155,0.124,1.282
8,Anton Stach,a,0,MID,Leeds,1017.0,38.74,82.9,0.152,0.153,1.238
9,Ibrahima Konaté,a,1,DEF,Liverpool,1072.3,38.72,86.6,0.041,0.047,1.146
10,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1032.6,38.64,65.3,0.297,0.057,1.556
11,Mathias Jensen,a,0,MID,Brentford,1064.0,38.49,81.2,0.147,0.161,1.442
12,Pascal Struijk,a,0,DEF,Leeds,1017.0,38.48,86.6,0.072,0.053,1.230
13,Marc Guiu Paz,a,0,FWD,Chelsea,1081.2,38.45,47.2,0.773,0.303,1.617
14,Matheus Nunes,a,1,DEF,Man City,1077.6,37.92,86.1,0.041,0.068,0.978
15,Ferdi Kadıoğlu,a,0,DEF,Brighton,1032.6,37.85,86.3,0.046,0.050,1.181
16,Jan Paul van Hecke,a,0,DEF,Brighton,1032.6,37.69,86.1,0.037,0.051,1.164
17,Jayden Bogle,a,0,DEF,Leeds,1017.0,37.38,83.9,0.060,0.054,1.216
18,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1064.0,37.37,88.5,NaN,NaN,1.157
19,Pascal Groß,a,0,MID,Brighton,1032.6,37.14,84.7,0.099,0.140,1.149
20,Jeremie Frimpong,a,0,DEF,Liverpool,1072.3,37.14,62.3,0.049,0.057,1.012
21,Enzo Le Fée,a,0,MID,Sunderland,1056.3,37.10,85.8,0.105,0.131,1.248
22,Moisés Caicedo Corozo,a,0,MID,Chelsea,1081.2,37.07,85.2,0.098,0.159,1.374
23,Tyrone Mings,a,1,DEF,Aston Villa,1047.8,37.06,78.6,0.041,0.040,1.203
24,Lewis Dunk,a,0,DEF,Brighton,1032.6,37.01,86.4,0.039,0.049,1.212
25,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1047.8,36.87,75.7,0.146,0.136,1.194
26,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1091.3,36.73,85.1,0.113,0.118,1.481
27,Habib Diarra,a,0,MID,Sunderland,1056.3,36.71,81.4,0.138,0.103,1.182
28,Pau Torres,a,0,DEF,Aston Villa,1047.8,36.69,77.3,0.044,0.037,1.225
29,Brian Brobbey,d,1,FWD,Sunderland,1056.3,36.57,62.1,0.471,0.194,1.277
30,Brenden Aaronson,a,0,MID,Leeds,1017.0,36.46,72.6,0.199,0.103,1.212
31,Jaidon Anthony,a,0,MID,Burnley,1082.3,36.45,82.2,0.167,0.100,1.841
32,Amadou Onana,a,0,MID,Aston Villa,1047.8,36.45,70.1,0.176,0.150,1.314
33,Rayan Aït-Nouri,a,0,DEF,Man City,1077.6,36.19,61.9,0.044,0.183,0.963
34,Lucas Digne,a,0,DEF,Aston Villa,1047.8,36.10,65.4,0.050,0.065,1.151
35,Joe Rodon,a,0,DEF,Leeds,1017.0,36.08,86.3,0.036,0.058,1.252
36,Gabriel Gudmundsson,a,0,DEF,Leeds,1017.0,35.81,79.9,0.034,0.069,1.244
37,Kiernan Dewsbury-Hall,a,0,MID,Everton,1101.0,35.78,84.2,0.100,0.124,1.415
38,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1076.8,35.75,82.3,0.037,0.082,1.324
39,Max Alleyne,d,0,DEF,Man City,1077.6,35.63,62.0,0.187,0.048,1.158
40,James Justin,a,0,DEF,Leeds,1017.0,35.61,81.4,0.036,0.051,1.258
41,Trai Hume,a,0,DEF,Sunderland,1056.3,35.49,84.5,0.045,0.040,1.264
42,Reiss Nelson,d,0,MID,Brentford,1064.0,35.43,38.8,0.593,0.254,1.746
43,Ola Aina,a,0,DEF,Nott'm Forest,1050.6,35.42,83.6,0.036,0.048,1.280
44,Sam Byram,a,0,DEF,Leeds,1017.0,35.29,56.1,0.272,0.074,1.483
45,Axel Tuanzebe,d,0,DEF,Burnley,1082.3,35.21,76.0,0.248,0.034,1.949
46,Álex Jiménez Sánchez,a,0,DEF,Bournemouth,1070.6,35.18,86.0,0.039,0.051,1.326
47,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1050.6,35.18,74.3,0.145,0.109,1.304
48,Dwight McNeil,a,0,MID,Everton,1101.0,35.18,75.0,0.146,0.115,1.379
49,Jun'ai Byfield,a,0,DEF,Spurs,1061.2,35.15,59.4,0.248,0.086,1.575

In [9]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW30 AND 34

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Alexis Mac Allister,a,1,MID,Liverpool,1039.1,23.47,83.1,0.213,0.159,1.173
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.9,23.45,77.1,0.205,0.230,1.324
2,Dominik Szoboszlai,a,1,MID,Liverpool,1039.1,22.91,85.6,0.157,0.176,1.190
3,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1013.3,22.75,82.3,0.184,0.167,1.215
4,Alex Iwobi,a,0,MID,Fulham,1056.2,22.46,85.4,0.167,0.167,1.358
5,Ibrahima Konaté,a,1,DEF,Liverpool,1039.1,22.19,86.6,0.041,0.048,1.096
6,Alex Scott,a,0,MID,Bournemouth,1060.1,21.79,85.8,0.159,0.126,1.254
7,Mathias Jensen,a,0,MID,Brentford,1027.3,21.63,81.2,0.149,0.165,1.379
8,Diego Gómez Amarilla,a,0,MID,Brighton,1038.3,21.61,80.2,0.184,0.121,1.148
9,Jeremie Frimpong,a,0,DEF,Liverpool,1039.1,21.43,62.5,0.052,0.059,0.957
10,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1038.3,21.37,65.2,0.297,0.056,1.562
11,Marc Guiu Paz,a,0,FWD,Chelsea,1110.6,21.34,47.3,0.777,0.297,1.607
12,Ferdi Kadıoğlu,a,0,DEF,Brighton,1038.3,21.05,86.3,0.046,0.048,1.179
13,Jan Paul van Hecke,a,0,DEF,Brighton,1038.3,20.98,86.1,0.037,0.051,1.156
14,Anton Stach,a,0,MID,Leeds,1049.1,20.93,82.9,0.140,0.146,1.300
15,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1027.3,20.85,88.5,NaN,NaN,1.147
16,Tyrone Mings,a,1,DEF,Aston Villa,1036.0,20.81,78.6,0.040,0.041,1.167
17,Enzo Le Fée,a,0,MID,Sunderland,1051.4,20.63,85.8,0.105,0.130,1.234
18,Pascal Groß,a,0,MID,Brighton,1038.3,20.62,84.7,0.099,0.138,1.140
19,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1036.0,20.53,75.8,0.145,0.141,1.206
20,Pau Torres,a,0,DEF,Aston Villa,1036.0,20.51,77.3,0.042,0.037,1.195
21,Lewis Dunk,a,0,DEF,Brighton,1038.3,20.51,86.4,0.039,0.047,1.215
22,Habib Diarra,a,0,MID,Sunderland,1051.4,20.44,81.4,0.138,0.101,1.160
23,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1086.0,20.41,85.1,0.114,0.117,1.476
24,Moisés Caicedo Corozo,a,0,MID,Chelsea,1110.6,20.39,85.2,0.097,0.159,1.462
25,Brian Brobbey,d,1,FWD,Sunderland,1051.4,20.39,62.1,0.471,0.194,1.265
26,Ola Aina,a,0,DEF,Nott'm Forest,1013.3,20.28,83.6,0.037,0.052,1.224
27,Amadou Onana,a,0,MID,Aston Villa,1036.0,20.21,70.3,0.171,0.157,1.332
28,Reiss Nelson,d,0,MID,Brentford,1027.3,20.17,38.8,0.600,0.269,1.721
29,Pascal Struijk,a,0,DEF,Leeds,1049.1,20.13,86.6,0.066,0.047,1.345
30,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1013.3,20.09,86.6,0.035,0.047,1.266
31,Jaidon Anthony,a,0,MID,Burnley,1085.7,20.09,82.2,0.162,0.099,1.836
32,Nikola Milenković,a,0,DEF,Nott'm Forest,1013.3,20.06,86.1,0.041,0.052,1.271
33,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1013.3,20.03,74.3,0.151,0.118,1.171
34,Brenden Aaronson,a,0,MID,Leeds,1049.1,19.97,72.7,0.200,0.097,1.301
35,Axel Tuanzebe,d,0,DEF,Burnley,1085.7,19.95,76.2,0.248,0.035,1.879
36,Lucas Digne,a,0,DEF,Aston Villa,1036.0,19.94,65.6,0.046,0.067,1.139
37,Álex Jiménez Sánchez,a,0,DEF,Bournemouth,1060.1,19.91,86.0,0.040,0.051,1.299
38,Trai Hume,a,0,DEF,Sunderland,1051.4,19.84,84.5,0.045,0.040,1.248
39,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1080.9,19.80,82.3,0.037,0.082,1.331
40,Kiernan Dewsbury-Hall,a,0,MID,Everton,1125.4,19.68,84.2,0.099,0.118,1.429
41,Jun'ai Byfield,a,0,DEF,Spurs,1045.8,19.66,59.4,0.247,0.086,1.565
42,Jayden Bogle,a,0,DEF,Leeds,1049.1,19.61,84.0,0.054,0.045,1.317
43,Matheus Nunes,a,1,DEF,Man City,1066.0,19.60,86.0,0.042,0.075,0.912
44,Dwight McNeil,a,0,MID,Everton,1125.4,19.42,75.1,0.145,0.113,1.391
45,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1013.3,19.33,80.4,0.117,0.079,1.251
46,Tomáš Souček,a,0,MID,West Ham,1086.0,19.33,76.9,0.142,0.102,1.481
47,Joe Gomez,a,0,DEF,Liverpool,1039.1,19.25,66.6,0.052,0.067,1.313
48,Kevin Schade,a,0,MID,Brentford,1027.3,19.18,66.6,0.176,0.126,1.308
49,Ian Maatsen,a,1,DEF,Aston Villa,1036.0,19.17,73.3,0.040,0.065,1.403

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 30 to 34

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Fulham,a,Alex Iwobi,22.460919,Leandro Trossard,15.169656,7.291262
1,MID,Bournemouth,a,Alex Scott,21.793390,Leandro Trossard,15.169656,6.623734
2,MID,Brentford,a,Mathias Jensen,21.632729,Leandro Trossard,15.169656,6.463073
3,MID,Brighton,a,Diego Gómez Amarilla,21.609534,Leandro Trossard,15.169656,6.439878
4,MID,Leeds,a,Anton Stach,20.934803,Leandro Trossard,15.169656,5.765147
5,FWD,Chelsea,a,Marc Guiu Paz,21.344053,Igor Jesus Maciel da Cruz,15.781650,5.562402
6,MID,Sunderland,a,Enzo Le Fée,20.634643,Leandro Trossard,15.169656,5.464987
7,MID,Brighton,a,Pascal Groß,20.616225,Leandro Trossard,15.169656,5.446569
8,MID,Aston Villa,a,Douglas Luiz Soares de Paulo,20.533122,Leandro Trossard,15.169656,5.363466
9,MID,Sunderland,a,Habib Diarra,20.443869,Leandro Trossard,15.169656,5.274213
10,MID,West Ham,a,Mateus Gonçalo Espanha Fernandes,20.412026,Leandro Trossard,15.169656,5.242370
11,MID,Chelsea,a,Moisés Caicedo Corozo,20.388534,Leandro Trossard,15.169656,5.218877
12,MID,Aston Villa,a,Amadou Onana,20.206545,Leandro Trossard,15.169656,5.036889
13,MID,Brentford,d,Reiss Nelson,20.167641,Leandro Trossard,15.169656,4.997985
14,MID,Burnley,a,Jaidon Anthony,20.089639,Leandro Trossard,15.169656,4.919983
15,MID,Nott'm Forest,a,Callum Hudson-Odoi,20.033332,Leandro Trossard,15.169656,4.863676
16,MID,Leeds,a,Brenden Aaronson,19.972149,Leandro Trossard,15.169656,4.802493
17,MID,Everton,a,Kiernan Dewsbury-Hall,19.677342,Leandro Trossard,15.169656,4.507686
18,GK,Brentford,a,Hákon Rafn Valdimarsson,20.854310,David Raya Martín,16.498986,4.355324
19,MID,Everton,a,Dwight McNeil,19.423553,Leandro Trossard,15.169656,4.253897

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Leandro Trossard'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 30 and 34:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Leandro Trossard,30.0,MID,Arsenal,Everton,6.7,1068.541563,3.864222,59.719814,0.195939,0.152367,1.031064
1,Leandro Trossard,32.0,MID,Arsenal,Bournemouth,6.7,1071.696412,3.849007,59.719814,0.195939,0.152367,1.074665
2,Leandro Trossard,33.0,MID,Arsenal,Man City,6.7,1232.697317,3.608337,59.428508,0.172884,0.131178,1.346874
3,Leandro Trossard,34.0,MID,Arsenal,Newcastle,6.7,1078.356498,3.848090,59.719814,0.195939,0.151591,1.072827

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW30 to GW34
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Alexis Mac Allister,a,1,MID,Liverpool,1039.1,4.72,83.1,0.213,0.159,1.173
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.9,4.67,77.1,0.205,0.230,1.324
2,Dominik Szoboszlai,a,1,MID,Liverpool,1039.1,4.61,85.6,0.157,0.176,1.190
3,Ibrahima Konaté,a,1,DEF,Liverpool,1039.1,4.54,86.6,0.041,0.048,1.096
4,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1013.3,4.54,82.3,0.184,0.167,1.215
5,Alex Iwobi,a,0,MID,Fulham,1056.2,4.53,85.4,0.167,0.167,1.358
6,Alex Scott,a,0,MID,Bournemouth,1060.1,4.41,85.8,0.159,0.126,1.254
7,Mathias Jensen,a,0,MID,Brentford,1027.3,4.37,81.2,0.149,0.165,1.379
8,Jeremie Frimpong,a,0,DEF,Liverpool,1039.1,4.33,62.5,0.052,0.059,0.957
9,Diego Gómez Amarilla,a,0,MID,Brighton,1038.3,4.32,80.2,0.184,0.121,1.148
10,Marc Guiu Paz,a,0,FWD,Chelsea,1110.6,4.27,47.3,0.777,0.297,1.607
11,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1038.3,4.26,65.2,0.297,0.056,1.562
12,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1027.3,4.24,88.5,NaN,NaN,1.147
13,Ferdi Kadıoğlu,a,0,DEF,Brighton,1038.3,4.18,86.3,0.046,0.048,1.179
14,Anton Stach,a,0,MID,Leeds,1049.1,4.17,82.9,0.140,0.146,1.300
15,Jan Paul van Hecke,a,0,DEF,Brighton,1038.3,4.16,86.1,0.037,0.051,1.156
16,Tyrone Mings,a,1,DEF,Aston Villa,1036.0,4.12,78.6,0.040,0.041,1.167
17,Enzo Le Fée,a,0,MID,Sunderland,1051.4,4.12,85.8,0.105,0.130,1.234
18,Pascal Groß,a,0,MID,Brighton,1038.3,4.11,84.7,0.099,0.138,1.140
19,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1036.0,4.09,75.8,0.145,0.141,1.206
20,Pau Torres,a,0,DEF,Aston Villa,1036.0,4.09,77.3,0.042,0.037,1.195
21,Reiss Nelson,d,0,MID,Brentford,1027.3,4.08,38.8,0.600,0.269,1.721
22,Habib Diarra,a,0,MID,Sunderland,1051.4,4.08,81.4,0.138,0.101,1.160
23,Brian Brobbey,d,1,FWD,Sunderland,1051.4,4.08,62.1,0.471,0.194,1.265
24,Moisés Caicedo Corozo,a,0,MID,Chelsea,1110.6,4.08,85.2,0.097,0.159,1.462
25,Lewis Dunk,a,0,DEF,Brighton,1038.3,4.06,86.4,0.039,0.047,1.215
26,Ola Aina,a,0,DEF,Nott'm Forest,1013.3,4.04,83.6,0.037,0.052,1.224
27,Axel Tuanzebe,d,0,DEF,Burnley,1085.7,4.04,76.2,0.248,0.035,1.879
28,Álex Jiménez Sánchez,a,0,DEF,Bournemouth,1060.1,4.04,86.0,0.040,0.051,1.299
29,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1086.0,4.03,85.1,0.114,0.117,1.476
30,Amadou Onana,a,0,MID,Aston Villa,1036.0,4.03,70.3,0.171,0.157,1.332
31,Jaidon Anthony,a,0,MID,Burnley,1085.7,4.02,82.2,0.162,0.099,1.836
32,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1013.3,4.01,86.6,0.035,0.047,1.266
33,Pascal Struijk,a,0,DEF,Leeds,1049.1,4.01,86.6,0.066,0.047,1.345
34,Nikola Milenković,a,0,DEF,Nott'm Forest,1013.3,4.00,86.1,0.041,0.052,1.271
35,Brenden Aaronson,a,0,MID,Leeds,1049.1,3.98,72.7,0.200,0.097,1.301
36,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1013.3,3.98,74.3,0.151,0.118,1.171
37,Lucas Digne,a,0,DEF,Aston Villa,1036.0,3.97,65.6,0.046,0.067,1.139
38,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1080.9,3.96,82.3,0.037,0.082,1.331
39,Joe Gomez,a,0,DEF,Liverpool,1039.1,3.94,66.6,0.052,0.067,1.313
40,Trai Hume,a,0,DEF,Sunderland,1051.4,3.92,84.5,0.045,0.040,1.248
41,Sepp van den Berg,a,0,DEF,Brentford,1027.3,3.91,85.4,0.041,0.058,1.446
42,Michael Kayode,a,0,DEF,Brentford,1027.3,3.90,86.1,0.048,0.042,1.457
43,Jayden Bogle,a,0,DEF,Leeds,1049.1,3.90,84.0,0.054,0.045,1.317
44,Jun'ai Byfield,a,0,DEF,Spurs,1045.8,3.89,59.4,0.247,0.086,1.565
45,Kiernan Dewsbury-Hall,a,0,MID,Everton,1125.4,3.88,84.2,0.099,0.118,1.429
46,Ethan Pinnock,a,0,DEF,Brentford,1027.3,3.88,66.3,0.158,0.081,1.578
47,Kevin Schade,a,0,MID,Brentford,1027.3,3.87,66.6,0.176,0.126,1.308
48,Marcus Tavernier,a,0,MID,Bournemouth,1060.1,3.86,66.6,0.177,0.113,1.269
49,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1013.3,3.85,80.4,0.117,0.079,1.251

In [13]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [14]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [15]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.03 minute(s)