In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 30
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 31
Squad Points: 54.82

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gibbs-White,a,100.0,31.0,MID,Nott'm Forest,Spurs,4.855139,85.0
1,B.Fernandes,a,100.0,31.0,MID,Man Utd,Bournemouth,4.808697,77.0
2,Szoboszlai,a,100.0,31.0,MID,Liverpool,Brighton,4.577335,84.0
3,Jensen,a,NaN,31.0,MID,Brentford,Leeds,4.353630,78.0
4,Konaté,a,100.0,31.0,DEF,Liverpool,Brighton,4.339623,82.0
5,Mac Allister,a,100.0,31.0,MID,Liverpool,Brighton,4.335999,78.0
6,Mings,a,100.0,31.0,DEF,Aston Villa,West Ham,4.285771,69.0
7,Maatsen,a,NaN,31.0,DEF,Aston Villa,West Ham,4.229717,66.0
8,Martinez,a,100.0,31.0,GK,Aston Villa,West Ham,3.954957,90.0
9,Raúl,a,100.0,31.0,FWD,Fulham,Burnley,3.599810,65.0
10,Brobbey,a,75.0,31.0,FWD,Sunderland,Newcastle,3.435456,64.0
11,Igor Jesus,a,100.0,31.0,FWD,Nott'm Forest,Spurs,3.185611,72.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW31 AND 35

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,David Raya Martín,1,GK,Arsenal,1106.8,15.24,89.9,NaN,NaN,1.151
1,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1028.6,15.85,71.8,0.204,0.051,1.317
2,Raúl Jiménez Rodríguez,1,FWD,Fulham,1107.2,16.95,64.7,0.368,0.058,1.374
3,Brian Brobbey,1,FWD,Sunderland,1027.9,17.32,64.4,0.340,0.109,1.232
4,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1106.8,18.78,86.7,0.053,0.065,1.056
5,Matheus Nunes,1,DEF,Man City,1084.5,18.83,86.2,0.039,0.075,0.999
6,Emiliano Martínez Romero,1,GK,Aston Villa,1007.4,19.26,89.9,NaN,NaN,1.177
7,Ian Maatsen,1,DEF,Aston Villa,1007.4,20.46,65.9,0.041,0.063,1.095
8,Mathias Jensen,1,MID,Brentford,1036.6,21.31,78.2,0.167,0.128,1.311
9,Tyrone Mings,1,DEF,Aston Villa,1007.4,21.36,69.3,0.052,0.069,1.077
10,Ibrahima Konaté,1,DEF,Liverpool,1067.9,21.86,82.1,0.042,0.042,1.074
11,Alexis Mac Allister,1,MID,Liverpool,1067.9,21.87,77.8,0.179,0.158,1.231
12,Dominik Szoboszlai,1,MID,Liverpool,1067.9,23.00,83.5,0.180,0.192,1.321
13,Bruno Borges Fernandes,1,MID,Man Utd,1084.0,23.59,76.7,0.216,0.240,1.367
14,Morgan Gibbs-White,1,MID,Nott'm Forest,1028.6,23.93,85.2,0.232,0.140,1.182

In [7]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW31 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1067.3,38.34,76.7,0.217,0.252,1.321
1,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1050.3,38.04,85.2,0.235,0.134,1.257
2,Dominik Szoboszlai,a,1,MID,Liverpool,1085.1,36.37,83.5,0.178,0.179,1.358
3,Anton Stach,a,0,MID,Leeds,1014.8,35.33,81.0,0.173,0.172,1.212
4,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1051.7,35.03,86.5,0.055,0.068,0.922
5,Jan Paul van Hecke,a,0,DEF,Brighton,1032.6,34.84,85.5,0.041,0.052,1.082
6,Ferdi Kadıoğlu,a,0,DEF,Brighton,1032.6,34.79,87.2,0.042,0.045,1.099
7,Lewis Dunk,a,0,DEF,Brighton,1032.6,34.57,86.6,0.047,0.048,1.149
8,Alexis Mac Allister,a,1,MID,Liverpool,1085.1,34.56,77.8,0.177,0.150,1.261
9,Pascal Groß,a,0,MID,Brighton,1032.6,34.49,85.8,0.098,0.192,1.102
10,Jaidon Anthony,a,0,MID,Burnley,1084.6,34.27,80.4,0.228,0.112,1.885
11,Alex Scott,a,0,MID,Bournemouth,1095.0,34.27,85.7,0.157,0.115,1.264
12,Ibrahima Konaté,a,1,DEF,Liverpool,1085.1,34.25,82.1,0.041,0.041,1.110
13,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1075.1,34.22,85.5,0.117,0.141,1.344
14,Diego Gómez Amarilla,a,0,MID,Brighton,1032.6,34.13,80.9,0.167,0.118,1.084
15,Tomáš Souček,a,0,MID,West Ham,1075.1,33.67,82.1,0.159,0.128,1.315
16,Lucas Digne,a,0,DEF,Aston Villa,1040.5,33.63,71.2,0.051,0.068,1.135
17,Pau Torres,a,0,DEF,Aston Villa,1040.5,33.59,78.3,0.042,0.041,1.142
18,Mathias Jensen,a,1,MID,Brentford,1078.6,33.57,78.2,0.168,0.124,1.424
19,Estêvão Almeida de Oliveira Gonçalves,d,0,MID,Chelsea,1080.2,33.40,53.3,0.409,0.218,1.658
20,Marc Guiu Paz,a,0,FWD,Chelsea,1080.2,33.29,46.4,0.788,0.296,1.631
21,Amadou Onana,a,0,MID,Aston Villa,1040.5,33.13,73.9,0.158,0.149,1.161
22,Cristhian Mosquera,a,0,DEF,Arsenal,1051.7,33.12,68.9,0.036,0.058,0.800
23,Habib Diarra,a,0,MID,Sunderland,1053.7,33.10,83.2,0.152,0.099,1.189
24,Tyrone Mings,a,1,DEF,Aston Villa,1040.5,32.87,69.3,0.051,0.066,1.154
25,Dwight McNeil,a,0,MID,Everton,1079.3,32.72,80.3,0.146,0.125,1.344
26,Marcus Tavernier,a,0,MID,Bournemouth,1095.0,32.71,79.4,0.155,0.116,1.310
27,Enzo Le Fée,d,0,MID,Sunderland,1053.7,32.67,84.8,0.123,0.106,1.207
28,Pascal Struijk,a,0,DEF,Leeds,1014.8,32.59,86.3,0.060,0.046,1.288
29,Matheus Nunes,a,1,DEF,Man City,1088.8,32.48,86.2,0.039,0.072,1.025
30,Jayden Bogle,a,0,DEF,Leeds,1014.8,32.29,75.8,0.056,0.049,1.187
31,Rodrigo 'Rodri' Hernandez Cascante,a,0,MID,Man City,1088.8,32.04,85.4,0.124,0.210,0.953
32,Lamare Bogarde,a,0,DEF,Aston Villa,1040.5,31.90,59.0,0.039,0.057,1.020
33,Moisés Caicedo Corozo,a,0,MID,Chelsea,1080.2,31.85,78.6,0.106,0.145,1.364
34,Ola Aina,a,0,DEF,Nott'm Forest,1050.3,31.76,86.4,0.033,0.044,1.265
35,Jack Hinshelwood,a,0,MID,Brighton,1032.6,31.73,68.4,0.172,0.125,1.093
36,Axel Disasi,a,0,DEF,West Ham,1075.1,31.71,87.3,0.037,0.041,1.284
37,Joe Rodon,a,0,DEF,Leeds,1014.8,31.67,85.5,0.036,0.050,1.266
38,Aaron Wan-Bissaka,a,0,DEF,West Ham,1075.1,31.51,87.4,0.039,0.041,1.306
39,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1078.6,31.51,87.4,NaN,NaN,1.214
40,Harvey Barnes,a,0,MID,Newcastle,1066.4,31.50,64.0,0.221,0.127,1.247
41,Nikola Milenković,a,0,DEF,Nott'm Forest,1050.3,31.49,86.8,0.039,0.040,1.298
42,Kevin Schade,a,0,MID,Brentford,1078.6,31.44,66.5,0.213,0.122,1.416
43,Santiago Ignacio Bueno,a,0,DEF,Wolves,997.1,31.38,87.4,0.043,0.055,1.029
44,Ian Maatsen,a,1,DEF,Aston Villa,1040.5,31.29,65.9,0.040,0.061,1.197
45,James Tarkowski,a,0,DEF,Everton,1079.3,31.18,86.0,0.059,0.044,1.412
46,Melker Ellborg,a,0,GK,Sunderland,1053.7,31.10,89.5,NaN,NaN,1.379
47,James Justin,a,0,DEF,Leeds,1014.8,31.08,78.1,0.035,0.047,1.277
48,Trai Hume,a,0,DEF,Sunderland,1053.7,30.99,84.8,0.038,0.041,1.287
49,Stefan Ortega Moreno,d,0,GK,Nott'm Forest,1050.3,30.83,89.7,NaN,NaN,1.437

In [9]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW31 AND 35

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1028.6,23.93,85.2,0.232,0.140,1.182
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1084.0,23.59,76.7,0.216,0.240,1.367
2,Dominik Szoboszlai,a,1,MID,Liverpool,1067.9,23.00,83.5,0.180,0.192,1.321
3,Anton Stach,a,0,MID,Leeds,1016.5,22.02,81.0,0.172,0.170,1.235
4,Alexis Mac Allister,a,1,MID,Liverpool,1067.9,21.87,77.8,0.179,0.158,1.231
5,Ibrahima Konaté,a,1,DEF,Liverpool,1067.9,21.86,82.1,0.042,0.042,1.074
6,Pau Torres,a,0,DEF,Aston Villa,1007.4,21.73,78.4,0.043,0.041,1.062
7,Lucas Digne,a,0,DEF,Aston Villa,1007.4,21.65,71.4,0.049,0.071,1.063
8,Ferdi Kadıoğlu,a,0,DEF,Brighton,1047.4,21.52,87.1,0.042,0.044,1.126
9,Jaidon Anthony,a,0,MID,Burnley,1067.9,21.49,80.5,0.224,0.116,1.768
10,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1054.4,21.48,85.5,0.117,0.147,1.308
11,Pascal Groß,a,0,MID,Brighton,1047.4,21.48,85.8,0.099,0.186,1.116
12,Jan Paul van Hecke,a,0,DEF,Brighton,1047.4,21.47,85.5,0.041,0.051,1.113
13,Alex Scott,a,0,MID,Bournemouth,1096.1,21.45,85.7,0.157,0.117,1.263
14,Tyrone Mings,a,1,DEF,Aston Villa,1007.4,21.36,69.3,0.052,0.069,1.077
15,Lewis Dunk,a,0,DEF,Brighton,1047.4,21.32,86.5,0.049,0.049,1.184
16,Mathias Jensen,a,1,MID,Brentford,1036.6,21.31,78.2,0.167,0.128,1.311
17,Diego Gómez Amarilla,a,0,MID,Brighton,1047.4,21.23,80.8,0.167,0.114,1.096
18,Tomáš Souček,a,0,MID,West Ham,1054.4,21.21,82.2,0.160,0.134,1.271
19,Amadou Onana,a,0,MID,Aston Villa,1007.4,20.98,73.8,0.159,0.159,1.064
20,Habib Diarra,a,0,MID,Sunderland,1027.9,20.94,83.2,0.153,0.103,1.106
21,Marc Guiu Paz,a,0,FWD,Chelsea,1096.3,20.89,46.4,0.800,0.294,1.619
22,Estêvão Almeida de Oliveira Gonçalves,d,0,MID,Chelsea,1096.3,20.74,53.3,0.406,0.217,1.746
23,Enzo Le Fée,d,0,MID,Sunderland,1027.9,20.68,84.8,0.124,0.110,1.143
24,Lamare Bogarde,a,0,DEF,Aston Villa,1007.4,20.64,58.9,0.039,0.058,0.947
25,Axel Disasi,a,0,DEF,West Ham,1054.4,20.53,87.3,0.037,0.042,1.189
26,Aaron Wan-Bissaka,a,0,DEF,West Ham,1054.4,20.48,87.4,0.040,0.042,1.203
27,Ola Aina,a,0,DEF,Nott'm Forest,1028.6,20.48,86.4,0.033,0.045,1.195
28,Ian Maatsen,a,1,DEF,Aston Villa,1007.4,20.46,65.9,0.041,0.063,1.095
29,Marcus Tavernier,a,0,MID,Bournemouth,1096.1,20.43,79.4,0.154,0.117,1.328
30,Nikola Milenković,a,0,DEF,Nott'm Forest,1028.6,20.32,86.8,0.039,0.041,1.227
31,Dwight McNeil,a,0,MID,Everton,1118.8,20.20,80.3,0.145,0.119,1.417
32,Kevin Schade,a,0,MID,Brentford,1036.6,20.10,66.5,0.219,0.132,1.283
33,Trai Hume,a,0,DEF,Sunderland,1027.9,20.05,84.8,0.038,0.041,1.221
34,Pascal Struijk,a,0,DEF,Leeds,1016.5,19.89,86.3,0.059,0.045,1.357
35,Luke O'Nien,a,0,DEF,Sunderland,1027.9,19.89,74.5,0.031,0.044,1.160
36,Moisés Caicedo Corozo,a,0,MID,Chelsea,1096.3,19.86,78.9,0.105,0.146,1.401
37,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1036.6,19.83,87.5,NaN,NaN,1.170
38,Jack Hinshelwood,a,0,MID,Brighton,1047.4,19.73,68.4,0.173,0.120,1.112
39,El Hadji Malick Diouf,a,0,DEF,West Ham,1054.4,19.72,79.5,0.033,0.046,1.224
40,Jayden Bogle,a,0,DEF,Leeds,1016.5,19.64,75.8,0.056,0.050,1.265
41,Melker Ellborg,a,0,GK,Sunderland,1027.9,19.56,89.5,NaN,NaN,1.338
42,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1007.4,19.50,67.0,0.151,0.143,1.088
43,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1028.6,19.48,86.1,0.033,0.036,1.321
44,Harvey Barnes,a,0,MID,Newcastle,1096.9,19.43,64.0,0.220,0.120,1.313
45,Joe Rodon,a,0,DEF,Leeds,1016.5,19.32,85.5,0.037,0.049,1.335
46,Emiliano Martínez Romero,a,1,GK,Aston Villa,1007.4,19.26,89.9,NaN,NaN,1.177
47,Nordi Mukiele,d,0,DEF,Sunderland,1027.9,19.22,65.5,0.081,0.071,1.288
48,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1028.6,19.20,78.7,0.122,0.071,1.191
49,Jean-Clair Todibo,a,0,DEF,West Ham,1054.4,19.19,85.8,0.037,0.037,1.323

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 31 to 35

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,Chelsea,a,Marc Guiu Paz,20.892164,Igor Jesus Maciel da Cruz,15.852532,5.039632
1,GK,Brentford,a,Hákon Rafn Valdimarsson,19.825073,David Raya Martín,15.237779,4.587294
2,GK,Sunderland,a,Melker Ellborg,19.557949,David Raya Martín,15.237779,4.320170
3,GK,Nott'm Forest,d,Stefan Ortega Moreno,18.980148,David Raya Martín,15.237779,3.742369
4,GK,West Ham,a,Mads Hermansen,18.593247,David Raya Martín,15.237779,3.355468
5,GK,Nott'm Forest,a,Matz Sels,18.409028,David Raya Martín,15.237779,3.171249
6,DEF,Aston Villa,a,Pau Torres,21.726345,Gabriel dos Santos Magalhães,18.780811,2.945535
7,DEF,Aston Villa,a,Lucas Digne,21.652628,Gabriel dos Santos Magalhães,18.780811,2.871818
8,DEF,Brighton,a,Ferdi Kadıoğlu,21.524962,Gabriel dos Santos Magalhães,18.780811,2.744151
9,DEF,Brighton,a,Jan Paul van Hecke,21.468085,Gabriel dos Santos Magalhães,18.780811,2.687274
10,GK,Leeds,a,Lucas Estella Perri,17.883995,David Raya Martín,15.237779,2.646216
11,DEF,Brighton,a,Lewis Dunk,21.320109,Gabriel dos Santos Magalhães,18.780811,2.539298
12,GK,Man Utd,a,Altay Bayındır,17.754710,David Raya Martín,15.237779,2.516931
13,FWD,Brighton,a,Danny Welbeck,18.177288,Igor Jesus Maciel da Cruz,15.852532,2.324756
14,GK,Spurs,a,Guglielmo Vicario,17.377699,David Raya Martín,15.237779,2.139920
15,GK,Chelsea,a,Filip Jörgensen,17.209154,David Raya Martín,15.237779,1.971376
16,FWD,Spurs,a,Dominic Solanke-Mitchell,17.765737,Igor Jesus Maciel da Cruz,15.852532,1.913205
17,DEF,Aston Villa,a,Lamare Bogarde,20.636243,Gabriel dos Santos Magalhães,18.780811,1.855433
18,DEF,West Ham,a,Axel Disasi,20.533587,Gabriel dos Santos Magalhães,18.780811,1.752776
19,GK,Leeds,a,Karl Darlow,16.943224,David Raya Martín,15.237779,1.705445

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Leandro Trossard'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 31 and 35:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Leandro Trossard,32.0,MID,Arsenal,Bournemouth,6.6,1066.816076,4.082188,62.923835,0.215749,0.141395,0.949527
1,Leandro Trossard,33.0,MID,Arsenal,Man City,6.6,1226.620831,3.921245,63.717531,0.219547,0.129335,1.318867
2,Leandro Trossard,34.0,MID,Arsenal,Newcastle,6.6,1090.007827,4.023728,63.102850,0.215749,0.141395,1.140527
3,Leandro Trossard,35.0,MID,Arsenal,Fulham,6.6,1043.771647,4.194232,62.923835,0.216286,0.141754,0.793753

In [12]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'MID'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW31 to GW35
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1028.6,4.80,85.2,0.232,0.140,1.182
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1084.0,4.76,76.7,0.216,0.240,1.367
2,Dominik Szoboszlai,a,1,MID,Liverpool,1067.9,4.60,83.5,0.180,0.192,1.321
3,Alexis Mac Allister,a,1,MID,Liverpool,1067.9,4.37,77.8,0.179,0.158,1.231
4,Ibrahima Konaté,a,1,DEF,Liverpool,1067.9,4.37,82.1,0.042,0.042,1.074
5,Pau Torres,a,0,DEF,Aston Villa,1007.4,4.35,78.4,0.043,0.041,1.062
6,Anton Stach,a,0,MID,Leeds,1016.5,4.34,81.0,0.172,0.170,1.235
7,Lucas Digne,a,0,DEF,Aston Villa,1007.4,4.33,71.4,0.049,0.071,1.063
8,Ferdi Kadıoğlu,a,0,DEF,Brighton,1047.4,4.31,87.1,0.042,0.044,1.126
9,Pascal Groß,a,0,MID,Brighton,1047.4,4.31,85.8,0.099,0.186,1.116
10,Jan Paul van Hecke,a,0,DEF,Brighton,1047.4,4.31,85.5,0.041,0.051,1.113
11,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1054.4,4.30,85.5,0.117,0.147,1.308
12,Jaidon Anthony,a,0,MID,Burnley,1067.9,4.29,80.5,0.224,0.116,1.768
13,Lewis Dunk,a,0,DEF,Brighton,1047.4,4.28,86.5,0.049,0.049,1.184
14,Mathias Jensen,a,1,MID,Brentford,1036.6,4.27,78.2,0.167,0.128,1.311
15,Alex Scott,a,0,MID,Bournemouth,1096.1,4.26,85.7,0.157,0.117,1.263
16,Tomáš Souček,a,0,MID,West Ham,1054.4,4.25,82.2,0.160,0.134,1.271
17,Tyrone Mings,a,1,DEF,Aston Villa,1007.4,4.25,69.3,0.052,0.069,1.077
18,Diego Gómez Amarilla,a,0,MID,Brighton,1047.4,4.25,80.8,0.167,0.114,1.096
19,Amadou Onana,a,0,MID,Aston Villa,1007.4,4.19,73.8,0.159,0.159,1.064
20,Marc Guiu Paz,a,0,FWD,Chelsea,1096.3,4.18,46.4,0.800,0.294,1.619
21,Ola Aina,a,0,DEF,Nott'm Forest,1028.6,4.16,86.4,0.033,0.045,1.195
22,Habib Diarra,a,0,MID,Sunderland,1027.9,4.16,83.2,0.153,0.103,1.106
23,Nikola Milenković,a,0,DEF,Nott'm Forest,1028.6,4.14,86.8,0.039,0.041,1.227
24,Lamare Bogarde,a,0,DEF,Aston Villa,1007.4,4.12,58.9,0.039,0.058,0.947
25,Enzo Le Fée,d,0,MID,Sunderland,1027.9,4.11,84.8,0.124,0.110,1.143
26,Aaron Wan-Bissaka,a,0,DEF,West Ham,1054.4,4.11,87.4,0.040,0.042,1.203
27,Estêvão Almeida de Oliveira Gonçalves,d,0,MID,Chelsea,1096.3,4.11,53.3,0.406,0.217,1.746
28,Axel Disasi,a,0,DEF,West Ham,1054.4,4.10,87.3,0.037,0.042,1.189
29,Ian Maatsen,a,1,DEF,Aston Villa,1007.4,4.10,65.9,0.041,0.063,1.095
30,Marcus Tavernier,a,0,MID,Bournemouth,1096.1,4.06,79.4,0.154,0.117,1.328
31,Kevin Schade,a,0,MID,Brentford,1036.6,4.03,66.5,0.219,0.132,1.283
32,Dwight McNeil,a,0,MID,Everton,1118.8,4.03,80.3,0.145,0.119,1.417
33,El Hadji Malick Diouf,a,0,DEF,West Ham,1054.4,4.00,79.5,0.033,0.046,1.224
34,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1028.6,3.99,86.1,0.033,0.036,1.321
35,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1036.6,3.96,87.5,NaN,NaN,1.170
36,Moisés Caicedo Corozo,a,0,MID,Chelsea,1096.3,3.96,78.9,0.105,0.146,1.401
37,Jack Hinshelwood,a,0,MID,Brighton,1047.4,3.95,68.4,0.173,0.120,1.112
38,Trai Hume,a,0,DEF,Sunderland,1027.9,3.94,84.8,0.038,0.041,1.221
39,Melker Ellborg,a,0,GK,Sunderland,1027.9,3.91,89.5,NaN,NaN,1.338
40,Harvey Barnes,a,0,MID,Newcastle,1096.9,3.91,64.0,0.220,0.120,1.313
41,Pascal Struijk,a,0,DEF,Leeds,1016.5,3.89,86.3,0.059,0.045,1.357
42,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1007.4,3.89,67.0,0.151,0.143,1.088
43,Emiliano Martínez Romero,a,1,GK,Aston Villa,1007.4,3.87,89.9,NaN,NaN,1.177
44,Luke O'Nien,a,0,DEF,Sunderland,1027.9,3.87,74.5,0.031,0.044,1.160
45,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1028.6,3.85,78.7,0.122,0.071,1.191
46,Reiss Nelson,d,0,MID,Brentford,1036.6,3.84,35.6,0.613,0.265,1.716
47,Jean-Clair Todibo,a,0,DEF,West Ham,1054.4,3.84,85.8,0.037,0.037,1.323
48,Stefan Ortega Moreno,d,0,GK,Nott'm Forest,1028.6,3.83,89.7,NaN,NaN,1.418
49,Ethan Pinnock,a,0,DEF,Brentford,1036.6,3.83,68.4,0.138,0.042,1.497

In [13]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [14]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [15]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.02 minute(s)