In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 26
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 27
Squad Points: 70.83

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,27.0,DEF,Arsenal,Spurs,5.876090,86.0
1,Raya,a,NaN,27.0,GK,Arsenal,Spurs,4.965271,90.0
2,Konaté,a,100.0,27.0,DEF,Liverpool,Nott'm Forest,4.958979,87.0
3,B.Fernandes,a,100.0,27.0,MID,Man Utd,Everton,4.790409,85.0
4,Trossard,a,75.0,27.0,MID,Arsenal,Spurs,4.758223,75.0
5,Szoboszlai,a,0.0,27.0,MID,Liverpool,Nott'm Forest,4.614007,83.0
6,Martinez,a,100.0,27.0,GK,Aston Villa,Leeds,4.541445,87.0
7,Matheus N.,a,100.0,27.0,DEF,Man City,Newcastle,4.484185,83.0
8,Khusanov,a,100.0,27.0,DEF,Man City,Newcastle,4.262861,82.0
9,Amad,a,100.0,27.0,MID,Man Utd,Everton,4.103710,82.0
10,Gibbs-White,a,100.0,27.0,MID,Nott'm Forest,Liverpool,3.982940,83.0
11,Raúl,a,100.0,27.0,FWD,Fulham,Sunderland,3.839644,66.0
12,Brobbey,a,100.0,27.0,FWD,Sunderland,Fulham,3.575302,78.0
13,Tarkowski,a,NaN,27.0,DEF,Everton,Man Utd,3.470932,87.0
14,Igor Jesus,a,100.0,27.0,FWD,Nott'm Forest,Liverpool,2.726889,57.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW27 AND 31

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1096.2,14.05,56.7,0.233,0.056,1.458
1,David Raya Martín,1,GK,Arsenal,1059.8,17.08,89.7,NaN,NaN,0.834
2,Brian Brobbey,1,FWD,Sunderland,1048.5,17.81,77.8,0.248,0.074,1.291
3,Leandro Trossard,1,MID,Arsenal,1059.8,18.24,75.6,0.192,0.167,0.939
4,James Tarkowski,1,DEF,Everton,1091.0,18.55,87.4,0.041,0.042,1.462
5,Raúl Jiménez Rodríguez,1,FWD,Fulham,980.9,19.20,65.8,0.490,0.048,1.110
6,Abdukodir Khusanov,1,DEF,Man City,1016.5,19.47,80.8,0.038,0.056,0.869
7,Matheus Nunes,1,DEF,Man City,1016.5,20.14,82.5,0.039,0.120,0.893
8,Amad Diallo,1,MID,Man Utd,1086.6,20.54,81.7,0.146,0.126,1.453
9,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1059.8,20.59,85.8,0.062,0.124,0.907
10,Morgan Gibbs-White,1,MID,Nott'm Forest,1096.2,20.93,82.6,0.151,0.118,1.459
11,Emiliano Martínez Romero,1,GK,Aston Villa,1021.7,21.06,87.2,NaN,NaN,1.005
12,Dominik Szoboszlai,1,MID,Liverpool,988.4,23.08,83.0,0.167,0.182,0.944
13,Bruno Borges Fernandes,1,MID,Man Utd,1086.6,23.89,85.2,0.214,0.191,1.438
14,Ibrahima Konaté,1,DEF,Liverpool,988.4,24.72,87.4,0.053,0.049,0.881

In [7]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
        -- AND position IN ('MID','FWD')
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 27

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Caicedo,a,100.0,27.0,MID,Chelsea,Burnley,5.004652
1,Hincapie,a,100.0,27.0,DEF,Arsenal,Spurs,4.997345
2,Mings,a,100.0,27.0,DEF,Aston Villa,Leeds,4.880462
3,Bogarde,a,100.0,27.0,DEF,Aston Villa,Leeds,4.827297
4,Mosquera,a,100.0,27.0,DEF,Arsenal,Spurs,4.668918
5,Pau,a,100.0,27.0,DEF,Aston Villa,Leeds,4.656201
6,Pinnock,a,100.0,27.0,DEF,Brentford,Brighton,4.638848
7,Maatsen,a,NaN,27.0,DEF,Aston Villa,Leeds,4.638782
8,Digne,a,100.0,27.0,DEF,Aston Villa,Leeds,4.614454
9,Robertson,a,NaN,27.0,DEF,Liverpool,Nott'm Forest,4.604169

In [8]:
print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 38
    ORDER BY xpoints DESC
""")
view.head(10)

When to use second TRIPLE CAPTAIN chip (gws19-38)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,37.0,DEF,Arsenal,Burnley,6.103427
1,Gabriel dos Santos Magalhães,27.0,DEF,Arsenal,Spurs,5.876090
2,Gabriel dos Santos Magalhães,36.0,DEF,Arsenal,West Ham,5.873360
3,Matheus Nunes,34.0,DEF,Man City,Burnley,5.483741
4,Abdukodir Khusanov,34.0,DEF,Man City,Burnley,5.305870
5,Matheus Nunes,28.0,DEF,Man City,Leeds,5.283530
6,Matheus Nunes,30.0,DEF,Man City,West Ham,5.277119
7,Gabriel dos Santos Magalhães,35.0,DEF,Arsenal,Fulham,5.233876
8,Abdukodir Khusanov,28.0,DEF,Man City,Leeds,5.225590
9,Abdukodir Khusanov,30.0,DEF,Man City,West Ham,5.188583

In [ ]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW27 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1077.7,57.81,85.2,0.214,0.192,1.384
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1052.5,56.93,85.7,0.062,0.129,0.899
2,Ibrahima Konaté,a,1,DEF,Liverpool,1047.9,56.21,87.4,0.054,0.046,0.989
3,Lamare Bogarde,a,0,DEF,Aston Villa,1039.8,56.02,68.5,0.037,0.063,0.797
4,Mathias Jensen,a,0,MID,Brentford,1045.1,55.46,76.1,0.246,0.164,1.247
5,Tyrone Mings,a,0,DEF,Aston Villa,1039.8,55.44,78.1,0.040,0.051,0.922
6,Ethan Pinnock,a,0,DEF,Brentford,1045.1,55.15,69.9,0.254,0.057,1.409
7,Ian Maatsen,a,0,DEF,Aston Villa,1039.8,54.85,69.4,0.040,0.074,0.873
8,Vitaly Janelt,a,0,MID,Brentford,1045.1,54.49,85.8,0.150,0.183,1.230
9,Dominik Szoboszlai,a,1,MID,Liverpool,1047.9,53.96,83.0,0.165,0.168,1.147
10,Andrew Robertson,a,0,DEF,Liverpool,1047.9,53.63,66.3,0.044,0.057,0.902
11,Moisés Caicedo Corozo,a,0,MID,Chelsea,1086.9,53.51,85.7,0.143,0.188,1.313
12,Pau Torres,a,0,DEF,Aston Villa,1039.8,53.36,77.5,0.042,0.044,0.990
13,Dango Ouattara,a,0,MID,Brentford,1045.1,52.41,75.2,0.207,0.138,1.234
14,Lucas Digne,a,0,DEF,Aston Villa,1039.8,52.33,61.1,0.042,0.074,0.879
15,Matheus Nunes,a,1,DEF,Man City,1066.5,52.15,82.3,0.039,0.116,1.026
16,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1091.8,51.72,86.5,0.134,0.168,1.507
17,Kevin Schade,a,0,MID,Brentford,1045.1,51.00,51.6,0.437,0.187,1.273
18,John Stones,a,0,DEF,Man City,1066.5,50.98,55.8,0.281,0.126,1.241
19,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1061.0,50.94,72.4,0.195,0.154,1.304
20,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1081.0,50.70,82.6,0.154,0.124,1.399
21,Habib Diarra,a,0,MID,Sunderland,1051.2,50.15,80.6,0.156,0.125,1.260
22,Alex Scott,a,0,MID,Bournemouth,1061.0,50.08,84.3,0.142,0.109,1.284
23,Leandro Trossard,a,1,MID,Arsenal,1052.5,50.06,75.6,0.193,0.164,0.955
24,Pascal Groß,a,0,MID,Brighton,1054.0,49.89,84.9,0.127,0.118,1.281
25,Abdukodir Khusanov,a,1,DEF,Man City,1066.5,49.85,81.1,0.038,0.053,1.016
26,Amad Diallo,a,1,MID,Man Utd,1077.7,49.66,81.8,0.145,0.129,1.403
27,Michael Kayode,a,0,DEF,Brentford,1045.1,49.57,87.2,0.039,0.049,1.202
28,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1039.8,49.52,77.9,0.133,0.122,1.114
29,Marc Guiu Paz,a,0,FWD,Chelsea,1086.9,49.51,44.8,0.789,0.339,1.600
30,Emiliano Martínez Romero,a,1,GK,Aston Villa,1039.8,49.41,87.2,NaN,NaN,1.072
31,Alex Iwobi,a,0,MID,Fulham,1053.9,49.11,83.1,0.133,0.127,1.397
32,Jayden Bogle,a,0,DEF,Leeds,1046.0,49.10,84.5,0.069,0.048,1.316
33,Alexis Mac Allister,a,0,MID,Liverpool,1047.9,48.97,72.6,0.162,0.122,1.142
34,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1077.7,48.88,87.1,0.041,0.068,1.270
35,Ryan Gravenberch,a,0,MID,Liverpool,1047.9,48.71,86.7,0.075,0.142,1.198
36,Enzo Le Fée,a,0,MID,Sunderland,1051.2,48.49,86.4,0.090,0.127,1.267
37,Reiss Nelson,a,0,MID,Brentford,1045.1,48.41,45.7,0.481,0.249,1.608
38,Amadou Onana,a,0,MID,Aston Villa,1039.8,48.39,72.0,0.143,0.127,1.069
39,Amine Adli,a,0,MID,Bournemouth,1061.0,48.23,73.8,0.157,0.122,1.304
40,Rico Henry,a,0,DEF,Brentford,1045.1,48.05,81.2,0.039,0.050,1.215
41,Sepp van den Berg,a,0,DEF,Brentford,1045.1,47.99,84.2,0.039,0.041,1.235
42,Tomáš Souček,a,0,MID,West Ham,1091.8,47.68,82.3,0.149,0.086,1.501
43,Piero Hincapié,a,0,DEF,Arsenal,1052.5,47.55,75.8,0.041,0.059,1.073
44,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1081.0,47.48,82.9,0.140,0.081,1.427
45,Kristoffer Ajer,a,0,DEF,Brentford,1045.1,47.45,75.8,0.039,0.050,1.194
46,Emiliano Buendía Stati,a,0,MID,Aston Villa,1039.8,47.39,67.7,0.163,0.122,1.076
47,David Raya Martín,a,1,GK,Arsenal,1052.5,47.32,89.7,NaN,NaN,0.817
48,Luke Shaw,a,0,DEF,Man Utd,1077.7,47.04,87.5,0.039,0.046,1.319
49,Lisandro Martínez,a,0,DEF,Man Utd,1077.7,46.97,83.5,0.039,0.047,1.290

In [20]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW27 AND 31

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ibrahima Konaté,1,DEF,Liverpool,988.4,24.72,87.4,0.053,0.049,0.881
1,Bruno Borges Fernandes,1,MID,Man Utd,1086.6,23.89,85.2,0.214,0.191,1.438
2,Andrew Robertson,0,DEF,Liverpool,988.4,23.68,66.5,0.044,0.061,0.802
3,Ethan Pinnock,0,DEF,Brentford,984.1,23.63,69.9,0.252,0.064,1.344
4,Vitaly Janelt,0,MID,Brentford,984.1,23.44,85.7,0.157,0.201,1.113
5,Lamare Bogarde,0,DEF,Aston Villa,1021.7,23.43,68.5,0.036,0.061,0.793
6,Tyrone Mings,0,DEF,Aston Villa,1021.7,23.40,78.1,0.038,0.051,0.894
7,Mathias Jensen,0,MID,Brentford,984.1,23.33,75.8,0.243,0.161,1.128
8,Dominik Szoboszlai,1,MID,Liverpool,988.4,23.08,83.0,0.167,0.182,0.944
9,Ian Maatsen,0,DEF,Aston Villa,1021.7,22.96,69.7,0.039,0.072,0.865
10,Dango Ouattara,0,MID,Brentford,984.1,22.61,75.1,0.217,0.150,1.101
11,Pau Torres,0,DEF,Aston Villa,1021.7,22.47,77.5,0.043,0.042,0.973
12,Moisés Caicedo Corozo,0,MID,Chelsea,1089.9,22.45,85.7,0.147,0.184,1.301
13,Lucas Digne,0,DEF,Aston Villa,1021.7,21.98,61.4,0.042,0.070,0.867
14,Michael Kayode,0,DEF,Brentford,984.1,21.83,87.2,0.041,0.051,1.103
15,Rayan Vitor Simplício Rocha,0,MID,Bournemouth,1017.6,21.76,72.5,0.199,0.168,1.172
16,Kevin Schade,0,MID,Brentford,984.1,21.58,51.4,0.436,0.192,1.150
17,Alex Scott,0,MID,Bournemouth,1017.6,21.16,84.3,0.145,0.114,1.207
18,Rico Henry,0,DEF,Brentford,984.1,21.14,81.2,0.040,0.051,1.126
19,Emiliano Martínez Romero,1,GK,Aston Villa,1021.7,21.06,87.2,NaN,NaN,1.005
20,Ryan Gravenberch,0,MID,Liverpool,988.4,20.98,86.7,0.076,0.161,0.979
21,Kristoffer Ajer,0,DEF,Brentford,984.1,20.96,75.8,0.040,0.052,1.097
22,Alexis Mac Allister,0,MID,Liverpool,988.4,20.96,72.1,0.167,0.127,0.934
23,Morgan Gibbs-White,1,MID,Nott'm Forest,1096.2,20.93,82.6,0.151,0.118,1.459
24,Alex Iwobi,0,MID,Fulham,980.9,20.91,83.0,0.134,0.140,1.209
25,Habib Diarra,0,MID,Sunderland,1048.5,20.87,80.7,0.156,0.120,1.248
26,Sepp van den Berg,0,DEF,Brentford,984.1,20.87,84.1,0.039,0.043,1.162
27,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1137.1,20.87,86.5,0.132,0.147,1.714
28,Douglas Luiz Soares de Paulo,0,MID,Aston Villa,1021.7,20.72,77.7,0.132,0.123,1.057
29,Marc Guiu Paz,0,FWD,Chelsea,1089.9,20.63,44.8,0.792,0.335,1.608
30,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1059.8,20.59,85.8,0.062,0.124,0.907
31,Amad Diallo,1,MID,Man Utd,1086.6,20.54,81.7,0.146,0.126,1.453
32,Amine Adli,0,MID,Bournemouth,1017.6,20.54,73.6,0.160,0.130,1.187
33,Reiss Nelson,0,MID,Brentford,984.1,20.48,45.8,0.472,0.267,1.409
34,Pascal Groß,0,MID,Brighton,1112.1,20.31,84.9,0.124,0.106,1.374
35,Amadou Onana,0,MID,Aston Villa,1021.7,20.31,71.8,0.143,0.128,1.020
36,Timothy Castagne,0,DEF,Fulham,980.9,20.22,76.5,0.041,0.043,1.151
37,Enzo Le Fée,0,MID,Sunderland,1048.5,20.17,86.5,0.091,0.123,1.252
38,Matheus Nunes,1,DEF,Man City,1016.5,20.14,82.5,0.039,0.120,0.893
39,Diogo Dalot Teixeira,0,DEF,Man Utd,1086.6,19.94,87.1,0.041,0.067,1.313
40,Emiliano Buendía Stati,0,MID,Aston Villa,1021.7,19.91,67.8,0.163,0.122,1.030
41,Antonee Robinson,0,DEF,Fulham,980.9,19.90,69.2,0.040,0.048,1.117
42,John Stones,0,DEF,Man City,1016.5,19.76,55.6,0.281,0.136,1.083
43,Ibrahim Sangaré,0,MID,Nott'm Forest,1096.2,19.56,83.0,0.136,0.078,1.480
44,Jorge Cuenca Barreno,0,DEF,Fulham,980.9,19.50,72.7,0.039,0.056,1.219
45,Abdukodir Khusanov,1,DEF,Man City,1016.5,19.47,80.8,0.038,0.056,0.869
46,Álex Jiménez Sánchez,0,DEF,Bournemouth,1017.6,19.44,86.6,0.046,0.046,1.349
47,Emile Smith Rowe,0,MID,Fulham,980.9,19.34,67.0,0.156,0.119,1.037
48,Tomáš Souček,0,MID,West Ham,1137.1,19.28,81.9,0.142,0.078,1.697
49,Victor Lindelöf,0,DEF,Aston Villa,1021.7,19.27,31.5,0.036,0.061,0.830

In [ ]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 27 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,Chelsea,Marc Guiu Paz,20.631298,Igor Jesus Maciel da Cruz,14.054026,6.577272
1,MID,Brentford,Vitaly Janelt,23.435497,Leandro Trossard,18.240323,5.195174
2,DEF,Liverpool,Andrew Robertson,23.681421,James Tarkowski,18.550833,5.130588
3,MID,Brentford,Mathias Jensen,23.326428,Leandro Trossard,18.240323,5.086106
4,DEF,Brentford,Ethan Pinnock,23.630310,James Tarkowski,18.550833,5.079477
5,DEF,Aston Villa,Lamare Bogarde,23.431650,James Tarkowski,18.550833,4.880818
6,DEF,Aston Villa,Tyrone Mings,23.404055,James Tarkowski,18.550833,4.853222
7,DEF,Aston Villa,Ian Maatsen,22.960449,James Tarkowski,18.550833,4.409617
8,MID,Brentford,Dango Ouattara,22.609728,Leandro Trossard,18.240323,4.369406
9,MID,Chelsea,Moisés Caicedo Corozo,22.451307,Leandro Trossard,18.240323,4.210984
10,DEF,Aston Villa,Pau Torres,22.466599,James Tarkowski,18.550833,3.915766
11,MID,Bournemouth,Rayan Vitor Simplício Rocha,21.764784,Leandro Trossard,18.240323,3.524462
12,DEF,Aston Villa,Lucas Digne,21.979124,James Tarkowski,18.550833,3.428291
13,MID,Brentford,Kevin Schade,21.582905,Leandro Trossard,18.240323,3.342583
14,DEF,Brentford,Michael Kayode,21.833187,James Tarkowski,18.550833,3.282354
15,MID,Bournemouth,Alex Scott,21.156674,Leandro Trossard,18.240323,2.916351
16,FWD,Nott'm Forest,Lorenzo Lucca,16.881350,Igor Jesus Maciel da Cruz,14.054026,2.827323
17,MID,Liverpool,Ryan Gravenberch,20.977905,Leandro Trossard,18.240323,2.737583
18,MID,Liverpool,Alexis Mac Allister,20.960577,Leandro Trossard,18.240323,2.720255
19,MID,Fulham,Alex Iwobi,20.905277,Leandro Trossard,18.240323,2.664955

In [12]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Amad Diallo'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 27 and 31:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Amad Diallo,27.0,MID,Man Utd,Everton,6.2,1061.380748,4.103710,81.621837,0.144790,0.126306,1.469426
1,Amad Diallo,28.0,MID,Man Utd,Crystal Palace,6.2,1043.713830,4.164325,81.621837,0.145407,0.136792,1.401668
2,Amad Diallo,29.0,MID,Man Utd,Newcastle,6.2,1083.811172,4.153283,81.703887,0.152304,0.131441,1.465189
3,Amad Diallo,30.0,MID,Man Utd,Aston Villa,6.2,1168.435218,4.019103,81.717253,0.140624,0.115812,1.461520
4,Amad Diallo,31.0,MID,Man Utd,Bournemouth,6.2,1075.489641,4.100769,81.621837,0.144790,0.121977,1.466781

In [13]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.25 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW27 to GW31

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1059.8,5.59,85.8,0.062,0.124,0.907
1,Fábio Freitas Gouveia Carvalho,0,MID,Brentford,984.1,5.14,49.9,0.643,0.328,1.574
2,Conor Bradley,0,DEF,Liverpool,988.4,5.13,67.4,0.198,0.162,1.059
3,Ibrahima Konaté,1,DEF,Liverpool,988.4,4.98,87.4,0.053,0.049,0.881
4,Joško Gvardiol,0,DEF,Man City,1016.5,4.96,67.5,0.238,0.077,0.962
5,Tyrone Mings,0,DEF,Aston Villa,1021.7,4.86,78.1,0.038,0.051,0.894
6,Moisés Caicedo Corozo,0,MID,Chelsea,1089.9,4.84,85.7,0.147,0.184,1.301
7,Lamare Bogarde,0,DEF,Aston Villa,1021.7,4.81,68.5,0.036,0.061,0.793
8,Bruno Borges Fernandes,1,MID,Man Utd,1086.6,4.80,85.2,0.214,0.191,1.438
9,Piero Hincapié,0,DEF,Arsenal,1059.8,4.73,75.9,0.041,0.058,1.087
10,Ethan Pinnock,0,DEF,Brentford,984.1,4.70,69.9,0.252,0.064,1.344
11,Andrew Robertson,0,DEF,Liverpool,988.4,4.67,66.5,0.044,0.061,0.802
12,Leandro Trossard,1,MID,Arsenal,1059.8,4.67,75.6,0.192,0.167,0.939
13,Matheus Nunes,1,DEF,Man City,1016.5,4.66,82.5,0.039,0.120,0.893
14,David Raya Martín,1,GK,Arsenal,1059.8,4.66,89.7,NaN,NaN,0.834
15,Pau Torres,0,DEF,Aston Villa,1021.7,4.66,77.5,0.043,0.042,0.973
16,Ian Maatsen,0,DEF,Aston Villa,1021.7,4.65,69.7,0.039,0.072,0.865
17,John Stones,0,DEF,Man City,1016.5,4.62,55.6,0.281,0.136,1.083
18,Dominik Szoboszlai,1,MID,Liverpool,988.4,4.62,83.0,0.167,0.182,0.944
19,Mathias Jensen,0,MID,Brentford,984.1,4.61,75.8,0.243,0.161,1.128
20,Lucas Digne,0,DEF,Aston Villa,1021.7,4.60,61.4,0.042,0.070,0.867
21,Jean-Philippe Mateta,0,FWD,Crystal Palace,993.5,4.60,57.8,0.678,0.229,1.392
22,Vitaly Janelt,0,MID,Brentford,984.1,4.56,85.7,0.157,0.201,1.113
23,Emiliano Martínez Romero,1,GK,Aston Villa,1021.7,4.50,87.2,NaN,NaN,1.005
24,Cristhian Mosquera,0,DEF,Arsenal,1059.8,4.49,79.0,0.039,0.041,1.109
25,Abdukodir Khusanov,1,DEF,Man City,1016.5,4.47,80.8,0.038,0.056,0.869
26,Dango Ouattara,0,MID,Brentford,984.1,4.41,75.1,0.217,0.150,1.101
27,Rayan Vitor Simplício Rocha,0,MID,Bournemouth,1017.6,4.39,72.5,0.199,0.168,1.172
28,Marc Guiu Paz,0,FWD,Chelsea,1089.9,4.33,44.8,0.792,0.335,1.608
29,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1137.1,4.31,86.5,0.132,0.147,1.714
30,John McGinn,0,MID,Aston Villa,1021.7,4.29,58.2,0.305,0.164,1.185
31,Alex Scott,0,MID,Bournemouth,1017.6,4.28,84.3,0.145,0.114,1.207
32,Chris Richards,0,DEF,Crystal Palace,993.5,4.28,85.5,0.045,0.040,1.329
33,Kevin Schade,0,MID,Brentford,984.1,4.26,51.4,0.436,0.192,1.150
34,Rayan Aït-Nouri,0,DEF,Man City,1016.5,4.24,71.1,0.037,0.075,0.946
35,Ryan Gravenberch,0,MID,Liverpool,988.4,4.23,86.7,0.076,0.161,0.979
36,Douglas Luiz Soares de Paulo,0,MID,Aston Villa,1021.7,4.22,77.7,0.132,0.123,1.057
37,Alexis Mac Allister,0,MID,Liverpool,988.4,4.21,72.1,0.167,0.127,0.934
38,Álex Jiménez Sánchez,0,DEF,Bournemouth,1017.6,4.20,86.6,0.046,0.046,1.349
39,Justin Kluivert,0,MID,Bournemouth,1017.6,4.20,55.7,0.331,0.207,1.352
40,Habib Diarra,0,MID,Sunderland,1048.5,4.20,80.7,0.156,0.120,1.248
41,Amine Adli,0,MID,Bournemouth,1017.6,4.18,73.6,0.160,0.130,1.187
42,Jeremie Frimpong,0,DEF,Liverpool,988.4,4.18,60.5,0.046,0.058,0.975
43,Michael Kayode,0,DEF,Brentford,984.1,4.17,87.2,0.041,0.051,1.103
44,Chadi Riad Dnanou,0,DEF,Crystal Palace,993.5,4.17,72.2,0.034,0.047,1.169
45,Max Alleyne,0,DEF,Man City,1016.5,4.16,69.6,0.041,0.049,0.959
46,Amadou Onana,0,MID,Aston Villa,1021.7,4.14,71.8,0.143,0.128,1.020
47,Myles Lewis-Skelly,0,DEF,Arsenal,1059.8,4.13,58.3,0.176,0.050,1.314
48,Amad Diallo,1,MID,Man Utd,1086.6,4.12,81.7,0.146,0.126,1.453
49,Alex Iwobi,0,MID,Fulham,980.9,4.12,83.0,0.134,0.140,1.209

In [14]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [15]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [16]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.02 minute(s)