In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
stats_current_gameweek = 23
picks_current_gameweek = 23
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 24
Squad Points: 71.59

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gabriel,a,100.0,24.0,DEF,Arsenal,Leeds,6.110113,82.0
1,Matheus N.,a,75.0,24.0,DEF,Man City,Spurs,5.124422,66.0
2,Khusanov,a,100.0,24.0,DEF,Man City,Spurs,4.960311,81.0
3,B.Fernandes,a,100.0,24.0,MID,Man Utd,Fulham,4.545095,77.0
4,Raúl,a,100.0,24.0,FWD,Fulham,Man Utd,4.515927,86.0
5,Szoboszlai,a,100.0,24.0,MID,Liverpool,Newcastle,4.425574,86.0
6,Brobbey,a,100.0,24.0,FWD,Sunderland,Burnley,4.268094,85.0
7,Raya,a,NaN,24.0,GK,Arsenal,Leeds,4.229629,89.0
8,Gibbs-White,a,100.0,24.0,MID,Nott'm Forest,Crystal Palace,4.218642,86.0
9,Reijnders,a,NaN,24.0,MID,Man City,Spurs,4.172824,62.0
10,Konaté,d,25.0,24.0,DEF,Liverpool,Newcastle,4.076035,86.0
11,Mitoma,a,100.0,24.0,MID,Brighton,Everton,3.932956,75.0
12,Martinez,a,75.0,24.0,GK,Aston Villa,Brentford,3.906115,90.0
13,Tarkowski,a,NaN,24.0,DEF,Everton,Brighton,3.705735,87.0
14,Gyökeres,a,100.0,24.0,FWD,Arsenal,Leeds,3.291689,46.0

In [6]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
        -- AND position IN ('MID','FWD')
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 24

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Hume,a,NaN,24.0,DEF,Sunderland,Burnley,5.249054
1,White,a,100.0,24.0,DEF,Arsenal,Leeds,4.958971
2,Alleyne,a,NaN,24.0,DEF,Man City,Spurs,4.896832
3,Truffert,a,NaN,24.0,DEF,Bournemouth,Wolves,4.808724
4,A.Jimenez,a,NaN,24.0,DEF,Bournemouth,Wolves,4.774493
5,Senesi,a,100.0,24.0,DEF,Bournemouth,Wolves,4.704568
6,Hill,a,NaN,24.0,DEF,Bournemouth,Wolves,4.580325
7,Scott,a,100.0,24.0,MID,Bournemouth,Wolves,4.485318
8,Mosquera,a,100.0,24.0,DEF,Arsenal,Leeds,4.477159
9,Lewis,a,100.0,24.0,DEF,Man City,Spurs,4.462527

In [7]:
print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 38
    ORDER BY xpoints DESC
""")
view.head(10)

When to use second TRIPLE CAPTAIN chip (gws19-38)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,37.0,DEF,Arsenal,Burnley,6.535221
1,Gabriel dos Santos Magalhães,31.0,DEF,Arsenal,Wolves,6.507733
2,Gabriel dos Santos Magalhães,27.0,DEF,Arsenal,Spurs,6.131226
3,Gabriel dos Santos Magalhães,24.0,DEF,Arsenal,Leeds,6.110113
4,Gabriel dos Santos Magalhães,36.0,DEF,Arsenal,West Ham,6.110049
5,Matheus Nunes,34.0,DEF,Man City,Burnley,5.532363
6,Abdukodir Khusanov,34.0,DEF,Man City,Burnley,5.312246
7,Ibrahima Konaté,29.0,DEF,Liverpool,Wolves,5.266296
8,Matheus Nunes,28.0,DEF,Man City,Leeds,5.171814
9,Matheus Nunes,30.0,DEF,Man City,West Ham,5.171750

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND 38")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND 38
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW24 AND 38

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1039.7,79.57,82.0,0.069,0.165,0.850
1,John Stones,0,DEF,Man City,1064.0,70.11,61.4,0.302,0.138,1.462
2,Matheus Nunes,1,DEF,Man City,1064.0,69.91,65.9,0.039,0.108,0.892
3,Conor Gallagher,0,MID,Spurs,1088.8,69.29,77.6,0.253,0.172,1.644
4,Bruno Borges Fernandes,1,MID,Man Utd,1063.3,69.22,76.8,0.217,0.195,1.373
5,Dominik Szoboszlai,1,MID,Liverpool,1064.4,67.55,86.1,0.163,0.168,1.298
6,Raúl Jiménez Rodríguez,1,FWD,Fulham,1066.9,67.40,85.4,0.465,0.053,1.292
7,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1064.0,66.43,62.8,0.088,0.089,1.011
8,Max Alleyne,0,DEF,Man City,1064.0,66.19,74.7,0.036,0.040,0.994
9,Ethan Pinnock,0,DEF,Brentford,1069.5,65.91,72.1,0.220,0.064,1.497
10,Joško Gvardiol,0,DEF,Man City,1064.0,65.58,58.6,0.151,0.110,1.126
11,Trai Hume,0,DEF,Sunderland,1063.9,65.57,73.1,0.057,0.357,1.458
12,Abdukodir Khusanov,1,DEF,Man City,1064.0,65.17,81.1,0.043,0.041,1.103
13,Ibrahima Konaté,1,DEF,Liverpool,1064.4,64.77,86.4,0.040,0.046,1.153
14,Vitaly Janelt,0,MID,Brentford,1069.5,64.67,85.6,0.149,0.130,1.345
15,Harvey Barnes,0,MID,Newcastle,1083.1,64.53,80.1,0.200,0.116,1.365
16,Youri Tielemans,0,MID,Aston Villa,1045.1,64.25,81.3,0.120,0.164,1.135
17,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1064.0,63.89,82.1,0.115,0.143,0.974
18,Cristhian Mosquera,0,DEF,Arsenal,1039.7,63.42,59.5,0.207,0.051,1.231
19,Benjamin White,0,DEF,Arsenal,1039.7,63.37,61.3,0.050,0.056,0.924
20,Anton Stach,0,MID,Leeds,1062.4,63.04,79.5,0.140,0.159,1.311
21,Morgan Gibbs-White,1,MID,Nott'm Forest,1062.3,63.00,86.1,0.145,0.117,1.290
22,Matt Doherty,0,DEF,Wolves,1061.6,62.97,66.8,0.280,0.099,1.707
23,Diego Coppola,0,DEF,Brighton,1060.8,62.75,65.1,0.246,0.047,1.500
24,Alex Scott,0,MID,Bournemouth,1058.2,62.64,83.2,0.144,0.102,1.271
25,Matthijs de Ligt,0,DEF,Man Utd,1063.3,62.40,60.5,0.280,0.044,1.413
26,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1079.0,62.33,84.6,0.127,0.123,1.476
27,Matt O'Riley,0,MID,Brighton,1060.8,62.17,48.6,0.512,0.212,1.813
28,Emiliano Martínez Romero,1,GK,Aston Villa,1045.1,62.06,89.9,NaN,NaN,1.063
29,Enzo Le Fée,0,MID,Sunderland,1063.9,61.86,85.2,0.112,0.140,1.366
30,Marcus Tavernier,0,MID,Bournemouth,1058.2,61.85,75.5,0.150,0.142,1.206
31,Emil Krafth,0,DEF,Newcastle,1083.1,61.80,62.5,0.325,0.052,1.763
32,Martín Zubimendi Ibáñez,0,MID,Arsenal,1039.7,61.75,70.4,0.154,0.120,0.836
33,Emile Smith Rowe,0,MID,Fulham,1066.9,61.70,78.7,0.150,0.117,1.282
34,Mathias Jensen,0,MID,Brentford,1069.5,61.49,74.9,0.127,0.191,1.349
35,Callum Hudson-Odoi,0,MID,Nott'm Forest,1062.3,61.36,84.7,0.129,0.111,1.256
36,Arthur Masuaku,0,DEF,Sunderland,1063.9,61.21,59.0,0.314,0.112,1.627
37,Moisés Caicedo Corozo,0,MID,Chelsea,1062.7,61.19,80.4,0.124,0.129,1.280
38,Ibrahim Sangaré,0,MID,Nott'm Forest,1062.3,61.13,77.2,0.170,0.111,1.369
39,Pascal Struijk,0,DEF,Leeds,1062.4,61.10,87.2,0.049,0.054,1.303
40,Crysencio Summerville,0,MID,West Ham,1079.0,60.93,83.6,0.147,0.110,1.479
41,Brenden Aaronson,0,MID,Leeds,1062.4,60.71,84.8,0.123,0.123,1.340
42,Conor Bradley,0,DEF,Liverpool,1064.4,60.61,68.9,0.035,0.071,1.158
43,Fábio Freitas Gouveia Carvalho,0,MID,Brentford,1069.5,60.42,40.3,0.631,0.217,1.913
44,Neco Williams,0,DEF,Nott'm Forest,1062.3,60.24,87.3,0.035,0.056,1.301
45,Tijjani Reijnders,1,MID,Man City,1064.0,60.23,62.7,0.184,0.148,0.856
46,Emiliano Buendía Stati,0,MID,Aston Villa,1045.1,60.18,67.4,0.188,0.123,1.280
47,Ferdi Kadıoğlu,0,DEF,Brighton,1060.8,60.17,84.4,0.045,0.049,1.314
48,Jan Paul van Hecke,0,DEF,Brighton,1060.8,60.16,87.2,0.045,0.047,1.322
49,Ola Aina,0,DEF,Nott'm Forest,1062.3,60.10,84.8,0.035,0.040,1.243

In [9]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW24 AND 28

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1039.9,26.84,82.1,0.064,0.166,0.819
1,John Stones,0,DEF,Man City,1058.5,23.66,61.3,0.302,0.138,1.426
2,Matheus Nunes,1,DEF,Man City,1058.5,23.54,66.0,0.039,0.109,0.881
3,Bruno Borges Fernandes,1,MID,Man Utd,1026.9,23.44,76.8,0.223,0.209,1.342
4,Conor Gallagher,0,MID,Spurs,1140.3,22.59,77.4,0.247,0.168,1.888
5,Dominik Szoboszlai,1,MID,Liverpool,1072.3,22.58,86.1,0.162,0.167,1.227
6,Raúl Jiménez Rodríguez,1,FWD,Fulham,1079.7,22.43,85.6,0.461,0.052,1.309
7,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1058.5,22.38,62.9,0.088,0.088,0.990
8,Joško Gvardiol,0,DEF,Man City,1058.5,22.22,58.6,0.150,0.110,1.094
9,Max Alleyne,0,DEF,Man City,1058.5,22.16,74.9,0.035,0.039,0.985
10,Abdukodir Khusanov,1,DEF,Man City,1058.5,21.93,81.2,0.043,0.040,1.089
11,Youri Tielemans,0,MID,Aston Villa,1016.2,21.70,81.3,0.122,0.176,1.122
12,Ibrahima Konaté,1,DEF,Liverpool,1072.3,21.66,86.4,0.040,0.045,1.140
13,Ethan Pinnock,0,DEF,Brentford,1095.8,21.61,72.0,0.219,0.056,1.524
14,Benjamin White,0,DEF,Arsenal,1039.9,21.40,61.3,0.049,0.055,0.897
15,Vitaly Janelt,0,MID,Brentford,1095.8,21.40,85.5,0.148,0.124,1.375
16,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1058.5,21.39,82.1,0.115,0.146,0.954
17,Matthijs de Ligt,0,DEF,Man Utd,1026.9,21.34,60.8,0.274,0.043,1.369
18,Morgan Gibbs-White,1,MID,Nott'm Forest,1037.0,21.32,86.1,0.146,0.126,1.210
19,Harvey Barnes,0,MID,Newcastle,1099.8,21.31,80.0,0.199,0.111,1.425
20,Trai Hume,0,DEF,Sunderland,1083.8,21.30,73.1,0.058,0.354,1.521
21,Cristhian Mosquera,0,DEF,Arsenal,1039.9,21.25,59.4,0.205,0.050,1.214
22,Alex Scott,0,MID,Bournemouth,1033.9,21.12,83.3,0.147,0.106,1.251
23,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1066.3,20.93,84.6,0.129,0.125,1.525
24,Moisés Caicedo Corozo,0,MID,Chelsea,998.8,20.92,79.9,0.129,0.137,1.206
25,Marcus Tavernier,0,MID,Bournemouth,1033.9,20.89,75.7,0.152,0.152,1.177
26,Emiliano Martínez Romero,1,GK,Aston Villa,1016.2,20.86,89.9,NaN,NaN,1.033
27,Neco Williams,0,DEF,Nott'm Forest,1037.0,20.78,87.3,0.035,0.063,1.239
28,Ola Aina,0,DEF,Nott'm Forest,1037.0,20.77,84.9,0.035,0.048,1.180
29,Callum Hudson-Odoi,0,MID,Nott'm Forest,1037.0,20.76,84.7,0.130,0.118,1.174
30,Ibrahim Sangaré,0,MID,Nott'm Forest,1037.0,20.66,77.2,0.174,0.113,1.286
31,Nikola Milenković,0,DEF,Nott'm Forest,1037.0,20.65,84.7,0.035,0.055,1.200
32,Martín Zubimendi Ibáñez,0,MID,Arsenal,1039.9,20.61,70.4,0.153,0.119,0.805
33,Diogo Dalot Teixeira,0,DEF,Man Utd,1026.9,20.57,86.8,0.045,0.064,1.294
34,Diego Coppola,0,DEF,Brighton,1075.2,20.53,65.1,0.245,0.044,1.532
35,Adrien Truffert,0,DEF,Bournemouth,1033.9,20.51,87.1,0.043,0.053,1.240
36,Marcos Senesi Barón,0,DEF,Bournemouth,1033.9,20.50,84.3,0.041,0.054,1.229
37,Filip Jörgensen,0,GK,Chelsea,998.8,20.44,89.8,NaN,NaN,1.160
38,Matt O'Riley,0,MID,Brighton,1075.2,20.43,48.5,0.519,0.187,1.879
39,Benoît Badiashile Mukinayi,0,DEF,Chelsea,998.8,20.43,76.9,0.042,0.040,1.193
40,Álex Jiménez Sánchez,0,DEF,Bournemouth,1033.9,20.43,85.8,0.046,0.050,1.227
41,Emile Smith Rowe,0,MID,Fulham,1079.7,20.43,78.7,0.148,0.117,1.318
42,Enzo Le Fée,0,MID,Sunderland,1083.8,20.39,85.1,0.110,0.136,1.455
43,Crysencio Summerville,0,MID,West Ham,1066.3,20.38,83.7,0.148,0.113,1.520
44,Emiliano Buendía Stati,0,MID,Aston Villa,1016.2,20.29,67.4,0.190,0.128,1.244
45,Luke Shaw,0,DEF,Man Utd,1026.9,20.26,87.0,0.046,0.046,1.283
46,Mathias Jensen,0,MID,Brentford,1095.8,20.24,74.7,0.128,0.179,1.394
47,Carlos Henrique Casimiro,0,MID,Man Utd,1026.9,20.23,78.3,0.116,0.153,1.296
48,James Hill,0,DEF,Bournemouth,1033.9,20.19,82.8,0.046,0.052,1.255
49,Emil Krafth,0,DEF,Newcastle,1099.8,20.19,62.4,0.322,0.051,1.819

In [10]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW24 AND 28

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Viktor Gyökeres,1,FWD,Arsenal,1039.9,15.67,45.9,0.454,0.083,0.935
1,James Tarkowski,1,DEF,Everton,1074.5,18.41,87.2,0.042,0.046,1.487
2,David Raya Martín,1,GK,Arsenal,1039.9,18.94,88.8,NaN,NaN,0.932
3,Mitoma Kaoru,1,MID,Brighton,1075.2,19.68,75.4,0.148,0.110,1.310
4,Brian Brobbey,1,FWD,Sunderland,1083.8,19.74,84.7,0.289,0.071,1.350
5,Tijjani Reijnders,1,MID,Man City,1058.5,20.16,62.7,0.185,0.149,0.840
6,Emiliano Martínez Romero,1,GK,Aston Villa,1016.2,20.86,89.9,NaN,NaN,1.033
7,Morgan Gibbs-White,1,MID,Nott'm Forest,1037.0,21.32,86.1,0.146,0.126,1.210
8,Ibrahima Konaté,1,DEF,Liverpool,1072.3,21.66,86.4,0.040,0.045,1.140
9,Abdukodir Khusanov,1,DEF,Man City,1058.5,21.93,81.2,0.043,0.040,1.089
10,Raúl Jiménez Rodríguez,1,FWD,Fulham,1079.7,22.43,85.6,0.461,0.052,1.309
11,Dominik Szoboszlai,1,MID,Liverpool,1072.3,22.58,86.1,0.162,0.167,1.227
12,Bruno Borges Fernandes,1,MID,Man Utd,1026.9,23.44,76.8,0.223,0.209,1.342
13,Matheus Nunes,1,DEF,Man City,1058.5,23.54,66.0,0.039,0.109,0.881
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1039.9,26.84,82.1,0.064,0.166,0.819

In [11]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team: 24 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Man City,John Stones,70.113965,James Tarkowski,57.053391,13.060574
1,MID,Spurs,Conor Gallagher,69.293654,Mitoma Kaoru,59.316039,9.977615
2,DEF,Man City,Rúben dos Santos Gato Alves Dias,66.429918,James Tarkowski,57.053391,9.376526
3,DEF,Man City,Max Alleyne,66.188240,James Tarkowski,57.053391,9.134849
4,DEF,Brentford,Ethan Pinnock,65.907432,James Tarkowski,57.053391,8.854040
5,DEF,Man City,Joško Gvardiol,65.577082,James Tarkowski,57.053391,8.523690
6,DEF,Sunderland,Trai Hume,65.572259,James Tarkowski,57.053391,8.518867
7,FWD,Newcastle,William Osula,54.072990,Viktor Gyökeres,47.215382,6.857608
8,DEF,Arsenal,Cristhian Mosquera,63.418455,James Tarkowski,57.053391,6.365064
9,DEF,Arsenal,Benjamin White,63.368501,James Tarkowski,57.053391,6.315110
10,FWD,Wolves,Mateus Mané,53.137606,Viktor Gyökeres,47.215382,5.922224
11,DEF,Wolves,Matt Doherty,62.973775,James Tarkowski,57.053391,5.920383
12,DEF,Brighton,Diego Coppola,62.752533,James Tarkowski,57.053391,5.699142
13,MID,Brentford,Vitaly Janelt,64.668885,Mitoma Kaoru,59.316039,5.352846
14,DEF,Man Utd,Matthijs de Ligt,62.399432,James Tarkowski,57.053391,5.346041
15,FWD,Nott'm Forest,Igor Jesus Maciel da Cruz,52.556939,Viktor Gyökeres,47.215382,5.341556
16,MID,Newcastle,Harvey Barnes,64.528050,Mitoma Kaoru,59.316039,5.212011
17,MID,Aston Villa,Youri Tielemans,64.251866,Mitoma Kaoru,59.316039,4.935827
18,DEF,Newcastle,Emil Krafth,61.796932,James Tarkowski,57.053391,4.743541
19,MID,Man City,Bernardo Mota Veiga de Carvalho e Silva,63.891694,Mitoma Kaoru,59.316039,4.575655

In [12]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Amad Diallo'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 24 and 28:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Amad Diallo,24.0,MID,Man Utd,Fulham,6.2,1062.457219,3.797034,66.074817,0.162382,0.140578,1.365395
1,Amad Diallo,25.0,MID,Man Utd,Spurs,6.2,990.668127,4.020575,66.492090,0.188032,0.164686,1.198880
2,Amad Diallo,26.0,MID,Man Utd,West Ham,6.2,971.988000,4.071871,66.492090,0.192530,0.171337,1.209317
3,Amad Diallo,27.0,MID,Man Utd,Everton,6.2,1061.389703,3.797034,66.074817,0.162382,0.140578,1.365395
4,Amad Diallo,28.0,MID,Man Utd,Crystal Palace,6.2,1048.207524,3.837483,66.074817,0.166829,0.147981,1.336566

In [13]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.25 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW24 to GW28

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1039.9,5.84,82.1,0.064,0.166,0.819
1,John Stones,0,DEF,Man City,1058.5,4.98,61.3,0.302,0.138,1.426
2,Matheus Nunes,1,DEF,Man City,1058.5,4.91,66.0,0.039,0.109,0.881
3,Trai Hume,0,DEF,Sunderland,1083.8,4.90,73.1,0.058,0.354,1.521
4,Joško Gvardiol,0,DEF,Man City,1058.5,4.81,58.6,0.150,0.110,1.094
5,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1058.5,4.75,62.9,0.088,0.088,0.990
6,Benjamin White,0,DEF,Arsenal,1039.9,4.71,61.3,0.049,0.055,0.897
7,Abdukodir Khusanov,1,DEF,Man City,1058.5,4.68,81.2,0.043,0.040,1.089
8,Max Alleyne,0,DEF,Man City,1058.5,4.67,74.9,0.035,0.039,0.985
9,Bruno Borges Fernandes,1,MID,Man Utd,1026.9,4.62,76.8,0.223,0.209,1.342
10,Adrien Truffert,0,DEF,Bournemouth,1033.9,4.53,87.1,0.043,0.053,1.240
11,Raúl Jiménez Rodríguez,1,FWD,Fulham,1079.7,4.51,85.6,0.461,0.052,1.309
12,Álex Jiménez Sánchez,0,DEF,Bournemouth,1033.9,4.50,85.8,0.046,0.050,1.227
13,Arthur Masuaku,0,DEF,Sunderland,1083.8,4.48,58.8,0.312,0.106,1.694
14,Conor Gallagher,0,MID,Spurs,1140.3,4.44,77.4,0.247,0.168,1.888
15,Marcos Senesi Barón,0,DEF,Bournemouth,1033.9,4.44,84.3,0.041,0.054,1.229
16,Cristhian Mosquera,0,DEF,Arsenal,1039.9,4.41,59.4,0.205,0.050,1.214
17,Dominik Szoboszlai,1,MID,Liverpool,1072.3,4.40,86.1,0.162,0.167,1.227
18,Marcus Tavernier,0,MID,Bournemouth,1033.9,4.36,75.7,0.152,0.152,1.177
19,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1058.5,4.36,82.1,0.115,0.146,0.954
20,Alex Scott,0,MID,Bournemouth,1033.9,4.36,83.3,0.147,0.106,1.251
21,Julio Soler Barreto,0,DEF,Bournemouth,1033.9,4.32,52.3,0.308,0.048,1.468
22,James Hill,0,DEF,Bournemouth,1033.9,4.32,82.8,0.046,0.052,1.255
23,Morgan Gibbs-White,1,MID,Nott'm Forest,1037.0,4.27,86.1,0.146,0.126,1.210
24,Enzo Le Fée,0,MID,Sunderland,1083.8,4.25,85.1,0.110,0.136,1.455
25,Youri Tielemans,0,MID,Aston Villa,1016.2,4.25,81.3,0.122,0.176,1.122
26,Rico Lewis,0,DEF,Man City,1058.5,4.23,66.2,0.035,0.050,1.149
27,Martín Zubimendi Ibáñez,0,MID,Arsenal,1039.9,4.22,70.4,0.153,0.119,0.805
28,Benoît Badiashile Mukinayi,0,DEF,Chelsea,998.8,4.22,76.9,0.042,0.040,1.193
29,Matthijs de Ligt,0,DEF,Man Utd,1026.9,4.21,60.8,0.274,0.043,1.369
30,Moisés Caicedo Corozo,0,MID,Chelsea,998.8,4.21,79.9,0.129,0.137,1.206
31,Harvey Barnes,0,MID,Newcastle,1099.8,4.19,80.0,0.199,0.111,1.425
32,Ethan Pinnock,0,DEF,Brentford,1095.8,4.18,72.0,0.219,0.056,1.524
33,Brian Brobbey,1,FWD,Sunderland,1083.8,4.15,84.7,0.289,0.071,1.350
34,Ibrahim Sangaré,0,MID,Nott'm Forest,1037.0,4.14,77.2,0.174,0.113,1.286
35,Vitaly Janelt,0,MID,Brentford,1095.8,4.14,85.5,0.148,0.124,1.375
36,Filip Jörgensen,0,GK,Chelsea,998.8,4.14,89.8,NaN,NaN,1.160
37,Callum Hudson-Odoi,0,MID,Nott'm Forest,1037.0,4.13,84.7,0.130,0.118,1.174
38,Diego Coppola,0,DEF,Brighton,1075.2,4.13,65.1,0.245,0.044,1.532
39,Mateus Gonçalo Espanha Fernandes,0,MID,West Ham,1066.3,4.12,84.6,0.129,0.125,1.525
40,Matt Doherty,0,DEF,Wolves,1089.3,4.11,66.7,0.278,0.095,1.793
41,Tijjani Reijnders,1,MID,Man City,1058.5,4.10,62.7,0.185,0.149,0.840
42,David Raya Martín,1,GK,Arsenal,1039.9,4.10,88.8,NaN,NaN,0.932
43,Myles Lewis-Skelly,0,DEF,Arsenal,1039.9,4.10,49.8,0.065,0.061,1.034
44,Neco Williams,0,DEF,Nott'm Forest,1037.0,4.09,87.3,0.035,0.063,1.239
45,Malo Gusto,0,DEF,Chelsea,998.8,4.06,65.9,0.045,0.056,1.214
46,Ibrahima Konaté,1,DEF,Liverpool,1072.3,4.06,86.4,0.040,0.045,1.140
47,Tosin Adarabioyo,0,DEF,Chelsea,998.8,4.06,70.6,0.040,0.041,1.192
48,Emile Smith Rowe,0,MID,Fulham,1079.7,4.05,78.7,0.148,0.117,1.318
49,Matt O'Riley,0,MID,Brighton,1075.2,4.05,48.5,0.519,0.187,1.879

In [14]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [15]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [16]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.03 minute(s)